‪libpcl: ‪pcl/buf.h File Reference
buf.h File Reference
#include <pcl/types.h>
Macros
#define pcl_buf_putchar(b, c) pcl_buf_putint8(b, (int8_t)(c))
#define pcl_buf_getchar(b, chp) pcl_buf_getint8(b, (uint8_t *)(chp))
Functions
PCL_EXPORT pcl_buf_t * pcl_buf_init (pcl_buf_t *b, size_t size, bool omit_nul)
PCL_EXPORT pcl_buf_t * pcl_buf_grow (pcl_buf_t *b, int len)
PCL_EXPORT pcl_buf_t * pcl_buf_reset (pcl_buf_t *b)
PCL_EXPORT pcl_buf_t * pcl_buf_clear (pcl_buf_t *b)
PCL_EXPORT pcl_buf_t * pcl_buf_copy (pcl_buf_t *dest, pcl_buf_t *src)
PCL_EXPORT int pcl_buf_pos (pcl_buf_t *b, int *newpos)
‪Gets the current read/write position or sets the position of the buffer.
PCL_EXPORT char * pcl_buf_data (pcl_buf_t *b, int *lenp)
‪Gets the raw data pointer of the buffer.
PCL_EXPORT pcl_buf_t * pcl_buf_free (pcl_buf_t *b)
PCL_EXPORT int pcl_buf_put (pcl_buf_t *b, const void *data, int len)
PCL_EXPORT int pcl_buf_putstr (pcl_buf_t *b, const char *s)
PCL_INLINE int pcl_buf_putint8 (pcl_buf_t *b, uint8_t i)
PCL_EXPORT int pcl_buf_putint16 (pcl_buf_t *b, uint16_t i)
‪Puts a 16-bit integer into the buffer in network-byte order.
PCL_EXPORT int pcl_buf_putint32 (pcl_buf_t *b, uint32_t i)
‪Puts a 32-bit integer into the buffer in network-byte order.
PCL_EXPORT int pcl_buf_putint64 (pcl_buf_t *b, uint64_t i)
‪Puts a 64-bit integer into the buffer in network-byte order.
PCL_EXPORT int pcl_buf_putf (pcl_buf_t *b, const char *format,...)
PCL_EXPORT int pcl_buf_vputf (pcl_buf_t *b, const char *format, va_list ap)
PCL_EXPORT int pcl_buf_get (pcl_buf_t *b, void *buf, int len)
PCL_EXPORT int pcl_buf_getstr (pcl_buf_t *b, char *buf, int len)
PCL_INLINE int pcl_buf_getint8 (pcl_buf_t *b, uint8_t *i)
‪Gets an 8-bit integer from the buffer.
PCL_EXPORT int pcl_buf_getint16 (pcl_buf_t *b, uint16_t *i)
‪Gets a 16-bit integer from the buffer in host-byte order.
PCL_EXPORT int pcl_buf_getint32 (pcl_buf_t *b, uint32_t *i)
‪Gets a 32-bit integer from the buffer in host-byte order.
PCL_EXPORT int pcl_buf_getint64 (pcl_buf_t *b, uint64_t *i)
‪Gets a 64-bit integer from the buffer in host-byte order.
Macro Definition Documentation
pcl_buf_putchar
#define pcl_buf_putchar (b, c) pcl_buf_putint8(b, (int8_t)(c))
Definition at line 100 of file buf.h.
pcl_buf_getchar
#define pcl_buf_getchar (b, chp) pcl_buf_getint8(b, (uint8_t *)(chp))
Definition at line 142 of file buf.h.
Function Documentation
pcl_buf_init()
PCL_EXPORT pcl_buf_t* pcl_buf_init (pcl_buf_t * b, size_t size, bool omit_nul)
Parameters
b
size
omit_nul ‪if non-zero, putting strs (putstr, putf, vputf) will not append a NUL. This allows for using the buffer as a dynamic string rather than an array of data types. When zero, the buffer writes NUL bytes for all strings: "abc\0def\0\0" (trailing NUL byte always gets written). With a non-zero value: "abcdef\0". Example represents two calls to putstr. When non-zero, the only allowed GET calls are pcl_buf_get(), pcl_buf_getchar() and pcl_buf_getint8().
Returns
pcl_buf_grow()
PCL_EXPORT pcl_buf_t* pcl_buf_grow (pcl_buf_t * b, int len)
pcl_buf_reset()
PCL_EXPORT pcl_buf_t* pcl_buf_reset (pcl_buf_t * b)
pcl_buf_clear()
PCL_EXPORT pcl_buf_t* pcl_buf_clear (pcl_buf_t * b)
pcl_buf_copy()
PCL_EXPORT pcl_buf_t* pcl_buf_copy (pcl_buf_t * dest, pcl_buf_t * src)
pcl_buf_pos()
PCL_EXPORT int pcl_buf_pos (pcl_buf_t * b, int * newpos)
‪Gets the current read/write position or sets the position of the buffer.
Parameters
b ‪buffer pointer
[in] newpos ‪new position for the buffer, or NULL to retreive the current position.
Returns
‪If newpos is NULL, this returns the current position. If newpos is provided, this returns the previous position. If an error occurs, -1 is returned.
pcl_buf_data()
PCL_EXPORT char* pcl_buf_data (pcl_buf_t * b, int * lenp)
‪Gets the raw data pointer of the buffer.
This can also be used to retreive the buffer length.
Parameters
b ‪buffer pointer
lenp ‪If not NULL, this will receive the length of data.
Returns
‪pointer to the data or NULL on error.
pcl_buf_free()
PCL_EXPORT pcl_buf_t* pcl_buf_free (pcl_buf_t * b)
pcl_buf_put()
PCL_EXPORT int pcl_buf_put (pcl_buf_t * b, const void * data, int len)
Referenced by pcl_buf_putint8().
pcl_buf_putstr()
PCL_EXPORT int pcl_buf_putstr (pcl_buf_t * b, const char * s)
pcl_buf_putint8()
PCL_INLINE int pcl_buf_putint8 (pcl_buf_t * b, uint8_t i)
Definition at line 103 of file buf.h.
References pcl_buf_put().
pcl_buf_putint16()
PCL_EXPORT int pcl_buf_putint16 (pcl_buf_t * b, uint16_t i)
‪Puts a 16-bit integer into the buffer in network-byte order.
Parameters
b
i
Returns
pcl_buf_putint32()
PCL_EXPORT int pcl_buf_putint32 (pcl_buf_t * b, uint32_t i)
‪Puts a 32-bit integer into the buffer in network-byte order.
Parameters
b
i
Returns
pcl_buf_putint64()
PCL_EXPORT int pcl_buf_putint64 (pcl_buf_t * b, uint64_t i)
‪Puts a 64-bit integer into the buffer in network-byte order.
Parameters
b
i
Returns
pcl_buf_putf()
PCL_EXPORT int pcl_buf_putf (pcl_buf_t * b, const char * format, ...)
pcl_buf_vputf()
PCL_EXPORT int pcl_buf_vputf (pcl_buf_t * b, const char * format, va_list ap)
pcl_buf_get()
PCL_EXPORT int pcl_buf_get (pcl_buf_t * b, void * buf, int len)
Referenced by pcl_buf_getint8().
pcl_buf_getstr()
PCL_EXPORT int pcl_buf_getstr (pcl_buf_t * b, char * buf, int len)
pcl_buf_getint8()
PCL_INLINE int pcl_buf_getint8 (pcl_buf_t * b, uint8_t * i)
‪Gets an 8-bit integer from the buffer.
Parameters
b
i
Returns
‪number of bytes read or -1 on error
Definition at line 150 of file buf.h.
References pcl_buf_get().
pcl_buf_getint16()
PCL_EXPORT int pcl_buf_getint16 (pcl_buf_t * b, uint16_t * i)
‪Gets a 16-bit integer from the buffer in host-byte order.
Parameters
b
i
Returns
‪number of bytes read or -1 on error
pcl_buf_getint32()
PCL_EXPORT int pcl_buf_getint32 (pcl_buf_t * b, uint32_t * i)
‪Gets a 32-bit integer from the buffer in host-byte order.
Parameters
b
i
Returns
‪number of bytes read or -1 on error
pcl_buf_getint64()
PCL_EXPORT int pcl_buf_getint64 (pcl_buf_t * b, uint64_t * i)
‪Gets a 64-bit integer from the buffer in host-byte order.
Parameters
b
i
Returns
‪number of bytes read or -1 on error