/*
  Portable C Library ("PCL")
  Copyright (c) 1999-2020 Andrew Chernow
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

  * Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.

  * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

  * Neither the name of the copyright holder nor the names of its
    contributors may be used to endorse or promote products derived from
    this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/


_errmap(ERROR_INVALID_FUNCTION,            PCL_ENOIMPL)
_errmap(ERROR_PROC_NOT_FOUND,              PCL_ENOTFOUND)
_errmap(ERROR_FILE_NOT_FOUND,              PCL_ENOENT)
_errmap(ERROR_PATH_NOT_FOUND,              PCL_ENOENT)
_errmap(ERROR_TOO_MANY_OPEN_FILES,         PCL_EMFILE)
_errmap(ERROR_ACCESS_DENIED,               PCL_EACCES)
_errmap(ERROR_INVALID_HANDLE,              PCL_EBADH)
_errmap(ERROR_HANDLE_EOF,                  PCL_EOF)
_errmap(ERROR_OPERATION_ABORTED,           PCL_ECANCELLED)
_errmap(ERROR_INVALID_USER_BUFFER,         PCL_EBUF)
_errmap(ERROR_ARENA_TRASHED,               PCL_ENOMEM)
_errmap(ERROR_NOT_ENOUGH_MEMORY,           PCL_ENOMEM)
_errmap(ERROR_INVALID_BLOCK,               PCL_ENOMEM)
_errmap(ERROR_BAD_ENVIRONMENT,             PCL_E2BIG)
_errmap(ERROR_BAD_FORMAT,                  PCL_ENOEXEC)
_errmap(ERROR_INVALID_ACCESS,              PCL_EACCES)
_errmap(ERROR_INVALID_DATA,                PCL_EINVAL)
_errmap(ERROR_INVALID_DRIVE,               PCL_ENOENT)
_errmap(ERROR_CURRENT_DIRECTORY,           PCL_EACCES)
_errmap(ERROR_NOT_SAME_DEVICE,             PCL_EXDEV)
_errmap(ERROR_NO_MORE_FILES,               PCL_ENOMORE)
_errmap(ERROR_WRITE_PROTECT,               PCL_EROFS)
_errmap(ERROR_BAD_UNIT,                    PCL_ENODEV)
_errmap(ERROR_NOT_READY,                   PCL_ENOTREADY)
_errmap(ERROR_BAD_COMMAND,                 PCL_EBADCMD)
_errmap(ERROR_SEEK,                        PCL_ESPIPE)
_errmap(ERROR_NOT_DOS_DISK,                PCL_EACCES)
_errmap(ERROR_SECTOR_NOT_FOUND,            PCL_EACCES)
_errmap(ERROR_OUT_OF_PAPER,                PCL_ENOTREADY)
_errmap(ERROR_WRITE_FAULT,                 PCL_EIO)
_errmap(ERROR_READ_FAULT,                  PCL_EIO)
_errmap(ERROR_GEN_FAILURE,                 PCL_ENOTREADY) /* device not functioning */
_errmap(ERROR_SHARING_VIOLATION,           PCL_ELOCK)
_errmap(ERROR_LOCK_VIOLATION,              PCL_ELOCK)
_errmap(ERROR_WRONG_DISK,                  PCL_EACCES)
_errmap(ERROR_SHARING_BUFFER_EXCEEDED,     PCL_EACCES)
_errmap(ERROR_HANDLE_DISK_FULL,            PCL_ENOSPC)
_errmap(ERROR_REM_NOT_LIST,                PCL_ENOENT) /* can't find net path */
_errmap(ERROR_DUP_NAME,                    PCL_EEXIST) /* computer name exists on network */
_errmap(ERROR_NOT_SUPPORTED,               PCL_ENOIMPL)
_errmap(ERROR_BAD_NETPATH,                 PCL_ENOENT)
_errmap(ERROR_NETWORK_BUSY,                PCL_EBUSY)
_errmap(ERROR_DEV_NOT_EXIST,               PCL_ENODEV)
_errmap(ERROR_TOO_MANY_CMDS,               PCL_E2BIG)
_errmap(ERROR_PRINTQ_FULL,                 PCL_ENOTREADY)
_errmap(ERROR_NO_SPOOL_SPACE,              PCL_ENOTREADY)
_errmap(ERROR_PRINT_CANCELLED,             PCL_ECANCELLED)
_errmap(ERROR_NETNAME_DELETED,             PCL_EACCES)
_errmap(ERROR_NETWORK_ACCESS_DENIED,       PCL_EACCES)
_errmap(ERROR_BAD_DEV_TYPE,                PCL_ENODEV)
_errmap(ERROR_BAD_NET_NAME,                PCL_ENOENT)
_errmap(ERROR_FILE_EXISTS,                 PCL_EEXIST)
_errmap(ERROR_CANNOT_MAKE,                 PCL_EACCES)
_errmap(ERROR_FAIL_I24,                    PCL_EACCES)
_errmap(ERROR_INVALID_PASSWORD,            PCL_EACCES)
_errmap(ERROR_NO_NET_OR_BAD_PATH,          PCL_EPATH)
_errmap(ERROR_INVALID_PARAMETER,           PCL_EINVAL)
_errmap(ERROR_NET_WRITE_FAULT,             PCL_EIO)
_errmap(ERROR_NO_PROC_SLOTS,               PCL_ESRCH)
_errmap(ERROR_DISK_CHANGE,                 PCL_ENOTREADY)
_errmap(ERROR_DRIVE_LOCKED,                PCL_ELOCK)
_errmap(ERROR_BROKEN_PIPE,                 PCL_EPIPE)
_errmap(ERROR_OPEN_FAILED,                 PCL_ENOENT)
_errmap(ERROR_BUFFER_OVERFLOW,             PCL_EBUF)
_errmap(ERROR_DISK_FULL,                   PCL_ENOSPC)
_errmap(ERROR_NO_MORE_SEARCH_HANDLES,      PCL_EMFILE)
_errmap(ERROR_INVALID_TARGET_HANDLE,       PCL_EBADF)
_errmap(ERROR_CALL_NOT_IMPLEMENTED,        PCL_ENOIMPL)
_errmap(ERROR_SEM_TIMEOUT,                 PCL_ETIMEOUT)
_errmap(ERROR_INSUFFICIENT_BUFFER,         PCL_EBUF)
_errmap(ERROR_MORE_DATA,                   PCL_EBUF)
_errmap(ERROR_INVALID_NAME,                PCL_EPATH)
_errmap(ERROR_MOD_NOT_FOUND,               PCL_ENOENT)
_errmap(ERROR_WAIT_NO_CHILDREN,            PCL_ECHILD)
_errmap(ERROR_CHILD_NOT_COMPLETE,          PCL_ECHILD)
_errmap(ERROR_DIRECT_ACCESS_HANDLE,        PCL_EBADF)
_errmap(ERROR_NEGATIVE_SEEK,               PCL_ESPIPE)
_errmap(ERROR_SEEK_ON_DEVICE,              PCL_EACCES)
_errmap(ERROR_BUSY_DRIVE,                  PCL_EBUSY)
_errmap(ERROR_DIR_NOT_EMPTY,               PCL_ENOTEMPTY)
_errmap(ERROR_PATH_BUSY,                   PCL_EBUSY)
_errmap(ERROR_LABEL_TOO_LONG,              PCL_ENAMETOOLONG)
_errmap(ERROR_SIGNAL_REFUSED,              PCL_EACCES)
_errmap(ERROR_NOT_LOCKED,                  PCL_EACCES)
_errmap(ERROR_BAD_ARGUMENTS,               PCL_EINVAL)
_errmap(ERROR_BAD_PATHNAME,                PCL_EPATH)
_errmap(ERROR_MAX_THRDS_REACHED,           PCL_EAGAIN)
_errmap(ERROR_LOCK_FAILED,                 PCL_EIO)
_errmap(ERROR_BUSY,                        PCL_EBUSY)
_errmap(ERROR_ALREADY_EXISTS,              PCL_EEXIST)
_errmap(ERROR_INVALID_FLAG_NUMBER,         PCL_EINVAL)
_errmap(ERROR_ENVVAR_NOT_FOUND,            PCL_ENOTFOUND)
_errmap(ERROR_FILENAME_EXCED_RANGE,        PCL_ENAMETOOLONG)
_errmap(ERROR_META_EXPANSION_TOO_LONG,     PCL_ENAMETOOLONG)
_errmap(ERROR_INVALID_SIGNAL_NUMBER,       PCL_EINVAL)
_errmap(ERROR_LOCKED,                      PCL_ELOCK)
_errmap(ERROR_TOO_MANY_MODULES,            PCL_EMFILE)
_errmap(ERROR_NESTING_NOT_ALLOWED,         PCL_EACCES)
_errmap(ERROR_EXE_MACHINE_TYPE_MISMATCH,   PCL_ENOEXEC)
_errmap(ERROR_BAD_PIPE,                    PCL_EBADF)
_errmap(ERROR_PIPE_BUSY,                   PCL_EBUSY)
_errmap(ERROR_NO_DATA,                     PCL_EPIPE)
_errmap(ERROR_PIPE_NOT_CONNECTED,          PCL_EPIPE)
_errmap(WAIT_TIMEOUT,                      PCL_ETIMEOUT)
_errmap(ERROR_NO_MORE_ITEMS,               PCL_ENOMORE)
_errmap(ERROR_DIRECTORY,                   PCL_EPATH)
_errmap(ERROR_NOT_OWNER,                   PCL_EACCES)
_errmap(ERROR_PARTIAL_COPY,                PCL_ENOEXEC)
_errmap(ERROR_OPLOCK_NOT_GRANTED,          PCL_EACCES)
_errmap(ERROR_INVALID_ADDRESS,             PCL_EFAULT)
_errmap(ERROR_ARITHMETIC_OVERFLOW,         PCL_ERANGE)
_errmap(ERROR_EA_ACCESS_DENIED,            PCL_EACCES)
_errmap(ERROR_IO_PENDING,                  PCL_EAGAIN)
_errmap(ERROR_IO_INCOMPLETE,               PCL_EAGAIN)
_errmap(ERROR_NOACCESS,                    PCL_EACCES)
_errmap(ERROR_SWAPERROR,                   PCL_EFAULT)
_errmap(ERROR_STACK_OVERFLOW,              PCL_EFAULT)
_errmap(ERROR_INVALID_FLAGS,               PCL_EINVAL)
_errmap(ERROR_FILE_INVALID,                PCL_EFORMAT)
_errmap(ERROR_CANTOPEN,                    PCL_EPERM)
_errmap(ERROR_CANTREAD,                    PCL_EPERM)
_errmap(ERROR_CANTWRITE,                   PCL_EPERM)
_errmap(ERROR_REGISTRY_IO_FAILED,          PCL_EIO)
_errmap(ERROR_NO_LOG_SPACE,                PCL_ENOSPC)
_errmap(ERROR_NO_UNICODE_TRANSLATION,      PCL_EILSEQ)
_errmap(ERROR_IO_DEVICE,                   PCL_EIO)
_errmap(ERROR_CANCELLED,                   PCL_ECANCELLED)
_errmap(ERROR_INVALID_INDEX,               PCL_EINDEX)
_errmap(ERROR_SERVICE_REQUEST_TIMEOUT,     PCL_ETIMEOUT)
_errmap(ERROR_LOGON_FAILURE,               PCL_EAUTH)
_errmap(ERROR_INVALID_LOGON_HOURS,         PCL_EAUTH)
_errmap(ERROR_PASSWORD_EXPIRED,            PCL_EEXPIRED)
_errmap(ERROR_ACCOUNT_DISABLED,            PCL_EDISABLED)
_errmap(ERROR_INVALID_REPARSE_DATA,        PCL_EFORMAT)
_errmap(ERROR_REPARSE_TAG_INVALID,         PCL_ETYPE)
_errmap(ERROR_REPARSE_TAG_MISMATCH,        PCL_ETYPE)
_errmap(ERROR_INVALID_SUB_AUTHORITY,       PCL_EINVAL)
_errmap(ERROR_INVALID_ACL,                 PCL_EFORMAT)
_errmap(ERROR_INVALID_SID,                 PCL_EINVAL)
_errmap(ERROR_INVALID_SECURITY_DESCR,      PCL_EFORMAT)
_errmap(ERROR_ALLOTTED_SPACE_EXCEEDED,     PCL_EBUF)
_errmap(ERROR_INVALID_ID_AUTHORITY,        PCL_EINVAL)
_errmap(ERROR_NONE_MAPPED,                 PCL_ENOTFOUND)
_errmap(ERROR_PRIVILEGE_NOT_HELD,          PCL_EACCES)
_errmap(ERROR_INVALID_OWNER,               PCL_ETYPE)
_errmap(ERROR_INVALID_PRIMARY_GROUP,       PCL_ETYPE)
_errmap(ERROR_NO_TOKEN,                    PCL_ENOTFOUND)
_errmap(ERROR_NO_SUCH_LOGON_SESSION,       PCL_ENOTFOUND)
_errmap(ERROR_ACCOUNT_RESTRICTION,         PCL_EAUTH)
_errmap(ERROR_INVALID_WORKSTATION,         PCL_EAUTH)

/* Service Errors */
_errmap(ERROR_DEPENDENT_SERVICES_RUNNING, 	PCL_EBUSY)
_errmap(ERROR_INVALID_SERVICE_CONTROL,    	PCL_ETYPE)
_errmap(ERROR_SERVICE_REQUEST_TIMEOUT,    	PCL_ETIMEOUT)
_errmap(ERROR_SERVICE_NO_THREAD,          	PCL_EUNAVAIL)
_errmap(ERROR_SERVICE_DATABASE_LOCKED,    	PCL_ELOCK)
_errmap(ERROR_SERVICE_ALREADY_RUNNING,    	PCL_EALREADY)
_errmap(ERROR_INVALID_SERVICE_ACCOUNT,    	PCL_ETYPE)
_errmap(ERROR_SERVICE_DISABLED,           	PCL_EDISABLED)
_errmap(ERROR_CIRCULAR_DEPENDENCY,        	PCL_EINVAL)
_errmap(ERROR_SERVICE_DOES_NOT_EXIST,     	PCL_ENOTFOUND)
_errmap(ERROR_SERVICE_CANNOT_ACCEPT_CTRL, 	PCL_EINVAL)
_errmap(ERROR_SERVICE_NOT_ACTIVE,         	PCL_EUNAVAIL)
_errmap(ERROR_FAILED_SERVICE_CONTROLLER_CONNECT,	PCL_EBUSY)
_errmap(ERROR_EXCEPTION_IN_SERVICE,       	PCL_EUNDEF)
_errmap(ERROR_DATABASE_DOES_NOT_EXIST,    	PCL_ENOTFOUND)
_errmap(ERROR_SERVICE_SPECIFIC_ERROR,     	PCL_EUNDEF)
_errmap(ERROR_PROCESS_ABORTED,            	PCL_EABORT)
_errmap(ERROR_SERVICE_DEPENDENCY_FAIL,    	PCL_EUNAVAIL)
_errmap(ERROR_SERVICE_LOGON_FAILED,       	PCL_EAUTH)
_errmap(ERROR_SERVICE_START_HANG,         	PCL_EUNAVAIL)
_errmap(ERROR_INVALID_SERVICE_LOCK,       	PCL_EINVAL)
_errmap(ERROR_SERVICE_MARKED_FOR_DELETE,  	PCL_EUNAVAIL)
_errmap(ERROR_SERVICE_EXISTS,             	PCL_EEXIST)
_errmap(ERROR_ALREADY_RUNNING_LKG,        	PCL_EALREADY)
_errmap(ERROR_SERVICE_DEPENDENCY_DELETED, 	PCL_EUNAVAIL)
_errmap(ERROR_SERVICE_NEVER_STARTED,      	PCL_ENOTREADY)
_errmap(ERROR_DUPLICATE_SERVICE_NAME,     	PCL_EEXIST)
_errmap(ERROR_DIFFERENT_SERVICE_ACCOUNT,  	PCL_EAUTH)
_errmap(ERROR_CANNOT_DETECT_DRIVER_FAILURE, PCL_EUNDEF)
_errmap(ERROR_CANNOT_DETECT_PROCESS_ABORT,	PCL_EUNDEF)
_errmap(ERROR_NO_RECOVERY_PROGRAM,          PCL_EUNDEF)
_errmap(ERROR_SERVICE_NOT_IN_EXE,        	  PCL_ENOIMPL)
_errmap(ERROR_NOT_SAFEBOOT_SERVICE,      	  PCL_EUNAVAIL)
_errmap(E_NOINTERFACE,                      PCL_ENOTFOUND)
_errmap(REGDB_E_CLASSNOTREG,                PCL_ENOTFOUND)
_errmap(E_POINTER,                          PCL_EINVAL)
_errmap(0x80042316L,                        PCL_EINPROGRESS) /* VSS_E_SNAPSHOT_SET_IN_PROGRESS */

/* WSA Errors */
_errmap(WSAEADDRINUSE,                      PCL_EADDRINUSE)
_errmap(WSAEADDRNOTAVAIL,                   PCL_EADDRNOTAVAIL)
_errmap(WSAEAFNOSUPPORT,                    PCL_EAFNOSUPPORT)
_errmap(WSAECONNABORTED,                    PCL_ECONNABORTED)
_errmap(WSAECONNREFUSED,                    PCL_ECONNREFUSED)
_errmap(WSAECONNRESET,                      PCL_ECONNRESET)
_errmap(WSAEDESTADDRREQ,                    PCL_EDESTADDRREQ)
_errmap(WSAEHOSTDOWN,                       PCL_EHOSTDOWN)
_errmap(WSAEHOSTUNREACH,                    PCL_EHOSTUNREACH)
_errmap(WSAEISCONN,                         PCL_EISCONN)
_errmap(WSAEMSGSIZE,                        PCL_EMSGSIZE)

#if defined(WSAEMULTIHOP)
_errmap(WSAEMULTIHOP,                    PCL_EMULTIHOP)
#endif

_errmap(WSAENETDOWN,                       PCL_ENETDOWN)
_errmap(WSAENETRESET,                      PCL_ENETRESET)
_errmap(WSAENETUNREACH,                    PCL_ENETUNREACH)
_errmap(WSAENOBUFS,                        PCL_ENOBUFS)
_errmap(WSAENOPROTOOPT,                    PCL_ENOPROTOOPT)
_errmap(WSAENOTCONN,                       PCL_ENOTCONN)
_errmap(WSAENOTSOCK,                       PCL_ENOTSOCK)
_errmap(WSAEOPNOTSUPP,                     PCL_EOPNOTSUPP)
_errmap(WSAEPFNOSUPPORT,                   PCL_EPFNOSUPPORT)

#if defined(WSAPROTO)
_errmap(WSAEPROTO,                       PCL_EPROTO)
#endif

_errmap(WSAEPROTONOSUPPORT,                PCL_EPROTONOSUPPORT)
_errmap(WSAEPROTOTYPE,                     PCL_EPROTOTYPE)
_errmap(WSAEREMOTE,                        PCL_EREMOTE)
_errmap(WSAESHUTDOWN,                      PCL_ESHUTDOWN)
_errmap(WSAESOCKTNOSUPPORT,                PCL_ESOCKTNOSUPPORT)
_errmap(WSAESTALE,                         PCL_ESTALE)
_errmap(WSAETIMEDOUT,                      PCL_ETIMEOUT)
_errmap(WSAETOOMANYREFS,                   PCL_ETOOMANYREFS)
_errmap(WSAEUSERS,                         PCL_EUSERS)

/*
 * Windows has mapped some standard errors (like EFAULT) to WSA
 * codes.  Windows also has Non-Berkeley socket errors.
 */
_errmap(WSA_E_CANCELLED,                   PCL_ECANCELLED)
_errmap(WSA_E_NO_MORE,                     PCL_ENOMORE)
_errmap(WSAEACCES,                         PCL_EACCES)
_errmap(WSAEALREADY,                       PCL_EALREADY)
_errmap(WSAEBADF,                          PCL_EBADF)
_errmap(WSAECANCELLED,                     PCL_ECANCELLED)
_errmap(WSAEDISCON,                        PCL_ESHUTDOWN) /* gracefully shuting down socket */
_errmap(WSAEDQUOT,                         PCL_EDQUOT)
_errmap(WSAEFAULT,                         PCL_EFAULT)
_errmap(WSAEINPROGRESS,                    PCL_EINPROGRESS)
_errmap(WSAEINTR,                          PCL_EINTR)
_errmap(WSAEINVAL,                         PCL_EINVAL)
_errmap(WSAEINVALIDPROCTABLE,              PCL_EINVAL)
_errmap(WSAEINVALIDPROVIDER,               PCL_EINVAL)
_errmap(WSAELOOP,                          PCL_ELOOP)
_errmap(WSAEMFILE,                         PCL_EMFILE)
_errmap(WSAENAMETOOLONG,                   PCL_ENAMETOOLONG)
_errmap(WSAENOMORE,                        PCL_ENOMORE)
_errmap(WSAENOTEMPTY,                      PCL_ENOTEMPTY)
_errmap(WSAEPROCLIM,                       PCL_EPROCLIM)
_errmap(WSAEREFUSED,                       PCL_EACCES)
_errmap(WSAEWOULDBLOCK,                    PCL_EWOULDBLOCK)
_errmap(WSANOTINITIALISED,                 PCL_ENOTREADY)
_errmap(WSASYSNOTREADY,                    PCL_ENOTREADY)
_errmap(WSATYPE_NOT_FOUND,                 PCL_ETYPE)
_errmap(WSAVERNOTSUPPORTED,                PCL_ETYPE)
_errmap(WSAHOST_NOT_FOUND,                 PCL_EHOSTNOTFOUND)
_errmap(WSATRY_AGAIN,                      PCL_ETRYAGAIN)
_errmap(WSANO_RECOVERY,                    PCL_ENORECOVERY)
_errmap(WSANO_DATA,                        PCL_ENODATA)

#if WSANO_DATA != WSANO_ADDRESS /* VC7 remap */
_errmap(WSANO_ADDRESS,                   PCL_ENOADDRESS)
#endif

/* OLE Errors, not all but the most common */
_errmap(E_UNEXPECTED, 														PCL_EUNDEF)
_errmap(E_NOTIMPL,                 							PCL_ENOIMPL)
_errmap(E_OUTOFMEMORY,             							PCL_ENOMEM)
_errmap(E_INVALIDARG,              							PCL_EINVAL)
_errmap(E_NOINTERFACE,             							PCL_ENOIMPL)
_errmap(E_POINTER,                 							PCL_EFAULT)
_errmap(E_HANDLE,                  							PCL_EBADF)
_errmap(E_ABORT,                   							PCL_EABORT)
_errmap(E_FAIL,                    							PCL_EUNDEF)
_errmap(E_ACCESSDENIED,            							PCL_EACCES)
_errmap(E_PENDING,                 							PCL_EINPROGRESS)

/* RPC Errors (just a few) */
_errmap(RPC_E_CALL_REJECTED,                     PCL_EREJECTED)
_errmap(RPC_E_CALL_CANCELED,                     PCL_ECANCELLED)
_errmap(RPC_E_INVALID_DATAPACKET,                PCL_EFORMAT)
_errmap(RPC_E_INVALID_DATA,                      PCL_EFORMAT)
_errmap(RPC_E_INVALID_PARAMETER,                 PCL_EINVAL)
_errmap(RPC_E_OUT_OF_RESOURCES,                  PCL_ENOMEM)
_errmap(RPC_E_FAULT,                             PCL_EABORT)
_errmap(RPC_E_SERVERFAULT,                       PCL_EABORT)
_errmap(RPC_E_CHANGED_MODE,                 		 PCL_EINVAL)
_errmap(RPC_E_INVALIDMETHOD,                     PCL_ENOIMPL)
_errmap(RPC_E_RETRY,                             PCL_EAGAIN)
_errmap(RPC_E_SERVERCALL_RETRYLATER,             PCL_EAGAIN)
_errmap(RPC_E_SERVERCALL_REJECTED,               PCL_EREJECTED)
_errmap(RPC_E_VERSION_MISMATCH,                  PCL_EVERSION)
_errmap(RPC_E_INVALID_HEADER,                    PCL_EFORMAT)
_errmap(RPC_E_INVALID_OBJECT,                    PCL_ETYPE)
_errmap(RPC_E_ACCESS_DENIED,                     PCL_EACCES)
_errmap(RPC_E_REMOTE_DISABLED,                   PCL_EDISABLED)
_errmap(RPC_E_INVALID_OBJREF,                    PCL_EFORMAT)
_errmap(RPC_E_TIMEOUT,                           PCL_ETIMEOUT)
_errmap(RPC_E_NO_SYNC,                           PCL_ENOMORE)
_errmap(RPC_E_INVALID_STD_NAME,                  PCL_EINVAL)
_errmap(CO_E_ACCESSCHECKFAILED,                  PCL_EACCES)
_errmap(CO_E_NETACCESSAPIFAILED,                 PCL_EACCES)

/* Storage Errors */
_errmap(STG_E_INVALIDFUNCTION,        						PCL_ENOIMPL)
_errmap(STG_E_FILENOTFOUND,           						PCL_ENOENT)
_errmap(STG_E_PATHNOTFOUND,           						PCL_ENOENT)
_errmap(STG_E_TOOMANYOPENFILES,       						PCL_ENFILE)
_errmap(STG_E_ACCESSDENIED,           						PCL_EACCES)
_errmap(STG_E_INVALIDHANDLE,          						PCL_EBADF)
_errmap(STG_E_INSUFFICIENTMEMORY,     						PCL_ENOMEM)
_errmap(STG_E_INVALIDPOINTER,         						PCL_EINVAL)
_errmap(STG_E_NOMOREFILES,            						PCL_ENOMORE)
_errmap(STG_E_DISKISWRITEPROTECTED,   						PCL_EACCES)
_errmap(STG_E_SEEKERROR,              						PCL_ESPIPE)
_errmap(STG_E_WRITEFAULT,             						PCL_EIO)
_errmap(STG_E_READFAULT,              						PCL_EIO)
_errmap(STG_E_SHAREVIOLATION,         						PCL_ELOCK)
_errmap(STG_E_LOCKVIOLATION,          						PCL_ELOCK)
_errmap(STG_E_FILEALREADYEXISTS,      						PCL_EEXIST)
_errmap(STG_E_INVALIDPARAMETER,       						PCL_EINVAL)
_errmap(STG_E_MEDIUMFULL,             						PCL_ENOSPC)
_errmap(STG_E_PROPSETMISMATCHED,      						PCL_EFORMAT)
_errmap(STG_E_ABNORMALAPIEXIT,        						PCL_EFAULT)
_errmap(STG_E_INVALIDHEADER,          						PCL_EINVAL)
_errmap(STG_E_INVALIDNAME,            						PCL_EINVAL)
_errmap(STG_E_UNKNOWN,                						PCL_EUNDEF)
_errmap(STG_E_UNIMPLEMENTEDFUNCTION,  						PCL_ENOIMPL)
_errmap(STG_E_INVALIDFLAG,            						PCL_EINVAL)
_errmap(STG_E_INUSE,                  						PCL_EBUSY)
_errmap(STG_E_NOTCURRENT,             						PCL_EEXPIRED)
_errmap(STG_E_REVERTED,               						PCL_EREVOKED)
_errmap(STG_E_CANTSAVE,               						PCL_EPERM)
_errmap(STG_E_OLDFORMAT,              						PCL_EFORMAT)
_errmap(STG_E_OLDDLL,                 						PCL_EVERSION)
_errmap(STG_E_SHAREREQUIRED,          						PCL_EACCES)
_errmap(STG_E_NOTFILEBASEDSTORAGE,    						PCL_ETYPE)
_errmap(STG_E_EXTANTMARSHALLINGS,     						PCL_ENOTSUP)
_errmap(STG_E_DOCFILECORRUPT,         						PCL_EFORMAT)
_errmap(STG_E_BADBASEADDRESS,         						PCL_EFAULT)
_errmap(STG_E_DOCFILETOOLARGE,        						PCL_EFBIG)
_errmap(STG_E_NOTSIMPLEFORMAT,        						PCL_EFORMAT)

/* DNS errors (not the best mapping) */
_errmap(DNS_ERROR_RCODE_FORMAT_ERROR,             PCL_EFORMAT)
_errmap(DNS_ERROR_RCODE_SERVER_FAILURE,           PCL_ECONNABORTED)
_errmap(DNS_ERROR_RCODE_NAME_ERROR,               PCL_ENOTFOUND)
_errmap(DNS_ERROR_RCODE_NOT_IMPLEMENTED,          PCL_ENOIMPL)
_errmap(DNS_ERROR_RCODE_REFUSED,                  PCL_EACCES)
_errmap(DNS_ERROR_RCODE_YXDOMAIN,                 PCL_ENOTFOUND)
_errmap(DNS_ERROR_RCODE_YXRRSET,                  PCL_ENOTFOUND)
_errmap(DNS_ERROR_RCODE_NXRRSET,                  PCL_ENOTFOUND)
_errmap(DNS_ERROR_RCODE_NOTAUTH,                  PCL_EAUTH)
_errmap(DNS_ERROR_RCODE_NOTZONE,                  PCL_ENOTFOUND)
_errmap(DNS_ERROR_RCODE_BADSIG,                   PCL_EACCES)
_errmap(DNS_ERROR_RCODE_BADKEY,                   PCL_EACCES)
_errmap(DNS_ERROR_RCODE_BADTIME,                  PCL_EACCES)
