‪libpcl: ‪Dynamic Buffer
Dynamic Buffer
‪The buffer API provides a dynamically sized buffer for putting text and/or binary data.
Macros
#define pcl_buf_putchar(b, c) pcl_buf_putint8(b, (int8_t)(c))
‪Put a character into a buffer.
#define pcl_buf_getchar(b, chp) pcl_buf_getint8(b, (uint8_t *)(chp))
‪Get a character from a buffer.
Typedefs
typedef struct tag_pcl_buf pcl_buf_t
Functions
PCL_EXPORT pcl_buf_t * pcl_buf_init (pcl_buf_t *b, size_t size, bool text_mode)
‪Initializes a buffer object.
PCL_EXPORT pcl_buf_t * pcl_buf_grow (pcl_buf_t *b, int len)
‪Grow a buffer.
PCL_EXPORT pcl_buf_t * pcl_buf_reset (pcl_buf_t *b)
‪Reset a buffer to its initial state.
PCL_EXPORT pcl_buf_t * pcl_buf_clear (pcl_buf_t *b)
‪Clear a buffer.
PCL_EXPORT pcl_buf_t * pcl_buf_copy (pcl_buf_t *dest, const pcl_buf_t *src)
‪Copy a buffer.
PCL_EXPORT int pcl_buf_pos (pcl_buf_t *b, int *newpos)
‪Get or set the buffer position.
PCL_EXPORT char * pcl_buf_data (pcl_buf_t *b, int *lenp)
‪Get the buffer's data.
PCL_EXPORT pcl_buf_t * pcl_buf_free (pcl_buf_t *b)
‪Free all buffer resources and the buffer object itself.
PCL_EXPORT int pcl_buf_put (pcl_buf_t *b, const void *data, int len)
‪Put a blob into a buffer.
PCL_EXPORT int pcl_buf_putstr (pcl_buf_t *b, const char *s)
‪Put a string into a buffer.
PCL_INLINE int pcl_buf_putint8 (pcl_buf_t *b, uint8_t i)
‪Put an 8-bit integer into a buffer.
PCL_EXPORT int pcl_buf_putint16 (pcl_buf_t *b, uint16_t i)
‪Puts a 16-bit integer into a buffer in network-byte order.
PCL_EXPORT int pcl_buf_putint32 (pcl_buf_t *b, uint32_t i)
‪Puts a 32-bit integer into a buffer in network-byte order.
PCL_EXPORT int pcl_buf_putint64 (pcl_buf_t *b, uint64_t i)
‪Puts a 64-bit integer into a buffer in network-byte order.
PCL_EXPORT int pcl_buf_putf (pcl_buf_t *b, const char *format,...)
‪Put a formatted string into a buffer.
PCL_EXPORT int pcl_buf_vputf (pcl_buf_t *b, const char *format, va_list ap)
‪Put a formatted string into a buffer.
PCL_EXPORT int pcl_buf_get (pcl_buf_t *b, void *buf, int len)
‪Get a blob from a buffer.
PCL_EXPORT int pcl_buf_getstr (pcl_buf_t *b, char *buf, int len)
‪Get a string from a buffer.
PCL_INLINE int pcl_buf_getint8 (pcl_buf_t *b, uint8_t *i)
‪Get an 8-bit integer a the buffer.
PCL_EXPORT int pcl_buf_getint16 (pcl_buf_t *b, uint16_t *i)
‪Get a 16-bit integer from a buffer in host-byte order.
PCL_EXPORT int pcl_buf_getint32 (pcl_buf_t *b, uint32_t *i)
‪Get a 32-bit integer from a buffer in host-byte order.
PCL_EXPORT int pcl_buf_getint64 (pcl_buf_t *b, uint64_t *i)
‪Get a 64-bit integer from a buffer in host-byte order.
Detailed Description
The buffer API provides a dynamically sized buffer for putting text and/or binary data.
The buffer supports two modes: binary and text. In either mode, a trailing NUL is always written at the end of the buffer. This space is reserved internally.
Binary Mode
In binary mode, the buffer is an array of data type: integers, strings and blobs. Strings are written to the buffer with trailing NULs, avoiding the need to prefix string data with a length.
pcl_buf_t *buf = pcl_buf_init(NULL, 64, false);
pcl_buf_putstr(buf, "Hello"); // buffer contents: "Hello\0\0"
pcl_buf_putstr(buf, "World"); // buffer contents: "Hello\0World\0\0"
// binary mode only, "Hello\0World\0[32 bits in network-byte order]\0"
pcl_buf_putint32(buf, 3897463623);
pcl_buf_free(buf);
Binary mode supports putting and getting integer types: 8-bit, 16-bit, 32-bit and 64-bit. In all cases, integer types are written to the buffer in network-byte order.
Text Mode
In text mode, the buffer is an array of bytes: string buffer. In this mode, integer types cannot be used and those functions will return an error. Strings are written without a trailing NUL byte.
pcl_buf_t buf; // use stack memory
pcl_buf_init(&buf, 64, true);
pcl_buf_putstr(&buf, "Hello"); // buffer contents: "Hello\0"
pcl_buf_putstr(&buf, "World"); // buffer contains: "HelloWorld\0"
int len;
char *text = pcl_buf_data(&buf, &len); // len is optional
printf("%d] %s\n", len, text); // 10] HelloWorld
pcl_buf_clear(&buf); // 'text' invalid
Once all text data has been put, the data buffer can be retreived using pcl_buf_data. The returned pointer is a NUL terminated string. It is very common to use the printf style buffer functions while in text mode but can also be used in binary.
Macro Definition Documentation
pcl_buf_putchar
#define pcl_buf_putchar (b, c) pcl_buf_putint8(b, (int8_t)(c))
#include <pcl/buf.h>
‪Put a character into a buffer.
Parameters
b ‪pointer to a buffer
c ‪character
Returns
‪number of bytes written or -1 on error
Definition at line 173 of file buf.h.
pcl_buf_getchar
#define pcl_buf_getchar (b, chp) pcl_buf_getint8(b, (uint8_t *)(chp))
#include <pcl/buf.h>
‪Get a character from a buffer.
Parameters
b ‪pointer to a buffer
[out] chp ‪pointer to a character
Returns
‪number of bytes read or -1 on error
Definition at line 244 of file buf.h.
Typedef Documentation
pcl_buf_t
typedef struct tag_pcl_buf pcl_buf_t
#include <pcl/types.h>
Definition at line 59 of file types.h.
Function Documentation
pcl_buf_init()
PCL_EXPORT pcl_buf_t* pcl_buf_init (pcl_buf_t * b, size_t size, bool text_mode)
#include <pcl/buf.h>
‪Initializes a buffer object.
Parameters
b ‪pointer to a buffer to intialize. If this is NULL, a buffer will be allocated
size ‪intial size in bytes of the buffer
text_mode ‪indicates if this is a binary or text mode buffer
Returns
‪pointer to b if it was not NULL or a pointer to a newly allocated buffer.
pcl_buf_grow()
PCL_EXPORT pcl_buf_t* pcl_buf_grow (pcl_buf_t * b, int len)
#include <pcl/buf.h>
‪Grow a buffer.
Given a len, this ensures that writing len bytes won't overflow the buffer by reallocating the buffer's internal memory. This is used by all buffer put functions before attempting to write data.
Parameters
b ‪pointer to a buffer
len ‪number of new bytes to be added to the buffer
Returns
‪pointer to b or NULL on error
pcl_buf_reset()
PCL_EXPORT pcl_buf_t* pcl_buf_reset (pcl_buf_t * b)
#include <pcl/buf.h>
‪Reset a buffer to its initial state.
This sets the buffer's position and length to zero.
Parameters
b ‪pointer to a buffer
Returns
‪pointer to the b argument
pcl_buf_clear()
PCL_EXPORT pcl_buf_t* pcl_buf_clear (pcl_buf_t * b)
#include <pcl/buf.h>
‪Clear a buffer.
This is similar to a reset but also releases all resources used by the buffer.
Parameters
b ‪pointer to a buffer
Returns
‪pointer to the b argument
pcl_buf_copy()
PCL_EXPORT pcl_buf_t* pcl_buf_copy (pcl_buf_t * dest, const pcl_buf_t * src)
#include <pcl/buf.h>
‪Copy a buffer.
Parameters
dest ‪pointer to a buffer or NULL in which case this is allocated.
src ‪pointer to the buffer to copy
Returns
‪pointer to dest or, if dest is NULL, a newly allocated buffer
pcl_buf_pos()
PCL_EXPORT int pcl_buf_pos (pcl_buf_t * b, int * newpos)
#include <pcl/buf.h>
‪Get or set the buffer position.
Parameters
b ‪buffer pointer
newpos ‪new position for the buffer, or NULL to only get the current position.
Returns
‪If newpos is NULL, this returns the current position. If newpos is provided, this returns the previous position. If an error occurs, -1 is returned.
pcl_buf_data()
PCL_EXPORT char* pcl_buf_data (pcl_buf_t * b, int * lenp)
#include <pcl/buf.h>
‪Get the buffer's data.
This can also be used to retreive the buffer length.
Parameters
b ‪pointer to a buffer
[out] lenp ‪If not NULL, the buffer's length is written here
Returns
‪pointer to the data or NULL on error
pcl_buf_free()
PCL_EXPORT pcl_buf_t* pcl_buf_free (pcl_buf_t * b)
#include <pcl/buf.h>
‪Free all buffer resources and the buffer object itself.
Do not pass stack memory to this function. Instead, use pcl_buf_clear.
Parameters
b ‪pointer to a buffer
Returns
‪always NULL
pcl_buf_put()
PCL_EXPORT int pcl_buf_put (pcl_buf_t * b, const void * data, int len)
#include <pcl/buf.h>
‪Put a blob into a buffer.
Parameters
b ‪pointer to a buffer
data ‪pointer to the data to write to the buffer
len ‪number of bytes to put
Returns
‪number of bytes written or -1 on error
Referenced by pcl_buf_putint8().
pcl_buf_putstr()
PCL_EXPORT int pcl_buf_putstr (pcl_buf_t * b, const char * s)
#include <pcl/buf.h>
‪Put a string into a buffer.
Parameters
b ‪pointer to a buffer
s ‪pointer to a string
Returns
‪number of bytes written (including NUL if in binary mode) or -1 on error
pcl_buf_putint8()
PCL_INLINE int pcl_buf_putint8 (pcl_buf_t * b, uint8_t i)
#include <pcl/buf.h>
‪Put an 8-bit integer into a buffer.
Parameters
b ‪pointer to a buffer
i ‪8-bit integer to put
Returns
‪number of bytes written or -1 on error
Definition at line 181 of file buf.h.
References pcl_buf_put().
pcl_buf_putint16()
PCL_EXPORT int pcl_buf_putint16 (pcl_buf_t * b, uint16_t i)
#include <pcl/buf.h>
‪Puts a 16-bit integer into a buffer in network-byte order.
Parameters
b ‪pointer to a buffer
i ‪16-bit integer to put
Returns
‪number of bytes written or -1 on error
pcl_buf_putint32()
PCL_EXPORT int pcl_buf_putint32 (pcl_buf_t * b, uint32_t i)
#include <pcl/buf.h>
‪Puts a 32-bit integer into a buffer in network-byte order.
Parameters
b ‪pointer to a buffer
i ‪32-bit integer to put
Returns
‪number of bytes written or -1 on error
pcl_buf_putint64()
PCL_EXPORT int pcl_buf_putint64 (pcl_buf_t * b, uint64_t i)
#include <pcl/buf.h>
‪Puts a 64-bit integer into a buffer in network-byte order.
Parameters
b ‪pointer to a buffer
i ‪64-bit integer to put
Returns
‪number of bytes written or -1 on error
pcl_buf_putf()
PCL_EXPORT int pcl_buf_putf (pcl_buf_t * b, const char * format, ...)
#include <pcl/buf.h>
‪Put a formatted string into a buffer.
Parameters
b ‪pointer to a buffer
format ‪PCL format string
... ‪variable arguments
Returns
‪number of bytes written (including NUL if in binary mode) or -1 on error
pcl_buf_vputf()
PCL_EXPORT int pcl_buf_vputf (pcl_buf_t * b, const char * format, va_list ap)
#include <pcl/buf.h>
‪Put a formatted string into a buffer.
Parameters
b ‪pointer to a buffer
format ‪PCL format string
ap ‪variable arguments
Returns
‪number of bytes written (including NUL if in binary mode) or -1 on error
pcl_buf_get()
PCL_EXPORT int pcl_buf_get (pcl_buf_t * b, void * buf, int len)
#include <pcl/buf.h>
‪Get a blob from a buffer.
Parameters
b ‪pointer to a buffer
[out] buf ‪a buffer used to store the result
len ‪length in bytes of buf
Returns
‪number of bytes read or -1 on error
Referenced by pcl_buf_getint8().
pcl_buf_getstr()
PCL_EXPORT int pcl_buf_getstr (pcl_buf_t * b, char * buf, int len)
#include <pcl/buf.h>
‪Get a string from a buffer.
Parameters
b ‪pointer to a buffer
[out] buf ‪a buffer used to store the result
len ‪length in bytes of buf
Returns
‪number of bytes read (including NUL if in binary mode) or -1 on error
pcl_buf_getint8()
PCL_INLINE int pcl_buf_getint8 (pcl_buf_t * b, uint8_t * i)
#include <pcl/buf.h>
‪Get an 8-bit integer a the buffer.
Parameters
b ‪pointer to a buffer
[out] i ‪pointer to a 8-bit integer
Returns
‪number of bytes read or -1 on error
Definition at line 252 of file buf.h.
References pcl_buf_get().
pcl_buf_getint16()
PCL_EXPORT int pcl_buf_getint16 (pcl_buf_t * b, uint16_t * i)
#include <pcl/buf.h>
‪Get a 16-bit integer from a buffer in host-byte order.
Parameters
b ‪pointer to a buffer
[out] i ‪pointer to a 16-bit integer
Returns
‪number of bytes read or -1 on error
pcl_buf_getint32()
PCL_EXPORT int pcl_buf_getint32 (pcl_buf_t * b, uint32_t * i)
#include <pcl/buf.h>
‪Get a 32-bit integer from a buffer in host-byte order.
Parameters
b ‪pointer to a buffer
[out] i ‪pointer to a 32-bit integer
Returns
‪number of bytes read or -1 on error
pcl_buf_getint64()
PCL_EXPORT int pcl_buf_getint64 (pcl_buf_t * b, uint64_t * i)
#include <pcl/buf.h>
‪Get a 64-bit integer from a buffer in host-byte order.
Parameters
b ‪pointer to a buffer
[out] i ‪pointer to a 64bit integer
Returns
‪number of bytes read or -1 on error