‪libpcl: ‪pcl/socket.h File Reference
socket.h File Reference
#include <pcl/types.h>
#include <winsock2.h>
Data Structures
struct pcl_keepalive_t
Macros
#define PCL_SOCK_NONBLOCK 0x01
#define PCL_SOCK_CONNECTED 0x02
#define INVALID_SOCKET (pcl_socketfd_t)(-1)
#define POLLRDHUP 0x2000
#define SHUT_RD 0 /* No more receptions. */
#define SHUT_WR 1 /* No more transmissions. */
#define SHUT_RDWR 2 /* No more receptions or transmissions. */
Functions
PCL_EXPORT pcl_socket_t * pcl_socket (const char *host, int port)
PCL_EXPORT int pcl_connect (pcl_socket_t *sock)
PCL_EXPORT pcl_socket_t * pcl_accept (pcl_socket_t *sock)
PCL_EXPORT int pcl_select (int fds, fd_set *rset, fd_set *wset, fd_set *eset, struct timeval *tv)
PCL_EXPORT void pcl_shutdown (pcl_socket_t *sock, int how)
PCL_EXPORT ssize_t pcl_recv (pcl_socket_t *sock, void *buf, size_t count, int flags)
PCL_EXPORT bool pcl_recvall (pcl_socket_t *sock, void *buf, size_t count)
PCL_EXPORT ssize_t pcl_send (pcl_socket_t *sock, const void *data, size_t count, int flags)
PCL_EXPORT bool pcl_sendall (pcl_socket_t *sock, const void *data, size_t count)
PCL_EXPORT int pcl_bind (pcl_socket_t *sock)
PCL_EXPORT int pcl_listen (pcl_socket_t *sock, int backlog)
PCL_EXPORT void pcl_socket_close (pcl_socket_t *sock)
PCL_EXPORT bool pcl_socket_isalive (pcl_socket_t *sock)
PCL_EXPORT int pcl_socket_error (pcl_socket_t *sock)
PCL_EXPORT pcl_socketfd_t pcl_socket_fd (pcl_socket_t *sock)
PCL_EXPORT char * pcl_socket_ip (pcl_socket_t *sock)
PCL_EXPORT int pcl_socket_port (pcl_socket_t *sock)
PCL_EXPORT int pcl_socket_setrcvtimeo (pcl_socket_t *sock, uint32_t msecs)
PCL_EXPORT int pcl_socket_setsndtimeo (pcl_socket_t *sock, uint32_t msecs)
PCL_EXPORT int pcl_socket_setnonblocking (pcl_socket_t *sock, bool enable)
PCL_EXPORT void pcl_socket_setkeepalive (pcl_socket_t *sock, pcl_keepalive_t *ka)
PCL_EXPORT bool pcl_ispassive (pcl_socket_t *sock)
Macro Definition Documentation
PCL_SOCK_NONBLOCK
#define PCL_SOCK_NONBLOCK 0x01
Definition at line 53 of file socket.h.
PCL_SOCK_CONNECTED
#define PCL_SOCK_CONNECTED 0x02
Definition at line 54 of file socket.h.
INVALID_SOCKET
#define INVALID_SOCKET (pcl_socketfd_t)(-1)
Definition at line 57 of file socket.h.
POLLRDHUP
#define POLLRDHUP 0x2000
Definition at line 62 of file socket.h.
SHUT_RD
#define SHUT_RD 0 /* No more receptions. */
Definition at line 65 of file socket.h.
SHUT_WR
#define SHUT_WR 1 /* No more transmissions. */
Definition at line 68 of file socket.h.
SHUT_RDWR
#define SHUT_RDWR 2 /* No more receptions or transmissions. */
Definition at line 71 of file socket.h.
Function Documentation
pcl_socket()
PCL_EXPORT pcl_socket_t* pcl_socket (const char * host, int port)
Definition at line 46 of file socket.c.
References tag_pcl_socket::addr, tag_pcl_socket::fd, INVALID_SOCKET, ipcl_socket_alloc(), PCL_EAFNOSUPPORT, PCL_EINVAL, PCL_EPFNOSUPPORT, pcl_net_ai2pcl(), pcl_socket_close(), pcl_strcpy(), R_SETERR, tag_pcl_socket::sa_len, tag_pcl_socket::sa_protocol, tag_pcl_socket::sa_socktype, SETERR, SETERRMSG, SETLASTERR, strempty, and TRC.
Referenced by ipcl_ssl_configure_socket().
pcl_connect()
PCL_EXPORT int pcl_connect (pcl_socket_t * sock)
Definition at line 36 of file connect.c.
References tag_pcl_socket::addr, tag_pcl_socket::fd, tag_pcl_socket::flags, INVALID_SOCKET, PCL_EAGAIN, PCL_EALREADY, PCL_EINPROGRESS, PCL_EINTR, PCL_EINVAL, PCL_EISCONN, pcl_err_os2pcl(), PCL_SOCK_CONNECTED, pcl_sockerrno, tag_pcl_socket::sa_len, and SETERR.
Referenced by pcl_ssl_connect().
pcl_accept()
PCL_EXPORT pcl_socket_t* pcl_accept (pcl_socket_t * sock)
Definition at line 41 of file accept.c.
References tag_pcl_socket::addr, tag_pcl_socket::fd, tag_pcl_socket::flags, INVALID_SOCKET, ipcl_socket_alloc(), PCL_EAGAIN, PCL_EINPROGRESS, PCL_EINTR, pcl_err_os2pcl(), PCL_SOCK_CONNECTED, PCL_SOCK_NONBLOCK, pcl_sockerrno, pcl_socket_close(), pcl_socket_setnonblocking(), R_SETERR, tag_pcl_socket::sa_len, tag_pcl_socket::sa_protocol, and tag_pcl_socket::sa_socktype.
Referenced by pcl_ssl_accept().
pcl_select()
PCL_EXPORT int pcl_select (int fds, fd_set * rset, fd_set * wset, fd_set * eset, struct timeval * tv)
Definition at line 37 of file select.c.
References pcl_clock(), PCL_ETIMEOUT, pcl_usecdiff(), PCL_USECS, R_SETERR, and SETLASTERR.
pcl_shutdown()
PCL_EXPORT void pcl_shutdown (pcl_socket_t * sock, int how)
Definition at line 35 of file shutdown.c.
References tag_pcl_socket::fd, tag_pcl_socket::flags, INVALID_SOCKET, PCL_SOCK_CONNECTED, and SHUT_RDWR.
pcl_recv()
PCL_EXPORT ssize_t pcl_recv (pcl_socket_t * sock, void * buf, size_t count, int flags)
Definition at line 36 of file recv.c.
References tag_pcl_socket::fd, PCL_EAGAIN, PCL_EINTR, PCL_EINVAL, pcl_err_os2pcl(), PCL_EWOULDBLOCK, pcl_sockerrno, pcl_socket_isalive(), and SETERR.
Referenced by pcl_recvall().
pcl_recvall()
PCL_EXPORT bool pcl_recvall (pcl_socket_t * sock, void * buf, size_t count)
Definition at line 36 of file recvall.c.
References PCL_ECONNRESET, pcl_recv(), SETERR, and TRC.
pcl_send()
PCL_EXPORT ssize_t pcl_send (pcl_socket_t * sock, const void * data, size_t count, int flags)
Definition at line 36 of file send.c.
References tag_pcl_socket::fd, PCL_EAGAIN, PCL_EINTR, PCL_EINVAL, pcl_err_os2pcl(), PCL_EWOULDBLOCK, pcl_sockerrno, pcl_socket_isalive(), and SETERR.
Referenced by pcl_sendall().
pcl_sendall()
PCL_EXPORT bool pcl_sendall (pcl_socket_t * sock, const void * data, size_t count)
Definition at line 36 of file sendall.c.
References pcl_send(), and R_TRC.
pcl_bind()
PCL_EXPORT int pcl_bind (pcl_socket_t * sock)
Definition at line 45 of file bind.c.
References tag_pcl_socket::addr, tag_pcl_socket::fd, pcl_free(), pcl_sockerrno, pcl_unlink(), pcl_utf8_to_pcs(), tag_pcl_socket::sa_len, and SETOSERR.
Referenced by pcl_ssl_create().
pcl_listen()
PCL_EXPORT int pcl_listen (pcl_socket_t * sock, int backlog)
Definition at line 36 of file listen.c.
References tag_pcl_socket::fd, max, pcl_sockerrno, and SETOSERR.
Referenced by pcl_ssl_create().
pcl_socket_close()
PCL_EXPORT void pcl_socket_close (pcl_socket_t * sock)
Definition at line 40 of file socket_close.c.
References tag_pcl_socket::fd, INVALID_SOCKET, tag_pcl_socket::ipaddr, pcl_free(), and pcl_free_safe().
Referenced by pcl_accept(), pcl_socket(), and pcl_ssl_close().
pcl_socket_isalive()
PCL_EXPORT bool pcl_socket_isalive (pcl_socket_t * sock)
Definition at line 35 of file socket_isalive.c.
References tag_pcl_socket::fd, tag_pcl_socket::flags, INVALID_SOCKET, and PCL_SOCK_CONNECTED.
Referenced by pcl_recv(), pcl_send(), pcl_ssl_connect(), and pcl_ssl_isalive().
pcl_socket_error()
PCL_EXPORT int pcl_socket_error (pcl_socket_t * sock)
Definition at line 40 of file socket_error.c.
References tag_pcl_socket::fd, PCL_EOKAY, and pcl_err_os2pcl().
pcl_socket_fd()
PCL_EXPORT pcl_socketfd_t pcl_socket_fd (pcl_socket_t * sock)
Definition at line 36 of file socket_fd.c.
References tag_pcl_socket::fd, INVALID_SOCKET, PCL_EINVAL, and R_SETERR.
Referenced by ipcl_ssl_configure_socket(), pcl_ssl_accept(), and pcl_ssl_connect().
pcl_socket_ip()
PCL_EXPORT char* pcl_socket_ip (pcl_socket_t * sock)
Definition at line 39 of file socket_ip.c.
References tag_pcl_socket::addr, tag_pcl_socket::ipaddr, PCL_EINVAL, PCL_MAXIPLEN, pcl_net_addr2ip(), pcl_strdup(), R_SETERR, and R_TRC.
pcl_socket_port()
PCL_EXPORT int pcl_socket_port (pcl_socket_t * sock)
Definition at line 40 of file socket_port.c.
References tag_pcl_socket::addr, PCL_EINVAL, and SETERR.
pcl_socket_setrcvtimeo()
PCL_EXPORT int pcl_socket_setrcvtimeo (pcl_socket_t * sock, uint32_t msecs)
Definition at line 36 of file socket_setrcvtimeo.c.
References tag_pcl_socket::fd, pcl_sockerrno, and SETOSERR.
pcl_socket_setsndtimeo()
PCL_EXPORT int pcl_socket_setsndtimeo (pcl_socket_t * sock, uint32_t msecs)
Definition at line 36 of file socket_setsndtimeo.c.
References tag_pcl_socket::fd, pcl_sockerrno, and SETOSERR.
pcl_socket_setnonblocking()
PCL_EXPORT int pcl_socket_setnonblocking (pcl_socket_t * sock, bool enable)
Definition at line 40 of file socket_setnonblocking.c.
References tag_pcl_socket::fd, tag_pcl_socket::flags, PCL_SOCK_NONBLOCK, pcl_sockerrno, SETLASTERR, and SETOSERR.
Referenced by ipcl_ssl_configure_socket(), and pcl_accept().
pcl_socket_setkeepalive()
PCL_EXPORT void pcl_socket_setkeepalive (pcl_socket_t * sock, pcl_keepalive_t * ka)
Definition at line 40 of file socket_setkeepalive.c.
References pcl_keepalive_t::enable, tag_pcl_socket::fd, pcl_keepalive_t::idle, pcl_keepalive_t::interval, and pcl_keepalive_t::probes.
pcl_ispassive()
PCL_EXPORT bool pcl_ispassive (pcl_socket_t * sock)
Definition at line 40 of file socket_ispassive.c.
References tag_pcl_socket::fd, and SETLASTERR.