‪libpcl: ‪pcl/log.h File Reference
log.h File Reference
#include <pcl/time.h>
#include <pcl/defs.h>
Data Structures
struct tag_pcl_log_event
Macros
#define PCL_LOGLEV_DEBUG 0x000001u
#define PCL_LOGLEV_INFO 0x000002u
#define PCL_LOGLEV_WARN 0x000004u
#define PCL_LOGLEV_ERROR 0x000008u
#define PCL_LOGLEV_FATAL 0x000010u
#define PCL_LOGLEV_PANIC 0x000020u
#define PCL_LOGTRC_DEBUG 0x000100u
#define PCL_LOGTRC_INFO 0x000200u
#define PCL_LOGTRC_WARN 0x000400u
#define PCL_LOGTRC_ERROR 0x000800u
#define PCL_LOGTRC_FATAL 0x001000u
#define PCL_LOGTRC_PANIC 0x002000u
#define PCL_LOGOPT_UTC 0x010000u
#define PCL_LOG_MAXLEVELSTR 48u
#define PCL_LOGLEV_MASK 0x00ffu /* log level mask */
#define PCL_LOGTRC_MASK 0xff00u /* log trace mask */
#define PCL_LOGTRC_LSH 8u /* no. of bits to left shift level to get trace bit */
#define PCL_LOGLEV_TOTRACE(_level) (((_level) & (unsigned)PCL_LOGLEV_MASK) << (unsigned)PCL_LOGTRC_LSH)
#define PCL_LOGLEV_HASTRACE(_level) ((_level) & PCL_LOGLEV_TOTRACE(_level))
#define PCL_LOG_TIMEFORMAT "%b %d %H:%M:%S"
#define PCL_LOG_OPEN_MODE _P("a+b")
#define PCL_LOG_EVENT(level, msg, ...) pcl_log_event_default(PCL_LOCATION_ARGS, (uint32_t)(level), msg, __VA_ARGS__)
#define LOG_PANIC(msg, ...) PCL_LOG_EVENT(PCL_LOGLEV_PANIC, msg, __VA_ARGS__)
#define LOG_FATAL(msg, ...) PCL_LOG_EVENT(PCL_LOGLEV_FATAL, msg, __VA_ARGS__)
#define LOG_ERROR(msg, ...) PCL_LOG_EVENT(PCL_LOGLEV_ERROR, msg, __VA_ARGS__)
#define LOG_WARN(msg, ...) PCL_LOG_EVENT(PCL_LOGLEV_WARN, msg, __VA_ARGS__)
#define LOG_INFO(msg, ...) PCL_LOG_EVENT(PCL_LOGLEV_INFO, msg, __VA_ARGS__)
#define LOG_DEBUG(msg, ...) PCL_LOG_EVENT(PCL_LOGLEV_DEBUG, msg, __VA_ARGS__)
#define PCL_LOG_ERR(_e, _l, _m, ...)
#define LOG_PANIC_ERR(_e, _m, ...) PCL_LOG_ERR(_e,PCL_LOGLEV_PANIC,_m,__VA_ARGS__)
#define LOG_FATAL_ERR(_e, _m, ...) PCL_LOG_ERR(_e,PCL_LOGLEV_FATAL,_m,__VA_ARGS__)
#define LOG_ERROR_ERR(_e, _m, ...) PCL_LOG_ERR(_e,PCL_LOGLEV_ERROR,_m,__VA_ARGS__)
#define LOG_WARN_ERR(_e, _m, ...) PCL_LOG_ERR(_e,PCL_LOGLEV_WARN,_m,__VA_ARGS__)
#define LOG_INFO_ERR(_e, _m, ...) PCL_LOG_ERR(_e,PCL_LOGLEV_INFO,_m,__VA_ARGS__)
#define LOG_DEBUG_ERR(_e, _m, ...) PCL_LOG_ERR(_e,PCL_LOGLEV_DEBUG,_m,__VA_ARGS__)
#define PCL_LOG_OS(_o, _l, _m, ...)
#define LOG_PANIC_OS(_o, _m, ...) PCL_LOG_OS(_o,PCL_LOGLEV_PANIC,_m,__VA_ARGS__)
#define LOG_FATAL_OS(_o, _m, ...) PCL_LOG_OS(_o,PCL_LOGLEV_FATAL,_m,__VA_ARGS__)
#define LOG_ERROR_OS(_o, _m, ...) PCL_LOG_OS(_o,PCL_LOGLEV_ERROR,_m,__VA_ARGS__)
#define LOG_WARN_OS(_o, _m, ...) PCL_LOG_OS(_o,PCL_LOGLEV_WARN,_m,__VA_ARGS__)
#define LOG_INFO_OS(_o, _m, ...) PCL_LOG_OS(_o,PCL_LOGLEV_INFO,_m,__VA_ARGS__)
#define LOG_DEBUG_OS(_o, _m, ...) PCL_LOG_OS(_o,PCL_LOGLEV_DEBUG,_m,__VA_ARGS__)
#define PCL_LOG_LAST(_l, _m, ...)
#define LOG_PANIC_LAST(_m, ...) PCL_LOG_LAST(PCL_LOGLEV_PANIC,_m,__VA_ARGS__)
#define LOG_FATAL_LAST(_m, ...) PCL_LOG_LAST(PCL_LOGLEV_FATAL,_m,__VA_ARGS__)
#define LOG_ERROR_LAST(_m, ...) PCL_LOG_LAST(PCL_LOGLEV_ERROR,_m,__VA_ARGS__)
#define LOG_WARN_LAST(_m, ...) PCL_LOG_LAST(PCL_LOGLEV_WARN,_m,__VA_ARGS__)
#define LOG_INFO_LAST(_m, ...) PCL_LOG_LAST(PCL_LOGLEV_INFO,_m,__VA_ARGS__)
#define LOG_DEBUG_LAST(_m, ...) PCL_LOG_LAST(PCL_LOGLEV_DEBUG,_m,__VA_ARGS__)
Typedefs
typedef struct tag_pcl_log_event pcl_log_event_t
Functions
PCL_EXPORT int pcl_log_event_default (PCL_LOCATION_PARAMS, uint32_t level, const char *message,...)
PCL_EXPORT int pcl_log_event (pcl_log_event_t *e, const char *message,...)
PCL_EXPORT int pcl_log_vevent (pcl_log_event_t *e, const char *message, va_list ap)
PCL_INLINE const char * pcl_log_strlevel (uint32_t level)
‪convert an PCL_LOGLEV_xxx bit value to a string
Macro Definition Documentation
PCL_LOGLEV_DEBUG
#define PCL_LOGLEV_DEBUG 0x000001u
Definition at line 44 of file log.h.
PCL_LOGLEV_INFO
#define PCL_LOGLEV_INFO 0x000002u
Definition at line 45 of file log.h.
PCL_LOGLEV_WARN
#define PCL_LOGLEV_WARN 0x000004u
Definition at line 46 of file log.h.
PCL_LOGLEV_ERROR
#define PCL_LOGLEV_ERROR 0x000008u
Definition at line 47 of file log.h.
PCL_LOGLEV_FATAL
#define PCL_LOGLEV_FATAL 0x000010u
Definition at line 48 of file log.h.
PCL_LOGLEV_PANIC
#define PCL_LOGLEV_PANIC 0x000020u
Definition at line 49 of file log.h.
PCL_LOGTRC_DEBUG
#define PCL_LOGTRC_DEBUG 0x000100u
Definition at line 52 of file log.h.
PCL_LOGTRC_INFO
#define PCL_LOGTRC_INFO 0x000200u
Definition at line 53 of file log.h.
PCL_LOGTRC_WARN
#define PCL_LOGTRC_WARN 0x000400u
Definition at line 54 of file log.h.
PCL_LOGTRC_ERROR
#define PCL_LOGTRC_ERROR 0x000800u
Definition at line 55 of file log.h.
PCL_LOGTRC_FATAL
#define PCL_LOGTRC_FATAL 0x001000u
Definition at line 56 of file log.h.
PCL_LOGTRC_PANIC
#define PCL_LOGTRC_PANIC 0x002000u
Definition at line 57 of file log.h.
PCL_LOGOPT_UTC
#define PCL_LOGOPT_UTC 0x010000u
Definition at line 62 of file log.h.
PCL_LOG_MAXLEVELSTR
#define PCL_LOG_MAXLEVELSTR 48u
Definition at line 64 of file log.h.
PCL_LOGLEV_MASK
#define PCL_LOGLEV_MASK 0x00ffu /* log level mask */
Definition at line 65 of file log.h.
PCL_LOGTRC_MASK
#define PCL_LOGTRC_MASK 0xff00u /* log trace mask */
Definition at line 66 of file log.h.
PCL_LOGTRC_LSH
#define PCL_LOGTRC_LSH 8u /* no. of bits to left shift level to get trace bit */
Definition at line 67 of file log.h.
PCL_LOGLEV_TOTRACE
#define PCL_LOGLEV_TOTRACE (_level) (((_level) & (unsigned)PCL_LOGLEV_MASK) << (unsigned)PCL_LOGTRC_LSH)
Definition at line 70 of file log.h.
PCL_LOGLEV_HASTRACE
#define PCL_LOGLEV_HASTRACE (_level) ((_level) & PCL_LOGLEV_TOTRACE(_level))
Definition at line 74 of file log.h.
PCL_LOG_TIMEFORMAT
#define PCL_LOG_TIMEFORMAT "%b %d %H:%M:%S"
Definition at line 81 of file log.h.
PCL_LOG_OPEN_MODE
#define PCL_LOG_OPEN_MODE _P("a+b")
Definition at line 85 of file log.h.
PCL_LOG_EVENT
#define PCL_LOG_EVENT (level, msg, ...) pcl_log_event_default(PCL_LOCATION_ARGS, (uint32_t)(level), msg, __VA_ARGS__)
Definition at line 148 of file log.h.
LOG_PANIC
#define LOG_PANIC (msg, ...) PCL_LOG_EVENT(PCL_LOGLEV_PANIC, msg, __VA_ARGS__)
Definition at line 151 of file log.h.
LOG_FATAL
#define LOG_FATAL (msg, ...) PCL_LOG_EVENT(PCL_LOGLEV_FATAL, msg, __VA_ARGS__)
Definition at line 152 of file log.h.
LOG_ERROR
#define LOG_ERROR (msg, ...) PCL_LOG_EVENT(PCL_LOGLEV_ERROR, msg, __VA_ARGS__)
Definition at line 153 of file log.h.
LOG_WARN
#define LOG_WARN (msg, ...) PCL_LOG_EVENT(PCL_LOGLEV_WARN, msg, __VA_ARGS__)
Definition at line 154 of file log.h.
LOG_INFO
#define LOG_INFO (msg, ...) PCL_LOG_EVENT(PCL_LOGLEV_INFO, msg, __VA_ARGS__)
Definition at line 155 of file log.h.
LOG_DEBUG
#define LOG_DEBUG (msg, ...) PCL_LOG_EVENT(PCL_LOGLEV_DEBUG, msg, __VA_ARGS__)
Definition at line 156 of file log.h.
PCL_LOG_ERR
#define PCL_LOG_ERR (_e, _l, _m, ...)
Value:
  do{ \
  SETERR(_e); \
  PCL_LOG_EVENT(_l,_m,__VA_ARGS__); \
}while(0)
Definition at line 159 of file log.h.
LOG_PANIC_ERR
#define LOG_PANIC_ERR (_e, _m, ...) PCL_LOG_ERR(_e,PCL_LOGLEV_PANIC,_m,__VA_ARGS__)
Definition at line 163 of file log.h.
LOG_FATAL_ERR
#define LOG_FATAL_ERR (_e, _m, ...) PCL_LOG_ERR(_e,PCL_LOGLEV_FATAL,_m,__VA_ARGS__)
Definition at line 164 of file log.h.
LOG_ERROR_ERR
#define LOG_ERROR_ERR (_e, _m, ...) PCL_LOG_ERR(_e,PCL_LOGLEV_ERROR,_m,__VA_ARGS__)
Definition at line 165 of file log.h.
LOG_WARN_ERR
#define LOG_WARN_ERR (_e, _m, ...) PCL_LOG_ERR(_e,PCL_LOGLEV_WARN,_m,__VA_ARGS__)
Definition at line 166 of file log.h.
LOG_INFO_ERR
#define LOG_INFO_ERR (_e, _m, ...) PCL_LOG_ERR(_e,PCL_LOGLEV_INFO,_m,__VA_ARGS__)
Definition at line 167 of file log.h.
LOG_DEBUG_ERR
#define LOG_DEBUG_ERR (_e, _m, ...) PCL_LOG_ERR(_e,PCL_LOGLEV_DEBUG,_m,__VA_ARGS__)
Definition at line 168 of file log.h.
PCL_LOG_OS
#define PCL_LOG_OS (_o, _l, _m, ...)
Value:
  do{ \
  SETOSERR(_o); \
  PCL_LOG_EVENT(_l,_m,__VAR_ARGS__); \
}while(0)
Definition at line 171 of file log.h.
LOG_PANIC_OS
#define LOG_PANIC_OS (_o, _m, ...) PCL_LOG_OS(_o,PCL_LOGLEV_PANIC,_m,__VA_ARGS__)
Definition at line 175 of file log.h.
LOG_FATAL_OS
#define LOG_FATAL_OS (_o, _m, ...) PCL_LOG_OS(_o,PCL_LOGLEV_FATAL,_m,__VA_ARGS__)
Definition at line 176 of file log.h.
LOG_ERROR_OS
#define LOG_ERROR_OS (_o, _m, ...) PCL_LOG_OS(_o,PCL_LOGLEV_ERROR,_m,__VA_ARGS__)
Definition at line 177 of file log.h.
LOG_WARN_OS
#define LOG_WARN_OS (_o, _m, ...) PCL_LOG_OS(_o,PCL_LOGLEV_WARN,_m,__VA_ARGS__)
Definition at line 178 of file log.h.
LOG_INFO_OS
#define LOG_INFO_OS (_o, _m, ...) PCL_LOG_OS(_o,PCL_LOGLEV_INFO,_m,__VA_ARGS__)
Definition at line 179 of file log.h.
LOG_DEBUG_OS
#define LOG_DEBUG_OS (_o, _m, ...) PCL_LOG_OS(_o,PCL_LOGLEV_DEBUG,_m,__VA_ARGS__)
Definition at line 180 of file log.h.
PCL_LOG_LAST
#define PCL_LOG_LAST (_l, _m, ...)
Value:
  do{ \
  SETLASTERR(); \
  PCL_LOG_EVENT(_l,_m,__VA_ARGS__); \
}while(0)
Definition at line 183 of file log.h.
LOG_PANIC_LAST
#define LOG_PANIC_LAST (_m, ...) PCL_LOG_LAST(PCL_LOGLEV_PANIC,_m,__VA_ARGS__)
Definition at line 187 of file log.h.
LOG_FATAL_LAST
#define LOG_FATAL_LAST (_m, ...) PCL_LOG_LAST(PCL_LOGLEV_FATAL,_m,__VA_ARGS__)
Definition at line 188 of file log.h.
LOG_ERROR_LAST
#define LOG_ERROR_LAST (_m, ...) PCL_LOG_LAST(PCL_LOGLEV_ERROR,_m,__VA_ARGS__)
Definition at line 189 of file log.h.
LOG_WARN_LAST
#define LOG_WARN_LAST (_m, ...) PCL_LOG_LAST(PCL_LOGLEV_WARN,_m,__VA_ARGS__)
Definition at line 190 of file log.h.
LOG_INFO_LAST
#define LOG_INFO_LAST (_m, ...) PCL_LOG_LAST(PCL_LOGLEV_INFO,_m,__VA_ARGS__)
Definition at line 191 of file log.h.
LOG_DEBUG_LAST
#define LOG_DEBUG_LAST (_m, ...) PCL_LOG_LAST(PCL_LOGLEV_DEBUG,_m,__VA_ARGS__)
Definition at line 192 of file log.h.
Typedef Documentation
pcl_log_event_t
typedef struct tag_pcl_log_event pcl_log_event_t
Definition at line 1 of file log.h.
Function Documentation
pcl_log_event_default()
PCL_EXPORT int pcl_log_event_default (PCL_LOCATION_PARAMS , uint32_t level, const char * message, ...)
Definition at line 52 of file log_event_default.c.
References PCL_LOGLEV_INFO, PCL_LOGLEV_PANIC, PCL_LOGLEV_TOTRACE, PCL_LOGLEV_WARN, pcl_time(), and tag_pcl_log_event::stream.
pcl_log_event()
PCL_EXPORT int pcl_log_event (pcl_log_event_t * e, const char * message, ...)
Definition at line 35 of file log_event.c.
References pcl_log_vevent().
pcl_log_vevent()
PCL_EXPORT int pcl_log_vevent (pcl_log_event_t * e, const char * message, va_list ap)
Definition at line 43 of file log_vevent.c.
References countof, tag_pcl_log_event::ctx, tag_pcl_log_event::exit_code, tag_pcl_log_event::exit_context, tag_pcl_log_event::exit_handler, tag_pcl_log_event::exit_levels, tag_pcl_log_event::facility, tag_pcl_log_event::file, tag_pcl_err_ctx::frozen, tag_pcl_log_event::func, tag_pcl_log_event::level, tag_pcl_log_event::line, pcl_asprintf(), pcl_err_ctx(), pcl_err_ctx_fprintf(), pcl_fprintf(), pcl_free_safe(), pcl_gmtime(), pcl_localtime(), pcl_log_strlevel(), PCL_LOG_TIMEFORMAT, PCL_LOGLEV_HASTRACE, PCL_LOGOPT_UTC, pcl_sprintf(), pcl_strcpy(), pcl_strftime(), pcl_strrepchr(), pcl_vasprintf(), tag_pcl_log_event::stream, strempty, and tag_pcl_log_event::when.
Referenced by pcl_log_event().
pcl_log_strlevel()
PCL_INLINE const char* pcl_log_strlevel (uint32_t level)
‪convert an PCL_LOGLEV_xxx bit value to a string
Parameters
[in] level ‪log level
Returns
‪the level name as a string or ""
Definition at line 201 of file log.h.
References PCL_LOGLEV_DEBUG, PCL_LOGLEV_ERROR, PCL_LOGLEV_FATAL, PCL_LOGLEV_INFO, PCL_LOGLEV_MASK, PCL_LOGLEV_PANIC, and PCL_LOGLEV_WARN.
Referenced by pcl_log_vevent().