‪libpcl: ‪pcl/file.h File Reference
file.h File Reference
#include <pcl/types.h>
Macros
#define PCL_RDLOCK F_RDLCK
#define PCL_UNLOCK F_UNLCK
#define PCL_WRLOCK F_WRLCK
#define STDIN_FILENO 0
#define STDOUT_FILENO 1
#define STDERR_FILENO 2
#define PCL_O_RDONLY 0x00000000 /* open for reading only */
#define PCL_O_WRONLY 0x00000001 /* open for writing only */
#define PCL_O_RDWR 0x00000002 /* open for reading and writing */
#define PCL_O_ACCMODE 0x00000003 /* mask for above modes */
#define PCL_O_CREAT 0x00000008 /* create and open file */
#define PCL_O_APPEND 0x00000010 /* set the append mode (all writes at EOF */
#define PCL_O_TRUNC 0x00000020 /* truncate to zero length */
#define PCL_O_EXCL 0x00000040 /* open only if file doesn't already exist */
#define PCL_O_NONBLOCK 0x00000080 /* do not block on open or for data to become available */
#define PCL_O_CLOEXEC 0x00000100 /* close fd when exec() is invoked */
#define PCL_O_DIRECTORY 0x00000200 /* If not a directory, the open will fail */
#define PCL_O_NOFOLLOW 0x00000400 /* Do not follow symlinks, the open will fail */
#define PCL_O_SYNC 0x00000800 /* file is opened for synchronous I/O */
#define PCL_O_SHLOCK 0x00001000 /* share lock file, read lock */
#define PCL_O_EXLOCK 0x00002000 /* exclusive lock the file, read/write lock */
#define PCL_O_BACKUP
#define PCL_O_NOATIME 0x00008000 /* linux only */
#define PCL_O_TEMP 0x00010000 /* temp file: deleted after pcl_file_t is closed */
#define PCL_O_NDELAY PCL_O_NONBLOCK
#define PCL_O_NOINHERIT PCL_O_CLOEXEC
#define PCL_FF_FLOCK 0x0001 /* locked explicitly via pcl_file_lock */
#define PCL_FF_NONBLOCK 0x0002
#define PCL_FF_APPEND 0x0004
#define PCL_FF_READ 0x0008
#define PCL_FF_WRITE 0x0010
#define PCL_FF_OLOCK 0x0020 /* locked implicitly by pcl_file_open O_SHLOCK|O_EXLOCK */
#define PCL_FF_RDWR (PCL_FF_READ | PCL_FF_WRITE)
Functions
PCL_EXPORT pcl_file_t * pcl_file_open (const pchar_t *path, int oflags,...)
PCL_EXPORT int pcl_file_read (pcl_file_t *file, void *buf, size_t count)
PCL_EXPORT int pcl_file_write (pcl_file_t *file, const void *data, size_t count)
PCL_EXPORT int pcl_file_tryread (pcl_file_t *file, void *buf, size_t count, int ms_timeout)
PCL_EXPORT int pcl_file_trywrite (pcl_file_t *file, const void *data, size_t count, int ms_timeout)
PCL_EXPORT off_t pcl_file_seek (pcl_file_t *file, off_t offset, int whence)
PCL_EXPORT void pcl_file_close (pcl_file_t *file)
PCL_EXPORT int pcl_file_lock (pcl_file_t *file, int operation)
‪Lock a file with exclusive or shared access or unlock a file.
PCL_EXPORT int pcl_fdpath (int fd, pchar_t **out)
PCL_EXPORT pchar_t * pcl_realpath (const pchar_t *path, int *lenp)
‪Gets the canonicalized absolute pathname.
PCL_EXPORT int pcl_rename (const pchar_t *oldname, const pchar_t *newname)
‪Change the name or location of a file.
PCL_EXPORT int pcl_remove (const pchar_t *pathname)
‪Delete a file or directory.
PCL_EXPORT int pcl_unlink (const pchar_t *path)
‪Delete a file.
Macro Definition Documentation
PCL_RDLOCK
#define PCL_RDLOCK F_RDLCK
Definition at line 42 of file file.h.
PCL_UNLOCK
#define PCL_UNLOCK F_UNLCK
Definition at line 43 of file file.h.
PCL_WRLOCK
#define PCL_WRLOCK F_WRLCK
Definition at line 44 of file file.h.
STDIN_FILENO
#define STDIN_FILENO 0
Definition at line 49 of file file.h.
STDOUT_FILENO
#define STDOUT_FILENO 1
Definition at line 52 of file file.h.
STDERR_FILENO
#define STDERR_FILENO 2
Definition at line 55 of file file.h.
PCL_O_RDONLY
#define PCL_O_RDONLY 0x00000000 /* open for reading only */
Definition at line 58 of file file.h.
PCL_O_WRONLY
#define PCL_O_WRONLY 0x00000001 /* open for writing only */
Definition at line 59 of file file.h.
PCL_O_RDWR
#define PCL_O_RDWR 0x00000002 /* open for reading and writing */
Definition at line 60 of file file.h.
PCL_O_ACCMODE
#define PCL_O_ACCMODE 0x00000003 /* mask for above modes */
Definition at line 61 of file file.h.
PCL_O_CREAT
#define PCL_O_CREAT 0x00000008 /* create and open file */
Definition at line 62 of file file.h.
PCL_O_APPEND
#define PCL_O_APPEND 0x00000010 /* set the append mode (all writes at EOF */
Definition at line 63 of file file.h.
PCL_O_TRUNC
#define PCL_O_TRUNC 0x00000020 /* truncate to zero length */
Definition at line 64 of file file.h.
PCL_O_EXCL
#define PCL_O_EXCL 0x00000040 /* open only if file doesn't already exist */
Definition at line 65 of file file.h.
PCL_O_NONBLOCK
#define PCL_O_NONBLOCK 0x00000080 /* do not block on open or for data to become available */
Definition at line 66 of file file.h.
PCL_O_CLOEXEC
#define PCL_O_CLOEXEC 0x00000100 /* close fd when exec() is invoked */
Definition at line 67 of file file.h.
PCL_O_DIRECTORY
#define PCL_O_DIRECTORY 0x00000200 /* If not a directory, the open will fail */
Definition at line 68 of file file.h.
PCL_O_NOFOLLOW
#define PCL_O_NOFOLLOW 0x00000400 /* Do not follow symlinks, the open will fail */
Definition at line 69 of file file.h.
PCL_O_SYNC
#define PCL_O_SYNC 0x00000800 /* file is opened for synchronous I/O */
Definition at line 70 of file file.h.
PCL_O_SHLOCK
#define PCL_O_SHLOCK 0x00001000 /* share lock file, read lock */
Definition at line 71 of file file.h.
PCL_O_EXLOCK
#define PCL_O_EXLOCK 0x00002000 /* exclusive lock the file, read/write lock */
Definition at line 72 of file file.h.
PCL_O_BACKUP
#define PCL_O_BACKUP
Value:
                                           0x00004000     /* win32 only, sets FILE_FLAG_BACKUP_SEMANTICS
                                           and possibly other things in future */
Definition at line 73 of file file.h.
PCL_O_NOATIME
#define PCL_O_NOATIME 0x00008000 /* linux only */
Definition at line 74 of file file.h.
PCL_O_TEMP
#define PCL_O_TEMP 0x00010000 /* temp file: deleted after pcl_file_t is closed */
Definition at line 75 of file file.h.
PCL_O_NDELAY
#define PCL_O_NDELAY PCL_O_NONBLOCK
Definition at line 76 of file file.h.
PCL_O_NOINHERIT
#define PCL_O_NOINHERIT PCL_O_CLOEXEC
Definition at line 77 of file file.h.
PCL_FF_FLOCK
#define PCL_FF_FLOCK 0x0001 /* locked explicitly via pcl_file_lock */
Definition at line 80 of file file.h.
PCL_FF_NONBLOCK
#define PCL_FF_NONBLOCK 0x0002
Definition at line 81 of file file.h.
PCL_FF_APPEND
#define PCL_FF_APPEND 0x0004
Definition at line 82 of file file.h.
PCL_FF_READ
#define PCL_FF_READ 0x0008
Definition at line 83 of file file.h.
PCL_FF_WRITE
#define PCL_FF_WRITE 0x0010
Definition at line 84 of file file.h.
PCL_FF_OLOCK
#define PCL_FF_OLOCK 0x0020 /* locked implicitly by pcl_file_open O_SHLOCK|O_EXLOCK */
Definition at line 85 of file file.h.
PCL_FF_RDWR
#define PCL_FF_RDWR (PCL_FF_READ | PCL_FF_WRITE)
Definition at line 86 of file file.h.
Function Documentation
pcl_file_open()
PCL_EXPORT pcl_file_t* pcl_file_open (const pchar_t * path, int oflags, ...)
Definition at line 36 of file file_open.c.
References ipcl_file_alloc(), ipcl_file_init(), ipcl_file_open(), PCL_BADFD, PCL_EINVAL, pcl_file_close(), PCL_O_CREAT, R_SETERR, R_TRCMSG, and strempty.
Referenced by pcl_readdir(), pcl_tmpfile(), and pcl_utimes().
pcl_file_read()
PCL_EXPORT int pcl_file_read (pcl_file_t * file, void * buf, size_t count)
Definition at line 36 of file unix_read.c.
References BADARG, tag_pcl_file::fd, tag_pcl_file::flags, PCL_ENOTSUP, PCL_FF_NONBLOCK, PCL_FF_READ, pcl_file_tryread(), SETERRMSG, SETLASTERR, SETOSERR, and TRC.
Referenced by pcl_file_tryread().
pcl_file_write()
PCL_EXPORT int pcl_file_write (pcl_file_t * file, const void * data, size_t count)
Definition at line 36 of file unix_write.c.
References BADARG, tag_pcl_file::fd, tag_pcl_file::flags, PCL_ENOTSUP, PCL_FF_NONBLOCK, PCL_FF_WRITE, pcl_file_trywrite(), SETERRMSG, SETLASTERR, and TRC.
Referenced by pcl_file_trywrite().
pcl_file_tryread()
PCL_EXPORT int pcl_file_tryread (pcl_file_t * file, void * buf, size_t count, int ms_timeout)
Definition at line 37 of file unix_tryread.c.
References BADARG, tag_pcl_file::fd, tag_pcl_file::flags, PCL_EAGAIN, PCL_EBADF, PCL_ECONNRESET, PCL_ENOTSUP, PCL_FF_NONBLOCK, PCL_FF_READ, pcl_file_read(), SETERR, SETERR_OS, SETERRMSG, SETLASTERR, and TRC.
Referenced by pcl_file_read().
pcl_file_trywrite()
PCL_EXPORT int pcl_file_trywrite (pcl_file_t * file, const void * data, size_t count, int ms_timeout)
Definition at line 37 of file unix_trywrite.c.
References BADARG, tag_pcl_file::fd, tag_pcl_file::flags, PCL_EAGAIN, PCL_EBADF, PCL_ECONNRESET, PCL_ENOTSUP, PCL_FF_NONBLOCK, PCL_FF_WRITE, pcl_file_write(), SETERR, SETERR_OS, SETERRMSG, SETLASTERR, and TRC.
Referenced by pcl_file_write().
pcl_file_seek()
PCL_EXPORT off_t pcl_file_seek (pcl_file_t * file, off_t offset, int whence)
Definition at line 36 of file file_seek.c.
References BADARG, tag_pcl_file::fd, and SETLASTERR.
pcl_file_close()
PCL_EXPORT void pcl_file_close (pcl_file_t * file)
Definition at line 39 of file file_close.c.
References tag_pcl_file::fd, tag_pcl_file::flags, tag_pcl_err_ctx::frozen, PCL_BADFD, pcl_err_ctx(), PCL_FF_FLOCK, PCL_FF_NONBLOCK, PCL_FF_READ, PCL_FF_WRITE, pcl_file_lock(), pcl_free(), pcl_oserrno, pcl_setoserrno, and PCL_UNLOCK.
Referenced by pcl_fdopen(), pcl_file_open(), pcl_popen(), pcl_proc_exec(), pcl_readdir(), pcl_tmpfile(), and pcl_utimes().
pcl_file_lock()
PCL_EXPORT int pcl_file_lock (pcl_file_t * file, int operation)
‪Lock a file with exclusive or shared access or unlock a file.
Parameters
file
operation ‪PCL_WRLOCK exclusive, PCL_RDLOCK shared, PCL_UNLOCK unlock
Returns
‪0 for success and -1 on error
Definition at line 36 of file file_lock.c.
References BADARG, tag_pcl_file::fd, tag_pcl_file::flags, PCL_BADFD, PCL_EAGAIN, PCL_EINVAL, PCL_FF_FLOCK, PCL_FF_NONBLOCK, pcl_oserrno, PCL_RDLOCK, PCL_UNLOCK, PCL_WRLOCK, SETERR, SETERRMSG, and SETLASTERR.
Referenced by ipcl_file_open(), and pcl_file_close().
pcl_fdpath()
PCL_EXPORT int pcl_fdpath (int fd, pchar_t ** out)
Definition at line 51 of file fdpath.c.
References _P, BADARG, countof, FREEZE_ERR, pcl_aspprintf(), PCL_ENOTSUP, pcl_free(), PCL_MAXPATH, pcl_pcsdup(), pcl_pcslen(), pcl_pcsnicmp(), pcl_pmalloc(), pcl_sprintf(), pcl_strndup(), SETERR, SETLASTERR, and TRC.
Referenced by pcl_statent().
pcl_realpath()
PCL_EXPORT pchar_t* pcl_realpath (const pchar_t * path, int * lenp)
‪Gets the canonicalized absolute pathname.
Parameters
path ‪path to convert
[out] lenp ‪If not NULL, character length (excluding NUL) is written here
Returns
‪an allocated absolute path or NULL on error
Definition at line 44 of file realpath.c.
References PCL_EINVAL, pcl_malloc(), pcl_strndup(), R_SETERR, R_SETLASTERR, and strempty.
Referenced by pcl_opendir().
pcl_rename()
PCL_EXPORT int pcl_rename (const pchar_t * oldname, const pchar_t * newname)
‪Change the name or location of a file.
Parameters
oldname ‪The old name/path of the file
newname ‪if this exists, it will be replaced
Returns
‪0 on success and -1 on error
Definition at line 40 of file rename.c.
References pcl_err_osclear, and SETLASTERR.
pcl_remove()
PCL_EXPORT int pcl_remove (const pchar_t * pathname)
‪Delete a file or directory.
The directory must be empty. File can be a link, socket, FIFO or device.
Parameters
pathname
Returns
‪0 on success or -1 on error
Definition at line 41 of file remove.c.
References BADARG, tag_pcl_stat::mode, pcl_rmdir(), pcl_stat, pcl_unlink(), S_ISBLK, S_ISCHR, S_ISDIR, strempty, and TRC.
pcl_unlink()
PCL_EXPORT int pcl_unlink (const pchar_t * path)
‪Delete a file.
Parameters
path ‪file to delete
Returns
‪0 on success and -1 on error
See also
‪pcl_remove
Definition at line 41 of file unlink.c.
References pcl_err_osclear, pcl_oserrno, and SETLASTERR.
Referenced by ipcl_file_open(), pcl_bind(), and pcl_remove().