‪libpcl: ‪pcl/net.h File Reference
net.h File Reference
#include <pcl/types.h>
#include <ws2tcpip.h>
Functions
PCL_PUBLIC int pcl_net_ip2inet (int af, const char *ipstr, void *inaddr)
PCL_PUBLIC char * pcl_net_inet2ip (int af, const void *inaddr, char *ipbuf, size_t len)
PCL_PUBLIC int pcl_net_host2addr (const char *host, struct sockaddr *sa)
PCL_PUBLIC char * pcl_net_addr2ip (struct sockaddr *sa, char *ipbuf, size_t len)
PCL_PUBLIC int pcl_net_ai2pcl (int ai_retval)
PCL_PUBLIC int pcl_net_dns2pcl (int err)
PCL_PUBLIC int pcl_net_reverse (const char *ipaddr, char *host, size_t len)
PCL_PUBLIC pcl_array_t * pcl_net_resolve (const char *host)
‪Resolve a hostname to an array of IPv4 and/or IPv6 addresses.
PCL_PUBLIC pcl_array_t * pcl_net_dnstxtrec (const char *host)
‪Retrieve the DNS TXT records for a given host.
PCL_PUBLIC socklen_t pcl_net_addrlen (const struct sockaddr *addr)
Function Documentation
pcl_net_ip2inet()
PCL_PUBLIC int pcl_net_ip2inet (int af, const char * ipstr, void * inaddr)
Definition at line 36 of file net_ip2inet.c.
References BADARG, PCL_ETYPE, pcl_net_ai2pcl(), and SETERR.
pcl_net_inet2ip()
PCL_PUBLIC char* pcl_net_inet2ip (int af, const void * inaddr, char * ipbuf, size_t len)
Definition at line 35 of file net_inet2ip.c.
References PCL_EAFNOSUPPORT, pcl_net_addr2ip(), R_SETERR, and R_TRC.
pcl_net_host2addr()
PCL_PUBLIC int pcl_net_host2addr (const char * host, struct sockaddr * sa)
Definition at line 43 of file net_host2addr.c.
References BADARG, PCL_EOVERFLOW, PCL_MAXUNIXSOCKPATH, pcl_net_ai2pcl(), pcl_strcpy(), SETERR, and strempty.
pcl_net_addr2ip()
PCL_PUBLIC char* pcl_net_addr2ip (struct sockaddr * sa, char * ipbuf, size_t len)
Definition at line 42 of file net_addr2ip.c.
References PCL_EBUF, PCL_EINVAL, pcl_net_addrlen(), pcl_net_ai2pcl(), pcl_strcpy(), and R_SETERR.
Referenced by pcl_net_inet2ip(), and pcl_socket_ip().
pcl_net_ai2pcl()
PCL_PUBLIC int pcl_net_ai2pcl (int ai_retval)
Definition at line 35 of file net_ai2pcl.c.
References PCL_EAFNOSUPPORT, PCL_ECANCELLED, PCL_EFORMAT, PCL_EHOSTNOTFOUND, PCL_EINPROGRESS, PCL_EINTR, PCL_EINVAL, PCL_ENODATA, PCL_ENOMEM, PCL_EOKAY, PCL_EOVERFLOW, pcl_err_os2pcl(), PCL_ESOCKTNOSUPPORT, PCL_ETRYAGAIN, and PCL_EUNDEF.
Referenced by pcl_net_addr2ip(), pcl_net_host2addr(), pcl_net_ip2inet(), pcl_net_resolve(), pcl_net_reverse(), and pcl_socket().
pcl_net_dns2pcl()
PCL_PUBLIC int pcl_net_dns2pcl (int err)
Definition at line 35 of file net_dns2pcl.c.
References PCL_EAGAIN, PCL_EHOSTNOTFOUND, PCL_ENODATA, PCL_ENORECOVERY, pcl_err_os2pcl(), and pcl_oserrno.
Referenced by pcl_net_dnstxtrec().
pcl_net_reverse()
PCL_PUBLIC int pcl_net_reverse (const char * ipaddr, char * host, size_t len)
Definition at line 35 of file net_reverse.c.
References BADARG, pcl_net_ai2pcl(), SETERR, and strempty.
pcl_net_resolve()
PCL_PUBLIC pcl_array_t* pcl_net_resolve (const char * host)
‪Resolve a hostname to an array of IPv4 and/or IPv6 addresses.
Parameters
host ‪pointer to a hostname
Returns
‪pointer to an array of IP addresses or NULL on error.
Definition at line 38 of file net_resolve.c.
References pcl_array(), pcl_array_append(), pcl_cleanup_ptr(), pcl_net_ai2pcl(), pcl_strdup(), and R_SETERR.
pcl_net_dnstxtrec()
PCL_PUBLIC pcl_array_t* pcl_net_dnstxtrec (const char * host)
‪Retrieve the DNS TXT records for a given host.
Parameters
host ‪pointer to a host
Returns
‪pointer to an array where each element is a TXT record or NULL on error.
Definition at line 50 of file net_dnstxtrec.c.
References pcl_array(), pcl_array_append(), pcl_cleanup_ptr(), pcl_net_dns2pcl(), pcl_pcs_to_utf8(), pcl_strndup(), R_SETERRMSG, R_SETLASTERR, and R_SETOSERRMSG.
pcl_net_addrlen()
PCL_PUBLIC socklen_t pcl_net_addrlen (const struct sockaddr * addr)
Definition at line 41 of file net_addrlen.c.
Referenced by pcl_net_addr2ip().