‪libpcl: ‪pcl/errctx.h File Reference
errctx.h File Reference
#include <pcl/types.h>
Data Structures
struct tag_pcl_err_trace
‪Stack trace object implemented as a linked list.
struct tag_pcl_err_ctx
‪Represents a PCL error context, with optional stack trace.
Functions
PCL_EXPORT pcl_err_ctx_t * pcl_err_ctx_create (void)
‪Allocates a new error context.
PCL_EXPORT pcl_err_ctx_t * pcl_err_ctx_clone (const pcl_err_ctx_t *src)
‪Clone one context to another.
PCL_EXPORT pcl_err_ctx_t * pcl_err_ctx_clear (pcl_err_ctx_t *ctx)
‪Clears the given context.
PCL_EXPORT void pcl_err_ctx_free (pcl_err_ctx_t *ctx)
‪Release all resources held by the given context including the context itself.
PCL_EXPORT int pcl_err_ctx_fprintf (pcl_err_ctx_t *ctx, FILE *fp, int indent, const char *message,...)
PCL_EXPORT int pcl_err_ctx_vfprintf (pcl_err_ctx_t *ctx, FILE *fp, int indent, const char *message, va_list ap)
PCL_EXPORT int pcl_err_ctx_sprintf (pcl_err_ctx_t *ctx, char *buf, size_t size, int indent, const char *message,...)
PCL_EXPORT int pcl_err_ctx_vsprintf (pcl_err_ctx_t *ctx, char *buf, size_t size, int indent, const char *message, va_list ap)
Function Documentation
pcl_err_ctx_create()
PCL_EXPORT pcl_err_ctx_t* pcl_err_ctx_create (void)
‪Allocates a new error context.
Error codes are zero, messages are all NULL and the stack trace is empty.
Definition at line 36 of file err_ctx_create.c.
References pcl_zalloc().
Referenced by pcl_err_ctx_clone().
pcl_err_ctx_clone()
PCL_EXPORT pcl_err_ctx_t* pcl_err_ctx_clone (const pcl_err_ctx_t * src)
‪Clone one context to another.
This performs a deep copy, no shared pointers.
Parameters
src ‪context to clone
Returns
‪cloned version of given context or NULL if src is NULL
Definition at line 37 of file err_ctx_clone.c.
References tag_pcl_err_ctx::err, tag_pcl_err_trace::file, tag_pcl_err_trace::func, tag_pcl_err_trace::msg, tag_pcl_err_trace::next, tag_pcl_err_ctx::oserr, pcl_err_ctx_create(), pcl_malloc(), tag_pcl_err_trace::size, and tag_pcl_err_ctx::strace.
pcl_err_ctx_clear()
PCL_EXPORT pcl_err_ctx_t* pcl_err_ctx_clear (pcl_err_ctx_t * ctx)
‪Clears the given context.
A clear wipes out the stack trace and error codes. However, 'ctx' is completely valid after this call.
Parameters
ctx
Returns
‪pointer to the ctx argument
Definition at line 35 of file err_ctx_clear.c.
References tag_pcl_err_ctx::err, tag_pcl_err_ctx::frozen, ipcl_err_ctx_trace_free(), tag_pcl_err_ctx::oserr, PCL_EOKAY, and tag_pcl_err_ctx::strace.
Referenced by pcl_err_clear(), and pcl_err_vset().
pcl_err_ctx_free()
PCL_EXPORT void pcl_err_ctx_free (pcl_err_ctx_t * ctx)
‪Release all resources held by the given context including the context itself.
Warning
‪this will call pcl_memory_error if you try to free the per-thread context. The type parameter of pcl_memory_error is set to "err_ctx_free".
Parameters
ctx
Definition at line 47 of file err_ctx_free.c.
References tag_pcl_err_ctx::frozen, ipcl_err_ctx_destroy(), pcl_err_ctx(), PCL_LOCATION_ARGS, and pcl_memory_error().
pcl_err_ctx_fprintf()
PCL_EXPORT int pcl_err_ctx_fprintf (pcl_err_ctx_t * ctx, FILE * fp, int indent, const char * message, ...)
Parameters
ctx
fp
indent
message
...
Returns
‪number of characters written to the given stream, which can be zero if the current error is set to PCL_EOKAY. On failure, this returns -1 but DOES NOT set pcl_errno. It means there was an error writing the data to the fp argument.
Definition at line 35 of file err_ctx_fprintf.c.
References pcl_err_ctx_vfprintf().
Referenced by pcl_log_vevent().
pcl_err_ctx_vfprintf()
PCL_EXPORT int pcl_err_ctx_vfprintf (pcl_err_ctx_t * ctx, FILE * fp, int indent, const char * message, va_list ap)
Definition at line 36 of file err_ctx_vfprintf.c.
References tag_pcl_buf::data, tag_pcl_err_ctx::frozen, ipcl_err_ctx_serialize(), and tag_pcl_buf::len.
Referenced by pcl_err_ctx_fprintf(), and pcl_err_vfprintf().
pcl_err_ctx_sprintf()
PCL_EXPORT int pcl_err_ctx_sprintf (pcl_err_ctx_t * ctx, char * buf, size_t size, int indent, const char * message, ...)
Parameters
ctx
buf
size
indent
message
...
Returns
‪number of characters written to the given buffer or -1 on error. pcl_errno is NOT set. This will return -1 when buf is too small.
Definition at line 35 of file err_ctx_sprintf.c.
References pcl_err_ctx_vsprintf().
pcl_err_ctx_vsprintf()
PCL_EXPORT int pcl_err_ctx_vsprintf (pcl_err_ctx_t * ctx, char * buf, size_t size, int indent, const char * message, va_list ap)
Definition at line 37 of file err_ctx_vsprintf.c.
References tag_pcl_buf::data, tag_pcl_err_ctx::frozen, ipcl_err_ctx_serialize(), and tag_pcl_buf::len.
Referenced by pcl_err_ctx_sprintf(), and pcl_err_vsprintf().