‪libpcl: ‪pcl/stack.h File Reference
stack.h File Reference
#include <pcl/types.h>
Functions
PCL_EXPORT pcl_stack_t * pcl_stack (pcl_cleanup_t cleanup)
‪Create a stack object.
PCL_EXPORT int pcl_stack_size (pcl_stack_t *s)
‪Get the size (number of items) of a stack object.
PCL_EXPORT bool pcl_stack_empty (pcl_stack_t *s)
‪Indicates if a stack is empty.
PCL_EXPORT void pcl_stack_push (pcl_stack_t *s, void *item)
‪Add an item to the top of the stack.
PCL_EXPORT void * pcl_stack_peek (pcl_stack_t *s)
‪Retrievve an item from the top of the stack without removing it.
PCL_EXPORT void * pcl_stack_pop (pcl_stack_t *s)
‪Retrieve and remove an item from the top of the stack.
PCL_EXPORT void pcl_stack_clear (pcl_stack_t *s)
‪Remove all items from a stack.
PCL_EXPORT void pcl_stack_free (pcl_stack_t *s)
‪Release all resources used by a stack object.
Function Documentation
pcl_stack()
PCL_EXPORT pcl_stack_t* pcl_stack (pcl_cleanup_t cleanup)
‪Create a stack object.
Parameters
cleanup ‪optional item cleanup handler
Returns
‪pointer to a stack object or NULL on error
See also
‪pcl_cleanup_ptr
Definition at line 36 of file stack.c.
References tag_pcl_stack::cleanup, tag_pcl_stack::head, pcl_malloc(), and tag_pcl_stack::size.
pcl_stack_size()
PCL_EXPORT int pcl_stack_size (pcl_stack_t * s)
‪Get the size (number of items) of a stack object.
Parameters
s ‪pointer to a stack object
Returns
‪number of stack items
Definition at line 35 of file stack_size.c.
References tag_pcl_stack::size.
Referenced by pcl_stack_empty().
pcl_stack_empty()
PCL_EXPORT bool pcl_stack_empty (pcl_stack_t * s)
‪Indicates if a stack is empty.
Parameters
s ‪pointer to a stack object
Returns
Definition at line 35 of file stack_empty.c.
References pcl_stack_size().
Referenced by pcl_stack_peek(), and pcl_stack_pop().
pcl_stack_push()
PCL_EXPORT void pcl_stack_push (pcl_stack_t * s, void * item)
‪Add an item to the top of the stack.
Parameters
s ‪pointer to a stack object
item
Definition at line 36 of file stack_push.c.
References tag_pcl_stack::head, stack_item::next, pcl_malloc(), tag_pcl_stack::size, and stack_item::value.
pcl_stack_peek()
PCL_EXPORT void* pcl_stack_peek (pcl_stack_t * s)
‪Retrievve an item from the top of the stack without removing it.
Parameters
s ‪pointer to a stack object
Returns
Definition at line 35 of file stack_peek.c.
References tag_pcl_stack::head, pcl_stack_empty(), and stack_item::value.
pcl_stack_pop()
PCL_EXPORT void* pcl_stack_pop (pcl_stack_t * s)
‪Retrieve and remove an item from the top of the stack.
Note
‪it is the caller's responsibility to free the returned item.
Parameters
s ‪pointer to a stack object
Returns
Definition at line 36 of file stack_pop.c.
References tag_pcl_stack::head, stack_item::next, pcl_free(), pcl_stack_empty(), tag_pcl_stack::size, and stack_item::value.
pcl_stack_clear()
PCL_EXPORT void pcl_stack_clear (pcl_stack_t * s)
‪Remove all items from a stack.
This will call the optional cleanup handler.
Parameters
s ‪pointer to a stack object
Definition at line 36 of file stack_clear.c.
References tag_pcl_stack::cleanup, tag_pcl_stack::head, stack_item::next, pcl_free(), tag_pcl_stack::size, and stack_item::value.
Referenced by pcl_stack_free().
pcl_stack_free()
PCL_EXPORT void pcl_stack_free (pcl_stack_t * s)
‪Release all resources used by a stack object.
Parameters
s ‪pointer to a stack object
Definition at line 36 of file stack_free.c.
References pcl_free(), and pcl_stack_clear().