‪libpcl: ‪pcl/stat.h File Reference
stat.h File Reference
#include <pcl/time.h>
#include <sys/stat.h>
Data Structures
struct tag_pcl_stat
Macros
#define sys_stat stat
#define sys_fstat fstat
#define sys_lstat lstat
#define PCL_STAT_LINK 0x01
#define PCL_STAT_SKIP_WIN32OWNER 0x10
#define pcl_stat(path, stbuf) pcl_statent(path, -1, stbuf, 0)
#define pcl_fstat(fd, stbuf) pcl_statent(NULL, fd, stbuf, 0)
#define pcl_lstat(path, stbuf) pcl_statent(path, -1, stbuf, PCL_STAT_LINK)
#define S_IFMT 0170000 /* file type mask */
#define S_IFSOCK 0140000
#define S_IFLNK 0120000
#define S_IFREG 0100000
#define S_IFBLK 0060000
#define S_IFDIR 0040000
#define S_IFCHR 0020000
#define S_IFIFO 0010000
#define S_IFMOD 07777 /* mode bits: mask for file type & perms, pcl extension */
#define S_ISUID 04000 /* set-uid bit */
#define S_ISGID 02000 /* set-gid bit */
#define S_ISVTX 01000 /* sticky bit */
#define S_IRWXU 00700
#define S_IRUSR 00400
#define S_IWUSR 00200
#define S_IXUSR 00100
#define S_IRWXG 00070
#define S_IRGRP 00040
#define S_IWGRP 00020
#define S_IXGRP 00010
#define S_IRWXO 00007
#define S_IROTH 00004
#define S_IWOTH 00002
#define S_IXOTH 00001
#define S_ISLNK(m) (((m) & S_IFMT) == S_IFLNK)
#define S_ISREG(m) (((m) & S_IFMT) == S_IFREG)
#define S_ISDIR(m) (((m) & S_IFMT) == S_IFDIR)
#define S_ISCHR(m) (((m) & S_IFMT) == S_IFCHR)
#define S_ISBLK(m) (((m) & S_IFMT) == S_IFBLK)
#define S_ISFIFO(m) (((m) & S_IFMT) == S_IFIFO)
#define S_ISSOCK(m) (((m) & S_IFMT) == S_IFSOCK)
#define UF_NODUMP 0x00000001 /* do not dump file */
#define UF_IMMUTABLE 0x00000002 /* file may not be changed */
#define UF_APPEND 0x00000004 /* writes to file may only append */
#define UF_OPAQUE 0x00000008 /* directory is opaque wrt. union */
#define UF_NOUNLINK 0x00000010 /* file may not be removed or renamed */
#define UF_COMPRESSED 0x00000020 /* file is compressed */
#define UF_TRACKED 0x00000040 /* file renames and deletes are tracked */
#define UF_ENCRYPTED 0x00000080 /* item is encrypted */
#define UF_SPARSE 0x00000100 /* item is a sparse file */
#define UF_SYSTEM 0x00000200 /* item used exclusively by OS */
#define UF_HIDDEN 0x00008000 /* item is hidden */
#define SF_ARCHIVED 0x00010000 /* file is archived */
#define SF_IMMUTABLE 0x00020000 /* file may not be changed */
#define SF_APPEND 0x00040000 /* writes to file may only append */
#define SF_NOUNLINK 0x00100000 /* file may not be removed or renamed */
#define SF_SNAPSHOT 0x00200000 /* snapshot inode */
Typedefs
typedef struct stat sys_stat_t
Functions
PCL_EXPORT int pcl_statent (const pchar_t *path, int fd, pcl_stat_t *buf, int flags)
‪Get file or directory status.
PCL_EXPORT char * pcl_strmode (char *out, size_t out_size, mode_t mode)
PCL_EXPORT char * pcl_strflags (char *out, size_t len, uint32_t flags)
Macro Definition Documentation
sys_stat
#define sys_stat stat
Definition at line 45 of file stat.h.
sys_fstat
#define sys_fstat fstat
Definition at line 46 of file stat.h.
sys_lstat
#define sys_lstat lstat
Definition at line 47 of file stat.h.
PCL_STAT_LINK
#define PCL_STAT_LINK 0x01
Definition at line 52 of file stat.h.
PCL_STAT_SKIP_WIN32OWNER
#define PCL_STAT_SKIP_WIN32OWNER 0x10
Definition at line 59 of file stat.h.
pcl_stat
#define pcl_stat (path, stbuf) pcl_statent(path, -1, stbuf, 0)
Definition at line 61 of file stat.h.
pcl_fstat
#define pcl_fstat (fd, stbuf) pcl_statent(NULL, fd, stbuf, 0)
Definition at line 62 of file stat.h.
pcl_lstat
#define pcl_lstat (path, stbuf) pcl_statent(path, -1, stbuf, PCL_STAT_LINK)
Definition at line 63 of file stat.h.
S_IFMT
#define S_IFMT 0170000 /* file type mask */
Definition at line 71 of file stat.h.
S_IFSOCK
#define S_IFSOCK 0140000
Definition at line 74 of file stat.h.
S_IFLNK
#define S_IFLNK 0120000
Definition at line 77 of file stat.h.
S_IFREG
#define S_IFREG 0100000
Definition at line 80 of file stat.h.
S_IFBLK
#define S_IFBLK 0060000
Definition at line 83 of file stat.h.
S_IFDIR
#define S_IFDIR 0040000
Definition at line 86 of file stat.h.
S_IFCHR
#define S_IFCHR 0020000
Definition at line 89 of file stat.h.
S_IFIFO
#define S_IFIFO 0010000
Definition at line 92 of file stat.h.
S_IFMOD
#define S_IFMOD 07777 /* mode bits: mask for file type & perms, pcl extension */
Definition at line 100 of file stat.h.
S_ISUID
#define S_ISUID 04000 /* set-uid bit */
Definition at line 102 of file stat.h.
S_ISGID
#define S_ISGID 02000 /* set-gid bit */
Definition at line 105 of file stat.h.
S_ISVTX
#define S_ISVTX 01000 /* sticky bit */
Definition at line 108 of file stat.h.
S_IRWXU
#define S_IRWXU 00700
Definition at line 111 of file stat.h.
S_IRUSR
#define S_IRUSR 00400
Definition at line 114 of file stat.h.
S_IWUSR
#define S_IWUSR 00200
Definition at line 117 of file stat.h.
S_IXUSR
#define S_IXUSR 00100
Definition at line 120 of file stat.h.
S_IRWXG
#define S_IRWXG 00070
Definition at line 123 of file stat.h.
S_IRGRP
#define S_IRGRP 00040
Definition at line 126 of file stat.h.
S_IWGRP
#define S_IWGRP 00020
Definition at line 129 of file stat.h.
S_IXGRP
#define S_IXGRP 00010
Definition at line 132 of file stat.h.
S_IRWXO
#define S_IRWXO 00007
Definition at line 135 of file stat.h.
S_IROTH
#define S_IROTH 00004
Definition at line 138 of file stat.h.
S_IWOTH
#define S_IWOTH 00002
Definition at line 141 of file stat.h.
S_IXOTH
#define S_IXOTH 00001
Definition at line 144 of file stat.h.
S_ISLNK
#define S_ISLNK (m) (((m) & S_IFMT) == S_IFLNK)
Definition at line 148 of file stat.h.
S_ISREG
#define S_ISREG (m) (((m) & S_IFMT) == S_IFREG)
Definition at line 151 of file stat.h.
S_ISDIR
#define S_ISDIR (m) (((m) & S_IFMT) == S_IFDIR)
Definition at line 154 of file stat.h.
S_ISCHR
#define S_ISCHR (m) (((m) & S_IFMT) == S_IFCHR)
Definition at line 157 of file stat.h.
S_ISBLK
#define S_ISBLK (m) (((m) & S_IFMT) == S_IFBLK)
Definition at line 160 of file stat.h.
S_ISFIFO
#define S_ISFIFO (m) (((m) & S_IFMT) == S_IFIFO)
Definition at line 163 of file stat.h.
S_ISSOCK
#define S_ISSOCK (m) (((m) & S_IFMT) == S_IFSOCK)
Definition at line 166 of file stat.h.
UF_NODUMP
#define UF_NODUMP 0x00000001 /* do not dump file */
Definition at line 170 of file stat.h.
UF_IMMUTABLE
#define UF_IMMUTABLE 0x00000002 /* file may not be changed */
Definition at line 173 of file stat.h.
UF_APPEND
#define UF_APPEND 0x00000004 /* writes to file may only append */
Definition at line 176 of file stat.h.
UF_OPAQUE
#define UF_OPAQUE 0x00000008 /* directory is opaque wrt. union */
Definition at line 179 of file stat.h.
UF_NOUNLINK
#define UF_NOUNLINK 0x00000010 /* file may not be removed or renamed */
Definition at line 182 of file stat.h.
UF_COMPRESSED
#define UF_COMPRESSED 0x00000020 /* file is compressed */
Definition at line 185 of file stat.h.
UF_TRACKED
#define UF_TRACKED 0x00000040 /* file renames and deletes are tracked */
Definition at line 188 of file stat.h.
UF_ENCRYPTED
#define UF_ENCRYPTED 0x00000080 /* item is encrypted */
Definition at line 192 of file stat.h.
UF_SPARSE
#define UF_SPARSE 0x00000100 /* item is a sparse file */
Definition at line 193 of file stat.h.
UF_SYSTEM
#define UF_SYSTEM 0x00000200 /* item used exclusively by OS */
Definition at line 194 of file stat.h.
UF_HIDDEN
#define UF_HIDDEN 0x00008000 /* item is hidden */
Definition at line 198 of file stat.h.
SF_ARCHIVED
#define SF_ARCHIVED 0x00010000 /* file is archived */
Definition at line 201 of file stat.h.
SF_IMMUTABLE
#define SF_IMMUTABLE 0x00020000 /* file may not be changed */
Definition at line 204 of file stat.h.
SF_APPEND
#define SF_APPEND 0x00040000 /* writes to file may only append */
Definition at line 207 of file stat.h.
SF_NOUNLINK
#define SF_NOUNLINK 0x00100000 /* file may not be removed or renamed */
Definition at line 210 of file stat.h.
SF_SNAPSHOT
#define SF_SNAPSHOT 0x00200000 /* snapshot inode */
Definition at line 213 of file stat.h.
Typedef Documentation
sys_stat_t
typedef struct stat sys_stat_t
Definition at line 1 of file stat.h.
Function Documentation
pcl_statent()
PCL_EXPORT int pcl_statent (const pchar_t * path, int fd, pcl_stat_t * buf, int flags)
‪Get file or directory status.
This is normally not used directly. Instead, pcl_stat, pcl_fstat and pcl_lstat macros are used.
Parameters
path ‪filesystem entry to stat. If NULL, the fd argument must be valid.
fd ‪file descriptor representing the entry to stat. If < 0, path is expected to be valid.
buf ‪output stat buffer, this can be NULL in which case this function is merely an "exists" check.
flags ‪PCL_STAT_xxx flags such as PCL_STAT_LINK incicates this should perform an lstat.
Returns
‪on success 0 and -1 on error
Definition at line 39 of file statent.c.
References BADARG, ipcl_statent(), pcl_fdpath(), pcl_free_safe(), strempty, and TRC.
pcl_strmode()
PCL_EXPORT char* pcl_strmode (char * out, size_t out_size, mode_t mode)
Definition at line 35 of file strmode.c.
References S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFLNK, S_IFMT, S_IFREG, S_IFSOCK, S_IRGRP, S_IROTH, S_IRUSR, S_ISGID, S_ISUID, S_ISVTX, S_IWGRP, S_IWOTH, S_IWUSR, S_IXGRP, S_IXOTH, and S_IXUSR.
pcl_strflags()
PCL_EXPORT char* pcl_strflags (char * out, size_t len, uint32_t flags)
Definition at line 36 of file strflags.c.
References catflag, SF_APPEND, SF_ARCHIVED, SF_IMMUTABLE, SF_NOUNLINK, SF_SNAPSHOT, UF_APPEND, UF_COMPRESSED, UF_ENCRYPTED, UF_HIDDEN, UF_IMMUTABLE, UF_NODUMP, UF_NOUNLINK, UF_OPAQUE, UF_SPARSE, UF_SYSTEM, and UF_TRACKED.