‪libpcl: ‪pcl/time.h File Reference
time.h File Reference
#include <pcl/types.h>
#include <time.h>
#include <sys/time.h>
Data Structures
struct tag_pcl_time
struct pcl_tm_t
Macros
#define PCL_USECS 1000000
#define PCL_NSECS 1000000000
#define PCL_CLOCK_SEC PCL_NSECS
#define PCL_CLOCK_MSEC PCL_USECS
#define PCL_CLOCK_USEC 1000
Functions
PCL_PUBLIC pcl_time_t pcl_time (void)
PCL_PUBLIC int pcl_gmtime (const pcl_time_t *t, pcl_tm_t *result)
PCL_PUBLIC int pcl_localtime (const pcl_time_t *t, pcl_tm_t *result)
PCL_PUBLIC size_t pcl_strftime (char *out, size_t len, const char *format, const pcl_tm_t *tm)
PCL_PUBLIC int pcl_utimes (const pchar_t *path, pcl_time_t *atime, pcl_time_t *mtime, pcl_time_t *btime)
‪Set file times.
PCL_PUBLIC pcl_time_t pcl_mktime (pcl_tm_t *tu, bool utc)
‪Converts broken-down time to epoch nanoseconds.
PCL_PUBLIC bool pcl_sleep (uint64_t nsecs, bool(*cond)(void), uint32_t cond_interval)
‪Pause execution of the current thread for the given number of nanoseconds.
PCL_PUBLIC pcl_clock_t pcl_clock (void)
PCL_INLINE pcl_clock_t pcl_secdiff (pcl_clock_t start, pcl_clock_t end)
PCL_INLINE pcl_clock_t pcl_msecdiff (pcl_clock_t start, pcl_clock_t end)
PCL_INLINE pcl_clock_t pcl_usecdiff (pcl_clock_t start, pcl_clock_t end)
Macro Definition Documentation
PCL_USECS
#define PCL_USECS 1000000
Definition at line 46 of file time.h.
PCL_NSECS
#define PCL_NSECS 1000000000
Definition at line 47 of file time.h.
PCL_CLOCK_SEC
#define PCL_CLOCK_SEC PCL_NSECS
Definition at line 48 of file time.h.
PCL_CLOCK_MSEC
#define PCL_CLOCK_MSEC PCL_USECS
Definition at line 49 of file time.h.
PCL_CLOCK_USEC
#define PCL_CLOCK_USEC 1000
Definition at line 50 of file time.h.
Function Documentation
pcl_time()
PCL_PUBLIC pcl_time_t pcl_time (void)
Definition at line 35 of file time.c.
References ipcl_time_context(), ipcl_win32_ftime_to_pcl(), tag_pcl_time::nsec, PCL_NSECS, and tag_pcl_time::sec.
Referenced by pcl_log_event_default(), and pcl_proc_exec().
pcl_gmtime()
PCL_PUBLIC int pcl_gmtime (const pcl_time_t * t, pcl_tm_t * result)
Definition at line 116 of file break_down_time.c.
Referenced by pcl_log_vevent().
pcl_localtime()
PCL_PUBLIC int pcl_localtime (const pcl_time_t * t, pcl_tm_t * result)
Definition at line 110 of file break_down_time.c.
Referenced by pcl_log_vevent(), and pcl_sysinfo().
pcl_strftime()
PCL_PUBLIC size_t pcl_strftime (char * out, size_t len, const char * format, const pcl_tm_t * tm)
Parameters
out ‪output buffer. Set to NULL to query output length
len ‪size in bytes of output buffer. If this is 0 or out is NULL, the function merely queries for output length.
format
tm
Returns
Definition at line 37 of file strftime.c.
References BADARG, PCL_EBUF, SETERR, pcl_tm_t::tm_gmtoff, pcl_tm_t::tm_hour, pcl_tm_t::tm_isdst, pcl_tm_t::tm_mday, pcl_tm_t::tm_min, pcl_tm_t::tm_mon, pcl_tm_t::tm_sec, pcl_tm_t::tm_wday, pcl_tm_t::tm_yday, pcl_tm_t::tm_year, and pcl_tm_t::tm_zone.
Referenced by pcl_log_vevent().
pcl_utimes()
PCL_PUBLIC int pcl_utimes (const pchar_t * path, pcl_time_t * atime, pcl_time_t * mtime, pcl_time_t * btime)
‪Set file times.
Note
‪this function will not follow symlinks. times will be set on link itself.
Parameters
path ‪pointer to a path string
atime ‪access time
mtime ‪modified time
btime ‪creation/birth time, cannot be set on linux and is silently ignored.
Returns
‪0 for success and -1 on error
Definition at line 51 of file unix_utimes.c.
References tag_pcl_stat::atime, tag_pcl_stat::btime, tag_pcl_file::fd, ipcl_win32_pcl_to_ftime(), tag_pcl_stat::mode, tag_pcl_stat::mtime, tag_pcl_time::nsec, pcl_file_close(), pcl_file_open(), pcl_lstat, PCL_O_BACKUP, PCL_O_WRONLY, S_ISLNK, tag_pcl_time::sec, SETLASTERR, and TRC.
pcl_mktime()
PCL_PUBLIC pcl_time_t pcl_mktime (pcl_tm_t * tu, bool utc)
‪Converts broken-down time to epoch nanoseconds.
Parameters
tu
utc ‪true to interrupt tu as UTC and false for localtime
Returns
Definition at line 35 of file mktime.c.
References tag_pcl_time::nsec, tag_pcl_time::sec, pcl_tm_t::tm_hour, pcl_tm_t::tm_isdst, pcl_tm_t::tm_mday, pcl_tm_t::tm_min, pcl_tm_t::tm_mon, pcl_tm_t::tm_nsec, pcl_tm_t::tm_sec, pcl_tm_t::tm_wday, pcl_tm_t::tm_yday, and pcl_tm_t::tm_year.
pcl_sleep()
PCL_PUBLIC bool pcl_sleep (uint64_t nsecs, bool(*)(void) cond, uint32_t cond_interval)
‪Pause execution of the current thread for the given number of nanoseconds.
Parameters
nsecs ‪nanoseconds to sleep, guarenteed to sleep for this amount when cond parameter is NOT provided.
cond ‪When not NULL, this is called every cond_interval seconds and aborts the sleep operation if it returns true.
cond_interval ‪nanosecond interval between calls to optional "cond" argument. If this is zero, the default interval of 10000000 ns is used (10 ms). Note: cond is called prior to the first sleep. This argument is ignored if cond is NULL.
Returns
‪true for success and false otherwise. When cond is not NULL, true can mean the cond returned true or the function slept for the entire nsecs.
Definition at line 93 of file sleep.c.
pcl_clock()
PCL_PUBLIC pcl_clock_t pcl_clock (void)
Definition at line 36 of file clock.c.
References ipcl_time_context(), and PCL_NSECS.
Referenced by pcl_select().
pcl_secdiff()
PCL_INLINE pcl_clock_t pcl_secdiff (pcl_clock_t start, pcl_clock_t end)
Definition at line 142 of file time.h.
References PCL_CLOCK_SEC.
pcl_msecdiff()
PCL_INLINE pcl_clock_t pcl_msecdiff (pcl_clock_t start, pcl_clock_t end)
Definition at line 148 of file time.h.
References PCL_CLOCK_MSEC.
pcl_usecdiff()
PCL_INLINE pcl_clock_t pcl_usecdiff (pcl_clock_t start, pcl_clock_t end)
Definition at line 154 of file time.h.
References PCL_CLOCK_USEC.
Referenced by pcl_select().