‪libpcl: ‪pcl/usrgrp.h File Reference
usrgrp.h File Reference
#include <pcl/types.h>
Functions
PCL_EXPORT int pcl_getuser (const uid_t uid, char *out, size_t len)
PCL_EXPORT int pcl_getgroup (const gid_t gid, char *out, size_t len)
PCL_EXPORT int pcl_getuid (const char *name, uid_t *uidp)
‪Gets the user identifier for the given account user name.
int pcl_getgid (const char *name, gid_t *gidp)
‪Gets the group identifier for the given group name.
Function Documentation
pcl_getuser()
PCL_EXPORT int pcl_getuser (const uid_t uid, char * out, size_t len)
Definition at line 37 of file getuser.c.
References BADARG, ipcl_win32_sid_to_name(), PCL_ENOTFOUND, pcl_strcpy(), SETERR, SETLASTERR, SETOSERR, and TRC.
Referenced by pcl_getgroup().
pcl_getgroup()
PCL_EXPORT int pcl_getgroup (const gid_t gid, char * out, size_t len)
Definition at line 37 of file getgroup.c.
References PCL_ENOTFOUND, pcl_getuser(), pcl_strcpy(), SETERR, SETOSERR, and TRC.
pcl_getuid()
PCL_EXPORT int pcl_getuid (const char * name, uid_t * uidp)
‪Gets the user identifier for the given account user name.
Parameters
name ‪account user name
uidp ‪pointer to a uid_t to receive the user identifier. This can be NULL, in which case this function becomes an "exists" check.
Returns
‪0 on success and -1 on failure. If the user referenced by name does not exist, the pcl_errno is set to PCL_ENOTFOUND (not PCL_ENOENT, which the OS may set for other reasons).
Definition at line 38 of file getuid.c.
References BADARG, PCL_ENOTFOUND, pcl_strcpy(), SETERR, SETLASTERR, SETOSERR, and strempty.
Referenced by pcl_getgid(), and pcl_proc_exec().
pcl_getgid()
int pcl_getgid (const char * name, gid_t * gidp)
‪Gets the group identifier for the given group name.
Parameters
name ‪group name
gidp ‪pointer to a gid_t to receive the group identifier. This can be NULL, in which case this function becomes an "exists" check.
Returns
‪0 on success and -1 on failure. If the group referenced by name does not exist, the pcl_errno is set to PCL_ENOTFOUND (not PCL_ENOENT, which the OS may set for other reasons).
Definition at line 37 of file getgid.c.
References BADARG, PCL_ENOTFOUND, pcl_getuid(), SETERR, SETOSERR, strempty, and TRC.
Referenced by pcl_proc_exec().