‪libpcl: ‪pcl/thread.h File Reference
thread.h File Reference
#include <pcl/types.h>
#include <pthread.h>
Macros
#define _TIMESPEC_DEFINED
Typedefs
typedef void(* pcl_thread_start_t) (void *)
Functions
PCL_PUBLIC int pcl_thread (pthread_t *t, pcl_thread_start_t routine, void *a)
PCL_PUBLIC uint64_t pcl_thread_id (void)
PCL_PUBLIC int pcl_mutex_init (pthread_mutex_t *m)
PCL_PUBLIC int pcl_mutex_lock (pthread_mutex_t *m)
PCL_PUBLIC int pcl_mutex_trylock (pthread_mutex_t *m)
PCL_PUBLIC int pcl_mutex_unlock (pthread_mutex_t *m)
PCL_PUBLIC int pcl_mutex_destroy (pthread_mutex_t *m)
PCL_PUBLIC int pcl_tls_alloc (pthread_key_t *key, void(*destructor)(void *))
PCL_PUBLIC int pcl_tls_set (pthread_key_t key, void *value)
PCL_PUBLIC void * pcl_tls_get (pthread_key_t key)
PCL_PUBLIC int pcl_tls_free (pthread_key_t key)
Macro Definition Documentation
_TIMESPEC_DEFINED
#define _TIMESPEC_DEFINED
Definition at line 37 of file thread.h.
Typedef Documentation
pcl_thread_start_t
typedef void(* pcl_thread_start_t) (void *)
Definition at line 44 of file thread.h.
Function Documentation
pcl_thread()
PCL_PUBLIC int pcl_thread (pthread_t * t, pcl_thread_start_t routine, void * a)
Definition at line 58 of file thread.c.
References thread_start_t::arg, pcl_malloc(), thread_start_t::routine, and SETERR.
pcl_thread_id()
PCL_PUBLIC uint64_t pcl_thread_id (void)
Definition at line 42 of file thread_id.c.
pcl_mutex_init()
PCL_PUBLIC int pcl_mutex_init (pthread_mutex_t * m)
Definition at line 36 of file mutex_init.c.
References BADARG, and SETOSERR.
Referenced by ipcl_event_init().
pcl_mutex_lock()
PCL_PUBLIC int pcl_mutex_lock (pthread_mutex_t * m)
Definition at line 36 of file mutex_lock.c.
References BADARG, and SETOSERR.
Referenced by ipcl_event_context().
pcl_mutex_trylock()
PCL_PUBLIC int pcl_mutex_trylock (pthread_mutex_t * m)
Definition at line 36 of file mutex_trylock.c.
References BADARG, and SETOSERR.
pcl_mutex_unlock()
PCL_PUBLIC int pcl_mutex_unlock (pthread_mutex_t * m)
Definition at line 36 of file mutex_unlock.c.
References BADARG, and SETOSERR.
Referenced by ipcl_event_context_release().
pcl_mutex_destroy()
PCL_PUBLIC int pcl_mutex_destroy (pthread_mutex_t * m)
Definition at line 36 of file mutex_destroy.c.
References SETOSERR.
pcl_tls_alloc()
PCL_PUBLIC int pcl_tls_alloc (pthread_key_t * key, void(*)(void *) destructor)
Definition at line 36 of file tls_alloc.c.
References SETOSERR.
Referenced by ipcl_err_handler(), and ipcl_win32_stat_handler().
pcl_tls_set()
PCL_PUBLIC int pcl_tls_set (pthread_key_t key, void * value)
Definition at line 36 of file tls_set.c.
References SETOSERR.
pcl_tls_get()
PCL_PUBLIC void* pcl_tls_get (pthread_key_t key)
Definition at line 35 of file tls_get.c.
Referenced by pcl_err_get().
pcl_tls_free()
PCL_PUBLIC int pcl_tls_free (pthread_key_t key)
Definition at line 36 of file tls_free.c.
References SETOSERR.