‪libpcl: ‪/Users/andrew/projects/libpcl/src/error/err_serialize.c File Reference
err_serialize.c File Reference
#include "_error.h"
#include <pcl/buf.h>
#include <pcl/io.h>
Functions
pcl_buf_t * ipcl_err_serialize (int indent, const char *format, va_list ap)
Function Documentation
ipcl_err_serialize()
pcl_buf_t* ipcl_err_serialize (int indent, const char * format, va_list ap)
Definition at line 37 of file err_serialize.c.
References tag_pcl_err::buffer, tag_pcl_buf::data, tag_pcl_err::err, tag_pcl_err_trace::file, tag_pcl_err_trace::func, tag_pcl_buf::len, tag_pcl_err_trace::line, max, tag_pcl_err_trace::msg, tag_pcl_err_trace::next, pcl_buf_init(), pcl_buf_putchar(), pcl_buf_putf(), pcl_buf_reset(), pcl_buf_vputf(), PCL_EOKAY, pcl_err_get(), pcl_err_msg(), pcl_err_name(), pcl_sprintf(), PclBufText, tag_pcl_err::strace, and strempty.
Referenced by pcl_err_vfprintf(), and pcl_err_vsprintf().