‪libpcl: ‪/Users/andrew/projects/libpcl/src/error/_error.h File Reference
_error.h File Reference
#include <pcl/error.h>
Data Structures
struct ipcl_err_msgmap_t
struct ipcl_err_map_t
Functions
PCL_PRIVATE ipcl_err_msgmap_t * ipcl_err_msgmap (int *count)
PCL_PRIVATE ipcl_err_map_t * ipcl_err_map (int *count)
PCL_PRIVATE pcl_buf_t * ipcl_err_serialize (int indent, const char *format, va_list ap)
PCL_PRIVATE void ipcl_err_handler (uint32_t which, void *data)
PCL_PRIVATE pcl_err_trace_t * ipcl_err_trace_free (pcl_err_trace_t *head)
Function Documentation
ipcl_err_msgmap()
PCL_PRIVATE ipcl_err_msgmap_t* ipcl_err_msgmap (int * count)
Definition at line 40 of file msgmap.c.
References countof.
Referenced by pcl_err_code(), pcl_err_msg(), and pcl_err_name().
ipcl_err_map()
PCL_PRIVATE ipcl_err_map_t* ipcl_err_map (int * count)
Definition at line 53 of file errmap.c.
References countof.
Referenced by pcl_err_os2pcl(), and pcl_err_osname().
ipcl_err_serialize()
PCL_PRIVATE pcl_buf_t* ipcl_err_serialize (int indent, const char * format, va_list ap)
Definition at line 37 of file err_serialize.c.
References tag_pcl_err::buffer, tag_pcl_buf::data, tag_pcl_err::err, tag_pcl_err_trace::file, tag_pcl_err_trace::func, tag_pcl_buf::len, tag_pcl_err_trace::line, max, tag_pcl_err_trace::msg, tag_pcl_err_trace::next, pcl_buf_init(), pcl_buf_putchar(), pcl_buf_putf(), pcl_buf_reset(), pcl_buf_vputf(), PCL_EOKAY, pcl_err_get(), pcl_err_msg(), pcl_err_name(), pcl_sprintf(), PclBufText, tag_pcl_err::strace, and strempty.
Referenced by pcl_err_vfprintf(), and pcl_err_vsprintf().
ipcl_err_handler()
PCL_PRIVATE void ipcl_err_handler (uint32_t which, void * data)
Definition at line 63 of file err_ctx.c.
References PCL_EVENT_INIT, pcl_tls_alloc(), and UNUSED.
ipcl_err_trace_free()
PCL_PRIVATE pcl_err_trace_t* ipcl_err_trace_free (pcl_err_trace_t * head)
Definition at line 36 of file err_trace_free.c.
References tag_pcl_err_trace::next, and pcl_free().
Referenced by pcl_err_clear().