‪libpcl: ‪/Users/andrew/projects/libpcl/src/errctx/err_ctx_vsprintf.c File Reference
err_ctx_vsprintf.c File Reference
#include "_errctx.h"
#include <pcl/buf.h>
#include <string.h>
Functions
int pcl_err_ctx_vsprintf (pcl_err_ctx_t *ctx, char *buf, size_t size, int indent, const char *message, va_list ap)
Function Documentation
pcl_err_ctx_vsprintf()
int pcl_err_ctx_vsprintf (pcl_err_ctx_t * ctx, char * buf, size_t size, int indent, const char * message, va_list ap)
Definition at line 37 of file err_ctx_vsprintf.c.
References tag_pcl_buf::data, tag_pcl_err_ctx::frozen, ipcl_err_ctx_serialize(), and tag_pcl_buf::len.
Referenced by pcl_err_ctx_sprintf(), and pcl_err_vsprintf().