‪libpcl: ‪/Users/andrew/projects/libpcl/src/errctx/err_ctx_free.c File Reference
err_ctx_free.c File Reference
#include "_errctx.h"
#include <pcl/buf.h>
#include <pcl/alloc.h>
Functions
void ipcl_err_ctx_destroy (void *obj)
void pcl_err_ctx_free (pcl_err_ctx_t *ctx)
‪Release all resources held by the given context including the context itself.
Function Documentation
ipcl_err_ctx_destroy()
void ipcl_err_ctx_destroy (void * obj)
Definition at line 38 of file err_ctx_free.c.
References tag_pcl_err_ctx::buffer, ipcl_err_ctx_trace_free(), pcl_buf_free(), pcl_free(), and tag_pcl_err_ctx::strace.
Referenced by pcl_err_ctx_free().
pcl_err_ctx_free()
void pcl_err_ctx_free (pcl_err_ctx_t * ctx)
‪Release all resources held by the given context including the context itself.
Warning
‪this will call pcl_memory_error if you try to free the per-thread context. The type parameter of pcl_memory_error is set to "err_ctx_free".
Parameters
ctx
Definition at line 47 of file err_ctx_free.c.
References tag_pcl_err_ctx::frozen, ipcl_err_ctx_destroy(), pcl_err_ctx(), PCL_LOCATION_ARGS, and pcl_memory_error().