‪libpcl: ‪/Users/andrew/projects/libpcl/src/errctx/_errctx.h File Reference
_errctx.h File Reference
#include <pcl/errctx.h>
#include <pcl/error.h>
Functions
void ipcl_err_ctx_destroy (void *obj)
void ipcl_err_ctx_handler (uint32_t which, void *data)
pcl_buf_t * ipcl_err_ctx_serialize (pcl_err_ctx_t *ctx, int indent, const char *format, va_list ap)
pcl_err_trace_t * ipcl_err_ctx_trace_free (pcl_err_trace_t *head)
Function Documentation
ipcl_err_ctx_destroy()
void ipcl_err_ctx_destroy (void * obj)
Definition at line 38 of file err_ctx_free.c.
References tag_pcl_err_ctx::buffer, ipcl_err_ctx_trace_free(), pcl_buf_free(), pcl_free(), and tag_pcl_err_ctx::strace.
Referenced by pcl_err_ctx_free().
ipcl_err_ctx_handler()
void ipcl_err_ctx_handler (uint32_t which, void * data)
Definition at line 51 of file err_ctx.c.
References PCL_EVENT_INIT, pcl_tls_alloc(), and UNUSED.
ipcl_err_ctx_serialize()
pcl_buf_t* ipcl_err_ctx_serialize (pcl_err_ctx_t * ctx, int indent, const char * format, va_list ap)
Definition at line 37 of file err_ctx_serialize.c.
References tag_pcl_err_ctx::buffer, tag_pcl_buf::data, tag_pcl_err_ctx::err, tag_pcl_err_trace::file, tag_pcl_err_trace::func, tag_pcl_buf::len, tag_pcl_err_trace::line, tag_pcl_err_trace::msg, tag_pcl_err_trace::next, pcl_buf_init(), pcl_buf_putchar(), pcl_buf_putf(), pcl_buf_reset(), pcl_buf_vputf(), PCL_EOKAY, pcl_err_msg(), pcl_err_name(), pcl_sprintf(), PclBufText, tag_pcl_err_ctx::strace, and strempty.
Referenced by pcl_err_ctx_vfprintf(), and pcl_err_ctx_vsprintf().
ipcl_err_ctx_trace_free()
pcl_err_trace_t* ipcl_err_ctx_trace_free (pcl_err_trace_t * head)
Definition at line 36 of file err_ctx_trace_free.c.
References tag_pcl_err_trace::next, and pcl_free().
Referenced by ipcl_err_ctx_destroy(), and pcl_err_ctx_clear().