‪libpcl: ‪/Users/andrew/projects/libpcl/src/file/fdpath.c File Reference
fdpath.c File Reference
#include "_file.h"
#include <pcl/error.h>
#include <pcl/alloc.h>
#include <pcl/io.h>
#include <pcl/string.h>
#include <limits.h>
Functions
int pcl_fdpath (int fd, pchar_t **out)
Function Documentation
pcl_fdpath()
int pcl_fdpath (int fd, pchar_t ** out)
Definition at line 51 of file fdpath.c.
References _P, BADARG, countof, FREEZE_ERR, pcl_aspprintf(), PCL_ENOTSUP, pcl_free(), PCL_MAXPATH, pcl_pcsdup(), pcl_pcslen(), pcl_pcsnicmp(), pcl_pmalloc(), pcl_sprintf(), pcl_strndup(), SETERR, SETLASTERR, and TRC.
Referenced by pcl_statent().