‪libpcl: ‪/Users/andrew/projects/libpcl/src/file/win32_file_open.c File Reference
win32_file_open.c File Reference
#include "_file.h"
#include "../win32/_win32.h"
#include <pcl/error.h>
Functions
int ipcl_file_open (pcl_file_t *file, const pchar_t *path, int pcl_oflags, mode_t mode)
Function Documentation
ipcl_file_open()
int ipcl_file_open (pcl_file_t * file, const pchar_t * path, int pcl_oflags, mode_t mode)
Definition at line 37 of file win32_file_open.c.
References tag_pcl_file::fd, tag_pcl_file::flags, ipcl_win32_sd_clear(), ipcl_win32_sd_create(), PCL_BADFD, PCL_EINVAL, PCL_ENOTDIR, PCL_ETYPE, PCL_FF_OLOCK, PCL_O_BACKUP, PCL_O_CREAT, PCL_O_DIRECTORY, PCL_O_EXCL, PCL_O_EXLOCK, PCL_O_NOFOLLOW, PCL_O_NOINHERIT, PCL_O_NONBLOCK, PCL_O_RDWR, PCL_O_SHLOCK, PCL_O_SYNC, PCL_O_TEMP, PCL_O_TRUNC, PCL_O_WRONLY, pcl_oserrno, SETERR, SETERRMSG, SETLASTERR, SETLASTERRMSG, and TRC.
Referenced by pcl_file_open().