‪libpcl: ‪/Users/andrew/projects/libpcl/src/htable/_htable.h File Reference
_htable.h File Reference
#include <pcl/htable.h>
Macros
#define MAX_LOADFAC 0.75f
#define MIN_LOADFAC 0.2f
#define MIN_TABLE_SIZE 17
Functions
int ipcl_htable_capacity (int capacity)
pcl_htable_entry_t * ipcl_htable_lookup (pcl_htable_t *ht, const void *key, uintptr_t *code, int *index)
void ipcl_htable_remove_entry (pcl_htable_t *ht, pcl_htable_entry_t *ent, bool allow_rehash)
int ipcl_htable_rehash (pcl_htable_t *ht, bool grow)
Macro Definition Documentation
MAX_LOADFAC
#define MAX_LOADFAC 0.75f
Definition at line 37 of file _htable.h.
MIN_LOADFAC
#define MIN_LOADFAC 0.2f
Definition at line 38 of file _htable.h.
MIN_TABLE_SIZE
#define MIN_TABLE_SIZE 17
Definition at line 39 of file _htable.h.
Function Documentation
ipcl_htable_capacity()
int ipcl_htable_capacity (int capacity)
Definition at line 36 of file htable_capacity.c.
References countof, MIN_TABLE_SIZE, PCL_ERANGE, and SETERR.
Referenced by ipcl_htable_rehash(), and pcl_htable_create().
ipcl_htable_lookup()
pcl_htable_entry_t* ipcl_htable_lookup (pcl_htable_t * ht, const void * key, uintptr_t * code, int * index)
Definition at line 47 of file htable_lookup.c.
References tag_pcl_htable::capacity, tag_pcl_htable::entries, tag_pcl_htable::hashcode, tag_pcl_htable::key_equals, tag_pcl_htable::key_len, tag_pcl_htable_entry::next, PCL_ENOTFOUND, R_SETERR, and tag_pcl_htable::userp.
Referenced by pcl_htable_lookup(), and pcl_htable_put().
ipcl_htable_remove_entry()
void ipcl_htable_remove_entry (pcl_htable_t * ht, pcl_htable_entry_t * ent, bool allow_rehash)
Parameters
ht
ent
allow_rehash ‪When true and the table has fallen below the min_loadfac, a table rehash is automatically performed. When false, the min_loadfac check is skipped and no table rehash is performed. pcl_htable_clear is an example of why one might set this false. That function removes all entries and then shrinks the table to MIN_TABLE_SIZE. No reason to rehash while removing.
Definition at line 36 of file htable_remove_entry.c.
References tag_pcl_htable::capacity, tag_pcl_htable::count, ipcl_htable_rehash(), tag_pcl_htable_entry::key, tag_pcl_htable::min_loadfac, MIN_TABLE_SIZE, pcl_free(), tag_pcl_htable::remove_entry, tag_pcl_htable::userp, and tag_pcl_htable_entry::value.
Referenced by pcl_htable_clear(), and pcl_htable_remove().
ipcl_htable_rehash()
int ipcl_htable_rehash (pcl_htable_t * ht, bool grow)
Parameters
ht
grow ‪true to grow table and false to shrink. When true, the new table size is set to double its current value and then rounded up to the nearest prime. When false, the table size is divided in half and then rounded up to the nearest table size.
Returns
Definition at line 37 of file htable_rehash.c.
References tag_pcl_htable::capacity, tag_pcl_htable_entry::code, tag_pcl_htable::entries, ipcl_htable_capacity(), tag_pcl_htable_entry::next, pcl_free_safe(), pcl_zalloc(), and TRC.
Referenced by ipcl_htable_remove_entry(), and pcl_htable_put().