‪libpcl: ‪/Users/andrew/projects/libpcl/src/file/realpath.c File Reference
realpath.c File Reference
#include <pcl/error.h>
#include <pcl/string.h>
#include <limits.h>
#include <stdlib.h>
Functions
pchar_t * pcl_realpath (const pchar_t *path, int *lenp)
‪Gets the canonicalized absolute pathname.
Function Documentation
pcl_realpath()
pchar_t* pcl_realpath (const pchar_t * path, int * lenp)
‪Gets the canonicalized absolute pathname.
Parameters
path ‪path to convert
[out] lenp ‪If not NULL, character length (excluding NUL) is written here
Returns
‪an allocated absolute path or NULL on error
Definition at line 44 of file realpath.c.
References PCL_EINVAL, pcl_malloc(), pcl_strndup(), R_SETERR, R_SETLASTERR, and strempty.
Referenced by pcl_opendir().