‪libpcl: ‪/Users/andrew/projects/libpcl/src/event/_event.h File Reference
_event.h File Reference
#include <pcl/event.h>
#include <pcl/array.h>
Data Structures
struct ipcl_event_context_t
Functions
PCL_PRIVATE void ipcl_event_init (void)
PCL_PRIVATE ipcl_event_context_t * ipcl_event_context (void)
PCL_PRIVATE void ipcl_event_context_release (void)
Function Documentation
ipcl_event_init()
PCL_PRIVATE void ipcl_event_init (void)
Definition at line 39 of file event_context.c.
References pcl_mutex_init().
Referenced by pcl_init().
ipcl_event_context()
PCL_PRIVATE ipcl_event_context_t* ipcl_event_context (void)
Definition at line 46 of file event_context.c.
References pcl_mutex_lock().
Referenced by pcl_event_dispatch(), pcl_event_register(), and pcl_event_unregister().
ipcl_event_context_release()
PCL_PRIVATE void ipcl_event_context_release (void)
Definition at line 53 of file event_context.c.
References pcl_mutex_unlock().
Referenced by pcl_event_dispatch(), pcl_event_register(), and pcl_event_unregister().