‪libpcl: ‪/Users/andrew/projects/libpcl/src/file/fdpath.c File Reference
fdpath.c File Reference
#include "_file.h"
#include <pcl/error.h>
#include <pcl/alloc.h>
#include <pcl/io.h>
#include <pcl/string.h>
#include <limits.h>
Functions
int pcl_fdpath (int fd, tchar_t **out)
Function Documentation
pcl_fdpath()
int pcl_fdpath (int fd, tchar_t ** out)
Definition at line 51 of file fdpath.c.
References _T, BADARG, countof, FREEZE_ERR, pcl_astprintf(), PCL_ENOTSUP, pcl_free(), PCL_MAXPATH, pcl_sprintf(), pcl_strndup(), pcl_tcsdup(), pcl_tcslen(), pcl_tcsnicmp(), pcl_tmalloc(), SETERR, SETLASTERR, and TRC.
Referenced by pcl_statent().