‪libpcl: ‪/Users/andrew/projects/libpcl/src/file/unix_file_open.c File Reference
unix_file_open.c File Reference
#include "_file.h"
#include <pcl/error.h>
#include <pcl/io.h>
Functions
int ipcl_file_open (pcl_file_t *file, const pchar_t *path, int pcl_oflags, mode_t mode)
Function Documentation
ipcl_file_open()
int ipcl_file_open (pcl_file_t * file, const pchar_t * path, int pcl_oflags, mode_t mode)
Definition at line 37 of file unix_file_open.c.
References tag_pcl_file::fd, tag_pcl_file::flags, ipcl_sysoflags(), PCL_ENOTDIR, PCL_ETYPE, PCL_FF_FLOCK, PCL_FF_OLOCK, pcl_file_lock(), PCL_O_DIRECTORY, PCL_O_EXLOCK, PCL_O_NOFOLLOW, PCL_O_SHLOCK, PCL_O_TEMP, PCL_RDLOCK, pcl_unlink(), PCL_WRLOCK, S_ISDIR, S_ISLNK, SETERR, SETERRMSG, SETLASTERR, sys_lstat, and TRCMSG.