‪libpcl: ‪/Users/andrew/projects/libpcl/src/file/file_init.c File Reference
file_init.c File Reference
#include "_file.h"
#include <pcl/defs.h>
Functions
pcl_file_t * ipcl_file_init (pcl_file_t *file, int oflags)
‪Initialize a preallocated file using a set of file-flags.
Function Documentation
ipcl_file_init()
pcl_file_t* ipcl_file_init (pcl_file_t * file, int fflags)
‪Initialize a preallocated file using a set of file-flags.
Parameters
file
fflags
Returns
Definition at line 36 of file file_init.c.
References tag_pcl_file::fd, tag_pcl_file::flags, ipcl_oflags_to_fflags(), PCL_BADFD, PCL_FF_NONBLOCK, PCL_FF_READ, and PCL_FF_WRITE.
Referenced by pcl_file_open(), and pcl_proc_pipe().