‪libpcl: ‪/Users/andrew/projects/libpcl/src/event/_event.h File Reference
_event.h File Reference
#include <pcl/event.h>
Data Structures
struct ipcl_event_context_t
Functions
void ipcl_event_init (void)
ipcl_event_context_t * ipcl_event_context (void)
void ipcl_event_context_release (void)
Function Documentation
ipcl_event_init()
void ipcl_event_init (void)
Definition at line 39 of file event_context.c.
References pcl_mutex_init().
Referenced by pcl_init().
ipcl_event_context()
ipcl_event_context_t* ipcl_event_context (void)
Definition at line 45 of file event_context.c.
References pcl_mutex_lock().
Referenced by pcl_event_dispatch(), pcl_event_register(), and pcl_event_unregister().
ipcl_event_context_release()
void ipcl_event_context_release (void)
Definition at line 52 of file event_context.c.
References pcl_mutex_unlock().
Referenced by pcl_event_dispatch(), pcl_event_register(), and pcl_event_unregister().