‪libpcl: ‪/Users/andrew/projects/libpcl/src/file/file_close.c File Reference
file_close.c File Reference
#include "_file.h"
#include <pcl/alloc.h>
#include <pcl/defs.h>
#include <pcl/error.h>
Functions
void pcl_file_close (pcl_file_t *file)
Function Documentation
pcl_file_close()
void pcl_file_close (pcl_file_t * file)
Definition at line 38 of file file_close.c.
References tag_pcl_file::fd, tag_pcl_file::flags, PCL_BADFD, pcl_err_freeze(), PCL_FF_FLOCK, PCL_FF_NONBLOCK, PCL_FF_READ, PCL_FF_WRITE, pcl_file_lock(), pcl_free(), and PCL_UNLOCK.
Referenced by pcl_fdopen(), pcl_file_open(), pcl_popen(), pcl_proc_exec(), pcl_readdir(), pcl_tmpfile(), and pcl_utimes().