‪libpcl: ‪/Users/andrew/projects/libpcl/src/file/_file.h File Reference
_file.h File Reference
#include <pcl/file.h>
#include <fcntl.h>
#include <unistd.h>
Data Structures
struct tag_pcl_file
Functions
pcl_file_t * ipcl_file_alloc (pcl_fd_t fd, int fflags)
int ipcl_file_open (pcl_file_t *file, const tchar_t *path, int flags, mode_t mode)
pcl_file_t * ipcl_file_init (pcl_file_t *file, int fflags)
‪Initialize a preallocated file using a set of file-flags.
int ipcl_oflags_to_fflags (int oflags)
int ipcl_sysoflags (uint32_t pcl_oflags)
Function Documentation
ipcl_file_alloc()
pcl_file_t* ipcl_file_alloc (pcl_fd_t fd, int fflags)
Definition at line 36 of file file_alloc.c.
References tag_pcl_file::fd, tag_pcl_file::flags, and pcl_zalloc().
Referenced by pcl_file_open(), and pcl_proc_pipe().
ipcl_file_open()
int ipcl_file_open (pcl_file_t * file, const tchar_t * path, int flags, mode_t mode)
Definition at line 37 of file unix_file_open.c.
References tag_pcl_file::fd, tag_pcl_file::flags, ipcl_sysoflags(), ipcl_win32_sd_clear(), ipcl_win32_sd_create(), PCL_BADFD, PCL_EINVAL, PCL_ENOTDIR, PCL_ETYPE, PCL_FF_FLOCK, PCL_FF_OLOCK, pcl_file_lock(), PCL_O_BACKUP, PCL_O_CREAT, PCL_O_DIRECTORY, PCL_O_EXCL, PCL_O_EXLOCK, PCL_O_NOFOLLOW, PCL_O_NOINHERIT, PCL_O_NONBLOCK, PCL_O_RDWR, PCL_O_SHLOCK, PCL_O_SYNC, PCL_O_TEMP, PCL_O_TRUNC, PCL_O_WRONLY, pcl_oserrno, PCL_RDLOCK, pcl_unlink(), PCL_WRLOCK, S_ISDIR, S_ISLNK, SETERR, SETERRMSG, SETLASTERR, SETLASTERRMSG, sys_lstat, TRC, and TRCMSG.
Referenced by pcl_file_open().
ipcl_file_init()
pcl_file_t* ipcl_file_init (pcl_file_t * file, int fflags)
‪Initialize a preallocated file using a set of file-flags.
Parameters
file
fflags
Returns
Definition at line 36 of file file_init.c.
References tag_pcl_file::fd, tag_pcl_file::flags, ipcl_oflags_to_fflags(), PCL_BADFD, PCL_FF_NONBLOCK, PCL_FF_READ, and PCL_FF_WRITE.
Referenced by pcl_file_open(), and pcl_proc_pipe().
ipcl_oflags_to_fflags()
int ipcl_oflags_to_fflags (int oflags)
Definition at line 36 of file flagconv.c.
References PCL_FF_APPEND, PCL_FF_NONBLOCK, PCL_FF_RDWR, PCL_FF_READ, PCL_FF_WRITE, PCL_O_APPEND, PCL_O_NONBLOCK, PCL_O_RDWR, and PCL_O_WRONLY.
Referenced by ipcl_file_init().
ipcl_sysoflags()
int ipcl_sysoflags (uint32_t pcl_oflags)
Definition at line 57 of file flagconv.c.
References PCL_O_APPEND, PCL_O_CLOEXEC, PCL_O_CREAT, PCL_O_DIRECTORY, PCL_O_EXCL, PCL_O_EXLOCK, PCL_O_NOATIME, PCL_O_NOFOLLOW, PCL_O_NONBLOCK, PCL_O_RDONLY, PCL_O_RDWR, PCL_O_SHLOCK, PCL_O_SYNC, PCL_O_TRUNC, and PCL_O_WRONLY.
Referenced by ipcl_file_open().