‪libpcl: ‪/Users/andrew/projects/libpcl/src/htable/_htable.h File Reference
_htable.h File Reference
#include <pcl/htable.h>
Macros
#define MAX_LOADFAC 0.75f
#define MIN_LOADFAC 0.2f
#define MINTBLSIZE 8
Functions
PCL_PRIVATE int ipcl_htable_chkcapacity (uint64_t capacity)
PCL_PRIVATE pcl_htable_entry_t * ipcl_htable_lookup (const pcl_htable_t *ht, const void *key, uintptr_t *codep, int *hashidxp)
PCL_PRIVATE int ipcl_htable_rehash (pcl_htable_t *ht, bool grow)
PCL_PRIVATE void ipcl_htable_init (int capacity, pcl_htable_entry_t **entries, int **entry_lookup)
Macro Definition Documentation
MAX_LOADFAC
#define MAX_LOADFAC 0.75f
Definition at line 37 of file _htable.h.
MIN_LOADFAC
#define MIN_LOADFAC 0.2f
Definition at line 38 of file _htable.h.
MINTBLSIZE
#define MINTBLSIZE 8
Definition at line 39 of file _htable.h.
Function Documentation
ipcl_htable_chkcapacity()
PCL_PRIVATE int ipcl_htable_chkcapacity (uint64_t capacity)
Definition at line 36 of file htable_chkcapacity.c.
References max, MINTBLSIZE, PCL_ERANGE, and SETERR.
Referenced by ipcl_htable_rehash(), and pcl_htable().
ipcl_htable_lookup()
PCL_PRIVATE pcl_htable_entry_t* ipcl_htable_lookup (const pcl_htable_t * ht, const void * key, uintptr_t * codep, int * hashidxp)
Definition at line 47 of file htable_lookup.c.
References pcl_htable_entry_t::code, tag_pcl_htable::entries, tag_pcl_htable::entry_lookup, tag_pcl_htable::hashcode, pcl_htable_entry_t::key, tag_pcl_htable::key_equals, tag_pcl_htable::key_len, pcl_htable_entry_t::next, PCL_ENOTFOUND, R_SETERR, and tag_pcl_htable::table_mask.
Referenced by pcl_htable_lookup(), and pcl_htable_put().
ipcl_htable_rehash()
PCL_PRIVATE int ipcl_htable_rehash (pcl_htable_t * ht, bool grow)
Parameters
ht
grow ‪true to grow table and false to shrink. When true, the new table size is set to double its current value and then rounded up to the nearest prime. When false, the table size is divided in half and then rounded up to the nearest table size.
Returns
Definition at line 38 of file htable_rehash.c.
References tag_pcl_htable::capacity, pcl_htable_entry_t::code, tag_pcl_htable::count, tag_pcl_htable::count_used, tag_pcl_htable::entries, tag_pcl_htable::entry_lookup, ipcl_htable_chkcapacity(), ipcl_htable_init(), pcl_htable_entry_t::key, pcl_htable_entry_t::next, pcl_free(), tag_pcl_htable::table_mask, TRC, and pcl_htable_entry_t::value.
Referenced by pcl_htable_put(), and pcl_htable_remove().
ipcl_htable_init()
PCL_PRIVATE void ipcl_htable_init (int capacity, pcl_htable_entry_t ** entries, int ** entry_lookup)
Definition at line 37 of file htable_init.c.
References pcl_zalloc().
Referenced by ipcl_htable_rehash(), and pcl_htable_clear().