‪libpcl: ‪/Users/andrew/projects/libpcl/src/htable/htable_rehash.c File Reference
htable_rehash.c File Reference
#include "_htable.h"
#include <pcl/alloc.h>
#include <pcl/error.h>
Functions
int ipcl_htable_rehash (pcl_htable_t *ht, bool grow)
Function Documentation
ipcl_htable_rehash()
int ipcl_htable_rehash (pcl_htable_t * ht, bool grow)
Parameters
ht
grow ‪true to grow table and false to shrink. When true, the new table size is set to double its current value and then rounded up to the nearest prime. When false, the table size is divided in half and then rounded up to the nearest table size.
Returns
Definition at line 37 of file htable_rehash.c.
References tag_pcl_htable::capacity, tag_pcl_htable_entry::code, tag_pcl_htable::entries, ipcl_htable_capacity(), tag_pcl_htable_entry::next, pcl_free_safe(), pcl_zalloc(), and TRC.
Referenced by ipcl_htable_remove_entry(), and pcl_htable_put().