‪libpcl: ‪/Users/andrew/projects/libpcl/src/json/json_value_clear.c File Reference
json_value_clear.c File Reference
#include "_json.h"
#include <pcl/buf.h>
#include <pcl/htable.h>
#include <pcl/vector.h>
#include <pcl/alloc.h>
Functions
void ipcl_json_value_clear (pcl_json_value_t *v)
Function Documentation
ipcl_json_value_clear()
void ipcl_json_value_clear (pcl_json_value_t * v)
Definition at line 39 of file json_value_clear.c.
References tag_pcl_json_value::array, tag_pcl_json_value::object, pcl_free(), pcl_htable_free(), pcl_vector_free(), tag_pcl_json_value::string, and tag_pcl_json_value::type.