‪libpcl: ‪/Users/andrew/projects/libpcl/src/json/_json.h File Reference
_json.h File Reference
#include <pcl/json.h>
#include <pcl/error.h>
Data Structures
struct ipcl_json_state_t
Macros
#define JSON_THROW(message, ...) return R_SETERRMSG(NULL, PCL_ESYNTAX, message, __VA_ARGS__)
Functions
pcl_json_value_t * ipcl_json_parse_value (ipcl_json_state_t *s, pcl_json_value_t *valbuf)
ipcl_json_state_t * ipcl_json_skipws (ipcl_json_state_t *s)
char * ipcl_json_parse_string (ipcl_json_state_t *s)
pcl_vector_t * ipcl_json_parse_array (ipcl_json_state_t *s)
void ipcl_json_value_clear (pcl_json_value_t *v)
pcl_htable_t * ipcl_json_parse_object (ipcl_json_state_t *s)
Macro Definition Documentation
JSON_THROW
#define JSON_THROW (message, ...) return R_SETERRMSG(NULL, PCL_ESYNTAX, message, __VA_ARGS__)
Definition at line 38 of file _json.h.
Function Documentation
ipcl_json_parse_value()
pcl_json_value_t* ipcl_json_parse_value (ipcl_json_state_t * s, pcl_json_value_t * valbuf)
Definition at line 38 of file json_parse_value.c.
References tag_pcl_json_value::array, tag_pcl_json_value::boolean, ipcl_json_state_t::ctx, ipcl_json_state_t::end, ipcl_json_parse_array(), ipcl_json_parse_object(), ipcl_json_parse_string(), ipcl_json_skipws(), JSON_THROW, ipcl_json_state_t::next, tag_pcl_json_value::number, tag_pcl_json_value::object, pcl_err_crt2pcl, pcl_err_set(), PCL_LOCATION_ARGS, pcl_malloc(), tag_pcl_json_value::string, and tag_pcl_json_value::type.
Referenced by pcl_json_parse().
ipcl_json_skipws()
ipcl_json_state_t* ipcl_json_skipws (ipcl_json_state_t * s)
Definition at line 35 of file json_skipws.c.
References ipcl_json_state_t::end, JSON_THROW, ipcl_json_state_t::line, and ipcl_json_state_t::next.
Referenced by ipcl_json_parse_array(), ipcl_json_parse_object(), and ipcl_json_parse_value().
ipcl_json_parse_string()
char* ipcl_json_parse_string (ipcl_json_state_t * s)
Definition at line 134 of file json_parse_string.c.
References ipcl_json_state_t::ctx, JSON_THROW, ipcl_json_state_t::next, pcl_buf_init(), pcl_buf_putchar(), and PclBufText.
Referenced by ipcl_json_parse_value().
ipcl_json_parse_array()
pcl_vector_t* ipcl_json_parse_array (ipcl_json_state_t * s)
Definition at line 43 of file json_parse_array.c.
References ipcl_json_state_t::ctx, ipcl_json_skipws(), JSON_THROW, ipcl_json_state_t::next, and pcl_vector_create().
Referenced by ipcl_json_parse_value().
ipcl_json_value_clear()
void ipcl_json_value_clear (pcl_json_value_t * v)
Definition at line 39 of file json_value_clear.c.
References tag_pcl_json_value::array, tag_pcl_json_value::object, pcl_free(), pcl_htable_free(), pcl_vector_free(), tag_pcl_json_value::string, and tag_pcl_json_value::type.
ipcl_json_parse_object()
pcl_htable_t* ipcl_json_parse_object (ipcl_json_state_t * s)
Definition at line 46 of file json_parse_object.c.
References ipcl_json_state_t::ctx, ipcl_json_skipws(), JSON_THROW, ipcl_json_state_t::next, pcl_htable_create(), and tag_pcl_htable::remove_entry.
Referenced by ipcl_json_parse_value().