‪libpcl: ‪/Users/andrew/projects/libpcl/src/htable/htable_init.c File Reference
htable_init.c File Reference
#include "_htable.h"
#include <pcl/alloc.h>
#include <string.h>
Functions
void ipcl_htable_init (int capacity, pcl_htable_entry_t **entries, int **entry_lookup)
Function Documentation
ipcl_htable_init()
void ipcl_htable_init (int capacity, pcl_htable_entry_t ** entries, int ** entry_lookup)
Definition at line 37 of file htable_init.c.
References pcl_zalloc().
Referenced by ipcl_htable_rehash(), and pcl_htable_clear().