‪libpcl: ‪/Users/andrew/projects/libpcl/src/socket/_socket.h File Reference
_socket.h File Reference
#include <pcl/socket.h>
Data Structures
struct tag_pcl_socket
Macros
#define SOCK_ADDRBUFSIZE 128
Functions
pcl_socket_t * ipcl_socket_alloc (void)
Macro Definition Documentation
SOCK_ADDRBUFSIZE
#define SOCK_ADDRBUFSIZE 128
Definition at line 41 of file _socket.h.
Function Documentation
ipcl_socket_alloc()
pcl_socket_t* ipcl_socket_alloc (void)
Definition at line 36 of file socket_alloc.c.
References tag_pcl_socket::addr, tag_pcl_socket::fd, INVALID_SOCKET, pcl_zalloc(), tag_pcl_socket::sa_len, and SOCK_ADDRBUFSIZE.
Referenced by pcl_accept(), and pcl_socket().