‪libpcl: ‪/Users/andrew/projects/libpcl/src/log/log_vevent.c File Reference
log_vevent.c File Reference
#include <pcl/log.h>
#include <pcl/time.h>
#include <pcl/vector.h>
#include <pcl/error.h>
#include <pcl/io.h>
#include <pcl/string.h>
#include <pcl/alloc.h>
#include <stdlib.h>
Functions
int pcl_log_vevent (pcl_log_event_t *e, const char *message, va_list ap)
Function Documentation
pcl_log_vevent()
int pcl_log_vevent (pcl_log_event_t * e, const char * message, va_list ap)
Definition at line 42 of file log_vevent.c.
References countof, tag_pcl_log_event::exit_code, tag_pcl_log_event::exit_context, tag_pcl_log_event::exit_handler, tag_pcl_log_event::exit_levels, tag_pcl_log_event::facility, tag_pcl_log_event::file, tag_pcl_log_event::func, tag_pcl_log_event::level, tag_pcl_log_event::line, pcl_asprintf(), pcl_err_fprintf(), pcl_err_freeze(), pcl_fprintf(), pcl_free_safe(), pcl_gmtime(), pcl_localtime(), pcl_log_strlevel(), PCL_LOG_TIMEFORMAT, PCL_LOGLEV_HASTRACE, PCL_LOGOPT_UTC, pcl_sprintf(), pcl_strcpy(), pcl_strftime(), pcl_strrepchr(), pcl_vasprintf(), tag_pcl_log_event::stream, strempty, and tag_pcl_log_event::when.
Referenced by pcl_log_event().