‪libpcl: ‪/Users/andrew/projects/libpcl/src/json/json_parse_object.c File Reference
json_parse_object.c File Reference
#include "_json.h"
#include <pcl/htable.h>
#include <pcl/alloc.h>
Functions
pcl_json_t * ipcl_json_parse_object (ipcl_json_state_t *s)
Function Documentation
ipcl_json_parse_object()
pcl_json_t* ipcl_json_parse_object (ipcl_json_state_t * s)
Definition at line 37 of file json_parse_object.c.
References ipcl_json_state_t::ctx, ipcl_json_state_t::end, ipcl_json_parse_string(), ipcl_json_parse_value(), ipcl_json_skipws(), JSON_THROW, ipcl_json_state_t::next, pcl_free(), pcl_json_free(), pcl_json_object(), pcl_json_object_put(), PCL_JSON_SHALLOW, and PCL_JSON_SKIPUTF8CHK.
Referenced by ipcl_json_parse_value().