‪libpcl: ‪/Users/andrew/projects/libpcl/src/net/net_ai2pcl.c File Reference
net_ai2pcl.c File Reference
#include "_net.h"
Functions
int pcl_net_ai2pcl (int ai_retval)
Function Documentation
pcl_net_ai2pcl()
int pcl_net_ai2pcl (int ai_retval)
Definition at line 35 of file net_ai2pcl.c.
References PCL_EAFNOSUPPORT, PCL_ECANCELLED, PCL_EFORMAT, PCL_EHOSTNOTFOUND, PCL_EINPROGRESS, PCL_EINTR, PCL_EINVAL, PCL_ENODATA, PCL_ENOMEM, PCL_EOKAY, PCL_EOVERFLOW, pcl_err_os2pcl(), PCL_ESOCKTNOSUPPORT, PCL_ETRYAGAIN, and PCL_EUNDEF.
Referenced by ipcl_net_resolve(), pcl_net_addr2ip(), pcl_net_host2addr(), pcl_net_ip2inet(), pcl_net_reverse(), and pcl_socket().