‪libpcl: ‪/Users/andrew/projects/libpcl/src/net/net_resolve.c File Reference
net_resolve.c File Reference
#include "_net.h"
#include <pcl/vector.h>
#include <pcl/string.h>
Functions
pcl_vector_t * ipcl_net_resolve (const char *host)
Function Documentation
ipcl_net_resolve()
pcl_vector_t* ipcl_net_resolve (const char * host)
Definition at line 37 of file net_resolve.c.
References pcl_net_ai2pcl(), pcl_strdup(), pcl_vector_append, pcl_vector_cleanup_dblptr(), pcl_vector_create(), and R_SETERR.