‪libpcl: ‪/Users/andrew/projects/libpcl/src/json/_json.h File Reference
_json.h File Reference
#include <pcl/json.h>
#include <pcl/error.h>
#include <pcl/buf.h>
Data Structures
struct ipcl_json_state_t
struct ipcl_json_encode_t
struct tag_pcl_json_path
Macros
#define JSON_THROW(message, ...) return R_SETERRMSG(NULL, PCL_ESYNTAX, message, __VA_ARGS__)
#define PRINT_TABS(_enc)
Enumerations
enum path_type_t {
PclPathRoot,
PclPathMember,
PclPathWildcardMember,
PclPathRecursiveDescent,
PclPathElement,
PclPathWildcardElement,
PclPathElementList,
PclPathElementSlice
}
Functions
pcl_json_t * ipcl_json_parse_value (ipcl_json_state_t *s)
char * ipcl_json_parse_string (ipcl_json_state_t *s)
pcl_json_t * ipcl_json_parse_array (ipcl_json_state_t *s)
pcl_json_t * ipcl_json_parse_object (ipcl_json_state_t *s)
pcl_json_t * ipcl_json_parse_number (ipcl_json_state_t *s)
ipcl_json_state_t * ipcl_json_skipws (ipcl_json_state_t *s)
int ipcl_json_utf8check (const char *s, size_t len)
pcl_buf_t * ipcl_json_encode_value (ipcl_json_encode_t *enc, pcl_json_t *value)
pcl_buf_t * ipcl_json_encode_string (ipcl_json_encode_t *enc, const char *string)
pcl_buf_t * ipcl_json_encode_array (ipcl_json_encode_t *enc, pcl_array_t *array)
pcl_buf_t * ipcl_json_encode_object (ipcl_json_encode_t *enc, pcl_htable_t *obj)
Macro Definition Documentation
JSON_THROW
#define JSON_THROW (message, ...) return R_SETERRMSG(NULL, PCL_ESYNTAX, message, __VA_ARGS__)
Definition at line 39 of file _json.h.
PRINT_TABS
#define PRINT_TABS (_enc)
Value:
  for(int __i = 0; __i < (enc)->tabs; __i++) \
    pcl_buf_putchar((enc)->b, '\t')
Definition at line 42 of file _json.h.
Enumeration Type Documentation
path_type_t
enum path_type_t
Enumerator
PclPathRoot
PclPathMember
PclPathWildcardMember
PclPathRecursiveDescent
PclPathElement
PclPathWildcardElement
PclPathElementList
PclPathElementSlice
Definition at line 65 of file _json.h.
Function Documentation
ipcl_json_parse_value()
pcl_json_t* ipcl_json_parse_value (ipcl_json_state_t * s)
Definition at line 37 of file json_parse_value.c.
References ipcl_json_state_t::ctx, ipcl_json_state_t::end, ipcl_json_parse_array(), ipcl_json_parse_number(), ipcl_json_parse_object(), ipcl_json_parse_string(), ipcl_json_skipws(), JSON_THROW, ipcl_json_state_t::next, pcl_json_false(), pcl_json_null(), PCL_JSON_SHALLOW, PCL_JSON_SKIPUTF8CHK, pcl_json_str(), and pcl_json_true().
Referenced by ipcl_json_parse_array(), ipcl_json_parse_object(), and pcl_json_decode().
ipcl_json_parse_string()
char* ipcl_json_parse_string (ipcl_json_state_t * s)
Definition at line 133 of file json_parse_string.c.
References ipcl_json_state_t::ctx, JSON_THROW, ipcl_json_state_t::next, pcl_buf_init(), pcl_buf_putchar(), and PclBufText.
Referenced by ipcl_json_parse_object(), and ipcl_json_parse_value().
ipcl_json_parse_array()
pcl_json_t* ipcl_json_parse_array (ipcl_json_state_t * s)
Definition at line 35 of file json_parse_array.c.
References ipcl_json_state_t::ctx, ipcl_json_state_t::end, ipcl_json_parse_value(), ipcl_json_skipws(), JSON_THROW, ipcl_json_state_t::next, pcl_json_arr(), pcl_json_arradd(), pcl_json_free(), PCL_JSON_FREEVALONERR, and R_TRCMSG.
Referenced by ipcl_json_parse_value().
ipcl_json_parse_object()
pcl_json_t* ipcl_json_parse_object (ipcl_json_state_t * s)
Definition at line 37 of file json_parse_object.c.
References ipcl_json_state_t::ctx, ipcl_json_state_t::end, ipcl_json_parse_string(), ipcl_json_parse_value(), ipcl_json_skipws(), JSON_THROW, ipcl_json_state_t::next, pcl_free(), pcl_json_free(), PCL_JSON_FREEVALONERR, pcl_json_obj(), pcl_json_objput(), PCL_JSON_SHALLOW, and PCL_JSON_SKIPUTF8CHK.
Referenced by ipcl_json_parse_value().
ipcl_json_parse_number()
pcl_json_t* ipcl_json_parse_number (ipcl_json_state_t * s)
Definition at line 38 of file json_parse_number.c.
References ipcl_json_state_t::end, JSON_THROW, ipcl_json_state_t::next, pcl_err_crt2pcl, pcl_err_set(), pcl_json_int(), pcl_json_real(), PCL_LOCATION_ARGS, pcl_strtoll(), and R_TRC.
Referenced by ipcl_json_parse_value().
ipcl_json_skipws()
ipcl_json_state_t* ipcl_json_skipws (ipcl_json_state_t * s)
Definition at line 36 of file json_skipws.c.
References ipcl_json_state_t::end, JSON_THROW, ipcl_json_state_t::line, and ipcl_json_state_t::next.
Referenced by ipcl_json_parse_array(), ipcl_json_parse_object(), and ipcl_json_parse_value().
ipcl_json_utf8check()
int ipcl_json_utf8check (const char * s, size_t len)
Parameters
s
len ‪if zero, strlen is used so s must be NUL-terminated in this case
Returns
Definition at line 51 of file json_utf8check.c.
References PCL_EILSEQ, and SETERRMSG.
Referenced by pcl_json_objput(), pcl_json_str(), and pcl_json_strn().
ipcl_json_encode_value()
pcl_buf_t* ipcl_json_encode_value (ipcl_json_encode_t * enc, pcl_json_t * value)
Definition at line 36 of file json_encode_value.c.
References tag_pcl_json::array, ipcl_json_encode_t::b, tag_pcl_json::boolean, tag_pcl_json::integer, ipcl_json_encode_array(), ipcl_json_encode_object(), ipcl_json_encode_string(), tag_pcl_json::object, pcl_buf_putf(), pcl_buf_putstr(), PCL_ETYPE, R_SETERRMSG, tag_pcl_json::real, tag_pcl_json::string, and tag_pcl_json::type.
Referenced by ipcl_json_encode_array(), ipcl_json_encode_object(), and pcl_json_encode().
ipcl_json_encode_string()
pcl_buf_t* ipcl_json_encode_string (ipcl_json_encode_t * enc, const char * string)
Definition at line 35 of file json_encode_string.c.
References ipcl_json_encode_t::b, pcl_buf_putchar(), pcl_buf_putf(), and pcl_buf_putstr().
Referenced by ipcl_json_encode_object(), and ipcl_json_encode_value().
ipcl_json_encode_array()
pcl_buf_t* ipcl_json_encode_array (ipcl_json_encode_t * enc, pcl_array_t * array)
Definition at line 36 of file json_encode_array.c.
References ipcl_json_encode_t::b, tag_pcl_array::count, tag_pcl_array::elements, ipcl_json_encode_t::format, ipcl_json_encode_value(), pcl_buf_putchar(), PRINT_TABS, and ipcl_json_encode_t::tabs.
Referenced by ipcl_json_encode_value().
ipcl_json_encode_object()
pcl_buf_t* ipcl_json_encode_object (ipcl_json_encode_t * enc, pcl_htable_t * obj)
Definition at line 36 of file json_encode_object.c.
References ipcl_json_encode_t::b, tag_pcl_htable::count, ipcl_json_encode_t::format, ipcl_json_encode_string(), ipcl_json_encode_value(), tag_pcl_htable_entry::key, pcl_buf_putchar(), pcl_htable_iter(), PRINT_TABS, ipcl_json_encode_t::tabs, and tag_pcl_htable_entry::value.
Referenced by ipcl_json_encode_value().