‪libpcl: ‪/Users/andrew/projects/libpcl/src/json/json_encode_value.c File Reference
json_encode_value.c File Reference
#include "_json.h"
#include <math.h>
Functions
pcl_buf_t * ipcl_json_encode_value (ipcl_json_encode_t *enc, pcl_json_t *value)
Function Documentation
ipcl_json_encode_value()
pcl_buf_t* ipcl_json_encode_value (ipcl_json_encode_t * enc, pcl_json_t * value)
Definition at line 36 of file json_encode_value.c.
References tag_pcl_json::array, ipcl_json_encode_t::b, tag_pcl_json::boolean, tag_pcl_json::integer, ipcl_json_encode_array(), ipcl_json_encode_object(), ipcl_json_encode_string(), tag_pcl_json::object, pcl_buf_putf(), pcl_buf_putstr(), PCL_ETYPE, R_SETERRMSG, tag_pcl_json::real, tag_pcl_json::string, and tag_pcl_json::type.
Referenced by ipcl_json_encode_array(), ipcl_json_encode_object(), and pcl_json_encode().