‪libpcl: ‪/Users/andrew/projects/libpcl/src/ssl/ssl_certentry.c File Reference
ssl_certentry.c File Reference
#include "_ssl.h"
#include <pcl/vector.h>
#include <pcl/string.h>
Functions
pcl_vector_t * pcl_ssl_certentry (pcl_ssl_t *ssl, int entry_type)
Function Documentation
pcl_ssl_certentry()
pcl_vector_t* pcl_ssl_certentry (pcl_ssl_t * ssl, int entry_type)
Definition at line 37 of file ssl_certentry.c.
References BADARG, PCL_ENOTFOUND, PCL_ETYPE, PCL_SSL_CERT_COMMON_NAME, PCL_SSL_CERT_COUNTRY_NAME, PCL_SSL_CERT_LOCALITY_NAME, PCL_SSL_CERT_ORG_NAME, PCL_SSL_CERT_ORG_UNIT, PCL_SSL_CERT_STATE, pcl_strndup(), pcl_vector_append, pcl_vector_cleanup_dblptr(), pcl_vector_create(), SETERR, SETERRMSG, and tag_pcl_ssl::ssl.