‪libpcl: ‪/Users/andrew/projects/libpcl/src/ssl/ssl_close.c File Reference
ssl_close.c File Reference
#include "_ssl.h"
#include <pcl/socket.h>
#include <openssl/err.h>
Functions
void pcl_ssl_close (pcl_ssl_t *ssl)
Function Documentation
pcl_ssl_close()
void pcl_ssl_close (pcl_ssl_t * ssl)
Definition at line 37 of file ssl_close.c.
References tag_pcl_ssl::err, pcl_openssl_error_t::msg, pcl_socket_close(), tag_pcl_ssl::sock, and tag_pcl_ssl::ssl.
Referenced by pcl_ssl_connect(), pcl_ssl_free(), pcl_ssl_handshake(), pcl_ssl_recv(), and pcl_ssl_send().