‪libpcl: ‪/Users/andrew/projects/libpcl/src/socket/recv.c File Reference
recv.c File Reference
#include "_socket.h"
#include <pcl/error.h>
Functions
ssize_t pcl_recv (pcl_socket_t *sock, void *buf, size_t count, int flags)
Function Documentation
pcl_recv()
ssize_t pcl_recv (pcl_socket_t * sock, void * buf, size_t count, int flags)
Definition at line 36 of file recv.c.
References tag_pcl_socket::fd, PCL_EAGAIN, PCL_EINTR, PCL_EINVAL, pcl_err_os2pcl(), PCL_EWOULDBLOCK, pcl_sockerrno, pcl_socket_isalive(), and SETERR.
Referenced by pcl_recvall().