‪libpcl: ‪/Users/andrew/projects/libpcl/src/json/json_parse_value.c File Reference
json_parse_value.c File Reference
#include "_json.h"
#include <pcl/alloc.h>
#include <string.h>
Functions
pcl_json_t * ipcl_json_parse_value (ipcl_json_state_t *s)
Function Documentation
ipcl_json_parse_value()
pcl_json_t* ipcl_json_parse_value (ipcl_json_state_t * s)
Definition at line 37 of file json_parse_value.c.
References ipcl_json_state_t::ctx, ipcl_json_state_t::end, ipcl_json_parse_array(), ipcl_json_parse_number(), ipcl_json_parse_object(), ipcl_json_parse_string(), ipcl_json_skipws(), JSON_THROW, ipcl_json_state_t::next, pcl_json_false(), pcl_json_null(), PCL_JSON_SHALLOW, PCL_JSON_SKIPUTF8CHK, pcl_json_str(), and pcl_json_true().
Referenced by ipcl_json_parse_array(), ipcl_json_parse_object(), and pcl_json_decode().