‪libpcl: ‪/Users/andrew/projects/libpcl/src/ssl/ssl_recv.c File Reference
ssl_recv.c File Reference
#include "_ssl.h"
#include <openssl/err.h>
Functions
int pcl_ssl_recv (pcl_ssl_t *ssl, void *buf, size_t len)
Function Documentation
pcl_ssl_recv()
int pcl_ssl_recv (pcl_ssl_t * ssl, void * buf, size_t len)
Definition at line 36 of file ssl_recv.c.
References PCL_EAGAIN, PCL_ECONNABORTED, PCL_ECONNRESET, PCL_EOKAY, pcl_err_clear(), pcl_err_os2pcl(), PCL_ESSL, PCL_EUNDEF, pcl_oserrno, pcl_ssl_close(), SETERR, SETERRMSG, tag_pcl_ssl::ssl, and sslerror.