‪libpcl: ‪/Users/andrew/projects/libpcl/src/net/net_dnstxtrec.c File Reference
net_dnstxtrec.c File Reference
#include "_net.h"
#include <pcl/vector.h>
#include <pcl/string.h>
#include <Windns.h>
Functions
pcl_vector_t * pcl_net_dnstxtrec (const char *host)
Function Documentation
pcl_net_dnstxtrec()
pcl_vector_t* pcl_net_dnstxtrec (const char * host)
Definition at line 49 of file net_dnstxtrec.c.
References pcl_net_dns2pcl(), pcl_pcs_to_utf8(), pcl_strndup(), pcl_vector_append, pcl_vector_cleanup_dblptr(), pcl_vector_create(), R_SETERRMSG, R_SETLASTERR, and R_SETOSERRMSG.