‪libpcl: ‪/Users/andrew/projects/libpcl/src/sysinfo/_sysinfo.h File Reference
_sysinfo.h File Reference
#include <pcl/sysinfo.h>
Functions
void ipcl_sysinfo (pcl_sysinfo_t *info, void *uts)
‪Implemented separately by darwin, linux and windows.
Function Documentation
ipcl_sysinfo()
void ipcl_sysinfo (pcl_sysinfo_t * info, void * uts)
‪Implemented separately by darwin, linux and windows.
Parameters
info ‪pointer to an output buffer, as passed to pcl_sysinfo().
uts ‪struct uts for unixes and unused by windows, uninsitalized int* is passed in.
Definition at line 44 of file darwin_sysinfo.c.
References BUILDVER, pcl_sysinfo_t::cpu_cores, pcl_sysinfo_t::cpu_model, pcl_sysinfo_t::cpu_sockets, pcl_sysinfo_t::memory, pcl_strcpy(), pcl_strnicmp(), pcl_strtrim(), PRODNAME, PRODVER, UNUSED, pcl_sysinfo_t::vendor, and pcl_sysinfo_t::version.
Referenced by pcl_sysinfo().