‪libpcl: ‪/Users/andrew/projects/libpcl/src/net/net_addr2ip.c File Reference
net_addr2ip.c File Reference
#include "_net.h"
#include <pcl/string.h>
#include <sys/un.h>
Functions
char * pcl_net_addr2ip (struct sockaddr *sa, char *ipbuf, size_t len)
Function Documentation
pcl_net_addr2ip()
char* pcl_net_addr2ip (struct sockaddr * sa, char * ipbuf, size_t len)
Definition at line 42 of file net_addr2ip.c.
References PCL_EBUF, PCL_EINVAL, pcl_net_addrlen(), pcl_net_ai2pcl(), pcl_strcpy(), and R_SETERR.
Referenced by pcl_net_inet2ip(), and pcl_socket_ip().