‪libpcl: ‪/Users/andrew/projects/libpcl/src/net/net_resolve.c File Reference
net_resolve.c File Reference
#include "_net.h"
#include <pcl/array.h>
#include <pcl/string.h>
#include <pcl/alloc.h>
Functions
pcl_array_t * pcl_net_resolve (const char *host)
‪Resolve a hostname to an array of IPv4 and/or IPv6 addresses.
Function Documentation
pcl_net_resolve()
pcl_array_t* pcl_net_resolve (const char * host)
‪Resolve a hostname to an array of IPv4 and/or IPv6 addresses.
Parameters
host ‪pointer to a hostname
Returns
‪pointer to an array of IP addresses or NULL on error.
Definition at line 38 of file net_resolve.c.
References pcl_array(), pcl_array_append(), pcl_cleanup_ptr(), pcl_net_ai2pcl(), pcl_strdup(), and R_SETERR.