‪libpcl: ‪/Users/andrew/projects/libpcl/src/socket/socket_close.c File Reference
socket_close.c File Reference
#include "_socket.h"
#include <pcl/alloc.h>
Functions
void pcl_socket_close (pcl_socket_t *sock)
Function Documentation
pcl_socket_close()
void pcl_socket_close (pcl_socket_t * sock)
Definition at line 40 of file socket_close.c.
References tag_pcl_socket::fd, INVALID_SOCKET, tag_pcl_socket::ipaddr, pcl_free(), and pcl_free_safe().
Referenced by pcl_accept(), pcl_socket(), and pcl_ssl_close().