‪libpcl: ‪/Users/andrew/projects/libpcl/src/stat/statent.c File Reference
statent.c File Reference
#include "_stat.h"
#include <pcl/file.h>
#include <pcl/error.h>
#include <pcl/alloc.h>
#include <pcl/string.h>
Functions
int pcl_statent (const tchar_t *path, int fd, pcl_stat_t *buf, int flags)
‪Get file or directory status.
Function Documentation
pcl_statent()
int pcl_statent (const tchar_t * path, int fd, pcl_stat_t * buf, int flags)
‪Get file or directory status.
This is normally not used directly. Instead, pcl_stat, pcl_fstat and pcl_lstat macros are used.
Parameters
path ‪filesystem entry to stat. If NULL, the fd argument must be valid.
fd ‪file descriptor representing the entry to stat. If < 0, path is expected to be valid.
buf ‪output stat buffer, this can be NULL in which case this function is merely an "exists" check.
flags ‪PCL_STAT_xxx flags such as PCL_STAT_LINK incicates this should perform an lstat.
Returns
‪on success 0 and -1 on error
Definition at line 39 of file statent.c.
References BADARG, ipcl_statent(), pcl_fdpath(), pcl_free_safe(), strempty, and TRC.