‪libpcl: ‪/Users/andrew/projects/libpcl/src/net/net_dnstxtrec.c File Reference
net_dnstxtrec.c File Reference
#include "_net.h"
#include <pcl/array.h>
#include <pcl/string.h>
#include <pcl/alloc.h>
#include <Windns.h>
Functions
pcl_array_t * pcl_net_dnstxtrec (const char *host)
‪Retrieve the DNS TXT records for a given host.
Function Documentation
pcl_net_dnstxtrec()
pcl_array_t* pcl_net_dnstxtrec (const char * host)
‪Retrieve the DNS TXT records for a given host.
Parameters
host ‪pointer to a host
Returns
‪pointer to an array where each element is a TXT record or NULL on error.
Definition at line 50 of file net_dnstxtrec.c.
References pcl_array(), pcl_array_append(), pcl_cleanup_ptr(), pcl_net_dns2pcl(), pcl_pcs_to_utf8(), pcl_strndup(), R_SETERRMSG, R_SETLASTERR, and R_SETOSERRMSG.