‪libpcl: ‪/Users/andrew/projects/libpcl/src/time/break_down_time.c File Reference
break_down_time.c File Reference
#include "_time.h"
#include <pcl/error.h>
Functions
int pcl_localtime (const pcl_time_t *t, pcl_tm_t *result)
int pcl_gmtime (const pcl_time_t *t, pcl_tm_t *result)
Function Documentation
pcl_localtime()
int pcl_localtime (const pcl_time_t * t, pcl_tm_t * result)
Definition at line 99 of file break_down_time.c.
Referenced by pcl_log_vevent(), and pcl_sysinfo().
pcl_gmtime()
int pcl_gmtime (const pcl_time_t * t, pcl_tm_t * result)
Definition at line 105 of file break_down_time.c.
Referenced by pcl_log_vevent().