‪libpcl: ‪/Users/andrew/projects/libpcl/src/sysinfo/sysinfo.c File Reference
sysinfo.c File Reference
#include "_sysinfo.h"
#include <pcl/time.h>
#include <pcl/string.h>
#include <pcl/alloc.h>
#include <Winsock2.h>
Functions
void pcl_sysinfo (pcl_sysinfo_t *info)
Function Documentation
pcl_sysinfo()
void pcl_sysinfo (pcl_sysinfo_t * info)
Definition at line 45 of file sysinfo.c.
References countof, pcl_sysinfo_t::cpu_model, pcl_sysinfo_t::gmtoff, pcl_sysinfo_t::hostname, ipcl_sysinfo(), pcl_sysinfo_t::name, pcl_free(), pcl_localtime(), pcl_pcscpy(), pcl_strcpy(), pcl_strtrim(), pcl_utf8_to_pcs(), pcl_tm_t::tm_gmtoff, pcl_tm_t::tm_zone, and pcl_sysinfo_t::tzabbr.