‪libpcl: ‪/Users/andrew/projects/libpcl/src/sysinfo/darwin_sysinfo.c File Reference
darwin_sysinfo.c File Reference
#include "_sysinfo.h"
#include <pcl/string.h>
#include <sys/sysctl.h>
#include <sys/utsname.h>
#include <stdio.h>
#include <stdlib.h>
Macros
#define PRODNAME "productname:"
#define PRODVER "productversion:"
#define BUILDVER "buildversion:"
Functions
void ipcl_sysinfo (pcl_sysinfo_t *info, void *_uts)
‪Implemented separately by darwin, linux and windows.
Macro Definition Documentation
PRODNAME
#define PRODNAME "productname:"
Definition at line 39 of file darwin_sysinfo.c.
PRODVER
#define PRODVER "productversion:"
Definition at line 40 of file darwin_sysinfo.c.
BUILDVER
#define BUILDVER "buildversion:"
Definition at line 41 of file darwin_sysinfo.c.
Function Documentation
ipcl_sysinfo()
void ipcl_sysinfo (pcl_sysinfo_t * info, void * uts)
‪Implemented separately by darwin, linux and windows.
Parameters
info ‪pointer to an output buffer, as passed to pcl_sysinfo().
uts ‪struct uts for unixes and unused by windows, uninsitalized int* is passed in.
Definition at line 44 of file darwin_sysinfo.c.
References BUILDVER, pcl_sysinfo_t::cpu_cores, pcl_sysinfo_t::cpu_model, pcl_sysinfo_t::cpu_sockets, pcl_sysinfo_t::memory, pcl_strcpy(), pcl_strnicmp(), pcl_strtrim(), PRODNAME, PRODVER, pcl_sysinfo_t::vendor, and pcl_sysinfo_t::version.