‪libpcl: ‪/Users/andrew/projects/libpcl/src/time/time.c File Reference
time.c File Reference
#include "_time.h"
Functions
pcl_time_t pcl_time (void)
Function Documentation
pcl_time()
pcl_time_t pcl_time (void)
Definition at line 35 of file time.c.
References ipcl_win32_ftime_to_pcl(), tag_pcl_time::nsec, PCL_NSECS, and tag_pcl_time::sec.
Referenced by pcl_log_event_default(), and pcl_proc_exec().