‪libpcl: ‪/Users/andrew/projects/libpcl/src/time/win32_utimes.c File Reference
win32_utimes.c File Reference
#include "_time.h"
#include "../file/_file.h"
#include <pcl/error.h>
Functions
int pcl_utimes (const tchar_t *path, pcl_time_t *atime, pcl_time_t *ctime, pcl_time_t *mtime, pcl_time_t *crtime, pcl_time_t *btime)
Function Documentation
pcl_utimes()
int pcl_utimes (const tchar_t * path, pcl_time_t * atime, pcl_time_t * ctime, pcl_time_t * mtime, pcl_time_t * crtime, pcl_time_t * btime)
Definition at line 37 of file win32_utimes.c.
References tag_pcl_file::fd, ipcl_win32_pcl_to_ftime(), pcl_file_close(), pcl_file_open(), PCL_O_BACKUP, PCL_O_WRONLY, SETLASTERR, TRC, and UNUSED.