‪libpcl: ‪/Users/andrew/projects/libpcl/src/win32/win32_token_info.c File Reference
win32_token_info.c File Reference
#include "_win32.h"
#include <pcl/alloc.h>
Functions
int ipcl_win32_token_into (HANDLE htok, TOKEN_INFORMATION_CLASS type, void **data)
Function Documentation
ipcl_win32_token_into()
int ipcl_win32_token_into (HANDLE htok, TOKEN_INFORMATION_CLASS type, void ** data)
Definition at line 36 of file win32_token_info.c.
References pcl_free(), pcl_malloc(), pcl_oserrno, and SETLASTERR.
Referenced by ipcl_win32_process_sid(), and ipcl_win32_sd_create().