‪libpcl: ‪Initialize Application
Initialize Application
‪Responisble for intializing the PCL library.
Data Structures
struct pcl_option_t
Macros
#define pcl_tmain main
Typedefs
typedef struct tag_pcl_optstate pcl_optstate_t
‪State management for argument parsing.
Enumerations
enum pcl_optpolicy {
PclNoArg,
PclReqArg,
PclOptArg
}
Functions
PCL_EXPORT void pcl_init (void)
‪Initializes the PCL library.
PCL_EXPORT pcl_optstate_t * pcl_initopt (int argc, tchar_t **argv, const tchar_t *optstr, pcl_option_t *options, int num_options)
‪Intialize command-line argument parser.
PCL_EXPORT int pcl_getopt (pcl_optstate_t *state, tchar_t **value, pcl_option_t **longopt)
‪Parse command-line arguments.
Detailed Description
Responisble for intializing the PCL library.
pcl_init must be called before any other PCL function. This is typically accomplished by calling it from within the application's main function. This module also includes a getopt implementation since calling pcl_init and argument parsing are typically both done in main.
Basic Usage
#include <pcl/init.h>
#include <pcl/error.h>
#include <pcl/io.h>
#include <stdlib.h>
int pcl_tmain(int argc, tchar_t **argv)
{
  // always call first
  pcl_init();
  // a requires argument, b has optional argument and c & d have no arguments
  const tchar_t *optstr = _T("a:b::cd");
  // match the 'val' member of pcl_option_t to the 'optstr' short options (not required)
  pcl_option_t options[] = {
    {_T("apple"), PclReqArg, _T('a')},
    {_T("banana"), PclOptArg, _T('b')},
    {_T("cherry"), PclNoArg, _T('c')}
    // 'd' is not mapped to a long option
  };
  // initialize option state
  pcl_optstate_t *state = pcl_initopt(argc, argv, optstr, options, countof(options));
  if(!state)
    PANIC("failed to initialize option state", 0);
  int opt;
  tchar_t *value;
  pcl_option_t *longopt;
  // 3rd argument longopt can be NULL, which is common
  while((opt = pcl_getopt(state, &value, &longopt)) > 0)
  {
    tchar_t *longname = longopt ? longopt->name : _T("<short-only>");
    switch(opt)
    {
      case _T('a'):
        pcl_printf("a:%ts] %ts\n", longname, value);
        break;
      case _T('b'):
         pcl_printf("b:%ts] %s\n", longname, value ? value : _T("<no-value>"));
         break;
      case _T('c'):
         pcl_printf("c:%ts] set\n", longname);
         break;
      case _T('d'):
      default:
        pcl_printf("d:%ts] set\n", longname); // prints "d:<short-only>] set\n"
    }
  }
  pcl_free(state);
  if(opt == -1)
    PANIC("getopt failed", 0);
  return app_start();
}
Macro Definition Documentation
pcl_tmain
#define pcl_tmain main
#include <pcl/init.h>
Definition at line 115 of file init.h.
Typedef Documentation
pcl_optstate_t
typedef struct tag_pcl_optstate pcl_optstate_t
#include <pcl/init.h>
‪State management for argument parsing.
See also
‪pcl_initopt, pcl_getopt
Definition at line 1 of file init.h.
Enumeration Type Documentation
pcl_optpolicy
enum pcl_optpolicy
#include <pcl/init.h>
Enumerator
PclNoArg
Option does not take any arguments.
PclReqArg
Option requires an argument.
PclOptArg
Option takes an optional argument.
Definition at line 122 of file init.h.
Function Documentation
pcl_init()
PCL_EXPORT void pcl_init (void)
#include <pcl/init.h>
‪Initializes the PCL library.
This must be called before using the PCL library.
Definition at line 62 of file init.c.
References countof, ipcl_event_init(), pcl_atomic_compare_exchange(), STDERR_FILENO, STDIN_FILENO, and STDOUT_FILENO.
pcl_initopt()
PCL_EXPORT pcl_optstate_t* pcl_initopt (int argc, tchar_t ** argv, const tchar_t * optstr, pcl_option_t * options, int num_options)
#include <pcl/init.h>
‪Intialize command-line argument parser.
This behaves very similar to POSIX getopt_long. Some differences are
‪This doesn't permute (rearrange) arguments
‪No support for '+' or POSIXLY_CORRECT
‪opaque pcl_optstate_t manages state rather than global variables
‪returns 0 when complete, not -1. -1 indicates an error
‪? never returned to indicate an error, -1 is always returned
‪this never outputs to stderr, it instead returns -1 and set pcl_errno
Warning
‪If the short options optstr defines different argument policies than the matching pcl_option_t.val, the behavior is undefined. If time is taken to map short => long, make sure policies match: PclNoArg, PclReqArg or PclOptArg.
Parameters
argc ‪argument count, typically from main
argv ‪pointer to an array of arguments, typically from main
optstr ‪option characters. If a character is followed by a colon, the option requires an argument. If followed by two colons, the option takes an optional argument. In either case, the argument can be specified as: "-Ovalue", "-O=value" or "-O value". When dealing with an optional argument, the 3rd form excludes the value if it begins with a '-': ie. "-O -value". This is not the case for a required argument. This can be NULL as long as the options parameter is not NULL.
options ‪array of option structures defining legitimate long options. The option structure defines an option name, option argument policy and a val used as the return value when a long option is found. Typically, val is set to its corresponding short option character, but this is not a requirement. The argument can be specified as "--long=value" or "--long value". As with short options, the 2nd form excludes optional arguments that begin with a '-': ie. "-long -value". This is not the case for a required argument. This can be NULL as long as the optstr parameter is not NULL.
num_options ‪number of option structures in the options parameter.
Returns
‪pointer to an option state structure, that must be freed by caller, or NULL on error. An error only occurs if there is an invalid argument.
Definition at line 37 of file initopt.c.
References tag_pcl_optstate::argc, tag_pcl_optstate::argidx, tag_pcl_optstate::argv, tag_pcl_optstate::next_optstr, tag_pcl_optstate::num_options, tag_pcl_optstate::options, tag_pcl_optstate::optstr, PCL_EINVAL, pcl_malloc(), and R_SETERR.
pcl_getopt()
PCL_EXPORT int pcl_getopt (pcl_optstate_t * state, tchar_t ** value, pcl_option_t ** longopt)
#include <pcl/init.h>
‪Parse command-line arguments.
Parameters
state ‪pointer to a getopt state structure intialized via pcl_initopt
value ‪pointer to a string to receive the value, if any. This can be NULL. If this is NULL, there is no way to get an option's argument value. This value must be copied to persist after argument parsing, since it is direct pointer to the argv array provided during pcl_initopt.
longopt ‪pointer to an option to receive the matching option object. The comparison works for long or short option parsing. When a short option is found with a matching pcl_option_t.val value, that option object is written here. For long options, the comparison is based off pcl_option_t.name. If a short option has no matching val within long option objects, or they were not provided to pcl_initopt, then this is set to NULL. This is an optional parameter and can be NULL.
Returns
‪The short option character or long option pcl_option_t.val. When all arguments have been parsed, this returns 0. On error, -1 is returned.
Definition at line 38 of file getopt.c.
References _T, tag_pcl_optstate::argc, tag_pcl_optstate::argidx, tag_pcl_optstate::argv, BADARG, tag_pcl_optstate::next_optstr, tag_pcl_optstate::num_options, tag_pcl_optstate::options, tag_pcl_optstate::optstr, PCL_EINVAL, pcl_tcschr(), pcl_tcscmp(), pcl_tcslen(), pcl_tmemcmp(), PclNoArg, PclOptArg, PclReqArg, SETERRMSG, and pcl_option_t::val.