‪libpcl: ‪/Users/andrew/projects/libpcl/src/win32/_win32.h File Reference
_win32.h File Reference
#include <pcl/types.h>
#include <pcl/error.h>
#include <pcl/string.h>
#include <windows.h>
#include <shlobj.h>
#include <sddl.h>
Macros
#define NT_READ_TO_MODE (FILE_READ_DATA | FILE_READ_EA | FILE_READ_ATTRIBUTES)
#define NT_WRITE_TO_MODE
#define NT_EXECUTE_TO_MODE (FILE_EXECUTE)
#define UNIX_READ_TO_RIGHTS (NT_READ_TO_MODE | READ_CONTROL | SYNCHRONIZE)
#define UNIX_WRITE_TO_RIGHTS
#define UNIX_EXECUTE_TO_RIGHTS
#define SID_ISGROUP(_sid_type)
Functions
void ipcl_win32_sd_init (SECURITY_DESCRIPTOR *sd)
int ipcl_win32_sd_create (SECURITY_DESCRIPTOR *sd, const pchar_t *owner, const pchar_t *group, mode_t mode)
int ipcl_win32_sd_get (const pchar_t *path, SECURITY_DESCRIPTOR **sd, DWORD *sdlen, PSID *world_sid, PSID *owner_sid, PSID *group_sid, BOOL *have_dacl, PACL *dacl, SECURITY_INFORMATION secinfo)
‪Get the SECURITY_DESCRIPTOR for the given path.
int ipcl_win32_sd_clear (SECURITY_DESCRIPTOR *sd)
‪Clears an "absolute" SECURITY_DESCRIPTOR.
int ipcl_win32_process_token (HANDLE *htok)
int ipcl_win32_token_into (HANDLE htok, TOKEN_INFORMATION_CLASS type, void **data)
PSID ipcl_win32_sid_dup (PSID sid)
‪Duplicates the given SID.
PSID ipcl_win32_name_to_sid (const pchar_t *name, int *type)
int ipcl_win32_sid_to_name (PSID sid, char *out, size_t len)
PSID ipcl_win32_world_sid (void)
‪Allocates a new world SID.
DWORD ipcl_win32_mode_to_rights (mode_t mode, int type)
‪Convert the user, group or other unix mode bits to Windows NT access rights.
mode_t ipcl_win32_rights_to_mode (DWORD rights, int type)
‪Converts the given NT access rights to user, group or other mode bits.
int ipcl_win32_logon (const pchar_t *username, const pchar_t *domain, const pchar_t *password, HANDLE *htok)
PSID ipcl_win32_process_sid (void)
‪Get TokenUser SID of process.
int ipcl_win32_file_security (const pchar_t *path, mode_t *mode, uid_t *uidp, gid_t *gidp)
Macro Definition Documentation
NT_READ_TO_MODE
#define NT_READ_TO_MODE (FILE_READ_DATA | FILE_READ_EA | FILE_READ_ATTRIBUTES)
Definition at line 42 of file _win32.h.
NT_WRITE_TO_MODE
#define NT_WRITE_TO_MODE
Value:
  (FILE_WRITE_DATA | \
  FILE_APPEND_DATA | FILE_WRITE_EA | FILE_WRITE_ATTRIBUTES)
Definition at line 44 of file _win32.h.
NT_EXECUTE_TO_MODE
#define NT_EXECUTE_TO_MODE (FILE_EXECUTE)
Definition at line 47 of file _win32.h.
UNIX_READ_TO_RIGHTS
#define UNIX_READ_TO_RIGHTS (NT_READ_TO_MODE | READ_CONTROL | SYNCHRONIZE)
Definition at line 49 of file _win32.h.
UNIX_WRITE_TO_RIGHTS
#define UNIX_WRITE_TO_RIGHTS
Value:
  (NT_WRITE_TO_MODE | READ_CONTROL | \
  SYNCHRONIZE | DELETE | FILE_DELETE_CHILD)
Definition at line 51 of file _win32.h.
UNIX_EXECUTE_TO_RIGHTS
#define UNIX_EXECUTE_TO_RIGHTS
Value:
  (NT_EXECUTE_TO_MODE | READ_CONTROL | \
  SYNCHRONIZE)
Definition at line 54 of file _win32.h.
SID_ISGROUP
#define SID_ISGROUP (_sid_type)
Value:
  (_sid_type == SidTypeGroup || \
  _sid_type == SidTypeAlias || _sid_type == SidTypeWellKnownGroup)
Definition at line 57 of file _win32.h.
Function Documentation
ipcl_win32_sd_init()
void ipcl_win32_sd_init (SECURITY_DESCRIPTOR * sd)
Definition at line 35 of file win32_sd_init.c.
Referenced by ipcl_win32_sd_clear(), and ipcl_win32_sd_create().
ipcl_win32_sd_create()
int ipcl_win32_sd_create (SECURITY_DESCRIPTOR * sd, const pchar_t * owner, const pchar_t * group, mode_t mode)
Definition at line 45 of file win32_sd_create.c.
References CLEANUP, ipcl_win32_mode_to_rights(), ipcl_win32_name_to_sid(), ipcl_win32_process_token(), ipcl_win32_sd_init(), ipcl_win32_sid_dup(), ipcl_win32_token_into(), ipcl_win32_world_sid(), pcl_free(), pcl_malloc(), S_IRGRP, S_IROTH, S_IRUSR, S_IRWXG, S_IRWXO, S_IRWXU, SETLASTERR, SID_ISGROUP, and strempty.
Referenced by ipcl_file_open(), and pcl_mkdir().
ipcl_win32_sd_get()
int ipcl_win32_sd_get (const pchar_t * path, SECURITY_DESCRIPTOR ** sd, DWORD * sdlen, PSID * world_sid, PSID * owner_sid, PSID * group_sid, BOOL * have_dacl, PACL * dacl, SECURITY_INFORMATION secinfo)
‪Get the SECURITY_DESCRIPTOR for the given path.
Parameters
[in] path
[out] sd ‪a pointer to a security descriptor pointer to receive an allocated self-relative descriptor for the given path. Caller must free this with pcl_free.
sdlen
world_sid ‪optional pointer to an allocated SID that must be passed to FreeSid.
owner_sid ‪optional pointer to the owner sid. This memory is owned by the security descriptor and must not passed to a free function.
group_sid ‪optional pointer to the group sid. This memory is owned by the security descriptor and must not passed to a free function.
have_dacl ‪optional pointer to a BOOL that indicates if the security descriptor has a DACL.
dacl ‪optional pointer to a DACL. This memory is owned by the security descriptor and must not passed to a free function.
secinfo ‪bit mask that indicates what security information is desired. See the WinAPI GetKernelObjectSecurity function.
Returns
‪0 for success and -1 on error. If this fails, no output arguments are valid.
Definition at line 74 of file win32_sd_get.c.
References ipcl_win32_world_sid(), pcl_free(), sd_get(), SETLASTERR, and TRC.
Referenced by ipcl_win32_file_security().
ipcl_win32_sd_clear()
int ipcl_win32_sd_clear (SECURITY_DESCRIPTOR * sd)
‪Clears an "absolute" SECURITY_DESCRIPTOR.
Typically this is used as the clear operation for descriptors populated by ipcl_win32_sd_create, but that is not a requirement. This can clear any valid absolute SECURITY_DESCRIPTOR.
Parameters
sd ‪pointer to a SECURITY_DESCRIPTOR. Note, this function doesn't free the descriptor pointer itself, just its internals. After this call, the descriptor is empty.
Returns
‪0 for success and -1 on error. This will fail if the provided security descriptor is NOT absolute.
Definition at line 36 of file win32_sd_clear.c.
References ipcl_win32_sd_init(), pcl_free(), and SETLASTERRMSG.
Referenced by ipcl_file_open(), and pcl_mkdir().
ipcl_win32_process_token()
int ipcl_win32_process_token (HANDLE * htok)
Definition at line 35 of file win32_process_token.c.
References pcl_oserrno, and SETLASTERR.
Referenced by ipcl_win32_process_sid(), and ipcl_win32_sd_create().
ipcl_win32_token_into()
int ipcl_win32_token_into (HANDLE htok, TOKEN_INFORMATION_CLASS type, void ** data)
Definition at line 36 of file win32_token_info.c.
References pcl_free(), pcl_malloc(), pcl_oserrno, and SETLASTERR.
Referenced by ipcl_win32_process_sid(), and ipcl_win32_sd_create().
ipcl_win32_sid_dup()
PSID ipcl_win32_sid_dup (PSID sid)
‪Duplicates the given SID.
Parameters
sid
Returns
Definition at line 36 of file win32_sid_dup.c.
References PCL_EINVAL, pcl_malloc(), and R_SETERR.
Referenced by ipcl_win32_process_sid(), and ipcl_win32_sd_create().
ipcl_win32_name_to_sid()
PSID ipcl_win32_name_to_sid (const pchar_t * name, int * type)
Definition at line 36 of file win32_name_to_sid.c.
References countof, PCL_EINVAL, pcl_free(), pcl_malloc(), R_SETERR, R_SETLASTERR, SETLASTERR, and strempty.
Referenced by ipcl_win32_sd_create().
ipcl_win32_sid_to_name()
int ipcl_win32_sid_to_name (PSID sid, char * out, size_t len)
Definition at line 36 of file win32_sid_to_name.c.
References PCL_EINVAL, pcl_sprintf(), SETERR, and SETLASTERR.
Referenced by pcl_getuser().
ipcl_win32_world_sid()
PSID ipcl_win32_world_sid (void)
‪Allocates a new world SID.
Returns
Definition at line 35 of file win32_world_sid.c.
References R_SETLASTERR.
Referenced by ipcl_win32_sd_create(), and ipcl_win32_sd_get().
ipcl_win32_mode_to_rights()
DWORD ipcl_win32_mode_to_rights (mode_t mode, int type)
‪Convert the user, group or other unix mode bits to Windows NT access rights.
Parameters
mode
type ‪one of S_IRUSR, S_IRGRP or S_IROTH
Returns
Definition at line 36 of file win32_mode_to_rights.c.
References S_IRGRP, S_IROTH, S_IRUSR, S_IRWXG, S_IRWXO, S_IRWXU, S_IWGRP, S_IWOTH, S_IWUSR, S_IXGRP, S_IXOTH, S_IXUSR, UNIX_EXECUTE_TO_RIGHTS, UNIX_READ_TO_RIGHTS, and UNIX_WRITE_TO_RIGHTS.
Referenced by ipcl_win32_sd_create().
ipcl_win32_rights_to_mode()
mode_t ipcl_win32_rights_to_mode (DWORD rights, int type)
‪Converts the given NT access rights to user, group or other mode bits.
Parameters
rights ‪the ACCESS_ALLOWED_ACE mask to convert
type ‪one of S_IRUSR, S_IRGRP or S_IROTH
Returns
‪unix style mode bits
Definition at line 36 of file win32_rights_to_mode.c.
References NT_EXECUTE_TO_MODE, NT_READ_TO_MODE, NT_WRITE_TO_MODE, S_IRGRP, S_IROTH, S_IRUSR, S_IWGRP, S_IWOTH, S_IWUSR, S_IXGRP, S_IXOTH, and S_IXUSR.
Referenced by ipcl_win32_file_security().
ipcl_win32_logon()
int ipcl_win32_logon (const pchar_t * username, const pchar_t * domain, const pchar_t * password, HANDLE * htok)
Definition at line 36 of file win32_logon.c.
References _P, PCL_EINVAL, SETERR, and SETLASTERRMSG.
ipcl_win32_process_sid()
PSID ipcl_win32_process_sid (void)
‪Get TokenUser SID of process.
Returns
‪application must free this
Definition at line 36 of file win32_process_sid.c.
References ipcl_win32_process_token(), ipcl_win32_sid_dup(), ipcl_win32_token_into(), pcl_free(), and TRC.
ipcl_win32_file_security()
int ipcl_win32_file_security (const pchar_t * path, mode_t * mode, uid_t * uidp, gid_t * gidp)
Definition at line 37 of file win32_file_security.c.
References ipcl_win32_rights_to_mode(), ipcl_win32_sd_get(), PCL_EINVAL, pcl_free(), pcl_strtrunc(), S_IRGRP, S_IROTH, S_IRUSR, S_IRWXG, S_IRWXO, S_IRWXU, SETERR, and TRC.