‪libpcl: ‪Standard Library
Standard Library
‪This library proves memory allocation, PRNG, integer conversions, unicode functions and hashing functions.
Functions
PCL_EXPORT tchar_t * pcl_realpath (const tchar_t *path, int *lenp)
‪Gets the canonicalized absolute pathname.
PCL_EXPORT char * pcl_tcs_to_utf8 (const tchar_t *src, size_t src_len, size_t *lenp)
‪Convert a tchar_t string to UTF-8.
PCL_EXPORT tchar_t * pcl_utf8_to_tcs (const char *src, size_t src_len, size_t *lenp)
‪Convert a UTF-8 string to a tchar_t string.
PCL_EXPORT int pcl_rand (void *buf, int num)
‪Generate random bytes.
Detailed Description
This library proves memory allocation, PRNG, integer conversions, unicode functions and hashing functions.
Function Documentation
pcl_realpath()
PCL_EXPORT tchar_t* pcl_realpath (const tchar_t * path, int * lenp)
#include <pcl/stdlib.h>
‪Gets the canonicalized absolute pathname.
Parameters
path ‪path to convert
[out] lenp ‪If not NULL, character length (excluding NUL) is written here
Returns
‪an allocated absolute path or NULL on error
Definition at line 45 of file realpath.c.
References PCL_EINVAL, pcl_malloc(), pcl_strndup(), R_SETERR, R_SETLASTERR, and strempty.
Referenced by pcl_opendir().
pcl_tcs_to_utf8()
PCL_EXPORT char* pcl_tcs_to_utf8 (const tchar_t * src, size_t src_len, size_t * lenp)
#include <pcl/stdlib.h>
‪Convert a tchar_t string to UTF-8.
Internally, this is just a strdup on Unix machines since a Unix tchar_t represents UTF-8.
Parameters
src ‪pointer to a tchar_t string
src_len ‪byte length of the src argument. If this is zero, strlen is used
lenp ‪If not NULL, character length will be written here
Returns
‪pointer to the result of conversion. This must be freed.
Definition at line 72 of file tcs_to_utf8.c.
References PCL_EINVAL, pcl_tcslen(), pcl_tcsndup(), and R_SETERR.
Referenced by pcl_net_dnstxtrec().
pcl_utf8_to_tcs()
PCL_EXPORT tchar_t* pcl_utf8_to_tcs (const char * src, size_t src_len, size_t * lenp)
#include <pcl/stdlib.h>
‪Convert a UTF-8 string to a tchar_t string.
Internally, this is just a strdup on Unix machines since a Unix tchar_t represents UTF-8.
Parameters
src ‪pointer to a UTF-8 string
src_len ‪byte length of the src argument. If this is zero, strlen is used
[out] lenp ‪If not NULL, character length will be written here
Returns
‪pointer to the result of conversion. This must be freed.
Definition at line 64 of file utf8_to_tcs.c.
References PCL_EINVAL, pcl_strndup(), and R_SETERR.
Referenced by pcl_bind(), and pcl_sysinfo().
pcl_rand()
PCL_EXPORT int pcl_rand (void * buf, int num)
#include <pcl/stdlib.h>
‪Generate random bytes.
Parameters
buf ‪pointer to a buffer to receive random bytes
num ‪number of bytes to generate
Returns
‪number of bytes generated
Definition at line 82 of file rand.c.
References pcl_atomic_add_fetch().
Referenced by pcl_proc_pipe(), and pcl_tmpfile().