‪libpcl: ‪Cryptography Functions
Cryptography Functions
‪A set of functions focused on cryptography.
Macros
#define PCL_MAXIVLEN 16
#define PCL_AEAD_TAGLEN 16
Functions
PCL_EXPORT int pcl_rand (void *buf, int num)
‪Generate random bytes.
PCL_EXPORT pcl_cipher_t * pcl_cipher_create (const char *algo, const void *key, const void *iv, const void *aad, uint32_t aad_len, bool enc)
‪Create a cipher object.
PCL_EXPORT int pcl_cipher_reset (pcl_cipher_t *ciph, const void *iv, const void *aad, uint32_t aad_len)
‪Reset a cipher so it can be reused.
PCL_EXPORT const char * pcl_cipher_name (pcl_cipher_t *ciph)
‪Get cipher name.
PCL_EXPORT bool pcl_cipher_isaead (pcl_cipher_t *ciph)
‪I this an AEAD cipher.
PCL_EXPORT int pcl_cipher_update (pcl_cipher_t *ciph, char *out, const void *in, int in_len)
‪Encrypt or dercypt more bytes.
PCL_EXPORT int pcl_cipher_final (pcl_cipher_t *ciph, char *out, char *tag)
‪Finalize encrypt or decrypt process.
PCL_EXPORT void pcl_cipher_free (pcl_cipher_t *ciph)
‪Release all resources used by a cipher object.
PCL_EXPORT pcl_digest_t * pcl_digest_create (const char *algo)
‪Create a message digest object.
PCL_EXPORT int pcl_digest_update (pcl_digest_t *d, const void *data, size_t len)
‪Update the data of a digest operation.
PCL_EXPORT void * pcl_digest_final (pcl_digest_t *d, int *lenp)
‪Finalize a digest operation.
PCL_EXPORT void * pcl_digest (const char *algo, const void *data, size_t *len)
‪Create a message digest.
PCL_EXPORT int pcl_digest_len (pcl_digest_t *d)
‪Get digest length.
PCL_EXPORT const char * pcl_digest_name (pcl_digest_t *d)
‪Get digest algorithm name.
PCL_EXPORT void * pcl_digest_free (pcl_digest_t *d)
‪Free a message digest.
Detailed Description
A set of functions focused on cryptography.
Macro Definition Documentation
PCL_MAXIVLEN
#define PCL_MAXIVLEN 16
#include <pcl/crypto.h>
Definition at line 41 of file crypto.h.
PCL_AEAD_TAGLEN
#define PCL_AEAD_TAGLEN 16
#include <pcl/crypto.h>
Definition at line 42 of file crypto.h.
Function Documentation
pcl_rand()
PCL_EXPORT int pcl_rand (void * buf, int num)
#include <pcl/crypto.h>
‪Generate random bytes.
Parameters
buf ‪pointer to a buffer to receive random bytes
num ‪number of bytes to generate
Returns
‪number of bytes generated
Definition at line 83 of file rand.c.
References pcl_atomic_add_fetch().
Referenced by pcl_proc_pipe(), and pcl_tmpfile().
pcl_cipher_create()
PCL_EXPORT pcl_cipher_t* pcl_cipher_create (const char * algo, const void * key, const void * iv, const void * aad, uint32_t aad_len, bool enc)
#include <pcl/crypto.h>
‪Create a cipher object.
Parameters
algo ‪cipher algorithm: supports "aes-128-gcm", "aes-256-gcm", "aes-128-cbc", "aes-256-cbc", "aes-128-ocb", "aes-256-ocb", "chacha20-poly1305".
key ‪cipher key. length expected to match algorithm
iv ‪cipher iv. The length depends on the cipher and mode. It is recommended to always provide 16 bytes to keep things simple, which is the maximum IV length across ciphers.
aad ‪additional authenticated data. This is only used by ciphers that support authenticated encryption with associated data (AEAD). This can be NULL in either case.
aad_len ‪number of aad bytes. If zero, aad parameter is ignored.
enc ‪when non-zero, create an encryption cipher, otherwise decryption
Returns
‪pointer to a cipher object or NULL on error
See also
‪PCL_MAXIVLEN, enum pcl_cipher_algo
Definition at line 35 of file cipher_create.c.
References tag_pcl_cipher::algo, tag_pcl_cipher::ctx, pcl_cipher_free(), pcl_cipher_isaead(), PCL_ECRYPT, PCL_EINVAL, pcl_malloc(), R_SETERR, and R_SETERRMSG.
pcl_cipher_reset()
PCL_EXPORT int pcl_cipher_reset (pcl_cipher_t * ciph, const void * iv, const void * aad, uint32_t aad_len)
#include <pcl/crypto.h>
‪Reset a cipher so it can be reused.
This should be called after calling pcl_cipher_final.
This requires providing a new IV since using the same IV across cycles is a very bad idea. The key cannot be changed. If the key needs to be changed, free this cipher and create a new one.
The goal of reset is to avoid tearing everything down and creating a whole new context when it is desired to reuse the same KEY: set of files, network packets, etc. Instead, it can be reset with a new IV and optional AAD data. After this call, use pcl_cipher_update and pcl_cipher_final as usual.
Parameters
ciph ‪pointer to a cipher object
iv
aad ‪additional authenticated data. This is only used by ciphers that support authenticated encryption with associated data (AEAD). This can be NULL in either case.
aad_len ‪number of aad bytes. If zero, aad parameter is ignored.
Returns
‪0 for success and -1 on error.
Definition at line 36 of file cipher_reset.c.
References tag_pcl_cipher::algo, BADARG, tag_pcl_cipher::ctx, pcl_cipher_isaead(), PCL_ECRYPT, PCL_EINVAL, and SETERRMSG.
pcl_cipher_name()
PCL_EXPORT const char* pcl_cipher_name (pcl_cipher_t * ciph)
#include <pcl/crypto.h>
‪Get cipher name.
Parameters
ciph ‪pointer to a cipher object
Returns
‪pointer to cipher name or NULL on error
Definition at line 35 of file cipher_name.c.
References tag_pcl_cipher::algo, PCL_EINVAL, and R_SETERR.
pcl_cipher_isaead()
PCL_EXPORT bool pcl_cipher_isaead (pcl_cipher_t * ciph)
#include <pcl/crypto.h>
‪I this an AEAD cipher.
Parameters
ciph ‪pointer to a cipher
Returns
‪true if AEAD supported, false if not
Definition at line 36 of file cipher_isaead.c.
References tag_pcl_cipher::algo, and pcl_stristr().
Referenced by pcl_cipher_create(), pcl_cipher_final(), and pcl_cipher_reset().
pcl_cipher_update()
PCL_EXPORT int pcl_cipher_update (pcl_cipher_t * ciph, char * out, const void * in, int in_len)
#include <pcl/crypto.h>
‪Encrypt or dercypt more bytes.
Parameters
ciph ‪pointer to a cipher object
out ‪pointer to an output buffer
in ‪pointer to an input (plain text)
in_len ‪number of bytes within in
Returns
‪number of bytes written to out or -1 on error
Definition at line 35 of file cipher_update.c.
References tag_pcl_cipher::algo, BADARG, tag_pcl_cipher::ctx, PCL_ECRYPT, and SETERRMSG.
pcl_cipher_final()
PCL_EXPORT int pcl_cipher_final (pcl_cipher_t * ciph, char * out, char * tag)
#include <pcl/crypto.h>
‪Finalize encrypt or decrypt process.
Parameters
ciph ‪pointer to a cipher object
out ‪pointer to output buffer which must be at least the size of a single block.
tag ‪Only used for AEAD ciphers. When encrypting, this must be a buffer of at least PCL_AEAD_TAGLEN bytes. When decrypting, this is the tag value which must be PCL_AEAD_TAGLEN bytes. This can be NULL.
Returns
‪number of bytes written to out (zero is valid) or -1 on error. When using AEAD during decryption, this will fail if the "expected" tag value is incorrect. In this case, the plaintext is not trustworthy and should be discarded.
See also
‪PCL_AEAD_TAGLEN
Definition at line 35 of file cipher_final.c.
References tag_pcl_cipher::algo, BADARG, tag_pcl_cipher::ctx, PCL_AEAD_TAGLEN, pcl_cipher_isaead(), PCL_ECRYPT, and SETERRMSG.
pcl_cipher_free()
PCL_EXPORT void pcl_cipher_free (pcl_cipher_t * ciph)
#include <pcl/crypto.h>
‪Release all resources used by a cipher object.
Parameters
ciph ‪pointer to a cipher object.
See also
‪pcl_cipher_reset
Definition at line 35 of file cipher_free.c.
References tag_pcl_cipher::ctx, and pcl_free().
Referenced by pcl_cipher_create().
pcl_digest_create()
PCL_EXPORT pcl_digest_t* pcl_digest_create (const char * algo)
#include <pcl/crypto.h>
‪Create a message digest object.
Parameters
algo ‪message digest algorithm: supports "md5", "sha1", "sha256", "sha512"
Returns
‪pointer to a message digest object
Definition at line 36 of file digest_create.c.
References tag_pcl_digest::algo, tag_pcl_digest::ctx, tag_pcl_digest::md, pcl_digest_free(), PCL_ECRYPT, PCL_EINVAL, pcl_malloc(), and R_SETERRMSG.
Referenced by pcl_digest().
pcl_digest_update()
PCL_EXPORT int pcl_digest_update (pcl_digest_t * d, const void * data, size_t len)
#include <pcl/crypto.h>
‪Update the data of a digest operation.
Parameters
d ‪pointer to a message digest object
data ‪pointer to data bytes
len ‪number of data bytes
Returns
‪0 for success and -1 on error
Definition at line 35 of file digest_update.c.
References BADARG, tag_pcl_digest::ctx, PCL_ECRYPT, and SETERR.
Referenced by pcl_digest().
pcl_digest_final()
PCL_EXPORT void* pcl_digest_final (pcl_digest_t * d, int * lenp)
#include <pcl/crypto.h>
‪Finalize a digest operation.
After this call, the digest object can be reused by calling pcl_digest_update and pcl_digest_final again.
Parameters
d ‪pointer to a message digest object
[out] lenp ‪if not NULL, the digest length will be written here
Returns
‪pointer to the message digest
Definition at line 36 of file digest_final.c.
References tag_pcl_digest::algo, tag_pcl_digest::ctx, tag_pcl_digest::md, PCL_EINVAL, pcl_malloc(), R_SETERR, and R_SETERRMSG.
Referenced by pcl_digest().
pcl_digest()
PCL_EXPORT void* pcl_digest (const char * algo, const void * data, size_t * len)
#include <pcl/crypto.h>
‪Create a message digest.
Parameters
algo ‪message digest algorithm: supports "md5", "sha1", "sha256", "sha512"
data ‪pointer to data bytes
[in,out] len ‪on input, this is the number of data bytes. On output, this is the number of bytes written to the returned digest.
Returns
‪pointer to a digest or NULL on error
Definition at line 35 of file digest.c.
References pcl_digest_create(), pcl_digest_final(), pcl_digest_free(), pcl_digest_update(), PCL_EINVAL, R_SETERR, and R_TRC.
pcl_digest_len()
PCL_EXPORT int pcl_digest_len (pcl_digest_t * d)
#include <pcl/crypto.h>
‪Get digest length.
Parameters
d ‪pointer to a message digest object
Returns
‪digest length or -1 on error
Definition at line 35 of file digest_len.c.
References BADARG, and tag_pcl_digest::md.
pcl_digest_name()
PCL_EXPORT const char* pcl_digest_name (pcl_digest_t * d)
#include <pcl/crypto.h>
‪Get digest algorithm name.
Parameters
d ‪pointer to a message digest object
Returns
‪pointer to digest algorithm name
Definition at line 35 of file digest_name.c.
References tag_pcl_digest::algo, PCL_EINVAL, and R_SETERR.
pcl_digest_free()
PCL_EXPORT void* pcl_digest_free (pcl_digest_t * d)
#include <pcl/crypto.h>
‪Free a message digest.
Parameters
d ‪pointer to a message digest object
Returns
‪always returns NULL
Definition at line 35 of file digest_free.c.
References tag_pcl_digest::ctx, and pcl_free().
Referenced by pcl_digest(), and pcl_digest_create().