‪libpcl: ‪/Users/andrew/projects/libpcl/src/win32/win32_sd_clear.c File Reference
win32_sd_clear.c File Reference
#include "_win32.h"
#include <pcl/alloc.h>
Functions
int ipcl_win32_sd_clear (SECURITY_DESCRIPTOR *sd)
‪Clears an "absolute" SECURITY_DESCRIPTOR.
Function Documentation
ipcl_win32_sd_clear()
int ipcl_win32_sd_clear (SECURITY_DESCRIPTOR * sd)
‪Clears an "absolute" SECURITY_DESCRIPTOR.
Typically this is used as the clear operation for descriptors populated by ipcl_win32_sd_create, but that is not a requirement. This can clear any valid absolute SECURITY_DESCRIPTOR.
Parameters
sd ‪pointer to a SECURITY_DESCRIPTOR. Note, this function doesn't free the descriptor pointer itself, just its internals. After this call, the descriptor is empty.
Returns
‪0 for success and -1 on error. This will fail if the provided security descriptor is NOT absolute.
Definition at line 36 of file win32_sd_clear.c.
References ipcl_win32_sd_init(), pcl_free(), and SETLASTERRMSG.
Referenced by ipcl_file_open(), and pcl_mkdir().