‪libpcl: ‪/Users/andrew/projects/libpcl/src/win32/win32_sd_create.c File Reference
win32_sd_create.c File Reference
#include "_win32.h"
#include <pcl/stat.h>
#include <pcl/alloc.h>
Macros
#define CLEANUP
Functions
int ipcl_win32_sd_create (SECURITY_DESCRIPTOR *sd, const tchar_t *owner, const tchar_t *group, mode_t mode)
Macro Definition Documentation
CLEANUP
#define CLEANUP
Value:
  do{ \
  pcl_free_safe(owner_sid); \
  pcl_free_safe(group_sid); \
  if(world_sid) \
    FreeSid(world_sid); \
  pcl_free_safe(dacl); \
}while(0)
Definition at line 36 of file win32_sd_create.c.
Function Documentation
ipcl_win32_sd_create()
int ipcl_win32_sd_create (SECURITY_DESCRIPTOR * sd, const tchar_t * owner, const tchar_t * group, mode_t mode)
Definition at line 45 of file win32_sd_create.c.
References CLEANUP, ipcl_win32_mode_to_rights(), ipcl_win32_name_to_sid(), ipcl_win32_process_token(), ipcl_win32_sd_init(), ipcl_win32_sid_dup(), ipcl_win32_token_into(), ipcl_win32_world_sid(), pcl_free(), pcl_malloc(), S_IRGRP, S_IROTH, S_IRUSR, S_IRWXG, S_IRWXO, S_IRWXU, SETLASTERR, SID_ISGROUP, and strempty.
Referenced by ipcl_file_open(), and pcl_mkdir().