‪libpcl: ‪/Users/andrew/projects/libpcl/src/ssl/ssl_certentry.c File Reference
ssl_certentry.c File Reference
#include "_ssl.h"
#include <pcl/array.h>
#include <pcl/string.h>
#include <pcl/alloc.h>
Functions
pcl_array_t * pcl_ssl_certentry (pcl_ssl_t *ssl, int entry_type)
‪Get all certificate entries of the given entry type.
Function Documentation
pcl_ssl_certentry()
pcl_array_t* pcl_ssl_certentry (pcl_ssl_t * ssl, int entry_type)
‪Get all certificate entries of the given entry type.
Parameters
ssl ‪pointer to a ssl object
entry_type ‪entry type, one of the PclCertXXX enum values.
Returns
‪pointer to an array or NULL if ann error occurs or no entries were found. In the latter case, PCL_ENOTFOUND is set.
Definition at line 38 of file ssl_certentry.c.
References BADARG, pcl_array(), pcl_array_append(), pcl_cleanup_ptr(), PCL_ENOTFOUND, PCL_ETYPE, pcl_strndup(), PclCertCommonName, PclCertCountryName, PclCertLocalityName, PclCertOrgName, PclCertOrgUNIT, PclCertState, SETERR, SETERRMSG, and tag_pcl_ssl::ssl.