‪libpcl: ‪Dynamic Buffer
Dynamic Buffer
‪The buffer API provides a dynamically sized buffer for putting text and/or binary data.
Data Structures
struct tag_pcl_buf
Typedefs
typedef struct tag_pcl_buf pcl_buf_t
Enumerations
enum pcl_buf_mode {
PclBufBinary,
PclBufText,
PclBufTextW,
PclBufTextT =PclBufText
}
Functions
PCL_EXPORT pcl_buf_t * pcl_buf_init (pcl_buf_t *b, size_t size, enum pcl_buf_mode mode)
‪Initializes a buffer object.
PCL_EXPORT pcl_buf_t * pcl_buf_grow (pcl_buf_t *b, int len)
‪Grow a buffer.
PCL_EXPORT pcl_buf_t * pcl_buf_reset (pcl_buf_t *b)
‪Reset a buffer to its initial state.
PCL_EXPORT pcl_buf_t * pcl_buf_clear (pcl_buf_t *b)
‪Clear a buffer.
PCL_EXPORT pcl_buf_t * pcl_buf_copy (pcl_buf_t *dest, const pcl_buf_t *src)
‪Copy a buffer.
PCL_EXPORT pcl_buf_t * pcl_buf_free (pcl_buf_t *b)
‪Free all buffer resources and the buffer object itself.
PCL_EXPORT int pcl_buf_put (pcl_buf_t *b, const void *data, int len)
‪Put a blob into a buffer.
PCL_EXPORT int pcl_buf_putstr (pcl_buf_t *b, const void *s)
‪Put a string into a buffer.
PCL_EXPORT int pcl_buf_putchar (pcl_buf_t *b, uint32_t c)
‪Put a character into a buffer.
PCL_EXPORT int pcl_buf_putint8 (pcl_buf_t *b, uint8_t i)
‪Put an 8-bit integer into a buffer.
PCL_EXPORT int pcl_buf_putint16 (pcl_buf_t *b, uint16_t i)
‪Puts a 16-bit integer into a buffer in network-byte order.
PCL_EXPORT int pcl_buf_putint32 (pcl_buf_t *b, uint32_t i)
‪Puts a 32-bit integer into a buffer in network-byte order.
PCL_EXPORT int pcl_buf_putint64 (pcl_buf_t *b, uint64_t i)
‪Puts a 64-bit integer into a buffer in network-byte order.
PCL_EXPORT int pcl_buf_putf (pcl_buf_t *b, const void *format,...)
‪Put a formatted string into a buffer.
PCL_EXPORT int pcl_buf_vputf (pcl_buf_t *b, const void *format, va_list ap)
‪Put a formatted string into a buffer.
PCL_EXPORT int pcl_buf_get (pcl_buf_t *b, void *buf, int len)
‪Get a blob from a buffer.
PCL_EXPORT int pcl_buf_getstr (pcl_buf_t *b, char *buf, int len)
‪Get a string from a buffer.
PCL_EXPORT int pcl_buf_getchar (pcl_buf_t *b, uint32_t *c)
‪Get a character from a buffer.
PCL_EXPORT int pcl_buf_getint8 (pcl_buf_t *b, uint8_t *i)
‪Get an 8-bit integer a the buffer.
PCL_EXPORT int pcl_buf_getint16 (pcl_buf_t *b, uint16_t *i)
‪Get a 16-bit integer from a buffer in host-byte order.
PCL_EXPORT int pcl_buf_getint32 (pcl_buf_t *b, uint32_t *i)
‪Get a 32-bit integer from a buffer in host-byte order.
PCL_EXPORT int pcl_buf_getint64 (pcl_buf_t *b, uint64_t *i)
‪Get a 64-bit integer from a buffer in host-byte order.
Detailed Description
The buffer API provides a dynamically sized buffer for putting text and/or binary data.
When a buffer is created, a buffer mode must be provided: one of PclBufBinary, PclBufText, PclBufTextW or PclBufTextT. Regardless of a buffer's mode, a trailing NUL is added on every put. The space is reserved internally and it not represented in the buffer's current position or length. The buffer thinks in "characters", not bytes. When in binary mode, it still performs character calculations but based on a one byte character.
Binary Mode
A binary buffer is an array of data types: integers, strings and blobs. A binary string is written to the buffer with a trailing NUL, avoiding the need for a length prefix. Integers are written in network-byte order and blobs are written as is. For blobs, if they are variable length, do pcl_buf_putint32 followed by pcl_buf_put. There is also int8, int16 and int64.
All buffer functions are available to PclBufBinary. Again, this mode deals with bytes but treats them as one byte characters.
pcl_buf_t *buf = pcl_buf_init(NULL, 64, PclBufBinary);
pcl_buf_putstr(buf, "Hello"); // buffer contents: "Hello\0\0"
// no trailing NUL for single characters, put as int8.
pcl_buf_putchar(buf, ' ');    // buffer contents: "Hello\0 \0"
// it may appear that the space is joined to World. However, when getting data back
// out of the buffer, the idea is to call the same set of functions to deserialize.
// Thus, pcl_buf_getchar gets the space and pcl_buf_getstr gets "World"
pcl_buf_putstr(buf, "World"); // buffer contents: "Hello\0 World\0\0"
// be careful with the raw put function, it won't add a NUL for strings
// unless you include the NUL in the length argument.
pcl_buf_put(buf, "abc", 3); // No trailing NUL put. Pass 4 or use pcl_buf_putstr
// binary mode only, "Hello\0 World\0abc[32 bits in network-byte order]\0"
// note the "abc" string without a NUL. pcl_buf_getstr cannot be used, one
// must use pcl_buf_getchar 3 times or pcl_buf_get with a length of 3.
pcl_buf_putint32(buf, 3897463623);
pcl_buf_free(buf);
Text Mode
In text mode, the buffer is an array of characters with the always present NUL at the end. Text mode buffers are limited to put, putstr, putchar, putf and putvf. Get functions aren't needed in text mode since one can simply access pcl_buf_t.data, which will be a NUL-terminated string. Directly accessing pcl_buf_t.data, means you must properly cast it if using PclBufTextW or PclBufTextT.
pcl_buf_t buf; // use stack memory
pcl_buf_init(&buf, 64, PclBufText);
pcl_buf_putstr(&buf, "Hello"); // buffer contents: "Hello\0"
pcl_buf_putstr(&buf, "World"); // buffer contains: "HelloWorld\0"
printf("%d] %s\n", buf.len, buf.data); // 10] HelloWorld
pcl_buf_clear(&buf); // not pcl_buf_free!
// For PclBufTextW (PclBufTextT is identical but use _T("") and tchar_t)
pcl_buf_init(&buf, 64, PclBufTextW);
pcl_buf_putstr(&buf, L"Hello");
printf("%ls\n", (wchar_t *)buf.data);
Typedef Documentation
pcl_buf_t
typedef struct tag_pcl_buf pcl_buf_t
#include <pcl/types.h>
Definition at line 60 of file types.h.
Enumeration Type Documentation
pcl_buf_mode
enum pcl_buf_mode
#include <pcl/buf.h>
Enumerator
PclBufBinary
Binary buffer mode.
Single byte characters and all put and get functions are available.
PclBufText
Text buffer mode.
This is a char buffer with limited access to functions.
PclBufTextW
Wide-text buffer mode.
This is a wchar_t buffer with limited acccess to functions.
PclBufTextT
Type-text buffer mode.
This is a tchar_t buffer with limited acccess to functions.
Definition at line 108 of file buf.h.
Function Documentation
pcl_buf_init()
PCL_EXPORT pcl_buf_t* pcl_buf_init (pcl_buf_t * b, size_t size, enum pcl_buf_mode mode)
#include <pcl/buf.h>
‪Initializes a buffer object.
Parameters
b ‪pointer to a buffer. If this is NULL, a buffer will be allocated
size ‪intial size in characters
mode ‪the buffer mode
Returns
‪pointer to b if it was not NULL or a pointer to a newly allocated buffer.
Definition at line 37 of file buf_init.c.
References tag_pcl_buf::chrsize, tag_pcl_buf::data, tag_pcl_buf::len, tag_pcl_buf::mode, PCL_EINVAL, pcl_malloc(), PclBufBinary, PclBufText, PclBufTextW, tag_pcl_buf::pos, R_SETERRMSG, and tag_pcl_buf::size.
Referenced by ipcl_err_ctx_serialize(), pcl_buf_copy(), and pcl_openssl_error().
pcl_buf_grow()
PCL_EXPORT pcl_buf_t* pcl_buf_grow (pcl_buf_t * b, int len)
#include <pcl/buf.h>
‪Grow a buffer.
Given a len, this ensures that writing len bytes won't overflow the buffer by reallocating the buffer's internal memory. This is used by all buffer put functions before attempting to write data.
Parameters
b ‪pointer to a buffer
len ‪number of new characters to be added to the buffer
Returns
‪pointer to b or NULL on error
Definition at line 36 of file buf_grow.c.
References tag_pcl_buf::chrsize, tag_pcl_buf::data, PCL_EINVAL, pcl_realloc(), tag_pcl_buf::pos, R_SETERR, and tag_pcl_buf::size.
Referenced by pcl_buf_put(), and pcl_buf_vputf().
pcl_buf_reset()
PCL_EXPORT pcl_buf_t* pcl_buf_reset (pcl_buf_t * b)
#include <pcl/buf.h>
‪Reset a buffer to its initial state.
This sets the buffer's position and length to zero.
Parameters
b ‪pointer to a buffer
Returns
‪pointer to the b argument
Definition at line 36 of file buf_reset.c.
References tag_pcl_buf::chrsize, tag_pcl_buf::data, tag_pcl_buf::len, and tag_pcl_buf::pos.
Referenced by ipcl_err_ctx_serialize().
pcl_buf_clear()
PCL_EXPORT pcl_buf_t* pcl_buf_clear (pcl_buf_t * b)
#include <pcl/buf.h>
‪Clear a buffer.
This is similar to a reset but also releases all resources used by the buffer.
Parameters
b ‪pointer to a buffer
Returns
‪pointer to the b argument
Definition at line 36 of file buf_clear.c.
References tag_pcl_buf::data, tag_pcl_buf::len, PCL_EINVAL, pcl_free_safe(), tag_pcl_buf::pos, R_SETERR, and tag_pcl_buf::size.
Referenced by pcl_buf_free().
pcl_buf_copy()
PCL_EXPORT pcl_buf_t* pcl_buf_copy (pcl_buf_t * dest, const pcl_buf_t * src)
#include <pcl/buf.h>
‪Copy a buffer.
Parameters
dest ‪pointer to a buffer or NULL in which case this is allocated.
src ‪pointer to the buffer to copy
Returns
‪pointer to dest or, if dest is NULL, a newly allocated buffer
Definition at line 37 of file buf_copy.c.
References tag_pcl_buf::chrsize, tag_pcl_buf::data, tag_pcl_buf::len, tag_pcl_buf::mode, pcl_buf_init(), PCL_EINVAL, pcl_realloc(), tag_pcl_buf::pos, R_SETERR, and tag_pcl_buf::size.
pcl_buf_free()
PCL_EXPORT pcl_buf_t* pcl_buf_free (pcl_buf_t * b)
#include <pcl/buf.h>
‪Free all buffer resources and the buffer object itself.
Do not pass stack memory to this function. Instead, use pcl_buf_clear.
Parameters
b ‪pointer to a buffer
Returns
‪always NULL
Definition at line 36 of file buf_free.c.
References pcl_buf_clear(), and pcl_free().
Referenced by pcl_err_ctx_free().
pcl_buf_put()
PCL_EXPORT int pcl_buf_put (pcl_buf_t * b, const void * data, int len)
#include <pcl/buf.h>
‪Put a blob into a buffer.
Parameters
b ‪pointer to a buffer
data ‪pointer to the data to write to the buffer
len ‪number of characters to put
Returns
‪number of characters written or -1 on error
Definition at line 36 of file buf_put.c.
References BADARG, tag_pcl_buf::chrsize, tag_pcl_buf::data, tag_pcl_buf::len, pcl_buf_grow(), and tag_pcl_buf::pos.
Referenced by pcl_buf_putchar(), pcl_buf_putint16(), pcl_buf_putint32(), pcl_buf_putint64(), pcl_buf_putint8(), and pcl_buf_putstr().
pcl_buf_putstr()
PCL_EXPORT int pcl_buf_putstr (pcl_buf_t * b, const void * s)
#include <pcl/buf.h>
‪Put a string into a buffer.
Parameters
b ‪pointer to a buffer
s ‪pointer to a string
Returns
‪number of characters written (including NUL if in binary mode) or -1 on error
Definition at line 36 of file buf_putstr.c.
References BADARG, tag_pcl_buf::chrsize, tag_pcl_buf::mode, pcl_buf_put(), and PclBufBinary.
pcl_buf_putchar()
PCL_EXPORT int pcl_buf_putchar (pcl_buf_t * b, uint32_t c)
#include <pcl/buf.h>
‪Put a character into a buffer.
No NUL is added when putting a char.
Parameters
b ‪pointer to a buffer
c ‪character
Returns
‪number of bytes written or -1 on error
Definition at line 35 of file buf_putchar.c.
References BADARG, and pcl_buf_put().
Referenced by ipcl_err_ctx_serialize().
pcl_buf_putint8()
PCL_EXPORT int pcl_buf_putint8 (pcl_buf_t * b, uint8_t i)
#include <pcl/buf.h>
‪Put an 8-bit integer into a buffer.
Note
‪PclBufBinary mode only
Parameters
b ‪pointer to a buffer
i ‪8-bit integer to put
Returns
‪number of bytes written or -1 on error
Definition at line 35 of file buf_putint8.c.
References BADARG, tag_pcl_buf::mode, pcl_buf_put(), and PclBufBinary.
pcl_buf_putint16()
PCL_EXPORT int pcl_buf_putint16 (pcl_buf_t * b, uint16_t i)
#include <pcl/buf.h>
‪Puts a 16-bit integer into a buffer in network-byte order.
Note
‪PclBufBinary mode only
Parameters
b ‪pointer to a buffer
i ‪16-bit integer to put
Returns
‪number of bytes written or -1 on error
Definition at line 36 of file buf_putint16.c.
References BADARG, tag_pcl_buf::mode, pcl_buf_put(), and PclBufBinary.
pcl_buf_putint32()
PCL_EXPORT int pcl_buf_putint32 (pcl_buf_t * b, uint32_t i)
#include <pcl/buf.h>
‪Puts a 32-bit integer into a buffer in network-byte order.
Note
‪PclBufBinary mode only
Parameters
b ‪pointer to a buffer
i ‪32-bit integer to put
Returns
‪number of bytes written or -1 on error
Definition at line 36 of file buf_putint32.c.
References BADARG, tag_pcl_buf::mode, pcl_buf_put(), and PclBufBinary.
pcl_buf_putint64()
PCL_EXPORT int pcl_buf_putint64 (pcl_buf_t * b, uint64_t i)
#include <pcl/buf.h>
‪Puts a 64-bit integer into a buffer in network-byte order.
Note
‪PclBufBinary mode only
Parameters
b ‪pointer to a buffer
i ‪64-bit integer to put
Returns
‪number of bytes written or -1 on error
Definition at line 41 of file buf_putint64.c.
References BADARG, tag_pcl_buf::mode, pcl_buf_put(), and PclBufBinary.
pcl_buf_putf()
PCL_EXPORT int pcl_buf_putf (pcl_buf_t * b, const void * format, ...)
#include <pcl/buf.h>
‪Put a formatted string into a buffer.
Parameters
b ‪pointer to a buffer
format ‪PCL format string. The string must match the buffer mode. PclBufText uses char*, PclBufTextW uses wchar_t* and PclBufTextT uses tchar_t* .
... ‪variable arguments
Returns
‪number of characters written (including NUL if in binary mode) or -1 on error
Definition at line 35 of file buf_putf.c.
References pcl_buf_vputf().
Referenced by ipcl_err_ctx_serialize().
pcl_buf_vputf()
PCL_EXPORT int pcl_buf_vputf (pcl_buf_t * b, const void * format, va_list ap)
#include <pcl/buf.h>
‪Put a formatted string into a buffer.
Parameters
b ‪pointer to a buffer
format ‪PCL format string. The string must match the buffer mode. PclBufText uses char*, PclBufTextW uses wchar_t* and PclBufTextT uses tchar_t* .
ap ‪variable arguments
Returns
‪number of characters written (including NUL if in binary mode) or -1 on error
Definition at line 37 of file buf_vputf.c.
References tag_pcl_buf::chrsize, tag_pcl_buf::data, tag_pcl_buf::len, tag_pcl_buf::mode, pcl_buf_grow(), pcl_vsprintf(), pcl_vswprintf(), PclBufBinary, tag_pcl_buf::pos, SETERR, and tag_pcl_buf::size.
Referenced by ipcl_err_ctx_serialize(), and pcl_buf_putf().
pcl_buf_get()
PCL_EXPORT int pcl_buf_get (pcl_buf_t * b, void * buf, int len)
#include <pcl/buf.h>
‪Get a blob from a buffer.
Note
‪PclBufBinary mode only
Parameters
b ‪pointer to a buffer
[out] buf ‪a buffer used to store the result
len ‪length in bytes of buf if in binary mode, otherwise character length
Returns
‪number of bytes read or -1 on error
Definition at line 36 of file buf_get.c.
References tag_pcl_buf::chrsize, tag_pcl_buf::data, tag_pcl_buf::len, tag_pcl_buf::mode, PCL_EINVAL, PCL_EOF, PclBufBinary, tag_pcl_buf::pos, and SETERR.
Referenced by pcl_buf_getchar(), pcl_buf_getint16(), pcl_buf_getint32(), pcl_buf_getint64(), pcl_buf_getint8(), and pcl_buf_getstr().
pcl_buf_getstr()
PCL_EXPORT int pcl_buf_getstr (pcl_buf_t * b, char * buf, int len)
#include <pcl/buf.h>
‪Get a string from a buffer.
Note
‪PclBufBinary mode only
Parameters
b ‪pointer to a buffer
[out] buf ‪a buffer used to store the result
len ‪length in bytes of buf
Returns
‪number of bytes read (including NUL if in binary mode) or -1 on error
Definition at line 36 of file buf_getstr.c.
References BADARG, tag_pcl_buf::data, tag_pcl_buf::mode, pcl_buf_get(), PCL_EBUF, PclBufBinary, tag_pcl_buf::pos, and SETERR.
pcl_buf_getchar()
PCL_EXPORT int pcl_buf_getchar (pcl_buf_t * b, uint32_t * c)
#include <pcl/buf.h>
‪Get a character from a buffer.
Note
‪PclBufBinary mode only
Parameters
b ‪pointer to a buffer
[out] c ‪pointer to a character
Returns
‪number of bytes read or -1 on error
Definition at line 35 of file buf_getchar.c.
References pcl_buf_get().
pcl_buf_getint8()
PCL_EXPORT int pcl_buf_getint8 (pcl_buf_t * b, uint8_t * i)
#include <pcl/buf.h>
‪Get an 8-bit integer a the buffer.
Note
‪PclBufBinary mode only
Parameters
b ‪pointer to a buffer
[out] i ‪pointer to a 8-bit integer
Returns
‪number of bytes read or -1 on error
Definition at line 35 of file buf_getint8.c.
References BADARG, tag_pcl_buf::mode, pcl_buf_get(), and PclBufBinary.
pcl_buf_getint16()
PCL_EXPORT int pcl_buf_getint16 (pcl_buf_t * b, uint16_t * i)
#include <pcl/buf.h>
‪Get a 16-bit integer from a buffer in host-byte order.
Note
‪PclBufBinary mode only
Parameters
b ‪pointer to a buffer
[out] i ‪pointer to a 16-bit integer
Returns
‪number of bytes read or -1 on error
Definition at line 36 of file buf_getint16.c.
References BADARG, tag_pcl_buf::mode, pcl_buf_get(), PclBufBinary, and TRC.
pcl_buf_getint32()
PCL_EXPORT int pcl_buf_getint32 (pcl_buf_t * b, uint32_t * i)
#include <pcl/buf.h>
‪Get a 32-bit integer from a buffer in host-byte order.
Note
‪PclBufBinary mode only
Parameters
b ‪pointer to a buffer
[out] i ‪pointer to a 32-bit integer
Returns
‪number of bytes read or -1 on error
Definition at line 36 of file buf_getint32.c.
References BADARG, tag_pcl_buf::mode, pcl_buf_get(), PclBufBinary, and TRC.
pcl_buf_getint64()
PCL_EXPORT int pcl_buf_getint64 (pcl_buf_t * b, uint64_t * i)
#include <pcl/buf.h>
‪Get a 64-bit integer from a buffer in host-byte order.
Note
‪PclBufBinary mode only
Parameters
b ‪pointer to a buffer
[out] i ‪pointer to a 64bit integer
Returns
‪number of bytes read or -1 on error
Definition at line 41 of file buf_getint64.c.
References BADARG, tag_pcl_buf::mode, pcl_buf_get(), PclBufBinary, and TRC.