‪libpcl: ‪/Users/andrew/projects/libpcl/src/usrgrp/getuser.c File Reference
getuser.c File Reference
#include "_usrgrp.h"
#include <pcl/error.h>
#include <pcl/string.h>
Functions
int pcl_getuser (const uid_t uid, char *out, size_t len)
Function Documentation
pcl_getuser()
int pcl_getuser (const uid_t uid, char * out, size_t len)
Definition at line 37 of file getuser.c.
References BADARG, ipcl_win32_sid_to_name(), PCL_ENOTFOUND, pcl_strcpy(), SETERR, SETLASTERR, SETOSERR, and TRC.
Referenced by pcl_getgroup().