‪libpcl: ‪/Users/andrew/projects/libpcl/src/ssl/_ssl.h File Reference
_ssl.h File Reference
#include <pcl/ssl.h>
#include <pcl/error.h>
#include <openssl/ssl.h>
Data Structures
struct tag_pcl_ssl
Macros
#define sslerror(_ssl) pcl_ssl_error(_ssl)->msg
Functions
PCL_PRIVATE int ipcl_ssl_configure_socket (pcl_ssl_t *ssl, const char *host, int port)
Macro Definition Documentation
sslerror
#define sslerror (_ssl) pcl_ssl_error(_ssl)->msg
Definition at line 40 of file _ssl.h.
Function Documentation
ipcl_ssl_configure_socket()
PCL_PRIVATE int ipcl_ssl_configure_socket (pcl_ssl_t * ssl, const char * host, int port)
Definition at line 36 of file ssl_configure_socket.c.
References tag_pcl_ssl::flags, PCL_SOCK_NONBLOCK, pcl_socket(), pcl_socket_fd(), pcl_socket_setnonblocking(), PCL_SSL_PASSIVE, tag_pcl_ssl::sock, and TRCMSG.
Referenced by pcl_ssl(), pcl_ssl_accept(), and pcl_ssl_connect().