‪libpcl: ‪Vector
Vector
‪A PCL Vector is a dynamic and contiguous block of memory for an array of same-sized elements.
Data Structures
struct tag_pcl_vector
‪Vector object.
Macros
#define pcl_vector_get(v, pos) ((void *)(((pcl_vector_t *)(v))->elems + ((pos) * ((pcl_vector_t *)(v))->size)))
‪Get an element.
#define pcl_vector_getptr(v, pos) *((void **)pcl_vector_get(v, pos))
‪Dereference an element and return it.
#define pcl_vector_append(v, elem) pcl_vector_insert(v, (const void *)(elem), ((pcl_vector_t *)(v))->count)
‪Append an element.
Typedefs
typedef struct tag_pcl_vector pcl_vector_t
‪Vector object.
typedef void(* pcl_vector_cleanup_t) (pcl_vector_t *v, void *elem)
‪A callback cleanup function for vector elements.
Functions
PCL_EXPORT pcl_vector_t * pcl_vector_init (pcl_vector_t *v, int capacity, size_t elemsize, pcl_vector_cleanup_t cleanup)
‪Initialize a vector.
PCL_EXPORT pcl_vector_t * pcl_vector_create (int capacity, size_t elemsize, pcl_vector_cleanup_t cleanup)
‪Creates a new vector object.
PCL_EXPORT void * pcl_vector_insert (pcl_vector_t *v, const void *elem, int pos)
‪Insert an element.
PCL_EXPORT void * pcl_vector_append_str (pcl_vector_t *v, const char *s)
‪Allocate and append a string.
PCL_EXPORT int pcl_vector_remove (pcl_vector_t *v, int pos)
‪Remove an element.
PCL_EXPORT void * pcl_vector_get_safe (pcl_vector_t *v, int pos)
‪Get an element with bounds checking (safe version of pcl_vector_get).
PCL_EXPORT void * pcl_vector_getptr_safe (pcl_vector_t *v, int pos)
‪Dereference an element with bounds checking and return it.
PCL_EXPORT pcl_vector_t * pcl_vector_compact (pcl_vector_t *v)
‪Compact a vector such that its element capacity matches its element count.
PCL_EXPORT pcl_vector_t * pcl_vector_clear (pcl_vector_t *v)
‪Clear/remove all elements from a vector.
PCL_EXPORT pcl_vector_t * pcl_vector_uninit (pcl_vector_t *v)
‪Release all resources used by a vector.
PCL_EXPORT void pcl_vector_free (pcl_vector_t *v)
‪Release all resources used by a vector as well as the vector itself.
PCL_EXPORT void pcl_vector_cleanup_dblptr (pcl_vector_t *v, void *elem)
‪Built-in element cleanup handler for double pointer elements.
PCL_EXPORT pcl_vector_t * pcl_vector_sort (pcl_vector_t *v, int(*cmp)(const void *, const void *))
‪Sort a vector using qsort.
Detailed Description
A PCL Vector is a dynamic and contiguous block of memory for an array of same-sized elements.
The vector automatically expands this block of memory if an insertion would exceed the vector's current capacity. The vector never automatically shrinks itself during an element removal, but a vector can be shrunk using pcl_vector_compact.
Basic Usage
#include <pcl/init.h>
#include <pcl/vector.h>
#include <stdio.h>
int main(int argc, char **argv)
{
  // always first
  pcl_init();
  // cleanup handler can be NULL, integer doesn't need it
  pcl_vector_t *vec = pcl_vector_create(8, sizeof(int), NULL);
  for(int i=0; i < vec->capacity * 2; i++)
    pcl_vector_append(vec, &i); // vector will have to expand after 8 appends
  for(int i=0; i < vec->count; i++)
  {
    int *elem = pcl_vector_get(vec, i);
    printf("%d\n", *elem); // 0\n1\n...15\n
  }
  pcl_vector_free(vec);
}
Macro Definition Documentation
pcl_vector_get
#define pcl_vector_get (v, pos) ((void *)(((pcl_vector_t *)(v))->elems + ((pos) * ((pcl_vector_t *)(v))->size)))
#include <pcl/vector.h>
‪Get an element.
Warning
‪this provides no bounds checking on pos and is designed to be used in cases where pos is known to be valid: such as a loop constrained by the vector's count. This is an optimization for the most common usage pattern. Expect a core dump or undefined behavior if v or pos is invalid.
Parameters
v ‪pointer to a vector
pos ‪zero-based position of element to retreive
Returns
‪pointer to element at pos
See also
‪pcl_vector_get_safe
Definition at line 136 of file vector.h.
pcl_vector_getptr
#define pcl_vector_getptr (v, pos) *((void **)pcl_vector_get(v, pos))
#include <pcl/vector.h>
‪Dereference an element and return it.
Warning
‪this provides no bounds checking on pos and is designed to be used in cases where pos is known to be valid: such as a loop constrained by the vector's count. This is an optimization for the most common usage pattern. Expect a core dump or undefined behavior if v or pos is invalid.
Parameters
v ‪pointer to a vector
pos ‪zero-based position of element to retreive
Returns
‪pointer to element at pos
See also
‪pcl_vector_getptr_safe
Definition at line 149 of file vector.h.
pcl_vector_append
#define pcl_vector_append (v, elem) pcl_vector_insert(v, (const void *)(elem), ((pcl_vector_t *)(v))->count)
#include <pcl/vector.h>
‪Append an element.
Parameters
v ‪pointer to a vector
elem ‪pointer to an element
Returns
‪pointer to the vector element inserted or NULL on error
Definition at line 156 of file vector.h.
Typedef Documentation
pcl_vector_t
typedef struct tag_pcl_vector pcl_vector_t
#include <pcl/types.h>
‪Vector object.
Used to track elements and grow the internal elements array when required.
Definition at line 60 of file types.h.
pcl_vector_cleanup_t
typedef void(* pcl_vector_cleanup_t) (pcl_vector_t *v, void *elem)
#include <pcl/vector.h>
‪A callback cleanup function for vector elements.
This is needed if the vector elements contain any dynamic memory or the elements are pointers to pointers: such as a vector of strings. When a structure contains allocated members, only free the allocated members – not the structure/element itself. The vector owns the structure. However, if elements are pointers to pointers, you will need to derefence elem and free that pointer.
Note
‪optionally, the pcl_vector_t.cleanup_ptr can be set and utilized within the callback.
Parameters
v ‪pointer to a vector
elem ‪pointer to the element being removed. If elements are pointers to pointers, like strings, remember to dereference: pcl_free(*(char **) elem).
See also
‪pcl_vector_create, pcl_vector_cleanup_dblptr
Definition at line 87 of file vector.h.
Function Documentation
pcl_vector_init()
PCL_EXPORT pcl_vector_t* pcl_vector_init (pcl_vector_t * v, int capacity, size_t elemsize, pcl_vector_cleanup_t cleanup)
#include <pcl/vector.h>
‪Initialize a vector.
This is used internally by pcl_vector_create. This is only useful in cases where caller already has a vector object allocated or caller is using stack memory.
Parameters
v ‪pointer to a vector
capacity ‪initial capacity of the vector as number of elements
elemsize ‪byte size of each element
cleanup ‪element cleanup handler called whenever an element is removed from the vector.
Returns
‪pointer to the v argument
See also
‪pcl_vector_uninit
Definition at line 36 of file vector_init.c.
References tag_pcl_vector::capacity, tag_pcl_vector::cleanup, tag_pcl_vector::cleanup_ptr, tag_pcl_vector::count, tag_pcl_vector::elems, max, pcl_malloc(), and tag_pcl_vector::size.
Referenced by pcl_vector_create().
pcl_vector_create()
PCL_EXPORT pcl_vector_t* pcl_vector_create (int capacity, size_t elemsize, pcl_vector_cleanup_t cleanup)
#include <pcl/vector.h>
‪Creates a new vector object.
Parameters
capacity ‪initial capacity of the vector as number of elements
elemsize ‪byte size of each element
cleanup ‪element cleanup handler called whenever an element is removed from the vector.
Returns
‪an allocated vector object that must be freed by the application
See also
‪pcl_vector_free
Definition at line 36 of file vector_create.c.
References pcl_malloc(), and pcl_vector_init().
Referenced by ipcl_net_resolve(), pcl_htable_keys(), pcl_net_dnstxtrec(), and pcl_ssl_certentry().
pcl_vector_insert()
PCL_EXPORT void* pcl_vector_insert (pcl_vector_t * v, const void * elem, int pos)
#include <pcl/vector.h>
‪Insert an element.
To append an element, set pos to pcl_vector_t.count
Note
‪Starting at elem, pcl_vector_t.size bytes are copied into the vector's internal memory.
Parameters
v ‪pointer to a vector
elem ‪pointer to an element. If this is NULL, a zero'd element is inserted
pos ‪the 0-based position to insert the new element. If this is equal to the pcl_vector_t.count, the element will be appended.
Returns
‪pointer to the element inserted, which is not the same as elem. NULL is returned on error.
Definition at line 37 of file vector_insert.c.
References tag_pcl_vector::capacity, tag_pcl_vector::count, tag_pcl_vector::elems, pcl_realloc(), pcl_vector_get, and tag_pcl_vector::size.
pcl_vector_append_str()
PCL_EXPORT void* pcl_vector_append_str (pcl_vector_t * v, const char * s)
#include <pcl/vector.h>
‪Allocate and append a string.
This function should only be used with string vectors, where the element size was set to the size of a pointer. Elements added with this function will require a pcl_vector_cleanup_t handler.
Example
// identical to: pcl_vector_append_str(vec, "hello")
char *s = pcl_strdup("hello");
pcl_vector_append(vec, &s);
Parameters
v ‪pointer to a vector
s ‪pointer to a string that is internally allocated and then appended to the vector. If this is NULL, a zero'd element is appended.
Returns
‪pointer to the vector element. The returned pointer needs to be dereferenced to get its value. NULL is returned on error. If s is NULL, a valid pointer is returned but dereferencing it will produce a NULL pointer.
See also
‪pcl_vector_cleanup_dblptr
Definition at line 37 of file vector_append_str.c.
References PCL_EINVAL, pcl_strdup(), pcl_vector_append, and R_SETERR.
pcl_vector_remove()
PCL_EXPORT int pcl_vector_remove (pcl_vector_t * v, int pos)
#include <pcl/vector.h>
‪Remove an element.
Parameters
v ‪pointer to a vector
pos ‪a zero-based position of the element to remove
Returns
‪0 for success and -1 on error.
Definition at line 36 of file vector_remove.c.
References tag_pcl_vector::cleanup, tag_pcl_vector::count, pcl_vector_get, and tag_pcl_vector::size.
pcl_vector_get_safe()
PCL_EXPORT void* pcl_vector_get_safe (pcl_vector_t * v, int pos)
#include <pcl/vector.h>
‪Get an element with bounds checking (safe version of pcl_vector_get).
Parameters
v ‪pointer to a vector
pos ‪zero-based position of element to get
Returns
‪pointer to the element or NULL on error
See also
‪pcl_vector_get
Definition at line 36 of file vector_get_s.c.
References PCL_ENOTFOUND, pcl_vector_get, and R_SETERR.
pcl_vector_getptr_safe()
PCL_EXPORT void* pcl_vector_getptr_safe (pcl_vector_t * v, int pos)
#include <pcl/vector.h>
‪Dereference an element with bounds checking and return it.
Parameters
v ‪pointer to a vector
pos ‪zero-based position of element to retreive
Returns
‪pointer to element at pos or NULL on error
See also
‪pcl_vector_getptr
Definition at line 36 of file vector_getptr_s.c.
References PCL_ENOTFOUND, pcl_vector_getptr, and R_SETERR.
pcl_vector_compact()
PCL_EXPORT pcl_vector_t* pcl_vector_compact (pcl_vector_t * v)
#include <pcl/vector.h>
‪Compact a vector such that its element capacity matches its element count.
Parameters
v ‪pointer to a vector
Returns
‪pointer to v argument
Definition at line 36 of file vector_compact.c.
References tag_pcl_vector::capacity, tag_pcl_vector::count, tag_pcl_vector::elems, pcl_realloc(), and tag_pcl_vector::size.
pcl_vector_clear()
PCL_EXPORT pcl_vector_t* pcl_vector_clear (pcl_vector_t * v)
#include <pcl/vector.h>
‪Clear/remove all elements from a vector.
This doesn't adjust the vector's capacity. To adjust its capacity, call pcl_vector_compact after this.
Parameters
v ‪pointer to a vector
Returns
‪pointer to the v argument
See also
‪pcl_vector_compact
Definition at line 35 of file vector_clear.c.
References tag_pcl_vector::cleanup, tag_pcl_vector::count, and pcl_vector_get.
Referenced by pcl_vector_free(), and pcl_vector_uninit().
pcl_vector_uninit()
PCL_EXPORT pcl_vector_t* pcl_vector_uninit (pcl_vector_t * v)
#include <pcl/vector.h>
‪Release all resources used by a vector.
Note
‪This does not free the vector object itself. This function is designed to be used with pcl_vector_init. After this call, the given vector must be reinitialized.
Parameters
v ‪pointer to a vector
Returns
‪pointer to the v argument
See also
‪pcl_vector_init
Definition at line 37 of file vector_uninit.c.
References tag_pcl_vector::elems, pcl_free_safe(), and pcl_vector_clear().
pcl_vector_free()
PCL_EXPORT void pcl_vector_free (pcl_vector_t * v)
#include <pcl/vector.h>
‪Release all resources used by a vector as well as the vector itself.
Parameters
v ‪pointer to a vector that is unusable after this call. If this is NULL, the function silently ignores the request.
See also
‪pcl_vector_create
Definition at line 36 of file vector_free.c.
References tag_pcl_vector::elems, pcl_free_safe(), and pcl_vector_clear().
pcl_vector_cleanup_dblptr()
PCL_EXPORT void pcl_vector_cleanup_dblptr (pcl_vector_t * v, void * elem)
#include <pcl/vector.h>
‪Built-in element cleanup handler for double pointer elements.
This is typically used for pointer tables: like a vector of strings. It will internally dereference an element and pass it to pcl_free
Example
pcl_vector_t *vec = pcl_vector_create(16, sizeof(char **), pcl_vector_cleanup_dblptr);
pcl_vector_append_str(vec, "Hello World");
pcl_vector_remove(vec, 0); // calls pcl_vector_cleanup_dblptr
Parameters
v ‪pointer to a vector
elem ‪pointer to an element
Definition at line 36 of file vector_cleanup_dblptr.c.
References pcl_free_safe(), and UNUSED.
Referenced by ipcl_net_resolve(), pcl_net_dnstxtrec(), and pcl_ssl_certentry().
pcl_vector_sort()
PCL_EXPORT pcl_vector_t* pcl_vector_sort (pcl_vector_t * v, int(*)(const void *, const void *) cmp)
#include <pcl/vector.h>
‪Sort a vector using qsort.
Parameters
v ‪ppointer to a vector
cmp ‪pointer to a function comparator whose behavior is identical to qsort
Returns
‪pointer to the v argument
Definition at line 42 of file vector_qsort.c.
References tag_pcl_vector::count, tag_pcl_vector::elems, and tag_pcl_vector::size.