‪libpcl: ‪Array Management
Array Management
‪An array is a pointer table of allocated elements.
Data Structures
struct tag_pcl_array
Typedefs
typedef void(* pcl_array_cleanup_t) (pcl_array_t *arr, void *elem)
‪Array element cleanup habndler.
Functions
PCL_EXPORT pcl_array_t * pcl_array_create (int initial_capacity, pcl_array_cleanup_t cleanup)
‪Create an array.
PCL_EXPORT void * pcl_array_get (pcl_array_t *arr, int index)
‪Get an element from an array.
PCL_EXPORT int pcl_array_set (pcl_array_t *arr, void *elem, int index)
‪Set an element of an array, replacing a possible existing element.
PCL_EXPORT int pcl_array_add (pcl_array_t *arr, void *elem)
‪Add an element.
PCL_EXPORT int pcl_array_remove (pcl_array_t *arr, int index)
‪Remove an element from an array.
PCL_EXPORT void pcl_array_cleanup_ptr (pcl_array_t *arr, void *elem)
‪An element cleanup callback that passes elem to pcl_free.
PCL_EXPORT void pcl_array_free (pcl_array_t *arr)
‪Free an array.
Detailed Description
An array is a pointer table of allocated elements.
This differs from a PCL vector in that there is no concept of element size. The elements are user allocated pointers that can all be the same type of object, different objects or even NULL. A vector allocates a contiguos block of memory of same size elements, while the array is a pointer table. It is common to interact with an array's elements directly, while this is cumbersome with a vector. A vector can be used like a pointer table, but is a bit awkward because elements must be added as pointers to pointers: element size would be sizeof(void*). Thus, when getting an element from a vector, one must dereference the element value: *(void **)pcl_vector_get(v, 0). The array doesn't allow adding elements in any order like the vector. Adding to an array is always an append operation. However, elements can be replaced via pcl_array_set.
Create argv array
// create an argv array of 4 arguments with a trailing NULL
pcl_array_t *arr = pcl_array_create(5, pcl_array_cleanup_ptr);
pcl_array_add(arr, strdup("-a"));
pcl_array_add(arr, strdup("--quiet"));
pcl_array_add(arr, strdup("--file=\"example/file.txt\""));
pcl_array_add(arr, strdup("-t"));
// replace element 0 with -b, cleanup handler called for element 0
if(something_is_true)
  pcl_array_set(arr, strdup("-b"), 0);
// remove quiet if noisey is true, internally does a cleanup and memmove
if(noisey)
  pcl_array_remove(arr, 1);
// note, any unset element defaults to NULL.
execv("some_program", arr->elements);
pcl_array_free(arr);
Typedef Documentation
pcl_array_cleanup_t
typedef void(* pcl_array_cleanup_t) (pcl_array_t *arr, void *elem)
#include <pcl/array.h>
‪Array element cleanup habndler.
This is used whenever an element is being removed from an array: pcl_array_set, pcl_array_remove and pcl_array_free.
Note
‪NULL elements are never passed to this cleanup
Parameters
arr ‪pointer to an array object
elem ‪pointer to the element to cleanup
Definition at line 85 of file array.h.
Function Documentation
pcl_array_create()
PCL_EXPORT pcl_array_t* pcl_array_create (int initial_capacity, pcl_array_cleanup_t cleanup)
#include <pcl/array.h>
‪Create an array.
Parameters
initial_capacity ‪initial size of array
cleanup ‪pointer to a cleanup routine.
Returns
‪pointer to a new array object
See also
‪pcl_array_cleanup_ptr
Definition at line 36 of file array_create.c.
References tag_pcl_array::capacity, tag_pcl_array::cleanup, tag_pcl_array::count, tag_pcl_array::elements, max, pcl_malloc(), and pcl_zalloc().
Referenced by pcl_htable_keys(), and pcl_json_array().
pcl_array_get()
PCL_EXPORT void* pcl_array_get (pcl_array_t * arr, int index)
#include <pcl/array.h>
‪Get an element from an array.
This is typically not used when iterating over an array, as one can just directly access the element via the elements member. However, this is useful for cases when not looping an array as it performs bounds checking of index.
Parameters
arr ‪pointer to an array object
index ‪element index
Returns
‪pointer to an element or NULL on error. To distinguish between an error and a NULL element, check pcl_errno. It will be PCL_EOKAY if a NULL element.
Definition at line 37 of file array_get.c.
References tag_pcl_array::count, tag_pcl_array::elements, PCL_EINDEX, PCL_EINVAL, pcl_err_clear(), and R_SETERR.
Referenced by pcl_json_array_get().
pcl_array_set()
PCL_EXPORT int pcl_array_set (pcl_array_t * arr, void * elem, int index)
#include <pcl/array.h>
‪Set an element of an array, replacing a possible existing element.
When setting elements, the array's count is not consulted. Instead, this allows a set operation as long as index is less than capacity. This will set count to index + 1 if count is less than index + 1. This is very different than pcl_array_add, which always appends to the array, using count as the next index, and growing the array if required. When performing a set operation, the array is never grown. Thus, trying to set an element at an index greater than or equal to capacity will throw a PCL_EINDEX error.
If an element exists at index, it is removed and passed to the cleanup handler if both the cleanup handler and element are not NULL.
Parameters
arr ‪arr pointer to an array object
elem ‪pointer to an element
index ‪element index
Returns
‪0 for success and -1 on error.
See also
‪pcl_array_add
Definition at line 36 of file array_set.c.
References tag_pcl_array::capacity, tag_pcl_array::cleanup, tag_pcl_array::count, tag_pcl_array::elements, PCL_EINDEX, PCL_EINVAL, and SETERR.
pcl_array_add()
PCL_EXPORT int pcl_array_add (pcl_array_t * arr, void * elem)
#include <pcl/array.h>
‪Add an element.
This is an append operation. The array is grown if required.
Parameters
arr ‪pointer to an array object
elem ‪pointer to an element
Returns
‪the new element count or -1 on error.
See also
‪pcl_array_set
Definition at line 37 of file array_add.c.
References tag_pcl_array::capacity, tag_pcl_array::count, tag_pcl_array::elements, PCL_EINVAL, pcl_realloc(), and SETERR.
Referenced by pcl_htable_keys(), and pcl_json_array_add().
pcl_array_remove()
PCL_EXPORT int pcl_array_remove (pcl_array_t * arr, int index)
#include <pcl/array.h>
‪Remove an element from an array.
This will call the cleanup handler if both the cleanup handler and element at index are not NULL.
Parameters
arr ‪pointer to an array object
index ‪element index
Returns
‪the new count of element or -1 on error.
Definition at line 37 of file array_remove.c.
References tag_pcl_array::cleanup, tag_pcl_array::count, tag_pcl_array::elements, PCL_EINDEX, PCL_EINVAL, and SETERR.
pcl_array_cleanup_ptr()
PCL_EXPORT void pcl_array_cleanup_ptr (pcl_array_t * arr, void * elem)
#include <pcl/array.h>
‪An element cleanup callback that passes elem to pcl_free.
This is a very commonly needed callback. It merely calls pcl_free(elem).
Parameters
arr
elem
Definition at line 36 of file array_cleanup_ptr.c.
References pcl_free_safe(), and UNUSED.
pcl_array_free()
PCL_EXPORT void pcl_array_free (pcl_array_t * arr)
#include <pcl/array.h>
‪Free an array.
This will call the cleanup handler, if not NULL, for all elements that are not NULL and then free the array object.
Parameters
arr ‪pointer to an array object
Definition at line 36 of file array_free.c.
References tag_pcl_array::cleanup, tag_pcl_array::count, tag_pcl_array::elements, and pcl_free().
Referenced by pcl_json_free().