‪libpcl: ‪Process Management
Process Management
‪This module contains functions for managing processes.
Data Structures
struct pcl_proc_exec_t
‪Contains input and output parameters for a call to pcl_proc_exec().
Macros
#define PCL_EXEC_STDIN 0x0001
‪Get a write handle to the spawned process's STDIN.
#define PCL_EXEC_STDIN_NB 0x0002
‪Get a non-blocking write handle to the spawned process's STDIN.
#define PCL_EXEC_STDOUT 0x0004
‪Get a read handle to the spawned process's STDOUT.
#define PCL_EXEC_STDOUT_NB 0x0008
‪Get a non-blocking read handle to the spawned process's STDIN.
#define PCL_EXEC_STDERR 0x0010
‪Get a read handle to the spawned process's STDERR.
#define PCL_EXEC_STDERR_NB 0x0020
‪Get a non-blocking read handle to the spawned process's STDERR.
#define PCL_EXEC_SHELL 0x0040
‪Indicates that the command to exec should be passed to the SHELL.
#define PCL_EXEC_HANDLE 0x0080
‪Get a raw operating system handle to the spawned process.
#define PCL_EXEC_LDPATH 0x0100
‪Sets the library search path within the new process.
#define PRIV_RDFILE _T("SeBackupPrivilege")
‪Grant all read access to files, bypassing access checks.
#define PRIV_WRFILE _T("SeRestorePrivilege")
‪Grant all write access to files, bypassing access checks.
#define PRIV_PROCESS _T("SeDebugPrivilege")
‪Grant all access to processes owned by other accounts.
#define PRIV_MKSYMLINK _T("SeCreateSymbolicLinkPrivilege")
‪Grant the ability to make (create) symbolic links.
Functions
PCL_EXPORT int pcl_proc_exec (pcl_proc_exec_t *exec, int flags)
‪Execute a command within a child process.
PCL_EXPORT int pcl_proc_pipe (pcl_file_t *pipes[2], int rd_oflags, int wr_oflags)
‪Creates a pipe pair of pcl_file_t objects using the given read and write open flags (PCL_O_xxx).
PCL_EXPORT pid_t pcl_proc_self (void)
‪Gets the Process ID of the calling process (PID).
PCL_EXPORT tchar_t * pcl_proc_path (pid_t pid)
‪Get a process's path.
PCL_EXPORT int pcl_proc_setpriv (const tchar_t *priv, bool enable)
‪Enables or disables a process privilege.
PCL_EXPORT void pcl_proc_close (pcl_prochandle_t handle)
‪Close a process handle.
PCL_EXPORT int pcl_proc_parsecmd (const tchar_t *shell_cmd, tchar_t ***out)
‪Converts the given shell command to a valid argv array, which is NULL terminated.
PCL_EXPORT void * pcl_proc_freeargv (int targc, tchar_t **targv)
‪Free an argv array.
PCL_EXPORT tchar_t * pcl_getenv (const tchar_t *name)
‪Get the value of an environment variable.
PCL_EXPORT int pcl_setenv (const tchar_t *name, const tchar_t *value, bool overwrite)
‪Set the value of an environment variable.
PCL_EXPORT int pcl_unsetenv (const tchar_t *name)
‪Unset an environment variable.
Detailed Description
This module contains functions for managing processes.
Macro Definition Documentation
PCL_EXEC_STDIN
#define PCL_EXEC_STDIN 0x0001
#include <pcl/process.h>
‪Get a write handle to the spawned process's STDIN.
The pcl_file_t (handle) is stored in pcl_proc_exec_t.f_stdin and must be closed by the caller after use. If PCL_EXEC_STDIN_NB is also set, this flag is ignored.
See also
‪PCL_EXEC_STDIN_NB
Definition at line 46 of file process.h.
PCL_EXEC_STDIN_NB
#define PCL_EXEC_STDIN_NB 0x0002
#include <pcl/process.h>
‪Get a non-blocking write handle to the spawned process's STDIN.
The pcl_file_t (handle) is stored in pcl_proc_exec_t.f_stdin and must be closed by the caller after use. If this is set, it takes precedence over PCL_EXEC_STDIN.
See also
‪PCL_EXEC_STDIN
Definition at line 53 of file process.h.
PCL_EXEC_STDOUT
#define PCL_EXEC_STDOUT 0x0004
#include <pcl/process.h>
‪Get a read handle to the spawned process's STDOUT.
The pcl_file_t (handle) is stored in pcl_proc_exec_t.f_stdout and must be closed by the caller after use. If PCL_EXEC_STDOUT_NB is also set, this flag is ignored.
See also
‪PCL_EXEC_STDOUT_NB
Definition at line 60 of file process.h.
PCL_EXEC_STDOUT_NB
#define PCL_EXEC_STDOUT_NB 0x0008
#include <pcl/process.h>
‪Get a non-blocking read handle to the spawned process's STDIN.
The pcl_file_t (handle) is stored in pcl_proc_exec_t.f_stdin and must be closed by the caller after use. If this is set, it takes precedence over PCL_EXEC_STDOUT.
See also
‪PCL_EXEC_STDOUT
Definition at line 67 of file process.h.
PCL_EXEC_STDERR
#define PCL_EXEC_STDERR 0x0010
#include <pcl/process.h>
‪Get a read handle to the spawned process's STDERR.
The pcl_file_t (handle) is stored in pcl_proc_exec_t.f_stderr and must be closed by the caller after use. If PCL_EXEC_STDERR_NB is also set, this flag is ignored.
See also
‪PCL_EXEC_STDERR_NB
Definition at line 74 of file process.h.
PCL_EXEC_STDERR_NB
#define PCL_EXEC_STDERR_NB 0x0020
#include <pcl/process.h>
‪Get a non-blocking read handle to the spawned process's STDERR.
The pcl_file_t (handle) is stored in pcl_proc_exec_t.f_stderr and must be closed by the caller after use. If this is set, it takes precedence over PCL_EXEC_STDERR.
See also
‪PCL_EXEC_STDERR
Definition at line 81 of file process.h.
PCL_EXEC_SHELL
#define PCL_EXEC_SHELL 0x0040
#include <pcl/process.h>
‪Indicates that the command to exec should be passed to the SHELL.
On unix, this uses $SHELL -c "your_command" and on windows, this uses COMSPEC% /C "your_command.
This is only required for internal (builtin) commands. These are commands that are built into windows CMD.EXE or the Unix shell: like BASH cd. Thus, you must do cmd.exe /C "command" or sh -c "command" to exec them. This will work for non-built-in commands but incurs an unnecessary shell.
Definition at line 91 of file process.h.
PCL_EXEC_HANDLE
#define PCL_EXEC_HANDLE 0x0080
#include <pcl/process.h>
‪Get a raw operating system handle to the spawned process.
This will be written to pcl_proc_exec_t.handle. It is a windows process HANDLE or a Unix PID. This must be passed to pcl_proc_close when no longer needed. On Unix, the pcl_proc_close doesn't do anything but for cross-platform applications, it should be called to avoid preprocessing.
Definition at line 99 of file process.h.
PCL_EXEC_LDPATH
#define PCL_EXEC_LDPATH 0x0100
#include <pcl/process.h>
‪Sets the library search path within the new process.
The library path is set to the value of pcl_proc_exec_t.ldpath; a colon separated list of paths. On windows colons are replaced for ';' so either can be used.
On Unix, if 'ldpath' is NULL, exec tries pcl_proc_exec_t.cwd and then getcwd. If none of these work, the flag is ignored.
On windows, if pcl_proc_exec_t.ldpath is NULL, pcl_proc_exec ignores this flag (continues) and there are no fallback attempts like on Unix. This is because on windows, the current working directory is already part of the library search path.
pcl_proc_exec_t.ldpath must be NULL for exec to try another one. An empty string is completely valid and can be used to clear the library search path for this new process; but not effect the system-wide search paths.
‪Windows: added to PATH => https://docs.microsoft.com/en-us/cpp/build/search-path-used-by-windows-to-locate-a-dll
‪Linux: added to LD_LIBRARY_PATH
‪Darwin: added to DYLD_LIBRARY_PATH
Definition at line 120 of file process.h.
PRIV_RDFILE
#define PRIV_RDFILE _T("SeBackupPrivilege")
#include <pcl/process.h>
‪Grant all read access to files, bypassing access checks.
Great for backup operations.
See also
‪pcl_proc_setpriv
Definition at line 134 of file process.h.
PRIV_WRFILE
#define PRIV_WRFILE _T("SeRestorePrivilege")
#include <pcl/process.h>
‪Grant all write access to files, bypassing access checks.
Great for restore operations.
See also
‪pcl_proc_setpriv
Definition at line 140 of file process.h.
PRIV_PROCESS
#define PRIV_PROCESS _T("SeDebugPrivilege")
#include <pcl/process.h>
‪Grant all access to processes owned by other accounts.
This is required to use PCL's process list/stat API.
See also
‪pcl_proc_setpriv
Definition at line 146 of file process.h.
PRIV_MKSYMLINK
#define PRIV_MKSYMLINK _T("SeCreateSymbolicLinkPrivilege")
#include <pcl/process.h>
‪Grant the ability to make (create) symbolic links.
See also
‪pcl_proc_setpriv
Definition at line 151 of file process.h.
Function Documentation
pcl_proc_exec()
PCL_EXPORT int pcl_proc_exec (pcl_proc_exec_t * exec, int flags)
#include <pcl/process.h>
‪Execute a command within a child process.
Parameters
exec
flags ‪bitmask of PROC_EXEC_xxx flags
Returns
‪0 on success and -1 on error.
Definition at line 72 of file unix_proc_exec.c.
References _T, BADARG, CLOSE_ALL, CLOSE_FDS, CLOSE_FILES, pcl_proc_exec_t::command, countof, pcl_proc_exec_t::cwd, pcl_proc_exec_t::f_stderr, pcl_proc_exec_t::f_stdin, pcl_proc_exec_t::f_stdout, tag_pcl_file::fd, FREEZE_ERR, pcl_proc_exec_t::group, pcl_proc_exec_t::handle, pcl_proc_exec_t::ldpath, LIBPATH, tag_pcl_time::nsec, PCL_BADFD, pcl_chdir(), PCL_EBADCMD, PCL_EOKAY, pcl_err_fprintf(), pcl_err_os2pcl(), pcl_errno, PCL_EXEC_HANDLE, PCL_EXEC_LDPATH, PCL_EXEC_SHELL, PCL_EXEC_STDERR, PCL_EXEC_STDERR_NB, PCL_EXEC_STDIN, PCL_EXEC_STDIN_NB, PCL_EXEC_STDOUT, PCL_EXEC_STDOUT_NB, pcl_file_close(), pcl_getgid(), pcl_getuid(), pcl_malloc(), PCL_MAXPATH, PCL_O_CLOEXEC, PCL_O_NONBLOCK, pcl_proc_freeargv(), pcl_proc_parsecmd(), pcl_proc_pipe(), pcl_stprintf(), pcl_stristr(), pcl_tcscatf(), pcl_tcscpy(), pcl_tcsdup(), pcl_tcslen(), pcl_tcsskipws(), pcl_time(), pcl_tmalloc(), pcl_tmemcpy(), pcl_proc_exec_t::pid, tag_pcl_time::sec, SETERRMSG, SETLASTERR, pcl_proc_exec_t::start, STDERR_FILENO, STDIN_FILENO, STDOUT_FILENO, strempty, TRC, TRCMSG, pcl_proc_exec_t::user, and zero.
Referenced by pcl_popen().
pcl_proc_pipe()
PCL_EXPORT int pcl_proc_pipe (pcl_file_t * pipes[2], int rd_oflags, int wr_oflags)
#include <pcl/process.h>
‪Creates a pipe pair of pcl_file_t objects using the given read and write open flags (PCL_O_xxx).
Note that unlike the unix pipe2 function, this version allows you to set different flags for both the read and write ends of the pipe. pipes[0]=read and pipes[1]=write. Again, the rd_oflags and wr_oflags are PCL_O_xxx open flags, not POSIX O_xxx flags. PCL_O_RDONLY is automatically added to the rd_oflags and PCL_O_WRONLY to wr_oflags. PCL_O_RDWR is removed if present.
Parameters
pipes ‪a two element array of pcl_file_t pointers. Element 0 is set to the read end of the pipe and element 1 to the write end.
rd_oflags ‪a bitmask of PCL_O_xxx flags for the read end of the pipe
wr_oflags ‪a bitmask of PCL_O_xxx flags for the write end of the pipe
Returns
‪0 on success and -1 on error
Definition at line 41 of file proc_pipe.c.
References ipcl_file_alloc(), ipcl_file_init(), PCL_O_CLOEXEC, PCL_O_NONBLOCK, PCL_O_RDONLY, PCL_O_RDWR, PCL_O_WRONLY, pcl_proc_self(), pcl_rand(), and SETLASTERR.
Referenced by pcl_proc_exec().
pcl_proc_self()
PCL_EXPORT pid_t pcl_proc_self (void)
#include <pcl/process.h>
‪Gets the Process ID of the calling process (PID).
Returns
‪process id
Definition at line 35 of file proc_self.c.
Referenced by pcl_proc_path(), pcl_proc_pipe(), and pcl_proc_setpriv().
pcl_proc_path()
PCL_EXPORT tchar_t* pcl_proc_path (pid_t pid)
#include <pcl/process.h>
‪Get a process's path.
Parameters
pid ‪process id
Returns
‪pointer to the allocated process image path or NULL on error. This value must be freed.
Definition at line 41 of file unix_proc_path.c.
References pcl_proc_self(), pcl_tcsndup(), and R_SETLASTERR.
pcl_proc_setpriv()
PCL_EXPORT int pcl_proc_setpriv (const tchar_t * priv, bool enable)
#include <pcl/process.h>
‪Enables or disables a process privilege.
'priv' can be any privilege defined in winnt.h and supported by LookupPrivilegeValue on windows. Currently, only one of the PRIV_xxx constants are known to PCL if libpcl ever decides to provide functionality for non-Windows based machines.
Parameters
priv ‪privilege name
enable ‪true to enable and false to disable
Returns
‪0 on success and -1 on error. Unix system always return zero and currently provides no functionality.
Definition at line 36 of file proc_setpriv.c.
References pcl_proc_self(), SETLASTERR, and UNUSED.
pcl_proc_close()
PCL_EXPORT void pcl_proc_close (pcl_prochandle_t handle)
#include <pcl/process.h>
‪Close a process handle.
Note
‪this does nothing on unixes.
Parameters
handle ‪wijndows HANDLE and Unix pid.
Definition at line 36 of file proc_close.c.
References UNUSED.
pcl_proc_parsecmd()
PCL_EXPORT int pcl_proc_parsecmd (const tchar_t * shell_cmd, tchar_t *** out)
#include <pcl/process.h>
‪Converts the given shell command to a valid argv array, which is NULL terminated.
Note
‪a blank shell_cmd, will result in zero being returned which could be an error to an application.
Parameters
shell_cmd ‪pointer to the shell command to parse
out ‪pointer to a pointer table to receive the results. Use pcl_proc_freeargv when done with this value.
Returns
‪the number of arguments, exlcuding terminating NULL element, or -1 on error
Definition at line 38 of file proc_parsecmd.c.
References BADARG, PCL_ESYNTAX, pcl_malloc(), pcl_proc_freeargv(), pcl_realloc(), pcl_tcsndup(), pcl_tcsskipws(), and SETERRMSG.
Referenced by pcl_proc_exec().
pcl_proc_freeargv()
PCL_EXPORT void* pcl_proc_freeargv (int targc, tchar_t ** targv)
#include <pcl/process.h>
‪Free an argv array.
Parameters
targc ‪number of arguments (exlcuding trailing NULL element)
targv ‪pointer to an argument array
Returns
‪always returns NULL
See also
‪pcl_proc_parsecmd
Definition at line 36 of file proc_freecmd.c.
References pcl_free_safe().
Referenced by pcl_proc_exec(), and pcl_proc_parsecmd().
pcl_getenv()
PCL_EXPORT tchar_t* pcl_getenv (const tchar_t * name)
#include <pcl/process.h>
‪Get the value of an environment variable.
Parameters
name ‪name of the environment variable
Returns
‪pointer to the environment variable's value. This is an allocated value that must be freed. If name was not found, NULL is returned.
Definition at line 40 of file getenv.c.
References pcl_free(), pcl_malloc(), and pcl_tcsdup().
Referenced by pcl_tmpfile().
pcl_setenv()
PCL_EXPORT int pcl_setenv (const tchar_t * name, const tchar_t * value, bool overwrite)
#include <pcl/process.h>
‪Set the value of an environment variable.
Parameters
name ‪name of the environment variable
value ‪pointer to the value to set
overwrite ‪When true, if name already exists it will be overwritten. If this is false, the value will not be set. If name doesn't exist, this argument is ignored.
Returns
‪o on success and -1 on error
Definition at line 36 of file setenv.c.
References BADARG, SETLASTERR, and strempty.
pcl_unsetenv()
PCL_EXPORT int pcl_unsetenv (const tchar_t * name)
#include <pcl/process.h>
‪Unset an environment variable.
Parameters
name ‪name of the environment variable
Returns
‪o on success and -1 on error
Definition at line 36 of file unsetenv.c.
References BADARG, SETLASTERR, and strempty.