‪libpcl: ‪Events
Events
‪Definitions for managing synchronous events.
Macros
#define PCL_EVENT_INIT 0
‪Passed to a pcl_event_handler_t function to indicate that the PCL library is being initialized.
#define PCL_EVENT_THREADINIT 1
‪Passed to a pcl_event_handler_t function to indicate that a thread is being initialized.
#define PCL_EVENT_USERBASE 10
‪User-defined events should be greater than or equal to this value.
Typedefs
typedef void(* pcl_event_handler_t) (uint32_t event, void *data)
‪Event handler prototype.
Functions
PCL_EXPORT void pcl_event_dispatch (uint32_t event, void *data)
‪Dispatches an event to the calling thread.
PCL_EXPORT void pcl_event_register (pcl_event_handler_t handler)
‪Registers a new event handler.
PCL_EXPORT void pcl_event_unregister (pcl_event_handler_t handler)
‪Unregisters a previously registered event handler.
Detailed Description
Definitions for managing synchronous events.
Macro Definition Documentation
PCL_EVENT_INIT
#define PCL_EVENT_INIT 0
#include <pcl/event.h>
‪Passed to a pcl_event_handler_t function to indicate that the PCL library is being initialized.
Definition at line 44 of file event.h.
PCL_EVENT_THREADINIT
#define PCL_EVENT_THREADINIT 1
#include <pcl/event.h>
‪Passed to a pcl_event_handler_t function to indicate that a thread is being initialized.
This is automatically triggered by pcl_thread_create. If a thread is created by other means, call pcl_event_dispatch manually within the thread start routine.
See also
‪pcl_init_thread
Definition at line 51 of file event.h.
PCL_EVENT_USERBASE
#define PCL_EVENT_USERBASE 10
#include <pcl/event.h>
‪User-defined events should be greater than or equal to this value.
Definition at line 54 of file event.h.
Typedef Documentation
pcl_event_handler_t
typedef void(* pcl_event_handler_t) (uint32_t event, void *data)
#include <pcl/event.h>
‪Event handler prototype.
Parameters
event ‪the event identifier
data ‪optional pointer to event data
Definition at line 64 of file event.h.
Function Documentation
pcl_event_dispatch()
PCL_EXPORT void pcl_event_dispatch (uint32_t event, void * data)
#include <pcl/event.h>
‪Dispatches an event to the calling thread.
Note
‪dispatching is a per-thread synchronous operation. This function won't return until all event handlers have completed.
Parameters
event ‪event id to dispatch. The internal event_handlers ignore all events except PCL_EVENT_INIT and PCL_EVENT_THREADINIT. However, applications can create custom events and respond accordingly.
data ‪event data. PCL_EVENT_INIT and PCL_EVENT_THREADINIT do not use event data
Definition at line 35 of file event_dispatch.c.
References ipcl_event_context_t::count, ipcl_event_context_t::handlers, ipcl_event_context(), and ipcl_event_context_release().
pcl_event_register()
PCL_EXPORT void pcl_event_register (pcl_event_handler_t handler)
#include <pcl/event.h>
‪Registers a new event handler.
Parameters
handler ‪event handler
Definition at line 36 of file event_register.c.
References ipcl_event_context_t::count, ipcl_event_context_t::handlers, ipcl_event_context(), ipcl_event_context_release(), pcl_realloc(), and ipcl_event_context_t::size.
pcl_event_unregister()
PCL_EXPORT void pcl_event_unregister (pcl_event_handler_t handler)
#include <pcl/event.h>
‪Unregisters a previously registered event handler.
Parameters
handler ‪event handler
Definition at line 36 of file event_unregister.c.
References ipcl_event_context_t::count, ipcl_event_context_t::handlers, ipcl_event_context(), and ipcl_event_context_release().