‪libpcl: ‪TCHAR Functions
TCHAR Functions
String Management
‪The pchar_t functions map char or wchar_t string functions.
Functions
size_t pcl_pcslen (const pchar_t *s)
‪Get a string's length.
pchar_t * pcl_pcschr (const pchar_t *s, pchar_t c)
‪Find the first occurance of a character within a string.
pchar_t * pcl_pcsrchr (const pchar_t *s, pchar_t c)
‪Find the last occurance of a character within a string.
pchar_t pcl_topupper (pchar_t c)
‪Uppercase a character.
pchar_t pcl_toplower (pchar_t c)
‪Lowercase a character.
int pcl_pcsfbytes (pchar_t *buf, size_t bufl, uint64_t nbytes, int decimal)
‪Format a number in byte units.
int pcl_pcscmp (const char *a, const char *b)
‪Compare two strings.
int pcl_pcsncmp (const char *a, const char *b, size_t len)
‪Compare two strings.
int pcl_pcsicmp (const pchar_t *a, const pchar_t *b)
‪Compare two strings ignoring case.
int pcl_pcsnicmp (const pchar_t *a, const pchar_t *b, size_t n)
‪Compare two strings ignoring case.
pchar_t * pcl_pcscpy (pchar_t *dest, size_t size, const pchar_t *src)
‪Copy a string.
pchar_t * pcl_pcsncpy (pchar_t *dest, size_t size, const pchar_t *src, size_t len)
‪Copy a portion of a string.
pchar_t * pcl_pcsstr (const pchar_t *haystack, const pchar_t *needle)
‪Find the first occurance of a string within another string.
pchar_t * pcl_pcsistr (const pchar_t *haystack, const pchar_t *needle)
‪Find the first occurance of a string within another string ignoring case.
pchar_t * pcl_pcsdup (const pchar_t *s)
‪Duplicate a string.
pchar_t * pcl_pcsndup (const pchar_t *s, size_t len)
‪Duplicate a portion of a string.
pchar_t * pcl_pcscat (pchar_t *dest, size_t size, const pchar_t *src)
‪Concatenate two strings.
pchar_t * pcl_pcsncat (pchar_t *dest, size_t size, const pchar_t *src, size_t len)
‪Concatenate two strings.
pchar_t * pcl_pcscatf (pchar_t *dest, size_t size, const pchar_t *format,...)
‪Concatenate two strings using a format.
pchar_t * pcl_vpcscatf (pchar_t *dest, size_t size, const pchar_t *format, va_list ap)
‪Concatenate two strings using a format.
pchar_t * pcl_apcscatf (const pchar_t *src, const pchar_t *format,...)
‪Allocate and concatenate two strings using a format.
pchar_t * pcl_vapcscatf (const pchar_t *src, const pchar_t *format, va_list ap)
‪Allocate and concatenate two strings using a format.
pchar_t * pcl_pcstrim (pchar_t *s)
‪Trim whitespace from the front and back of a string.
pchar_t * pcl_pcsltrim (pchar_t *s)
‪Trim whitespace from the front (left) of a string.
pchar_t * pcl_pcsrtrim (pchar_t *s)
‪Trim whitespace from the back (right) of a string.
pchar_t * pcl_pcstrimset (pchar_t *s, const pchar_t *set, bool left, bool right)
‪Trim a set of characters from a string.
pchar_t * pcl_pcsreplace (const pchar_t *subject, const pchar_t *from, const pchar_t *to)
‪Replace all occurances of a search string with a replacement string.
pchar_t * pcl_pcsireplace (const pchar_t *subject, const pchar_t *from, const pchar_t *to)
‪Replace all occurances of a search string with a replacement string ignoring case.
pcl_vector_t * pcl_pcssplit (const pchar_t *s, const pchar_t *delim)
‪Split a string into a vector.
pcl_vector_t * pcl_pcsisplit (const pchar_t *s, const pchar_t *delim)
‪Split a string into a vector ignoring case.
pchar_t * pcl_pcslower (pchar_t *s)
‪Lowercase a string.
pchar_t * pcl_pcsupper (pchar_t *s)
‪Uppercase a string.
pchar_t * pcl_pcstrunc (pchar_t *dest, size_t size, const pchar_t *src)
‪Copy and truncate a string.
pchar_t * pcl_pcsslice (const pchar_t *s, size_t pos, size_t len)
‪Extract a slice of a string.
pchar_t * pcl_pcsrepchr (pchar_t *s, pchar_t oldch, pchar_t newch)
‪Replace all occurance of a character in a string.
pchar_t * pcl_pcsskipws (const pchar_t *s)
‪Skip whitespace.
pchar_t * pcl_pmemcpy (void *dest, const void *src, size_t n)
‪Copy memory area.
pchar_t * pcl_pmemmove (void *dest, const void *src, size_t n)
‪Copy memory area that can overlap.
int pcl_pmemcmp (void *a, void *b, size_t n)
‪Comare memory blocks.
Detailed Description
The pchar_t functions map char or wchar_t string functions.
They are all implemented as macros but documented as functions. This makes the docs as clear as possible in regards to return values, parameters, etc. These functions (macros) will map wchar_t versions on Windows and char versions on Unixes. The wchar_t versions are UTF-16 while the char versions are expected to be UTF-8. The pchar_t versions are prefixed with pcs or include a t in the name (like pcl_topupper). The pcs prefix extends the wcs naming.
Function Documentation
pcl_pcslen()
size_t pcl_pcslen (const pchar_t * s)
#include <pcl/string.h>
‪Get a string's length.
Parameters
s ‪pointer to a string
Returns
‪character length of string
Note
‪implemented as a macro
Referenced by pcl_fdpath(), pcl_getopt(), pcl_pcs_to_utf8(), pcl_proc_exec(), pcl_readdir(), and pcl_tmpfile().
pcl_pcschr()
pchar_t* pcl_pcschr (const pchar_t * s, pchar_t c)
#include <pcl/string.h>
‪Find the first occurance of a character within a string.
Parameters
s ‪pointer to a string
c ‪character to find
Returns
‪first occurance of c within s or NULL if not found
Note
‪implemented as a macro
Referenced by pcl_getopt(), and pcl_mkdirs().
pcl_pcsrchr()
pchar_t* pcl_pcsrchr (const pchar_t * s, pchar_t c)
#include <pcl/string.h>
‪Find the last occurance of a character within a string.
Parameters
s ‪pointer to a string
c ‪character to find
Returns
‪last occurance of c within s or NULL if not found
Note
‪implemented as a macro
Referenced by ipcl_statent().
pcl_topupper()
pchar_t pcl_topupper (pchar_t c)
#include <pcl/string.h>
‪Uppercase a character.
Parameters
c ‪character
Returns
‪uppercase character
Note
‪implemented as a macro
pcl_toplower()
pchar_t pcl_toplower (pchar_t c)
#include <pcl/string.h>
‪Lowercase a character.
Parameters
c ‪character
Returns
‪lowercase character
Note
‪implemented as a macro
pcl_pcsfbytes()
int pcl_pcsfbytes (pchar_t * buf, size_t bufl, uint64_t nbytes, int decimal)
#include <pcl/string.h>
‪Format a number in byte units.
This uses multiples of 1024 and supports the following units: Kibibyte, Mebibyte, Gibibyte, Tebibyte, Pebibyte, Exibyte. The formatted unit is appened to the converted number value as a single uppercase character (no spaces): 10K, 50M, etc. For values less than 1024, no unit is appened; this is just bytes.
Parameters
buf ‪pointer to a buffer to write formatted value
bufl ‪character length of buf
nbytes ‪number of bytes, value to format
decimal ‪number of decimal places to include in the formatted value.
Returns
‪number of character written to buf or -1 on error.
Note
‪implemented as a macro
pcl_pcscmp()
int pcl_pcscmp (const char * a, const char * b)
#include <pcl/string.h>
‪Compare two strings.
Parameters
a ‪pointer to a string
b ‪pointer to a string
Returns
‪an integer less than, equal to or greater than zero if a is found, respectively, to be less than, to match or be greater than b
Note
‪implemented as a macro
Referenced by pcl_getopt(), and pcl_readdir().
pcl_pcsncmp()
int pcl_pcsncmp (const char * a, const char * b, size_t len)
#include <pcl/string.h>
‪Compare two strings.
Parameters
a ‪pointer to a string
b ‪pointer to a string
len ‪number of characters to compare
Returns
‪an integer less than, equal to or greater than zero if a is found, respectively, to be less than, to match or be greater than b
Note
‪implemented as a macro
pcl_pcsicmp()
int pcl_pcsicmp (const pchar_t * a, const pchar_t * b)
#include <pcl/string.h>
‪Compare two strings ignoring case.
Parameters
a ‪pointer to a string
b ‪pointer to a string
Returns
‪an integer less than, equal to or greater than zero if a is found, respectively, to be less than, to match or be greater than b
Note
‪implemented as a macro
pcl_pcsnicmp()
int pcl_pcsnicmp (const pchar_t * a, const pchar_t * b, size_t n)
#include <pcl/string.h>
‪Compare two strings ignoring case.
Parameters
a ‪pointer to a string
b ‪pointer to a string
n ‪compare only the first N bytes
Returns
‪an integer less than, equal to or greater than zero if a is found, respectively, to be less than, to match or be greater than b
Note
‪implemented as a macro
Referenced by pcl_fdpath().
pcl_pcscpy()
pchar_t* pcl_pcscpy (pchar_t * dest, size_t size, const pchar_t * src)
#include <pcl/string.h>
‪Copy a string.
Parameters
dest ‪pointer to a buffer
size ‪character length of dest
src ‪pointer to the string to copy
Returns
‪pointer to dest or NULL on error
Note
‪implemented as a macro
Referenced by pcl_mkdirs(), pcl_proc_exec(), pcl_rmdir_r(), and pcl_sysinfo().
pcl_pcsncpy()
pchar_t* pcl_pcsncpy (pchar_t * dest, size_t size, const pchar_t * src, size_t len)
#include <pcl/string.h>
‪Copy a portion of a string.
Parameters
dest ‪pointer to a buffer
size ‪character length of dest. one byte is always reserved for NUL.
src ‪pointer to the string to copy
len ‪number of characters in src to copy
Returns
‪pointer to dest or NULL on error.
Note
‪implemented as a macro
Referenced by pcl_readdir().
pcl_pcsstr()
pchar_t* pcl_pcsstr (const pchar_t * haystack, const pchar_t * needle)
#include <pcl/string.h>
‪Find the first occurance of a string within another string.
Parameters
haystack ‪pointer to the source string
needle ‪pointer to the search string
Returns
‪pointer to the first occurance of needle within haystack
Note
‪implemented as a macro
pcl_pcsistr()
pchar_t* pcl_pcsistr (const pchar_t * haystack, const pchar_t * needle)
#include <pcl/string.h>
‪Find the first occurance of a string within another string ignoring case.
Parameters
haystack ‪pointer to the source string
needle ‪pointer to the search string
Returns
‪pointer to the first occurance of needle within haystack
Note
‪implemented as a macro
pcl_pcsdup()
pchar_t* pcl_pcsdup (const pchar_t * s)
#include <pcl/string.h>
‪Duplicate a string.
Parameters
s ‪pointer to string
Returns
‪pointer to allocated duplicate
Note
‪implemented as a macro
Referenced by pcl_fdpath(), pcl_getenv(), and pcl_proc_exec().
pcl_pcsndup()
pchar_t* pcl_pcsndup (const pchar_t * s, size_t len)
#include <pcl/string.h>
‪Duplicate a portion of a string.
Parameters
s ‪pointer to string
len ‪number of characters to duplicate
Returns
‪pointer to allocated duplicate
Note
‪implemented as a macro
Referenced by pcl_pcs_to_utf8(), pcl_proc_parsecmd(), and pcl_proc_path().
pcl_pcscat()
pchar_t* pcl_pcscat (pchar_t * dest, size_t size, const pchar_t * src)
#include <pcl/string.h>
‪Concatenate two strings.
Parameters
dest ‪pointer to a buffer
size ‪character length of dest
src ‪pointer to the string to copy
Returns
‪pointer to dest
Note
‪implemented as a macro
pcl_pcsncat()
pchar_t* pcl_pcsncat (pchar_t * dest, size_t size, const pchar_t * src, size_t len)
#include <pcl/string.h>
‪Concatenate two strings.
Parameters
dest ‪pointer to a buffer to append to
size ‪character length of dest
src ‪pointer to the string to copy
len ‪character length of src to copy
Returns
‪pointer to dest
Note
‪implemented as a macro
pcl_pcscatf()
pchar_t* pcl_pcscatf (pchar_t * dest, size_t size, const pchar_t * format, ...)
#include <pcl/string.h>
‪Concatenate two strings using a format.
Parameters
dest ‪pointer to a buffer to append to
size ‪character length of dest
format ‪printf-style format string
... ‪variable arguments
Returns
‪pointer to dest
Note
‪implemented as a macro
Referenced by pcl_proc_exec().
pcl_vpcscatf()
pchar_t* pcl_vpcscatf (pchar_t * dest, size_t size, const pchar_t * format, va_list ap)
#include <pcl/string.h>
‪Concatenate two strings using a format.
Parameters
dest ‪pointer to a buffer to append to
size ‪character length of dest
format ‪printf-style format string
ap ‪variable argument list
Returns
‪pointer to dest
Note
‪implemented as a macro
pcl_apcscatf()
pchar_t* pcl_apcscatf (const pchar_t * src, const pchar_t * format, ...)
#include <pcl/string.h>
‪Allocate and concatenate two strings using a format.
Parameters
src ‪pointer to a string to to use as the first set of characters. This can be NULL.
format ‪printf-style format string
... ‪variable arguments
Returns
‪pointer to an allocated string starting with src, if not NULL, and ending with the formatted results.
Note
‪implemented as a macro
pcl_vapcscatf()
pchar_t* pcl_vapcscatf (const pchar_t * src, const pchar_t * format, va_list ap)
#include <pcl/string.h>
‪Allocate and concatenate two strings using a format.
Parameters
src ‪pointer to a string to use as the first set of characters. This can be NULL.
format ‪printf-style format string
ap ‪variable argument list
Returns
‪pointer to an allocated string starting with src, if not NULL, and ending with the formatted results.
Note
‪implemented as a macro
pcl_pcstrim()
pchar_t* pcl_pcstrim (pchar_t * s)
#include <pcl/string.h>
‪Trim whitespace from the front and back of a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to the s argument
Note
‪implemented as a macro
pcl_pcsltrim()
pchar_t* pcl_pcsltrim (pchar_t * s)
#include <pcl/string.h>
‪Trim whitespace from the front (left) of a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to the s argument
Note
‪implemented as a macro
pcl_pcsrtrim()
pchar_t* pcl_pcsrtrim (pchar_t * s)
#include <pcl/string.h>
‪Trim whitespace from the back (right) of a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to the s argument
Note
‪implemented as a macro
pcl_pcstrimset()
pchar_t* pcl_pcstrimset (pchar_t * s, const pchar_t * set, bool left, bool right)
#include <pcl/string.h>
‪Trim a set of characters from a string.
Parameters
s ‪pointer to a string
set ‪a set of characters (as a string) to trim. If this is NULL, a default set is used: " \t\n\v\f\r"
left ‪true to trim from the front (left) of s
right ‪true to trim from the back (right) of s
Returns
‪pointer to s
Note
‪implemented as a macro
pcl_pcsreplace()
pchar_t* pcl_pcsreplace (const pchar_t * subject, const pchar_t * from, const pchar_t * to)
#include <pcl/string.h>
‪Replace all occurances of a search string with a replacement string.
Parameters
subject ‪pointer to source string
from ‪pointer to the search string within subject
to ‪pointer to the replacement string
Returns
‪an allocated string with all occurances of from replaced with to
Note
‪implemented as a macro
pcl_pcsireplace()
pchar_t* pcl_pcsireplace (const pchar_t * subject, const pchar_t * from, const pchar_t * to)
#include <pcl/string.h>
‪Replace all occurances of a search string with a replacement string ignoring case.
Parameters
subject ‪pointer to source string
from ‪pointer to the search string within subject
to ‪pointer to the replacement string
Returns
‪an allocated string with all occurances of from replaced with to
Note
‪implemented as a macro
pcl_pcssplit()
pcl_vector_t* pcl_pcssplit (const pchar_t * s, const pchar_t * delim)
#include <pcl/string.h>
‪Split a string into a vector.
Parameters
s ‪pointer to a string
delim ‪pointer to a delimiter to split on
Returns
‪pointer to a vector containing the split parts. The delimiter string is never included in part elements.
Note
‪implemented as a macro
pcl_pcsisplit()
pcl_vector_t* pcl_pcsisplit (const pchar_t * s, const pchar_t * delim)
#include <pcl/string.h>
‪Split a string into a vector ignoring case.
Parameters
s ‪pointer to a string
delim ‪pointer to a delimiter to split on
Returns
‪pointer to a vector containing the split parts. The delimiter string is never included in part elements.
Note
‪implemented as a macro
pcl_pcslower()
pchar_t* pcl_pcslower (pchar_t * s)
#include <pcl/string.h>
‪Lowercase a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to s in lowercase
Note
‪implemented as a macro
pcl_pcsupper()
pchar_t* pcl_pcsupper (pchar_t * s)
#include <pcl/string.h>
‪Uppercase a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to s in uppercase
Note
‪implemented as a macro
pcl_pcstrunc()
pchar_t* pcl_pcstrunc (pchar_t * dest, size_t size, const pchar_t * src)
#include <pcl/string.h>
‪Copy and truncate a string.
This will copy as much as possible. If dest is not large enough, this will truncate src to fit within dest.
Parameters
dest ‪pointer to a buffer. if src can't fit, truncate
size ‪character count of dest
src ‪pointer to string to copy
Returns
‪pointer to dest
Note
‪implemented as a macro
pcl_pcsslice()
pchar_t* pcl_pcsslice (const pchar_t * s, size_t pos, size_t len)
#include <pcl/string.h>
‪Extract a slice of a string.
This is also known as substr.
Parameters
s ‪pointer to a string
pos ‪starting character position
len ‪number of characters to extract
Returns
‪pointer to an allocated slice of s
Note
‪implemented as a macro
pcl_pcsrepchr()
pchar_t* pcl_pcsrepchr (pchar_t * s, pchar_t oldch, pchar_t newch)
#include <pcl/string.h>
‪Replace all occurance of a character in a string.
Parameters
s ‪pointer to a string
oldch ‪search character
newch ‪replacement character
Returns
‪pointer to s argument
Note
‪implemented as a macro
pcl_pcsskipws()
pchar_t* pcl_pcsskipws (const pchar_t * s)
#include <pcl/string.h>
‪Skip whitespace.
Parameters
s ‪pointer to a string
Returns
‪pointer to the first character in s that is not a whitespace character.
Note
‪implemented as a macro
Referenced by pcl_proc_exec(), and pcl_proc_parsecmd().
pcl_pmemcpy()
pchar_t* pcl_pmemcpy (void * dest, const void * src, size_t n)
#include <pcl/string.h>
‪Copy memory area.
Parameters
dest ‪pointer to the copy destination
src ‪pointer to the source data
n ‪number of pchar_t characters to copy
Returns
‪pointer to dest
Note
‪implemented as a macro
Referenced by pcl_proc_exec().
pcl_pmemmove()
pchar_t* pcl_pmemmove (void * dest, const void * src, size_t n)
#include <pcl/string.h>
‪Copy memory area that can overlap.
Parameters
dest ‪pointer to the copy destination
src ‪pointer to the source data
n ‪number of pchar_t characters to copy
Returns
‪pointer to dest
Note
‪implemented as a macro
pcl_pmemcmp()
int pcl_pmemcmp (void * a, void * b, size_t n)
#include <pcl/string.h>
‪Comare memory blocks.
Parameters
a ‪pointer to memory block
b ‪pointer to memory block
n ‪number of pchar_t characters to compare
Returns
‪an integer less than, equal to or greater than zero if a is found, respectively, to be less than, to match or be greater than b
Referenced by pcl_getopt().