‪libpcl: ‪/Users/andrew/projects/libpcl/src/win32/win32_sd_get.c File Reference
win32_sd_get.c File Reference
#include "_win32.h"
#include <pcl/alloc.h>
Functions
SECURITY_DESCRIPTOR * sd_get (const pchar_t *path, DWORD *len, int sec_info)
int ipcl_win32_sd_get (const pchar_t *path, SECURITY_DESCRIPTOR **sd, DWORD *sdlen, PSID *world_sid, PSID *owner_sid, PSID *group_sid, BOOL *have_dacl, PACL *dacl, SECURITY_INFORMATION secinfo)
‪Get the SECURITY_DESCRIPTOR for the given path.
Function Documentation
sd_get()
SECURITY_DESCRIPTOR* sd_get (const pchar_t * path, DWORD * len, int sec_info)
Definition at line 36 of file win32_sd_get.c.
References pcl_free(), pcl_malloc(), and R_SETLASTERR.
Referenced by ipcl_win32_sd_get().
ipcl_win32_sd_get()
int ipcl_win32_sd_get (const pchar_t * path, SECURITY_DESCRIPTOR ** sd, DWORD * sdlen, PSID * world_sid, PSID * owner_sid, PSID * group_sid, BOOL * have_dacl, PACL * dacl, SECURITY_INFORMATION secinfo)
‪Get the SECURITY_DESCRIPTOR for the given path.
Parameters
[in] path
[out] sd ‪a pointer to a security descriptor pointer to receive an allocated self-relative descriptor for the given path. Caller must free this with pcl_free.
sdlen
world_sid ‪optional pointer to an allocated SID that must be passed to FreeSid.
owner_sid ‪optional pointer to the owner sid. This memory is owned by the security descriptor and must not passed to a free function.
group_sid ‪optional pointer to the group sid. This memory is owned by the security descriptor and must not passed to a free function.
have_dacl ‪optional pointer to a BOOL that indicates if the security descriptor has a DACL.
dacl ‪optional pointer to a DACL. This memory is owned by the security descriptor and must not passed to a free function.
secinfo ‪bit mask that indicates what security information is desired. See the WinAPI GetKernelObjectSecurity function.
Returns
‪0 for success and -1 on error. If this fails, no output arguments are valid.
Definition at line 74 of file win32_sd_get.c.
References ipcl_win32_world_sid(), pcl_free(), sd_get(), SETLASTERR, and TRC.
Referenced by ipcl_win32_file_security().