‪libpcl: ‪/Users/andrew/projects/libpcl/src/win32/win32_process_sid.c File Reference
win32_process_sid.c File Reference
#include "_win32.h"
#include <pcl/alloc.h>
Functions
PSID ipcl_win32_process_sid (void)
‪Get TokenUser SID of process.
Function Documentation
ipcl_win32_process_sid()
PSID ipcl_win32_process_sid (void)
‪Get TokenUser SID of process.
Returns
‪application must free this
Definition at line 36 of file win32_process_sid.c.
References ipcl_win32_process_token(), ipcl_win32_sid_dup(), ipcl_win32_token_into(), pcl_free(), and TRC.