‪libpcl: ‪JSON Parser
JSON Parser
‪A JSON parser.
Data Structures
struct tag_pcl_json
Macros
#define PCL_JSON_SKIPUTF8CHK 0x01
‪Skip UTF-8 validation.
#define PCL_JSON_SHALLOW 0x02
‪Shallow copy string.
#define PCL_JSON_EMPTYASNULL 0x04
‪Empty strings will be encoded as a JSON null.
#define PCL_JSON_ALLOWNULL 0x08
‪A NULL string will not raise an error, but rather encode value as a JSON null.
#define PCL_JSON_FREEVALONERR 0x10
‪When adding json objects to collections, if the add operation fails this flags will free the value being added.
#define pcl_json_isnull(_j) ((_j) ? (_j)->type == 0 : false)
#define pcl_json_isboolean(_j) ((_j) ? (_j)->type == 'b' : false)
#define pcl_json_istrue(_j) ((_j) ? pcl_json_isboolean(_j) && (_j)->boolean : false)
#define pcl_json_isfalse(_j) ((_j) ? pcl_json_isboolean(_j) && !(_j)->boolean : false)
#define pcl_json_isreal(_j) ((_j) ? (_j)->type == 'r' : false)
#define pcl_json_isinteger(_j) ((_j) ? (_j)->type == 'i' : false)
#define pcl_json_isnumber(_j) (pcl_json_isreal(_j) || pcl_json_isinteger(_j))
#define pcl_json_isstring(_j) ((_j) ? (_j)->type == 's' : false)
#define pcl_json_isarray(_j) ((_j) ? (_j)->type == 'a' : false)
#define pcl_json_isobject(_j) ((_j) ? (_j)->type == 'o' : false)
Functions
PCL_EXPORT pcl_json_t * pcl_json_decode (const char *json, size_t len, const char **end)
‪Decode a JSON string.
PCL_EXPORT char * pcl_json_encode (pcl_json_t *value, bool format)
PCL_EXPORT void pcl_json_free (pcl_json_t *j)
PCL_EXPORT pcl_json_t * pcl_json_object (void)
‪Create an object.
PCL_EXPORT int pcl_json_object_put (pcl_json_t *obj, char *key, pcl_json_t *value, uint32_t flags)
PCL_EXPORT pcl_json_t * pcl_json_object_get (pcl_json_t *obj, const char *key)
PCL_EXPORT pcl_json_t * pcl_json_array (void)
‪Create an array object.
PCL_EXPORT int pcl_json_array_add (pcl_json_t *arr, pcl_json_t *elem, uint32_t flags)
‪Add an element to an array.
PCL_EXPORT pcl_json_t * pcl_json_array_get (pcl_json_t *arr, int index)
PCL_EXPORT pcl_json_t * pcl_json_string (char *str, uint32_t flags)
‪Create a string.
PCL_EXPORT pcl_json_t * pcl_json_string_len (const char *str, size_t len, uint32_t flags)
‪Create a string.
PCL_EXPORT pcl_json_t * pcl_json_boolean (bool value)
‪Create a boolean.
PCL_EXPORT pcl_json_t * pcl_json_true (void)
PCL_EXPORT pcl_json_t * pcl_json_false (void)
PCL_EXPORT pcl_json_t * pcl_json_null (void)
PCL_EXPORT pcl_json_t * pcl_json_real (double real)
PCL_EXPORT pcl_json_t * pcl_json_integer (long long integer)
Detailed Description
A JSON parser.
Macro Definition Documentation
PCL_JSON_SKIPUTF8CHK
#define PCL_JSON_SKIPUTF8CHK 0x01
#include <pcl/json.h>
‪Skip UTF-8 validation.
Only set this flag if you know for sure a string is valid UTF-8. Otherwise, you can end up with an invalid JSON document that will be rejected by parsers outside of PCL.
See also
‪pcl_json_string, pcl_json_string_len
Definition at line 46 of file json.h.
PCL_JSON_SHALLOW
#define PCL_JSON_SHALLOW 0x02
#include <pcl/json.h>
‪Shallow copy string.
By default, pcl_json_string makes a copy of the provided string. Setting this flag avoids the copy and the PCL json module will manage the pointer.
See also
‪pcl_json_string
Definition at line 52 of file json.h.
PCL_JSON_EMPTYASNULL
#define PCL_JSON_EMPTYASNULL 0x04
#include <pcl/json.h>
‪Empty strings will be encoded as a JSON null.
See also
‪pcl_json_string, pcl_json_string_len
Definition at line 57 of file json.h.
PCL_JSON_ALLOWNULL
#define PCL_JSON_ALLOWNULL 0x08
#include <pcl/json.h>
‪A NULL string will not raise an error, but rather encode value as a JSON null.
See also
‪pcl_json_string, pcl_json_string_len
Definition at line 62 of file json.h.
PCL_JSON_FREEVALONERR
#define PCL_JSON_FREEVALONERR 0x10
#include <pcl/json.h>
‪When adding json objects to collections, if the add operation fails this flags will free the value being added.
pcl_json_t *val = pcl_json_integer(10);
// NULL key will force an error, this will free 'val'
pcl_json_object_put(obj, NULL, val, PCL_JSON_FREEVALONERR);
// identical to
if(pcl_json_object_put(obj, NULL, val, 0) < 0)
  pcl_json_free(val);
See also
‪pcl_json_object_put, pcl_json_array_add
Definition at line 79 of file json.h.
pcl_json_isnull
#define pcl_json_isnull (_j) ((_j) ? (_j)->type == 0 : false)
#include <pcl/json.h>
Definition at line 85 of file json.h.
pcl_json_isboolean
#define pcl_json_isboolean (_j) ((_j) ? (_j)->type == 'b' : false)
#include <pcl/json.h>
Definition at line 86 of file json.h.
pcl_json_istrue
#define pcl_json_istrue (_j) ((_j) ? pcl_json_isboolean(_j) && (_j)->boolean : false)
#include <pcl/json.h>
Definition at line 87 of file json.h.
pcl_json_isfalse
#define pcl_json_isfalse (_j) ((_j) ? pcl_json_isboolean(_j) && !(_j)->boolean : false)
#include <pcl/json.h>
Definition at line 88 of file json.h.
pcl_json_isreal
#define pcl_json_isreal (_j) ((_j) ? (_j)->type == 'r' : false)
#include <pcl/json.h>
Definition at line 89 of file json.h.
pcl_json_isinteger
#define pcl_json_isinteger (_j) ((_j) ? (_j)->type == 'i' : false)
#include <pcl/json.h>
Definition at line 90 of file json.h.
pcl_json_isnumber
#define pcl_json_isnumber (_j) (pcl_json_isreal(_j) || pcl_json_isinteger(_j))
#include <pcl/json.h>
Definition at line 91 of file json.h.
pcl_json_isstring
#define pcl_json_isstring (_j) ((_j) ? (_j)->type == 's' : false)
#include <pcl/json.h>
Definition at line 92 of file json.h.
pcl_json_isarray
#define pcl_json_isarray (_j) ((_j) ? (_j)->type == 'a' : false)
#include <pcl/json.h>
Definition at line 93 of file json.h.
pcl_json_isobject
#define pcl_json_isobject (_j) ((_j) ? (_j)->type == 'o' : false)
#include <pcl/json.h>
Definition at line 94 of file json.h.
Function Documentation
pcl_json_decode()
PCL_EXPORT pcl_json_t* pcl_json_decode (const char * json, size_t len, const char ** end)
#include <pcl/json.h>
‪Decode a JSON string.
This parses a JSON string that represents a single JSON value. A JSON value can be an object {}, array [], string "", number -102.84, boolean true or false or a null null. Parsing stops when the parsing of the JSON value at json is complete, regardless of the len argument. However, if a complete JSON value is not found before reaching json + len, an error occurs. The json string can contain bogus data after the value being parsed, since the parser stops at the end of the value. For example:
{
  "name": "Henry Ford"
}#invalid json here
The above is completely valid, since a valid JSON object exists and ends before any invalid JSON text is encountered. When the end argument is supplied, it would be pointing at the '#' in the above example. This is very useful if a string contains multiple JSON values. pcl_json_decode can be called a multiple times passing the value of end as json, allowing one to iterate through a series of json values.
Parameters
json ‪pointer to a json string. This must be NUL terminated if len is 0.
len ‪number of bytes within json argument. If 0, json must be NUL terminated.
end ‪pointer to the first character not parsed. This can be NULL.
Returns
‪pointer to a json value or NULL on error
Definition at line 37 of file json_decode.c.
References ipcl_json_state_t::ctx, ipcl_json_state_t::end, ipcl_json_parse_value(), ipcl_json_state_t::line, min, ipcl_json_state_t::next, PCL_EINVAL, R_SETERR, R_SETERRMSG, and R_TRCMSG.
pcl_json_encode()
PCL_EXPORT char* pcl_json_encode (pcl_json_t * value, bool format)
#include <pcl/json.h>
Definition at line 37 of file json_encode.c.
References ipcl_json_encode_t::b, tag_pcl_buf::data, ipcl_json_encode_t::format, ipcl_json_encode_value(), pcl_buf_clear(), pcl_buf_init(), PclBufText, and ipcl_json_encode_t::tabs.
pcl_json_free()
PCL_EXPORT void pcl_json_free (pcl_json_t * j)
#include <pcl/json.h>
Definition at line 38 of file json_free.c.
References tag_pcl_json::array, tag_pcl_json::object, pcl_array_free(), pcl_free(), pcl_free_safe(), pcl_htable_free(), pcl_json_false(), pcl_json_null(), pcl_json_true(), tag_pcl_json::string, and tag_pcl_json::type.
Referenced by ipcl_json_parse_array(), ipcl_json_parse_object(), pcl_err_vjson(), pcl_json_array_add(), and pcl_json_object_put().
pcl_json_object()
PCL_EXPORT pcl_json_t* pcl_json_object (void)
#include <pcl/json.h>
‪Create an object.
It is safe to use the hash table module for managing a JSON object. Internally, a json object is backed by a pcl_htable_t. For a given pcl_json_t, ensure the type member is 'o' and then use json->object with the htable functions. However, do not use pcl_htable_free.
Returns
‪pointer to a json object of type object
Definition at line 45 of file json_object.c.
References tag_pcl_json::object, pcl_htable_create(), pcl_malloc(), tag_pcl_htable::remove_entry, and tag_pcl_json::type.
Referenced by ipcl_json_parse_object(), and pcl_err_vjson().
pcl_json_object_put()
PCL_EXPORT int pcl_json_object_put (pcl_json_t * obj, char * key, pcl_json_t * value, uint32_t flags)
#include <pcl/json.h>
Definition at line 38 of file json_object_put.c.
References BADARG, ipcl_json_utf8check(), tag_pcl_json::object, PCL_ETYPE, pcl_free(), pcl_htable_put(), pcl_json_free(), PCL_JSON_FREEVALONERR, pcl_json_isobject, PCL_JSON_SHALLOW, PCL_JSON_SKIPUTF8CHK, pcl_strdup(), SETERRMSG, TRC, TRCMSG, and tag_pcl_json::type.
Referenced by ipcl_json_parse_object(), and pcl_err_vjson().
pcl_json_object_get()
PCL_EXPORT pcl_json_t* pcl_json_object_get (pcl_json_t * obj, const char * key)
#include <pcl/json.h>
Definition at line 36 of file json_object_get.c.
References tag_pcl_json::object, PCL_EINVAL, pcl_errno, PCL_ETYPE, pcl_htable_get(), pcl_json_isobject, R_SETERR, R_SETERRMSG, R_TRC, and tag_pcl_json::type.
pcl_json_array()
PCL_EXPORT pcl_json_t* pcl_json_array (void)
#include <pcl/json.h>
‪Create an array object.
It is safe to use the array module for managing a JSON array. Internally, a json array is backed by a pcl_array_t. For a given pcl_json_t, ensure the type member is 'a' and then use json->array with the array functions. However, do not use pcl_array_free.
Returns
‪pointer to a json object of type array
Definition at line 44 of file json_array.c.
References tag_pcl_json::array, pcl_array_create(), pcl_malloc(), and tag_pcl_json::type.
Referenced by ipcl_json_parse_array(), and pcl_err_vjson().
pcl_json_array_add()
PCL_EXPORT int pcl_json_array_add (pcl_json_t * arr, pcl_json_t * elem, uint32_t flags)
#include <pcl/json.h>
‪Add an element to an array.
Parameters
arr
elem
Returns
‪new element count on success and -1 on error
Definition at line 36 of file json_array_add.c.
References tag_pcl_json::array, BADARG, tag_pcl_array::count, pcl_array_add(), PCL_ETYPE, pcl_json_free(), PCL_JSON_FREEVALONERR, pcl_json_isarray, SETERRMSG, TRCMSG, and tag_pcl_json::type.
Referenced by ipcl_json_parse_array(), and pcl_err_vjson().
pcl_json_array_get()
PCL_EXPORT pcl_json_t* pcl_json_array_get (pcl_json_t * arr, int index)
#include <pcl/json.h>
Parameters
arr
index
Returns
Definition at line 36 of file json_array_get.c.
References tag_pcl_json::array, pcl_array_get(), PCL_EINVAL, PCL_ETYPE, pcl_json_isarray, R_SETERR, R_SETERRMSG, R_TRC, and tag_pcl_json::type.
pcl_json_string()
PCL_EXPORT pcl_json_t* pcl_json_string (char * str, uint32_t flags)
#include <pcl/json.h>
‪Create a string.
Parameters
str ‪pointer to a NUL-terminated string
flags ‪a bitmask of flags. If PCL_JSON_SKIPUTF8CHK is set, no UTF-8 validation is performed. If PCL_JSON_SHALLOW is set, a direct pointer to str is stored: ie. no copy. If PCL_JSON_SHALLOW is not set, str is copied. Note that if PCL_JSON_EMPTYASNULL and PCL_JSON_SHALLOW are both set and str is empty, caller is still repsonsible to free the empty string. This is because the json module isn't managing it. For this reason, one should avoid setting both of these flags. If PCL_JSON_EMPTYASNULL, then an empty str will cause a json null object to be returned. If PCL_JSON_ALLOWNULL is set, if str is NULL, a json null object will be returned.
Returns
‪pointer to a json object or NULL on error. Note that a NULL str is an error unless PCL_JSON_ALLOWNULL is set.
See also
‪pcl_json_string_len
Definition at line 37 of file json_string.c.
References ipcl_json_utf8check(), PCL_EINVAL, PCL_JSON_ALLOWNULL, PCL_JSON_EMPTYASNULL, pcl_json_null(), PCL_JSON_SHALLOW, PCL_JSON_SKIPUTF8CHK, pcl_malloc(), pcl_strndup(), R_SETERR, R_TRC, tag_pcl_json::string, and tag_pcl_json::type.
Referenced by ipcl_json_parse_value(), and pcl_err_vjson().
pcl_json_string_len()
PCL_EXPORT pcl_json_t* pcl_json_string_len (const char * str, size_t len, uint32_t flags)
#include <pcl/json.h>
‪Create a string.
Note
‪this function always copies len characters of the given str
Parameters
str ‪pointer to string, which does not need to be NUL-terminated
len ‪number of characters to copy from str
flags ‪bitmask of flags. PCL_JSON_SHALLOW is not supported. If PCL_JSON_SKIPUTF8CHK is set, no UTF-8 validation is performed. If PCL_JSON_EMPTYASNULL, then a len of zero will cause a json null object to be returned. If PCL_JSON_ALLOWNULL is set, if str is NULL, a json null object will be returned.
Returns
‪pointer to a json object or NULL on error. Note that a NULL str is an error unless PCL_JSON_ALLOWNULL is set.
See also
‪pcl_json_string
Definition at line 37 of file json_string_len.c.
References ipcl_json_utf8check(), PCL_EINVAL, PCL_JSON_ALLOWNULL, PCL_JSON_EMPTYASNULL, pcl_json_null(), PCL_JSON_SKIPUTF8CHK, pcl_malloc(), pcl_strndup(), R_SETERR, R_TRC, tag_pcl_json::string, and tag_pcl_json::type.
pcl_json_boolean()
PCL_EXPORT pcl_json_t* pcl_json_boolean (bool value)
#include <pcl/json.h>
‪Create a boolean.
Parameters
value
Returns
Definition at line 36 of file json_boolean.c.
References pcl_json_false(), and pcl_json_true().
pcl_json_true()
PCL_EXPORT pcl_json_t* pcl_json_true (void)
#include <pcl/json.h>
Definition at line 35 of file json_true.c.
References tag_pcl_json::type.
Referenced by ipcl_json_parse_value(), pcl_json_boolean(), and pcl_json_free().
pcl_json_false()
PCL_EXPORT pcl_json_t* pcl_json_false (void)
#include <pcl/json.h>
Definition at line 35 of file json_false.c.
References tag_pcl_json::type.
Referenced by ipcl_json_parse_value(), pcl_json_boolean(), and pcl_json_free().
pcl_json_null()
PCL_EXPORT pcl_json_t* pcl_json_null (void)
#include <pcl/json.h>
Definition at line 36 of file json_null.c.
References tag_pcl_json::type.
Referenced by ipcl_json_parse_value(), pcl_json_free(), pcl_json_string(), and pcl_json_string_len().
pcl_json_real()
PCL_EXPORT pcl_json_t* pcl_json_real (double real)
#include <pcl/json.h>
Definition at line 37 of file json_real.c.
References PCL_EINVAL, pcl_malloc(), R_SETERRMSG, tag_pcl_json::real, and tag_pcl_json::type.
Referenced by ipcl_json_parse_number().
pcl_json_integer()
PCL_EXPORT pcl_json_t* pcl_json_integer (long long integer)
#include <pcl/json.h>
Definition at line 36 of file json_integer.c.
References tag_pcl_json::integer, pcl_malloc(), and tag_pcl_json::type.
Referenced by ipcl_json_parse_number(), and pcl_err_vjson().