‪libpcl: ‪Directory Management
Directory Management
‪The directory API provides a suite of function for managing and traversing directories.
Data Structures
struct pcl_dirent_t
‪Directory entry object.
Typedefs
typedef struct tag_pcl_dir pcl_dir_t
‪Directory handle.
Enumerations
enum pcl_dirent_type_t {
PclDirentUnknown,
PclDirentFifo,
PclDirentChar,
PclDirentDir,
PclDirentBlock,
PclDirentFile,
PclDirentLink,
PclDirentSocket
}
‪Directory entry types.
Functions
PCL_PUBLIC pcl_dir_t * pcl_opendir (const pchar_t *path)
‪Open a directory.
PCL_PUBLIC const pchar_t * pcl_dir_path (pcl_dir_t *dir, int *lenp)
‪Get a directory handle's path.
PCL_PUBLIC bool pcl_readdir (pcl_dir_t *dir, pcl_dirent_t *ent, pcl_stat_t *st)
‪Read an entry from a directory handle.
PCL_PUBLIC void pcl_closedir (pcl_dir_t *dir)
‪Close a directory handle.
PCL_PUBLIC int pcl_rmdir (const pchar_t *path)
‪Remove a directory.
PCL_PUBLIC int pcl_rmdir_r (const pchar_t *path)
‪Recursively remove a directory.
PCL_PUBLIC int pcl_chdir (const pchar_t *path)
‪Change the current working directory.
PCL_PUBLIC int pcl_mkdir (const pchar_t *path, mode_t mode)
‪Create a directory.
PCL_PUBLIC int pcl_mkdirs (const pchar_t *path, mode_t mode)
‪Create a directory including any absent parents.
Detailed Description
The directory API provides a suite of function for managing and traversing directories.
Basic Usage
#include <pcl/init.h>
#include <pcl/error.h>
#include <pcl/dir.h>
#include <pcl/io.h>
int pcl_main(int argc, pchar_t *argv)
{
  // always first
  pcl_init();
  if(argc < 2)
    PANIC("Missing directory argument", 0);
  pcl_dir_t *dir = pcl_opendir(argv[1]);
  if(!dir)
    PANIC("Failed to open directory: '%Ps'", argv[1]);
  pcl_dirent_t ent;
  const pchar_t *dirpath = pcl_dir_path(dir, NULL);
  while(pcl_readdir(dir, &ent, NULL))
  {
    char *type;
    switch(ent.type)
    {
      case PclDirentFile:   type = "file"; break;
      case PclDirentDir:    type = "directory"; break;
      case PclDirentFifo:   type = "named pipe"; break;
      case PclDirentLink:   type = "symbolic link"; break;
      case PclDirentChar:   type = "character device"; break;
      case PclDirentBlock:  type = "block device"; break;
      case PclDirentSocket: type = "unix domain socket"; break;
      default:              type = "unknown";
    }
    // %/ is replaced with the platform-specific path separator
    pcl_printf("%s] %Ps%/%Ps\n", type, dirpath, ent.name);
  }
  pcl_closedir(dir);
  // when readdir is done, it returns false and pcl_errno is PCL_ENOMORE
  // note that 'dirpath' was freed with above pcl_closedir
  if(pcl_errno != PCL_ENOMORE)
    PANIC("readdir failed: '%Ps'", argv[1]);
  return 0;
}
Typedef Documentation
pcl_dir_t
typedef struct tag_pcl_dir pcl_dir_t
#include <pcl/types.h>
‪Directory handle.
Definition at line 74 of file types.h.
Enumeration Type Documentation
pcl_dirent_type_t
enum pcl_dirent_type_t
#include <pcl/dir.h>
‪Directory entry types.
Enumerator
PclDirentUnknown
Entry type could not be determined.
PclDirentFifo
Named pipe (FIFO)
PclDirentChar
Character device.
PclDirentDir
Directory.
PclDirentBlock
Block device.
PclDirentFile
Regular file.
PclDirentLink
Symbolic link.
PclDirentSocket
Unix domain socket.
Definition at line 96 of file dir.h.
Function Documentation
pcl_opendir()
PCL_PUBLIC pcl_dir_t* pcl_opendir (const pchar_t * path)
#include <pcl/dir.h>
‪Open a directory.
Parameters
path ‪directory path. Internally, this is converted to an absolute path and can be retreived using pcl_dir_path
Returns
‪pointer to a directory handle or NULL on error
Definition at line 42 of file opendir.c.
References _P, tag_pcl_dir::handle, tag_pcl_dir::path, tag_pcl_dir::pathlen, pcl_closedir(), PCL_EINVAL, pcl_malloc(), pcl_realloc(), pcl_realpath(), R_SETERR, R_TRC, SETLASTERRMSG, and strempty.
pcl_dir_path()
PCL_PUBLIC const pchar_t* pcl_dir_path (pcl_dir_t * dir, int * lenp)
#include <pcl/dir.h>
‪Get a directory handle's path.
Note
‪the returned path is always absolute.
Parameters
dir ‪pointer to a directory handle as returned by pcl_opendir
lenp ‪If not NULL, the path character length will be written here (excluding NUL)
Returns
‪directory handle's path or NULL on error
Definition at line 36 of file dir_path.c.
References tag_pcl_dir::path, tag_pcl_dir::pathlen, PCL_EINVAL, and R_SETERR.
pcl_readdir()
PCL_PUBLIC bool pcl_readdir (pcl_dir_t * dir, pcl_dirent_t * ent, pcl_stat_t * st)
#include <pcl/dir.h>
‪Read an entry from a directory handle.
Parameters
dir ‪pointer to a directory handle as returned by pcl_opendir
ent ‪pointer to an entry buffer to receive the results
st ‪If not NULL, a pcl_lstat will be executed for the entry. In most cases, the pcl_dirent_t.type can be used to avoid an expensive pcl_lstat.
Returns
‪true on success and false on error. When there are no more entries, this returns false and sets the pcl_errno to PCL_ENOMORE.
Definition at line 46 of file readdir.c.
References _P, countof, tag_pcl_file::fd, tag_pcl_dir::handle, pcl_dirent_t::name, pcl_dirent_t::namlen, tag_pcl_dir::path, pcl_aspprintf(), PCL_EINVAL, PCL_ENOMORE, pcl_err_osclear, pcl_file_close(), pcl_file_open(), pcl_free(), pcl_lstat, PCL_O_RDONLY, pcl_oserrno, pcl_pcscmp(), pcl_pcslen(), pcl_pcsncpy(), PclDirentBlock, PclDirentChar, PclDirentDir, PclDirentFifo, PclDirentFile, PclDirentLink, PclDirentSocket, PclDirentUnknown, R_SETERR, R_SETOSERR, R_TRC, SETLASTERR, and pcl_dirent_t::type.
pcl_closedir()
PCL_PUBLIC void pcl_closedir (pcl_dir_t * dir)
#include <pcl/dir.h>
‪Close a directory handle.
Parameters
dir ‪pointer to a directory handle as returned by pcl_opendir
Definition at line 36 of file closedir.c.
References tag_pcl_dir::handle, tag_pcl_dir::path, pcl_free(), and pcl_free_safe().
Referenced by pcl_opendir().
pcl_rmdir()
PCL_PUBLIC int pcl_rmdir (const pchar_t * path)
#include <pcl/dir.h>
‪Remove a directory.
Warning
‪The directory must be empty.
Parameters
path ‪directory to remove
Returns
‪0 for success and -1 on error
See also
‪pcl_rmdir_r
Definition at line 36 of file rmdir.c.
References BADARG, pcl_oserrno, SETLASTERR, and strempty.
Referenced by pcl_remove().
pcl_rmdir_r()
PCL_PUBLIC int pcl_rmdir_r (const pchar_t * path)
#include <pcl/dir.h>
‪Recursively remove a directory.
Parameters
path ‪directory to remove
Returns
‪0 for success and -1 on error
See also
‪pcl_rmdir
Definition at line 87 of file rmdir_r.c.
References countof, and pcl_pcscpy().
pcl_chdir()
PCL_PUBLIC int pcl_chdir (const pchar_t * path)
#include <pcl/dir.h>
‪Change the current working directory.
Parameters
path ‪new working directory
Returns
‪0 for success and -1 on error
Definition at line 36 of file chdir.c.
References SETLASTERR.
Referenced by pcl_proc_exec().
pcl_mkdir()
PCL_PUBLIC int pcl_mkdir (const pchar_t * path, mode_t mode)
#include <pcl/dir.h>
‪Create a directory.
Parameters
path ‪directory path
mode ‪permission bits
Returns
‪0 on success and -1 on error
Definition at line 41 of file mkdir.c.
References ipcl_win32_sd_clear(), ipcl_win32_sd_create(), pcl_err_osclear, SETLASTERRMSG, and TRCMSG.
Referenced by pcl_mkdirs().
pcl_mkdirs()
PCL_PUBLIC int pcl_mkdirs (const pchar_t * path, mode_t mode)
#include <pcl/dir.h>
‪Create a directory including any absent parents.
Same as unix mkdir -p /path/to/dir
Parameters
path ‪directory path
mode ‪permission bits, which are also applied to any parent created
Returns
‪0 on success and -1 on error
Definition at line 37 of file mkdirs.c.
References _P, countof, PCL_EEXIST, pcl_errno, pcl_mkdir(), pcl_oserrno, pcl_pcschr(), pcl_pcscpy(), pcl_pcsrepchr(), pcl_setoserrno, and TRCMSG.