‪libpcl: ‪/Users/andrew/projects/libpcl/src/win32/win32_file_security.c File Reference
win32_file_security.c File Reference
#include "_win32.h"
#include <pcl/stat.h>
#include <pcl/alloc.h>
Functions
int ipcl_win32_file_security (const pchar_t *path, mode_t *mode, uid_t *uidp, gid_t *gidp)
Function Documentation
ipcl_win32_file_security()
int ipcl_win32_file_security (const pchar_t * path, mode_t * mode, uid_t * uidp, gid_t * gidp)
Definition at line 37 of file win32_file_security.c.
References ipcl_win32_rights_to_mode(), ipcl_win32_sd_get(), PCL_EINVAL, pcl_free(), pcl_strtrunc(), S_IRGRP, S_IROTH, S_IRUSR, S_IRWXG, S_IRWXO, S_IRWXU, SETERR, and TRC.