‪libpcl: ‪String Management
String Management
‪A set of string utility functions.
Modules
TCHAR Functions
‪The pchar_t functions map char or wchar_t string functions.
Functions
PCL_PUBLIC int pcl_strfbytes (char *buf, size_t bufl, uint64_t nbytes, int decimal)
‪Format a number in byte units.
PCL_PUBLIC int pcl_wcsfbytes (wchar_t *buf, size_t bufl, uint64_t nbytes, int decimal)
‪Format a number in byte units.
PCL_PUBLIC int pcl_hex_encode (char *buf, size_t size, const void *data, size_t len)
‪Encode data as a hexadecimal string.
PCL_PUBLIC int pcl_hex_decode (void *buf, size_t size, const char *hex)
‪Decode a hexadecimal string.
PCL_PUBLIC int pcl_base64_encode (char *buf, size_t size, const void *data, size_t len)
‪Encode data as a base64 string.
PCL_PUBLIC int pcl_base64_decode (void *buf, size_t size, const char *b64)
‪Decode a base64 string.
PCL_PUBLIC int pcl_utf8_encode (uint32_t code, char *utf8buf)
‪UTF-8 encode a unicode codepoint.
PCL_PUBLIC int pcl_utf8_check (const char *s, size_t len)
‪Check that a string is valid UTF-8.
int pcl_stricmp (const char *a, const char *b)
‪Compare two strings ignoring case.
int pcl_wcsicmp (const wchar_t *a, const wchar_t *b)
‪Compare two strings ignoring case.
int pcl_strnicmp (const char *a, const char *b, size_t n)
‪Compare two strings ignoring case.
int pcl_wcsnicmp (const wchar_t *a, const wchar_t *b, size_t n)
‪Compare two strings ignoring case.
char * pcl_strcpy (char *dest, size_t size, const char *src)
‪Copy a string.
wchar_t * pcl_wcscpy (wchar_t *dest, size_t size, const wchar_t *src)
‪Copy a string.
PCL_PUBLIC char * pcl_strncpy (char *dest, size_t size, const char *src, size_t len)
‪Copy a portion of a string.
PCL_PUBLIC wchar_t * pcl_wcsncpy (wchar_t *dest, size_t size, const wchar_t *src, size_t len)
‪Copy a portion of a string.
char * pcl_stristr (const char *haystack, const char *needle)
‪Locate a substring ignoring case.
wchar_t * pcl_wcsistr (const wchar_t *haystack, const wchar_t *needle)
‪Locate a substring ignoring case.
char * pcl_strdup (const char *s)
‪Duplicate a string.
wchar_t * pcl_wcsdup (const wchar_t *s)
‪Duplicate a string.
PCL_PUBLIC char * pcl_strndup (const char *s, size_t len)
‪Duplicate a portion of a string.
PCL_PUBLIC wchar_t * pcl_wcsndup (const wchar_t *s, size_t len)
‪Duplicate a portion of a string.
char * pcl_strcat (char *dest, size_t size, const char *src)
‪Concatenate two strings.
wchar_t * pcl_wcscat (wchar_t *dest, size_t size, const wchar_t *src)
‪Concatenate two strings.
PCL_PUBLIC char * pcl_strncat (char *dest, size_t size, const char *src, size_t len)
‪Concatenate two strings.
PCL_PUBLIC wchar_t * pcl_wcsncat (wchar_t *dest, size_t size, const wchar_t *src, size_t len)
‪Concatenate two strings.
PCL_PUBLIC char * pcl_strcatf (char *dest, size_t size, const char *format,...)
‪Concatenate two strings using a format.
PCL_PUBLIC wchar_t * pcl_wcscatf (wchar_t *dest, size_t size, const wchar_t *format,...)
‪Concatenate two strings using a format.
PCL_PUBLIC char * pcl_vstrcatf (char *dest, size_t size, const char *format, va_list ap)
‪Concatenate two strings using a format.
PCL_PUBLIC wchar_t * pcl_vwcscatf (wchar_t *dest, size_t size, const wchar_t *format, va_list ap)
‪Concatenate two strings using a format.
PCL_PUBLIC char * pcl_astrcatf (const char *src, const char *format,...)
‪Allocate and concatenate two strings using a format.
PCL_PUBLIC wchar_t * pcl_awcscatf (const wchar_t *src, const wchar_t *format,...)
‪Allocate and concatenate two strings using a format.
PCL_PUBLIC char * pcl_vastrcatf (const char *src, const char *format, va_list ap)
‪Allocate and concatenate two strings using a format.
PCL_PUBLIC wchar_t * pcl_vawcscatf (const wchar_t *src, const wchar_t *format, va_list ap)
‪Allocate and concatenate two strings using a format.
char * pcl_strtrim (char *s)
‪Trim whitespace from the front and back of a string.
wchar_t * pcl_wcstrim (wchar_t *s)
‪Trim whitespace from the front and back of a string.
char * pcl_strltrim (char *s)
‪Trim whitespace from the front (left) of a string.
wchar_t * pcl_wcsltrim (wchar_t *s)
‪Trim whitespace from the front (left) of a string.
char * pcl_strrtrim (char *s)
‪Trim whitespace from the back (right) of a string.
wchar_t * pcl_wcsrtrim (wchar_t *s)
‪Trim whitespace from the back (right) of a string.
PCL_PUBLIC char * pcl_strtrimset (char *s, const char *set, bool left, bool right)
‪Trim a set of characters from a string.
PCL_PUBLIC wchar_t * pcl_wcstrimset (wchar_t *s, const wchar_t *set, bool left, bool right)
‪Trim a set of characters from a string.
PCL_PUBLIC char * pcl_strreplace (const char *subject, const char *from, const char *to)
‪Replace all occurances of a search string with a replacement string.
PCL_PUBLIC wchar_t * pcl_wcsreplace (const wchar_t *subject, const wchar_t *from, const wchar_t *to)
‪Replace all occurances of a search string with a replacement string.
PCL_PUBLIC char * pcl_strireplace (const char *subject, const char *from, const char *to)
‪Replace all occurances of a search string with a replacement string ignoring case.
PCL_PUBLIC wchar_t * pcl_wcsireplace (const wchar_t *subject, const wchar_t *from, const wchar_t *to)
‪Replace all occurances of a search string with a replacement string ignoring case.
PCL_PUBLIC pcl_array_t * pcl_strsplit (const char *s, const char *delim)
‪Split a string into an array.
PCL_PUBLIC pcl_array_t * pcl_wcssplit (const wchar_t *s, const wchar_t *delim)
‪Split a string into an array.
PCL_PUBLIC pcl_array_t * pcl_strisplit (const char *s, const char *delim)
‪Split a string into an array ignoring case.
PCL_PUBLIC pcl_array_t * pcl_wcsisplit (const wchar_t *s, const wchar_t *delim)
‪Split a string into an array ignoring case.
PCL_PUBLIC char * pcl_strlower (char *s)
‪Lowercase a string.
PCL_PUBLIC wchar_t * pcl_wcslower (wchar_t *s)
‪Lowercase a string.
PCL_PUBLIC char * pcl_strupper (char *s)
‪Uppercase a string.
PCL_PUBLIC wchar_t * pcl_wcsupper (wchar_t *s)
‪Uppercase a string.
PCL_PUBLIC char * pcl_strtrunc (char *dest, size_t size, const char *src)
‪Copy and truncate a string.
PCL_PUBLIC wchar_t * pcl_wcstrunc (wchar_t *dest, size_t size, const wchar_t *src)
‪Copy and truncate a string.
PCL_PUBLIC char * pcl_strslice (const char *s, size_t pos, size_t len)
‪Extract a slice of a string.
PCL_PUBLIC wchar_t * pcl_wcsslice (const wchar_t *s, size_t pos, size_t len)
‪Extract a slice of a string.
PCL_PUBLIC const char * pcl_strsignal (int signum)
‪Convert a signal number to a string.
PCL_INLINE char * pcl_strrepchr (char *s, int oldch, int newch)
‪Replace all occurance of a character in a string.
PCL_INLINE wchar_t * pcl_wcsrepchr (wchar_t *s, wchar_t oldch, wchar_t newch)
‪Replace all occurance of a character in a string.
PCL_INLINE char * pcl_strskipws (const char *s)
‪Skip whitespace.
PCL_INLINE wchar_t * pcl_wcsskipws (const wchar_t *s)
‪Skip whitespace.
PCL_PUBLIC char * pcl_pcs_to_utf8 (const pchar_t *src, size_t src_len, size_t *lenp)
‪Convert a pchar_t string to UTF-8.
PCL_PUBLIC pchar_t * pcl_utf8_to_pcs (const char *src, size_t src_len, size_t *lenp)
‪Convert a UTF-8 string to a pchar_t string.
Detailed Description
A set of string utility functions.
The PCL string library includes many standard C string functions for the sole purpose of providing buffer safe versions. There are other functions that have no counterpart in the standard C library, but are a common need.
Almost all PCL string functions come in two flavors: UTF-8 (char) and UTF-16 (wchar_t). These two version exists to support PCL's concept of a pchar_t: a char on Unixes and wchar_t on Windows. For example, the below shows some basic mappings:
pcl_pcscpy   => Unix pcl_strcpy, Windows pcl_wcscpy
pcl_pcsdup   => Unix pcl_strdup, Windows pcl_wcsdup
pcl_pcscatf  => Unix pcl_strcatf, Windows pcl_wcscatf
It is actually uncommon to use str or wcs versions directly in a cross-platform application. It is much more common to use the pcs versions.
Function Documentation
pcl_strfbytes()
PCL_PUBLIC int pcl_strfbytes (char * buf, size_t bufl, uint64_t nbytes, int decimal)
#include <pcl/string.h>
‪Format a number in byte units.
This uses multiples of 1024 and supports the following units: Kibibyte, Mebibyte, Gibibyte, Tebibyte, Pebibyte, Exibyte. The formatted unit is appened to the converted number value as a single uppercase character (no spaces): 10K, 50M, etc. For values less than 1024, no unit is appened; this is just bytes.
Parameters
buf ‪pointer to a buffer to write formatted value
bufl ‪character length of buf
nbytes ‪number of bytes, value to format
decimal ‪number of decimal places to include in the formatted value.
Returns
‪number of character written to buf or -1 on error.
pcl_wcsfbytes()
PCL_PUBLIC int pcl_wcsfbytes (wchar_t * buf, size_t bufl, uint64_t nbytes, int decimal)
#include <pcl/string.h>
‪Format a number in byte units.
This uses multiples of 1024 and supports the following units: Kibibyte, Mebibyte, Gibibyte, Tebibyte, Pebibyte, Exibyte. The formatted unit is appened to the converted number value as a single uppercase character (no spaces): 10K, 50M, etc. For values less than 1024, no unit is appened; this is just bytes.
Parameters
buf ‪pointer to a buffer to write formatted value
bufl ‪character length of buf
nbytes ‪number of bytes, value to format
decimal ‪number of decimal places to include in the formatted value.
Returns
‪number of character written to buf or -1 on error.
pcl_hex_encode()
PCL_PUBLIC int pcl_hex_encode (char * buf, size_t size, const void * data, size_t len)
#include <pcl/string.h>
‪Encode data as a hexadecimal string.
Parameters
buf ‪pointer to a buffer
size ‪character length of buf
data ‪pointer to the data to encode
len ‪number of data bytes to encode
Returns
‪number of characters written to buf or -1 on error
Definition at line 36 of file hex_encode.c.
References PCL_EBUF, and SETERR.
Referenced by pcl_tmpfile().
pcl_hex_decode()
PCL_PUBLIC int pcl_hex_decode (void * buf, size_t size, const char * hex)
#include <pcl/string.h>
‪Decode a hexadecimal string.
Warning
‪This does not add a NUL to buf
Parameters
buf ‪pointer to a buffer
size ‪byte length of buf which should be at least strlen(hex) bytes
hex ‪pointer to the hexadecimal string
Returns
‪number of bytes written to buf or -1 on error
Definition at line 54 of file hex_decode.c.
References BADARG, PCL_EBUF, and SETERR.
pcl_base64_encode()
PCL_PUBLIC int pcl_base64_encode (char * buf, size_t size, const void * data, size_t len)
#include <pcl/string.h>
‪Encode data as a base64 string.
Parameters
buf ‪pointer to a buffer
size ‪character length of buf
data ‪pointer to the data to encode
len ‪number of data bytes to encode
Returns
‪number of characters written to buf or -1 on error
Definition at line 37 of file base64_encode.c.
References BADARG, PCL_EBUF, and SETERR.
pcl_base64_decode()
PCL_PUBLIC int pcl_base64_decode (void * buf, size_t size, const char * b64)
#include <pcl/string.h>
‪Decode a base64 string.
Parameters
buf ‪pointer to a buffer
size ‪byte length of buf
b64 ‪pointer to the base64 string
Returns
‪number of bytes written to buf or -1 on error
Definition at line 37 of file base64_decode.c.
References BADARG, PCL_EBUF, and SETERR.
pcl_utf8_encode()
PCL_PUBLIC int pcl_utf8_encode (uint32_t code, char * utf8buf)
#include <pcl/string.h>
‪UTF-8 encode a unicode codepoint.
Parameters
code
utf8buf ‪output buffer, must be at least 4 bytes wide.
Returns
‪number of bytes written to utf8buf or -1 on error.
Definition at line 36 of file utf8_encode.c.
References BADARG, PCL_EINVCODEPT, and SETERRMSG.
pcl_utf8_check()
PCL_PUBLIC int pcl_utf8_check (const char * s, size_t len)
#include <pcl/string.h>
‪Check that a string is valid UTF-8.
Parameters
s ‪pointer to a string
len ‪number of bytes to check. If 0, s must be NUL-terminated.
Returns
‪0 if valid and -1 if not.
Definition at line 51 of file utf8_check.c.
References PCL_EILSEQ, and SETERRMSG.
Referenced by pcl_json_objput(), pcl_json_str(), and pcl_json_strn().
pcl_stricmp()
int pcl_stricmp (const char * a, const char * b)
#include <pcl/string.h>
‪Compare two strings ignoring case.
Parameters
a ‪pointer to a string
b ‪pointer to a string
Returns
‪an integer less than, equal to or greater than zero if a is found, respectively, to be less than, to match or be greater than b
Note
‪implemented as a macro
pcl_wcsicmp()
int pcl_wcsicmp (const wchar_t * a, const wchar_t * b)
#include <pcl/string.h>
‪Compare two strings ignoring case.
Parameters
a ‪pointer to a string
b ‪pointer to a string
Returns
‪an integer less than, equal to or greater than zero if a is found, respectively, to be less than, to match or be greater than b
Note
‪implemented as a macro
pcl_strnicmp()
int pcl_strnicmp (const char * a, const char * b, size_t n)
#include <pcl/string.h>
‪Compare two strings ignoring case.
Parameters
a ‪pointer to a string
b ‪pointer to a string
n ‪compare only the first N bytes
Returns
‪an integer less than, equal to or greater than zero if a is found, respectively, to be less than, to match or be greater than b
Note
‪implemented as a macro
Referenced by ipcl_sysinfo().
pcl_wcsnicmp()
int pcl_wcsnicmp (const wchar_t * a, const wchar_t * b, size_t n)
#include <pcl/string.h>
‪Compare two strings ignoring case.
Parameters
a ‪pointer to a string
b ‪pointer to a string
n ‪compare only the first N bytes
Returns
‪an integer less than, equal to or greater than zero if a is found, respectively, to be less than, to match or be greater than b
Note
‪implemented as a macro
pcl_strcpy()
char* pcl_strcpy (char * dest, size_t size, const char * src)
#include <pcl/string.h>
‪Copy a string.
Parameters
dest ‪pointer to a buffer
size ‪character length of dest
src ‪pointer to the string to copy
Returns
‪pointer to dest or NULL on error
Note
‪implemented as a macro
Referenced by ipcl_sysinfo(), pcl_err_osmsg(), pcl_getgroup(), pcl_getuid(), pcl_getuser(), pcl_log_vevent(), pcl_net_addr2ip(), pcl_net_host2addr(), pcl_socket(), and pcl_sysinfo().
pcl_wcscpy()
wchar_t* pcl_wcscpy (wchar_t * dest, size_t size, const wchar_t * src)
#include <pcl/string.h>
‪Copy a string.
Parameters
dest ‪pointer to a buffer
size ‪character length of dest
src ‪pointer to the string to copy
Returns
‪pointer to dest or NULL on error
Note
‪implemented as a macro
pcl_strncpy()
PCL_PUBLIC char* pcl_strncpy (char * dest, size_t size, const char * src, size_t len)
#include <pcl/string.h>
‪Copy a portion of a string.
Parameters
dest ‪pointer to a buffer
size ‪character length of dest. one byte is always reserved for NUL.
src ‪pointer to the string to copy
len ‪number of characters in src to copy
Returns
‪pointer to dest or NULL on error.
pcl_wcsncpy()
PCL_PUBLIC wchar_t* pcl_wcsncpy (wchar_t * dest, size_t size, const wchar_t * src, size_t len)
#include <pcl/string.h>
‪Copy a portion of a string.
Parameters
dest ‪pointer to a buffer
size ‪character length of dest. one byte is always reserved for NUL.
src ‪pointer to the string to copy
len ‪number of characters in src to copy
Returns
‪pointer to dest or NULL on error.
pcl_stristr()
char* pcl_stristr (const char * haystack, const char * needle)
#include <pcl/string.h>
‪Locate a substring ignoring case.
Parameters
haystack ‪pointer to a string to search within
needle ‪pointer to a string
Returns
‪pointer to the first occurance of needle within haystack or NULL on error.
Referenced by pcl_cipher_isaead(), and pcl_proc_exec().
pcl_wcsistr()
PCL_PUBLIC wchar_t * pcl_wcsistr (const wchar_t * haystack, const wchar_t * needle)
#include <pcl/string.h>
‪Locate a substring ignoring case.
Parameters
haystack ‪pointer to a string to search within
needle ‪pointer to a string
Returns
‪pointer to the first occurance of needle within haystack or NULL on error.
pcl_strdup()
char* pcl_strdup (const char * s)
#include <pcl/string.h>
‪Duplicate a string.
Parameters
s ‪pointer to string
Returns
‪pointer to allocated duplicate
Note
‪implemented as a macro
Referenced by pcl_json_objput(), pcl_net_resolve(), and pcl_socket_ip().
pcl_wcsdup()
wchar_t* pcl_wcsdup (const wchar_t * s)
#include <pcl/string.h>
‪Duplicate a string.
Parameters
s ‪pointer to string
Returns
‪pointer to allocated duplicate
Note
‪implemented as a macro
pcl_strndup()
PCL_PUBLIC char* pcl_strndup (const char * s, size_t len)
#include <pcl/string.h>
‪Duplicate a portion of a string.
Parameters
s ‪pointer to string
len ‪number of characters to duplicate
Returns
‪pointer to allocated duplicate
Referenced by pcl_fdpath(), pcl_json_compile(), pcl_json_str(), pcl_json_strn(), pcl_net_dnstxtrec(), pcl_realpath(), pcl_ssl_certentry(), and pcl_utf8_to_pcs().
pcl_wcsndup()
PCL_PUBLIC wchar_t* pcl_wcsndup (const wchar_t * s, size_t len)
#include <pcl/string.h>
‪Duplicate a portion of a string.
Parameters
s ‪pointer to string
len ‪number of characters to duplicate
Returns
‪pointer to allocated duplicate
pcl_strcat()
char* pcl_strcat (char * dest, size_t size, const char * src)
#include <pcl/string.h>
‪Concatenate two strings.
Parameters
dest ‪pointer to a buffer
size ‪character length of dest
src ‪pointer to the string to copy
Returns
‪pointer to dest
Note
‪implemented as a macro
pcl_wcscat()
wchar_t* pcl_wcscat (wchar_t * dest, size_t size, const wchar_t * src)
#include <pcl/string.h>
‪Concatenate two strings.
Parameters
dest ‪pointer to a buffer
size ‪character length of dest
src ‪pointer to the string to copy
Returns
‪pointer to dest
Note
‪implemented as a macro
pcl_strncat()
PCL_PUBLIC char* pcl_strncat (char * dest, size_t size, const char * src, size_t len)
#include <pcl/string.h>
‪Concatenate two strings.
Parameters
dest ‪pointer to a buffer to append to
size ‪character length of dest
src ‪pointer to the string to copy
len ‪character length of src to copy
Returns
‪pointer to dest
pcl_wcsncat()
PCL_PUBLIC wchar_t* pcl_wcsncat (wchar_t * dest, size_t size, const wchar_t * src, size_t len)
#include <pcl/string.h>
‪Concatenate two strings.
Parameters
dest ‪pointer to a buffer to append to
size ‪character length of dest
src ‪pointer to the string to copy
len ‪character length of src to copy
Returns
‪pointer to dest
pcl_strcatf()
PCL_PUBLIC char* pcl_strcatf (char * dest, size_t size, const char * format, ...)
#include <pcl/string.h>
‪Concatenate two strings using a format.
Parameters
dest ‪pointer to a buffer to append to
size ‪character length of dest
format ‪printf-style format string
... ‪variable arguments
Returns
‪pointer to dest
pcl_wcscatf()
PCL_PUBLIC wchar_t* pcl_wcscatf (wchar_t * dest, size_t size, const wchar_t * format, ...)
#include <pcl/string.h>
‪Concatenate two strings using a format.
Parameters
dest ‪pointer to a buffer to append to
size ‪character length of dest
format ‪printf-style format string
... ‪variable arguments
Returns
‪pointer to dest
pcl_vstrcatf()
PCL_PUBLIC char* pcl_vstrcatf (char * dest, size_t size, const char * format, va_list ap)
#include <pcl/string.h>
‪Concatenate two strings using a format.
Parameters
dest ‪pointer to a buffer to append to
size ‪character length of dest
format ‪printf-style format string
ap ‪variable argument list
Returns
‪pointer to dest
pcl_vwcscatf()
PCL_PUBLIC wchar_t* pcl_vwcscatf (wchar_t * dest, size_t size, const wchar_t * format, va_list ap)
#include <pcl/string.h>
‪Concatenate two strings using a format.
Parameters
dest ‪pointer to a buffer to append to
size ‪character length of dest
format ‪printf-style format string
ap ‪variable argument list
Returns
‪pointer to dest
pcl_astrcatf()
PCL_PUBLIC char* pcl_astrcatf (const char * src, const char * format, ...)
#include <pcl/string.h>
‪Allocate and concatenate two strings using a format.
Parameters
src ‪pointer to a string to to use as the first set of characters. This can be NULL.
format ‪printf-style format string
... ‪variable arguments
Returns
‪pointer to an allocated string starting with src, if not NULL, and ending with the formatted results.
pcl_awcscatf()
PCL_PUBLIC wchar_t* pcl_awcscatf (const wchar_t * src, const wchar_t * format, ...)
#include <pcl/string.h>
‪Allocate and concatenate two strings using a format.
Parameters
src ‪pointer to a string to to use as the first set of characters. This can be NULL.
format ‪printf-style format string
... ‪variable arguments
Returns
‪pointer to an allocated string starting with src, if not NULL, and ending with the formatted results.
pcl_vastrcatf()
PCL_PUBLIC char* pcl_vastrcatf (const char * src, const char * format, va_list ap)
#include <pcl/string.h>
‪Allocate and concatenate two strings using a format.
Parameters
src ‪pointer to a string to use as the first set of characters. This can be NULL.
format ‪printf-style format string
ap ‪variable argument list
Returns
‪pointer to an allocated string starting with src, if not NULL, and ending with the formatted results.
pcl_vawcscatf()
PCL_PUBLIC wchar_t* pcl_vawcscatf (const wchar_t * src, const wchar_t * format, va_list ap)
#include <pcl/string.h>
‪Allocate and concatenate two strings using a format.
Parameters
src ‪pointer to a string to use as the first set of characters. This can be NULL.
format ‪printf-style format string
ap ‪variable argument list
Returns
‪pointer to an allocated string starting with src, if not NULL, and ending with the formatted results.
pcl_strtrim()
char* pcl_strtrim (char * s)
#include <pcl/string.h>
‪Trim whitespace from the front and back of a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to the s argument
Note
‪implemented as a macro
Referenced by ipcl_sysinfo(), and pcl_sysinfo().
pcl_wcstrim()
wchar_t* pcl_wcstrim (wchar_t * s)
#include <pcl/string.h>
‪Trim whitespace from the front and back of a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to the s argument
Note
‪implemented as a macro
pcl_strltrim()
char* pcl_strltrim (char * s)
#include <pcl/string.h>
‪Trim whitespace from the front (left) of a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to the s argument
Note
‪implemented as a macro
pcl_wcsltrim()
wchar_t* pcl_wcsltrim (wchar_t * s)
#include <pcl/string.h>
‪Trim whitespace from the front (left) of a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to the s argument
Note
‪implemented as a macro
pcl_strrtrim()
char* pcl_strrtrim (char * s)
#include <pcl/string.h>
‪Trim whitespace from the back (right) of a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to the s argument
Note
‪implemented as a macro
pcl_wcsrtrim()
wchar_t* pcl_wcsrtrim (wchar_t * s)
#include <pcl/string.h>
‪Trim whitespace from the back (right) of a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to the s argument
Note
‪implemented as a macro
pcl_strtrimset()
PCL_PUBLIC char* pcl_strtrimset (char * s, const char * set, bool left, bool right)
#include <pcl/string.h>
‪Trim a set of characters from a string.
Parameters
s ‪pointer to a string
set ‪a set of characters (as a string) to trim. If this is NULL, a default set is used: " \t\n\v\f\r"
left ‪true to trim from the front (left) of s
right ‪true to trim from the back (right) of s
Returns
‪pointer to s
pcl_wcstrimset()
PCL_PUBLIC wchar_t* pcl_wcstrimset (wchar_t * s, const wchar_t * set, bool left, bool right)
#include <pcl/string.h>
‪Trim a set of characters from a string.
Parameters
s ‪pointer to a string
set ‪a set of characters (as a string) to trim. If this is NULL, a default set is used: " \t\n\v\f\r"
left ‪true to trim from the front (left) of s
right ‪true to trim from the back (right) of s
Returns
‪pointer to s
pcl_strreplace()
PCL_PUBLIC char* pcl_strreplace (const char * subject, const char * from, const char * to)
#include <pcl/string.h>
‪Replace all occurances of a search string with a replacement string.
Parameters
subject ‪pointer to source string
from ‪pointer to the search string within subject
to ‪pointer to the replacement string
Returns
‪an allocated string with all occurances of from replaced with to
pcl_wcsreplace()
PCL_PUBLIC wchar_t* pcl_wcsreplace (const wchar_t * subject, const wchar_t * from, const wchar_t * to)
#include <pcl/string.h>
‪Replace all occurances of a search string with a replacement string.
Parameters
subject ‪pointer to source string
from ‪pointer to the search string within subject
to ‪pointer to the replacement string
Returns
‪an allocated string with all occurances of from replaced with to
pcl_strireplace()
PCL_PUBLIC char* pcl_strireplace (const char * subject, const char * from, const char * to)
#include <pcl/string.h>
‪Replace all occurances of a search string with a replacement string ignoring case.
Parameters
subject ‪pointer to source string
from ‪pointer to the search string within subject
to ‪pointer to the replacement string
Returns
‪an allocated string with all occurances of from replaced with to
pcl_wcsireplace()
PCL_PUBLIC wchar_t* pcl_wcsireplace (const wchar_t * subject, const wchar_t * from, const wchar_t * to)
#include <pcl/string.h>
‪Replace all occurances of a search string with a replacement string ignoring case.
Parameters
subject ‪pointer to source string
from ‪pointer to the search string within subject
to ‪pointer to the replacement string
Returns
‪an allocated string with all occurances of from replaced with to
pcl_strsplit()
PCL_PUBLIC pcl_array_t* pcl_strsplit (const char * s, const char * delim)
#include <pcl/string.h>
‪Split a string into an array.
Parameters
s ‪pointer to a string
delim ‪pointer to a delimiter to split on
Returns
‪pointer to an array containing the split parts. The delimiter string is never included in part elements. This never returns NULL, however the array can be empty if s is NULL or "".
pcl_wcssplit()
PCL_PUBLIC pcl_array_t* pcl_wcssplit (const wchar_t * s, const wchar_t * delim)
#include <pcl/string.h>
‪Split a string into an array.
Parameters
s ‪pointer to a string
delim ‪pointer to a delimiter to split on
Returns
‪pointer to an array containing the split parts. The delimiter string is never included in part elements. This never returns NULL, however the array can be empty if s is NULL or "".
pcl_strisplit()
PCL_PUBLIC pcl_array_t* pcl_strisplit (const char * s, const char * delim)
#include <pcl/string.h>
‪Split a string into an array ignoring case.
Parameters
s ‪pointer to a string
delim ‪pointer to a delimiter to split on
Returns
‪pointer to an array containing the split parts. The delimiter string is never included in part elements. This never returns NULL, however the array can be empty if s is NULL or "".
pcl_wcsisplit()
PCL_PUBLIC pcl_array_t* pcl_wcsisplit (const wchar_t * s, const wchar_t * delim)
#include <pcl/string.h>
‪Split a string into an array ignoring case.
Parameters
s ‪pointer to a string
delim ‪pointer to a delimiter to split on
Returns
‪pointer to an array containing the split parts. The delimiter string is never included in part elements. This never returns NULL, however the array can be empty if s is NULL or "".
pcl_strlower()
PCL_PUBLIC char* pcl_strlower (char * s)
#include <pcl/string.h>
‪Lowercase a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to s in lowercase
pcl_wcslower()
PCL_PUBLIC wchar_t* pcl_wcslower (wchar_t * s)
#include <pcl/string.h>
‪Lowercase a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to s in lowercase
pcl_strupper()
PCL_PUBLIC char* pcl_strupper (char * s)
#include <pcl/string.h>
‪Uppercase a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to s in uppercase
pcl_wcsupper()
PCL_PUBLIC wchar_t* pcl_wcsupper (wchar_t * s)
#include <pcl/string.h>
‪Uppercase a string.
Parameters
s ‪pointer to a string
Returns
‪pointer to s in uppercase
pcl_strtrunc()
PCL_PUBLIC char* pcl_strtrunc (char * dest, size_t size, const char * src)
#include <pcl/string.h>
‪Copy and truncate a string.
This will copy as much as possible. If dest is not large enough, this will truncate src to fit within dest.
Parameters
dest ‪pointer to a buffer. if src can't fit, truncate
size ‪character count of dest
src ‪pointer to string to copy
Returns
‪pointer to dest
Referenced by ipcl_win32_file_security().
pcl_wcstrunc()
PCL_PUBLIC wchar_t* pcl_wcstrunc (wchar_t * dest, size_t size, const wchar_t * src)
#include <pcl/string.h>
‪Copy and truncate a string.
This will copy as much as possible. If dest is not large enough, this will truncate src to fit within dest.
Parameters
dest ‪pointer to a buffer. if src can't fit, truncate
size ‪character count of dest
src ‪pointer to string to copy
Returns
‪pointer to dest
pcl_strslice()
PCL_PUBLIC char* pcl_strslice (const char * s, size_t pos, size_t len)
#include <pcl/string.h>
‪Extract a slice of a string.
This is also known as substr.
Parameters
s ‪pointer to a string
pos ‪starting character position
len ‪number of characters to extract
Returns
‪pointer to an allocated slice of s
pcl_wcsslice()
PCL_PUBLIC wchar_t* pcl_wcsslice (const wchar_t * s, size_t pos, size_t len)
#include <pcl/string.h>
‪Extract a slice of a string.
This is also known as substr.
Parameters
s ‪pointer to a string
pos ‪starting character position
len ‪number of characters to extract
Returns
‪pointer to an allocated slice of s
pcl_strsignal()
PCL_PUBLIC const char* pcl_strsignal (int signum)
#include <pcl/string.h>
‪Convert a signal number to a string.
Parameters
signum ‪signal number
Returns
‪pointer to a string
Definition at line 36 of file strsignal.c.
References CASE.
Referenced by pcl_unix_siginfo().
pcl_strrepchr()
PCL_INLINE char* pcl_strrepchr (char * s, int oldch, int newch)
#include <pcl/string.h>
‪Replace all occurance of a character in a string.
Parameters
s ‪pointer to a string
oldch ‪search character
newch ‪replacement character
Returns
‪pointer to s argument
Definition at line 473 of file string.h.
Referenced by pcl_err_vtrace(), and pcl_log_vevent().
pcl_wcsrepchr()
PCL_INLINE wchar_t* pcl_wcsrepchr (wchar_t * s, wchar_t oldch, wchar_t newch)
#include <pcl/string.h>
‪Replace all occurance of a character in a string.
Parameters
s ‪pointer to a string
oldch ‪search character
newch ‪replacement character
Returns
‪pointer to s argument
Definition at line 483 of file string.h.
pcl_strskipws()
PCL_INLINE char* pcl_strskipws (const char * s)
#include <pcl/string.h>
‪Skip whitespace.
Parameters
s ‪pointer to a string
Returns
‪pointer to the first character in s that is not a whitespace character.
Definition at line 496 of file string.h.
Referenced by pcl_json_compile().
pcl_wcsskipws()
PCL_INLINE wchar_t* pcl_wcsskipws (const wchar_t * s)
#include <pcl/string.h>
‪Skip whitespace.
Parameters
s ‪pointer to a string
Returns
‪pointer to the first character in s that is not a whitespace character.
Definition at line 504 of file string.h.
pcl_pcs_to_utf8()
PCL_PUBLIC char* pcl_pcs_to_utf8 (const pchar_t * src, size_t src_len, size_t * lenp)
#include <pcl/string.h>
‪Convert a pchar_t string to UTF-8.
Internally, this is just a strdup on Unix machines since a Unix pchar_t represents UTF-8.
Parameters
src ‪pointer to a pchar_t string
src_len ‪byte length of the src argument. If this is zero, strlen is used
lenp ‪If not NULL, character length will be written here
Returns
‪pointer to the result of conversion. This must be freed.
Definition at line 71 of file pcs_to_utf8.c.
References PCL_EINVAL, pcl_pcslen(), pcl_pcsndup(), and R_SETERR.
Referenced by pcl_net_dnstxtrec().
pcl_utf8_to_pcs()
PCL_PUBLIC pchar_t* pcl_utf8_to_pcs (const char * src, size_t src_len, size_t * lenp)
#include <pcl/string.h>
‪Convert a UTF-8 string to a pchar_t string.
Internally, this is just a strdup on Unix machines since a Unix pchar_t represents UTF-8.
Parameters
src ‪pointer to a UTF-8 string
src_len ‪byte length of the src argument. If this is zero, strlen is used
[out] lenp ‪If not NULL, character length will be written here
Returns
‪pointer to the result of conversion. This must be freed.
Definition at line 63 of file utf8_to_pcs.c.
References PCL_EINVAL, pcl_strndup(), and R_SETERR.
Referenced by pcl_bind(), and pcl_sysinfo().