‪libpcl: ‪Input/Output Functions
Input/Output Functions
‪The IO module defines some basic IO functions as well as a suite of printf-style formatting functions.
Functions
PCL_PUBLIC FILE * pcl_fopen (const pchar_t *path, const pchar_t *mode)
‪Opens a FILE stream for reading and/or writing.
PCL_PUBLIC FILE * pcl_popen (const pchar_t *command,...)
‪Pipe a stream to or from a process.
PCL_PUBLIC int pcl_fileno (FILE *stream)
‪Get a file descriptor from a stream.
PCL_PUBLIC FILE * pcl_fdopen (pcl_file_t *file)
‪Open a file handle as a stream.
PCL_PUBLIC FILE * pcl_tmpfile (const pchar_t *dir, const pchar_t *prefix, const pchar_t *suffix, pchar_t **pathp, bool keep)
‪Create and open a unique temporary file.
PCL_PUBLIC int pcl_printf (const char *format,...)
‪Write a formatted character string to stdout.
PCL_PUBLIC int pcl_wprintf (const wchar_t *format,...)
‪Write a formatted character string to stdout.
PCL_PUBLIC int pcl_vprintf (const char *format, va_list ap)
‪Write a formatted character string to stdout.
PCL_PUBLIC int pcl_vwprintf (const wchar_t *format, va_list ap)
‪Write a formatted character string to stdout.
PCL_PUBLIC int pcl_fprintf (FILE *stream, const char *format,...)
‪Write a formatted character string to a stream.
PCL_PUBLIC int pcl_fwprintf (FILE *stream, const wchar_t *format,...)
‪Write a formatted character string to a stream.
PCL_PUBLIC int pcl_vfprintf (FILE *stream, const char *format, va_list ap)
‪Write a formatted character string to the given stream.
PCL_PUBLIC int pcl_vfwprintf (FILE *stream, const wchar_t *format, va_list ap)
‪Write a formatted character string to the given stream.
PCL_PUBLIC int pcl_sprintf (char *buf, size_t size, const char *format,...)
‪Write a formatted character string to a buffer.
PCL_PUBLIC int pcl_swprintf (wchar_t *buf, size_t size, const wchar_t *format,...)
‪Write a formatted character string to a buffer.
PCL_PUBLIC int pcl_vsprintf (char *buf, size_t size, const char *format, va_list ap)
‪Write a formatted character string to a buffer.
PCL_PUBLIC int pcl_vswprintf (wchar_t *buf, size_t size, const wchar_t *format, va_list ap)
‪Write a formatted character string to a buffer.
PCL_PUBLIC int pcl_asprintf (char **out, const char *format,...)
‪Write a formatted character string to an allocated buffer.
PCL_PUBLIC int pcl_aswprintf (wchar_t **out, const wchar_t *format,...)
‪Write a formatted character string to an allocated buffer.
PCL_PUBLIC int pcl_vasprintf (char **out, const char *format, va_list ap)
‪Write a formatted character string to an allocated buffer.
PCL_PUBLIC int pcl_vaswprintf (wchar_t **out, const wchar_t *format, va_list ap)
‪Write a formatted character string to an allocated buffer.
int pcl_pprintf (const pchar_t *format,...)
‪Write a formatted character string to stdout.
int pcl_vpprintf (const pchar_t *format, va_list ap)
‪Write a formatted character string to stdout.
int pcl_fpprintf (FILE *stream, const pchar_t *format,...)
‪Write a formatted character string to a stream.
int pcl_vfpprintf (FILE *stream, const pchar_t *format, va_list ap)
‪Write a formatted character string to the given stream.
int pcl_spprintf (pchar_t *buf, size_t size, const pchar_t *format,...)
‪Write a formatted character string to a buffer.
int pcl_vspprintf (pchar_t *buf, size_t size, const pchar_t *format, va_list ap)
‪Write a formatted character string to a buffer.
int pcl_aspprintf (pchar_t **out, const pchar_t *format,...)
‪Write a formatted character string to an allocated buffer.
int pcl_vaspprintf (pchar_t **out, const pchar_t *format, va_list ap)
‪Write a formatted character string to an allocated buffer.
Detailed Description
The IO module defines some basic IO functions as well as a suite of printf-style formatting functions.
Function Documentation
pcl_fopen()
PCL_PUBLIC FILE* pcl_fopen (const pchar_t * path, const pchar_t * mode)
#include <pcl/io.h>
‪Opens a FILE stream for reading and/or writing.
Parameters
path ‪absolute or relative path
mode ‪Can be 'r', 'r+', 'w', 'w+', 'a', 'a+', see any unix man page. Supports 'b'.
Returns
‪a valid stream or NULL on error
Definition at line 37 of file fopen.c.
References PCL_EINVAL, pcl_err_crt2os(), R_SETERR, SETOSERRMSG, and strempty.
pcl_popen()
PCL_PUBLIC FILE* pcl_popen (const pchar_t * command, ...)
#include <pcl/io.h>
‪Pipe a stream to or from a process.
This differs from the POSIX popen in that there is no type argument. Instead, this uses redirection symbols like a Unix shell.
Note
‪The Windows CRT popen only works when used within a console application. PCL's popen has no such restriction. This function internally calls pcl_proc_exec.
Mode     Description         Same as...
  <      read from stdout    popen("cmd", "r")
  >      write to stdin      popen("cmd", "w")
  ^      read from stderr    [no equivalent]
The below documents the other "flags" that can be specified in mode:
  !      set O_NONBLOCK      [no equivalent]
// read from the process's stdout without blocking. Process created with
// the following command: `ls -l /home/username`
pchar_t *homedir = pcl_getenv("HOME");
FILE *stream = pcl_popen(_P("<! ls -l %Ps"), homedir);
pcl_free(homedir);
Parameters
command ‪pointer to the command and optional flags
... ‪variable arguments
Returns
‪stream pointer or NULL on error
Definition at line 40 of file popen.c.
References pcl_proc_exec_t::command, pcl_proc_exec_t::f_stderr, pcl_proc_exec_t::f_stdin, pcl_proc_exec_t::f_stdout, PCL_EINVAL, PCL_EXEC_STDERR, PCL_EXEC_STDERR_NB, PCL_EXEC_STDIN, PCL_EXEC_STDIN_NB, PCL_EXEC_STDOUT, PCL_EXEC_STDOUT_NB, pcl_fdopen(), pcl_file_close(), pcl_free(), pcl_proc_exec(), pcl_vaspprintf(), R_SETERR, R_SETERRMSG, R_TRC, strempty, and TRC.
pcl_fileno()
PCL_PUBLIC int pcl_fileno (FILE * stream)
#include <pcl/io.h>
‪Get a file descriptor from a stream.
Parameters
stream ‪pointer to a FILE stream
Returns
‪file descriptor or -1 on error
Definition at line 36 of file fileno.c.
References SETLASTERR.
pcl_fdopen()
PCL_PUBLIC FILE* pcl_fdopen (pcl_file_t * file)
#include <pcl/io.h>
‪Open a file handle as a stream.
On success, a file stream is returned that must be closed via fclose. The provided file handle is released and cannot be used again. However, if this function fails, the caller is still repsonsible for closing the given file handle.
pcl_file_t *file = open_a_file();
FILE *fp = pcl_fdopen(file);
if(fp) // success
{
  fprintf(fp, "'fp' is valid here! 'file' is not.\n");
  fclose(fp);
}
else // failure
{
  printf("'file' is valid here. 'fp' is not.\n");
  pcl_file_close(file); // callee's responsibility
}
Parameters
file ‪pointer to a file handle
Returns
‪a file stream that must be closed with fclose
Definition at line 41 of file fdopen.c.
References tag_pcl_file::fd, tag_pcl_file::flags, FREEZE_ERR, PCL_BADFD, PCL_EINVAL, pcl_err_crt2os(), PCL_FF_RDWR, PCL_FF_WRITE, pcl_file_close(), R_SETOSERR, SETERR, and SETLASTERR.
Referenced by pcl_popen(), and pcl_tmpfile().
pcl_tmpfile()
PCL_PUBLIC FILE* pcl_tmpfile (const pchar_t * dir, const pchar_t * prefix, const pchar_t * suffix, pchar_t ** pathp, bool keep)
#include <pcl/io.h>
‪Create and open a unique temporary file.
This function will make several attempts to create the unique temporary file. The below is a list (in order) of what directories are attempted:
‪try the dir argument
‪Windows TMP or Unix TMPDIR
‪Windows TEMP or Unix P_tmpdir
"."
Parameters
dir ‪Optional directory path to create temp file within, can be NULL.
prefix ‪Optional prefix for the generated pathname. Can be NULL
suffix ‪Optional suffix for the generated pathname. Can be NULL
pathp ‪pointer to a pchar_t string that will receive the temp pathname. This can be NULL. When not NULL, this must be freed by the caller.
keep ‪If false, returned temp file will be automatically deleted once closed. When true, the file will persist after file close.
Returns
Definition at line 47 of file tmpfile.c.
References _P, countof, min, tag_pcl_stat::mode, PCL_EINVAL, PCL_ENOTFOUND, pcl_fdopen(), pcl_file_close(), pcl_file_open(), pcl_free(), pcl_free_safe(), pcl_getenv(), pcl_hex_encode(), PCL_MAXNAME, PCL_O_CREAT, PCL_O_EXCL, PCL_O_RDWR, PCL_O_TEMP, pcl_pcslen(), pcl_pmalloc(), pcl_rand(), pcl_spprintf(), pcl_stat, R_SETERR, R_SETERRMSG, R_TRC, RANDLEN, S_IRUSR, S_ISDIR, and S_IWUSR.
pcl_printf()
PCL_PUBLIC int pcl_printf (const char * format, ...)
#include <pcl/io.h>
‪Write a formatted character string to stdout.
Parameters
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
... ‪variable arguments matching format
Returns
‪number of characters written to stdout or a negative PCL error code.
pcl_wprintf()
PCL_PUBLIC int pcl_wprintf (const wchar_t * format, ...)
#include <pcl/io.h>
‪Write a formatted character string to stdout.
Parameters
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
... ‪variable arguments matching format
Returns
‪number of characters written to stdout or a negative PCL error code.
pcl_vprintf()
PCL_PUBLIC int pcl_vprintf (const char * format, va_list ap)
#include <pcl/io.h>
‪Write a formatted character string to stdout.
Parameters
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
ap ‪variable argument list
Returns
‪number of characters written to stdout or a negative PCL error code.
pcl_vwprintf()
PCL_PUBLIC int pcl_vwprintf (const wchar_t * format, va_list ap)
#include <pcl/io.h>
‪Write a formatted character string to stdout.
Parameters
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
ap ‪variable argument list
Returns
‪number of characters written to stdout or a negative PCL error code.
pcl_fprintf()
PCL_PUBLIC int pcl_fprintf (FILE * stream, const char * format, ...)
#include <pcl/io.h>
‪Write a formatted character string to a stream.
Parameters
stream ‪file stream to write to
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
... ‪variable arguments matching format
Returns
‪number of characters written to the stream or a negative PCL error code.
Referenced by pcl_log_vevent().
pcl_fwprintf()
PCL_PUBLIC int pcl_fwprintf (FILE * stream, const wchar_t * format, ...)
#include <pcl/io.h>
‪Write a formatted character string to a stream.
Parameters
stream ‪file stream to write to
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
... ‪variable arguments matching format
Returns
‪number of characters written to the stream or a negative PCL error code.
pcl_vfprintf()
PCL_PUBLIC int pcl_vfprintf (FILE * stream, const char * format, va_list ap)
#include <pcl/io.h>
‪Write a formatted character string to the given stream.
Parameters
stream ‪file stream to write to
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
ap ‪variable argument list
Returns
‪number of characters written to the stream or a negative PCL error code.
pcl_vfwprintf()
PCL_PUBLIC int pcl_vfwprintf (FILE * stream, const wchar_t * format, va_list ap)
#include <pcl/io.h>
‪Write a formatted character string to the given stream.
Parameters
stream ‪file stream to write to
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
ap ‪variable argument list
Returns
‪number of characters written to the stream or a negative PCL error code.
pcl_sprintf()
PCL_PUBLIC int pcl_sprintf (char * buf, size_t size, const char * format, ...)
#include <pcl/io.h>
‪Write a formatted character string to a buffer.
Parameters
buf ‪pointer to a buffer, set to NULL to query output length (excluding NUL)
size ‪character length of buf, ignored if buf is NULL
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
... ‪variable arguments matching format
Returns
‪number of characters written to buf or if buf is NULL, the number of characters that would have been written to buf. On error, a negative PCL error code is returned.
Referenced by ipcl_err_serialize(), ipcl_win32_sid_to_name(), pcl_fdpath(), pcl_log_vevent(), and pcl_unix_siginfo().
pcl_swprintf()
PCL_PUBLIC int pcl_swprintf (wchar_t * buf, size_t size, const wchar_t * format, ...)
#include <pcl/io.h>
‪Write a formatted character string to a buffer.
Parameters
buf ‪pointer to a buffer, set to NULL to query output length (excluding NUL)
size ‪character length of buf, ignored if buf is NULL
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
... ‪variable arguments matching format
Returns
‪number of characters written to buf or if buf is NULL, the number of characters that would have been written to buf. On error, a negative PCL error code is returned.
pcl_vsprintf()
PCL_PUBLIC int pcl_vsprintf (char * buf, size_t size, const char * format, va_list ap)
#include <pcl/io.h>
‪Write a formatted character string to a buffer.
Parameters
buf ‪pointer to a buffer, set to NULL to query output length (excluding NUL)
size ‪character length of buf, ignored if buf is NULL
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
ap ‪variable argument list
Returns
‪number of characters written to buf or if buf is NULL, the number of characters that would have been written to buf. On error, a negative PCL error code is returned.
Referenced by pcl_buf_vputf(), and pcl_err_vtrace().
pcl_vswprintf()
PCL_PUBLIC int pcl_vswprintf (wchar_t * buf, size_t size, const wchar_t * format, va_list ap)
#include <pcl/io.h>
‪Write a formatted character string to a buffer.
Parameters
buf ‪pointer to a buffer, set to NULL to query output length (excluding NUL)
size ‪character length of buf, ignored if buf is NULL
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
ap ‪variable argument list
Returns
‪number of characters written to buf or if buf is NULL, the number of characters that would have been written to buf. On error, a negative PCL error code is returned.
Referenced by pcl_buf_vputf().
pcl_asprintf()
PCL_PUBLIC int pcl_asprintf (char ** out, const char * format, ...)
#include <pcl/io.h>
‪Write a formatted character string to an allocated buffer.
Parameters
[out] out ‪pointer to an output pointer, this must be freed by caller. set to NULL to query output length (excluding NUL)
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
... ‪variable arguments matching format
Returns
‪number of characters written to out or if out is NULL, the number of characters that would have been written to out. On error, a negative PCL error code is returned.
Referenced by pcl_log_vevent().
pcl_aswprintf()
PCL_PUBLIC int pcl_aswprintf (wchar_t ** out, const wchar_t * format, ...)
#include <pcl/io.h>
‪Write a formatted character string to an allocated buffer.
Parameters
[out] out ‪pointer to an output pointer, this must be freed by caller. set to NULL to query output length (excluding NUL)
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
... ‪variable arguments matching format
Returns
‪number of characters written to out or if out is NULL, the number of characters that would have been written to out. On error, a negative PCL error code is returned.
pcl_vasprintf()
PCL_PUBLIC int pcl_vasprintf (char ** out, const char * format, va_list ap)
#include <pcl/io.h>
‪Write a formatted character string to an allocated buffer.
Parameters
[out] out ‪pointer to an output pointer, this must be freed by caller. set to NULL to query output length (excluding NUL)
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
ap ‪variable argument list
Returns
‪number of characters written to out or if out is NULL, the number of characters that would have been written to out. On error, a negative PCL error code is returned.
Referenced by pcl_err_vjson(), and pcl_log_vevent().
pcl_vaswprintf()
PCL_PUBLIC int pcl_vaswprintf (wchar_t ** out, const wchar_t * format, va_list ap)
#include <pcl/io.h>
‪Write a formatted character string to an allocated buffer.
Parameters
[out] out ‪pointer to an output pointer, this must be freed by caller. set to NULL to query output length (excluding NUL)
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
ap ‪variable argument list
Returns
‪number of characters written to out or if out is NULL, the number of characters that would have been written to out. On error, a negative PCL error code is returned.
pcl_pprintf()
int pcl_pprintf (const pchar_t * format, ...)
#include <pcl/io.h>
‪Write a formatted character string to stdout.
Parameters
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
... ‪variable arguments matching format
Returns
‪number of characters written to stdout or a negative PCL error code.
Note
‪implemented as a macro
pcl_vpprintf()
int pcl_vpprintf (const pchar_t * format, va_list ap)
#include <pcl/io.h>
‪Write a formatted character string to stdout.
Parameters
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
ap ‪variable argument list
Returns
‪number of characters written to stdout or a negative PCL error code.
Note
‪implemented as a macro
pcl_fpprintf()
int pcl_fpprintf (FILE * stream, const pchar_t * format, ...)
#include <pcl/io.h>
‪Write a formatted character string to a stream.
Parameters
stream ‪file stream to write to
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
... ‪variable arguments matching format
Returns
‪number of characters written to the stream or a negative PCL error code.
Note
‪implemented as a macro
pcl_vfpprintf()
int pcl_vfpprintf (FILE * stream, const pchar_t * format, va_list ap)
#include <pcl/io.h>
‪Write a formatted character string to the given stream.
Parameters
stream ‪file stream to write to
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
ap ‪variable argument list
Returns
‪number of characters written to the stream or a negative PCL error code.
Note
‪implemented as a macro
pcl_spprintf()
int pcl_spprintf (pchar_t * buf, size_t size, const pchar_t * format, ...)
#include <pcl/io.h>
‪Write a formatted character string to a buffer.
Parameters
buf ‪pointer to a buffer, set to NULL to query output length (excluding NUL)
size ‪character length of buf, ignored if buf is NULL
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
... ‪variable arguments matching format
Returns
‪number of characters written to buf or if buf is NULL, the number of characters that would have been written to buf. On error, a negative PCL error code is returned.
Note
‪implemented as a macro
Referenced by pcl_proc_exec(), and pcl_tmpfile().
pcl_vspprintf()
int pcl_vspprintf (pchar_t * buf, size_t size, const pchar_t * format, va_list ap)
#include <pcl/io.h>
‪Write a formatted character string to a buffer.
Parameters
buf ‪pointer to a buffer, set to NULL to query output length (excluding NUL)
size ‪character length of buf, ignored if buf is NULL
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
ap ‪variable argument list
Returns
‪number of characters written to buf or if buf is NULL, the number of characters that would have been written to buf. On error, a negative PCL error code is returned.
Note
‪implemented as a macro
pcl_aspprintf()
int pcl_aspprintf (pchar_t ** out, const pchar_t * format, ...)
#include <pcl/io.h>
‪Write a formatted character string to an allocated buffer.
Parameters
[out] out ‪pointer to an output pointer, this must be freed by caller. set to NULL to query output length (excluding NUL)
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
... ‪variable arguments matching format
Returns
‪number of characters written to out or if out is NULL, the number of characters that would have been written to out. On error, a negative PCL error code is returned.
Note
‪implemented as a macro
Referenced by pcl_fdpath(), and pcl_readdir().
pcl_vaspprintf()
int pcl_vaspprintf (pchar_t ** out, const pchar_t * format, va_list ap)
#include <pcl/io.h>
‪Write a formatted character string to an allocated buffer.
Parameters
[out] out ‪pointer to an output pointer, this must be freed by caller. set to NULL to query output length (excluding NUL)
format ‪format specifier string. PCL includes extensions: "%/" is the platform-specific path separater character, "%Ps" is a portable character string and "%Pc" is a portable character.
ap ‪variable argument list
Returns
‪number of characters written to out or if out is NULL, the number of characters that would have been written to out. On error, a negative PCL error code is returned.
Note
‪implemented as a macro
Referenced by pcl_popen().