‪libpcl: ‪Array Management
Array Management
‪An array is a pointer table of allocated elements.
Data Structures
struct tag_pcl_array
Functions
PCL_PUBLIC pcl_array_t * pcl_array (int initial_capacity, pcl_cleanup_t cleanup)
‪Create an array.
PCL_PUBLIC void * pcl_array_get (pcl_array_t *arr, int index)
‪Get an element from an array.
PCL_PUBLIC int pcl_array_indexof (pcl_array_t *arr, void *elem, pcl_compare_t compare)
‪Find the index of an array element value.
PCL_PUBLIC int pcl_array_set (pcl_array_t *arr, void *elem, int index)
‪Set an element of an array, replacing a possible existing element.
PCL_PUBLIC int pcl_array_insert (pcl_array_t *arr, void *elem, int index)
‪Insert an element.
PCL_PUBLIC int pcl_array_remove (pcl_array_t *arr, int index)
‪Remove an element from an array.
PCL_PUBLIC pcl_array_t * pcl_array_sort (pcl_array_t *arr, pcl_compare_t compare)
‪Sort an array using qsort.
PCL_PUBLIC void pcl_array_free (pcl_array_t *arr)
‪Free an array.
PCL_INLINE int pcl_array_append (pcl_array_t *arr, void *elem)
Detailed Description
An array is a pointer table of allocated elements.
This differs from a PCL vector in that there is no concept of element size. The elements are user allocated pointers that can all be the same type of object, different objects or even NULL.
It is common to interact (read) with an array's elements directly, while this is cumbersome with a vector. Although a vector can be used like a pointer table, it is a bit awkward because elements must be added as pointers to pointers: element size would be sizeof(void*). Thus, when getting an element from a vector, one must dereference the element value: *(void **) pcl_vector_get(v, 0).
Create argv array
// create an argv array of 4 arguments with a trailing NULL,
// including the file to be executed and trailing NULL.
pcl_array_t *arr = pcl_array(6, pcl_cleanup_ptr);
char *file = strdup("some_program");
pcl_array_append(arr, file);
pcl_array_append(arr, strdup("-a"));
pcl_array_append(arr, strdup("--quiet"));
pcl_array_append(arr, strdup("--file=\"example/file.txt\""));
pcl_array_append(arr, strdup("-t"));
// element 5 already NULL
// replace element 4 with -b, cleanup handler called for element 4
if(something_is_true)
  pcl_array_set(arr, strdup("-b"), 4);
// remove quiet if noisey is true, internally does a cleanup and memmove
if(noisey)
  pcl_array_remove(arr, 2);
// note, any unset element defaults to NULL.
execv(file, arr->elements);
pcl_array_free(arr);
Function Documentation
pcl_array()
PCL_PUBLIC pcl_array_t* pcl_array (int initial_capacity, pcl_cleanup_t cleanup)
#include <pcl/array.h>
‪Create an array.
Parameters
initial_capacity ‪initial size of array
cleanup ‪pointer to a cleanup routine.
Returns
‪pointer to a new array object
See also
‪pcl_cleanup_ptr
Definition at line 36 of file array.c.
References tag_pcl_array::capacity, tag_pcl_array::cleanup, tag_pcl_array::count, tag_pcl_array::elements, max, pcl_malloc(), and pcl_zalloc().
Referenced by pcl_htable_keys(), pcl_json_arr(), pcl_net_dnstxtrec(), pcl_net_resolve(), pcl_proc_parsecmd(), and pcl_ssl_certentry().
pcl_array_get()
PCL_PUBLIC void* pcl_array_get (pcl_array_t * arr, int index)
#include <pcl/array.h>
‪Get an element from an array.
This is typically not used when iterating over an array, as one can just directly access the element via the elements member. However, this is useful for cases when not looping an array as it performs bounds checking of index.
Parameters
arr ‪pointer to an array object
index ‪element index
Returns
‪pointer to an element or NULL on error. To distinguish between an error and a NULL element, check pcl_errno. It will be PCL_EOKAY if a NULL element.
Definition at line 37 of file array_get.c.
References tag_pcl_array::count, tag_pcl_array::elements, PCL_EINDEX, PCL_EINVAL, pcl_err_clear(), and R_SETERR.
Referenced by pcl_json_arrget().
pcl_array_indexof()
PCL_PUBLIC int pcl_array_indexof (pcl_array_t * arr, void * elem, pcl_compare_t compare)
#include <pcl/array.h>
‪Find the index of an array element value.
Parameters
arr ‪pointer to an array object
elem ‪pointer to an element value
compare ‪a comparator function. If NULL, pointer addresses are compared directly
Returns
‪index or -1 if not found
Definition at line 35 of file array_indexof.c.
References tag_pcl_array::count, and tag_pcl_array::elements.
Referenced by pcl_event_unregister().
pcl_array_set()
PCL_PUBLIC int pcl_array_set (pcl_array_t * arr, void * elem, int index)
#include <pcl/array.h>
‪Set an element of an array, replacing a possible existing element.
When setting elements, the array's count is not consulted. Instead, this allows a set operation as long as index is less than capacity. This will set count to index + 1 if count is less than index + 1. This is very different than pcl_array_insert or pcl_array_append, which always inserts an element, bound to array's current count, and growing the array if required. When performing a set operation, the array is never grown. Thus, trying to set an element at an index greater than or equal to capacity will throw a PCL_EINDEX error.
If an element exists at index, it is removed and passed to the cleanup handler if both the cleanup handler and element are not NULL.
If setting an element past count, all elements between count and index will be NULL.
Parameters
arr ‪arr pointer to an array object
elem ‪pointer to an element
index ‪element index
Returns
‪0 for success and -1 on error.
See also
‪pcl_array_append
Definition at line 36 of file array_set.c.
References tag_pcl_array::capacity, tag_pcl_array::cleanup, tag_pcl_array::count, tag_pcl_array::elements, PCL_EINDEX, PCL_EINVAL, and SETERR.
pcl_array_insert()
PCL_PUBLIC int pcl_array_insert (pcl_array_t * arr, void * elem, int index)
#include <pcl/array.h>
‪Insert an element.
Parameters
arr ‪pointer to an array object
elem ‪pointer to an element
index ‪the insertion index. this can be equal to the array's current count, in which case elem is appended
Returns
‪the new element count or -1 on error.
See also
‪pcl_array_set
Definition at line 38 of file array_insert.c.
References tag_pcl_array::capacity, tag_pcl_array::count, tag_pcl_array::elements, PCL_EINVAL, pcl_realloc(), and SETERR.
Referenced by pcl_array_append().
pcl_array_remove()
PCL_PUBLIC int pcl_array_remove (pcl_array_t * arr, int index)
#include <pcl/array.h>
‪Remove an element from an array.
This will call the cleanup handler if both the cleanup handler and element at index are not NULL.
Parameters
arr ‪pointer to an array object
index ‪element index
Returns
‪the new count of element or -1 on error.
Definition at line 37 of file array_remove.c.
References tag_pcl_array::cleanup, tag_pcl_array::count, tag_pcl_array::elements, PCL_EINDEX, PCL_EINVAL, and SETERR.
Referenced by pcl_event_unregister(), and pcl_json_arrremove().
pcl_array_sort()
PCL_PUBLIC pcl_array_t* pcl_array_sort (pcl_array_t * arr, pcl_compare_t compare)
#include <pcl/array.h>
‪Sort an array using qsort.
Parameters
arr ‪pointer to an array object
compare ‪pointer to a function comparator whose behavior is identical to qsort
Returns
‪pointer to the arr argument
Definition at line 42 of file array_sort.c.
References tag_pcl_array::count, and tag_pcl_array::elements.
pcl_array_free()
PCL_PUBLIC void pcl_array_free (pcl_array_t * arr)
#include <pcl/array.h>
‪Free an array.
This will call the cleanup handler, if not NULL, for all elements that are not NULL and then free the array object.
Parameters
arr ‪pointer to an array object
Definition at line 36 of file array_free.c.
References tag_pcl_array::cleanup, tag_pcl_array::count, tag_pcl_array::elements, pcl_free(), and pcl_free_safe().
Referenced by pcl_json_free(), pcl_proc_exec(), and pcl_proc_parsecmd().
pcl_array_append()
PCL_INLINE int pcl_array_append (pcl_array_t * arr, void * elem)
#include <pcl/array.h>
Definition at line 177 of file array.h.
References tag_pcl_array::count, and pcl_array_insert().
Referenced by pcl_event_register(), pcl_htable_keys(), pcl_json_arradd(), pcl_net_dnstxtrec(), pcl_net_resolve(), pcl_proc_parsecmd(), and pcl_ssl_certentry().