‪libpcl: ‪JSON Decoder and Encoder
JSON Decoder and Encoder
‪A JSON encoder and decoder.
Modules
Control Flags
‪A set of flags to control the handling of errors and strings.
Object Management
‪A set of functions for managing JSON objects of type object.
Array Management
‪A set of functions for managing JSON objects of type array.
Data Structures
struct tag_pcl_json
‪A JSON value object.
Macros
#define PCL_JSON_INVINT LONG_LONG_MIN
‪Invalid JSON integer value used as return value.
#define PCL_JSON_INVREAL DBL_MIN
‪Invalid JSON real value use as return value.
#define pcl_json_isnull(_j) ((_j) ? (_j)->type == 0 : false)
‪Indicates if a json object is a null value.
#define pcl_json_isbool(_j) ((_j) ? (_j)->type == 'b' : false)
‪Indicates if a json object is a boolean value.
#define pcl_json_istrue(_j) ((_j) ? pcl_json_isbool(_j) && (_j)->boolean : false)
‪Indicates if a json object is a boolean true value.
#define pcl_json_isfalse(_j) ((_j) ? pcl_json_isbool(_j) && !(_j)->boolean : false)
‪Indicates if a json object is a boolean false value.
#define pcl_json_isreal(_j) ((_j) ? (_j)->type == 'r' : false)
‪Indicates if a json object is a real value.
#define pcl_json_isint(_j) ((_j) ? (_j)->type == 'i' : false)
‪Indicates if a json object is an integer value.
#define pcl_json_isnum(_j) (pcl_json_isreal(_j) || pcl_json_isint(_j))
‪Indicates if a json object is a number (integer or real) value.
#define pcl_json_isstr(_j) ((_j) ? (_j)->type == 's' : false)
‪Indicates if a json object is a string value.
#define pcl_json_isarr(_j) ((_j) ? (_j)->type == 'a' : false)
‪Indicates if a json object is an array value.
#define pcl_json_isobj(_j) ((_j) ? (_j)->type == 'o' : false)
‪Indicates if a json object is an object value.
Typedefs
typedef struct tag_pcl_json pcl_json_t
‪A JSON value object.
Functions
PCL_PUBLIC pcl_json_t * pcl_json_decode (const char *json, size_t len, const char **end)
‪Decode a JSON string.
PCL_PUBLIC char * pcl_json_encode (pcl_json_t *value, bool format)
‪Encode a json object as a string.
PCL_PUBLIC pcl_json_path_t * pcl_json_compile (const char *path)
‪Compile a json path.
PCL_PUBLIC void pcl_json_freepath (pcl_json_path_t *path)
‪Release all resources used by a json path object.
PCL_PUBLIC pcl_array_t * pcl_json_match (pcl_json_t *j, const pcl_json_path_t *path)
‪Match a JSON value against a compiled JSON Path.
PCL_PUBLIC pcl_array_t * pcl_json_query (pcl_json_t *j, const char *path)
‪Query a json object with a path.
PCL_PUBLIC void pcl_json_free (pcl_json_t *j)
‪Release all resources used by a json value.
PCL_PUBLIC int pcl_json_count (const pcl_json_t *j)
‪Get count of array elements or object keys.
PCL_PUBLIC pcl_json_t * pcl_json_str (char *str, uint32_t flags)
‪Create a string object.
PCL_PUBLIC pcl_json_t * pcl_json_strn (const char *str, size_t len, uint32_t flags)
‪Create a string object.
PCL_PUBLIC pcl_json_t * pcl_json_bool (bool value)
‪Create a boolean value.
PCL_PUBLIC pcl_json_t * pcl_json_true (void)
‪Create a boolean true value.
PCL_PUBLIC pcl_json_t * pcl_json_false (void)
‪Create a boolean false value.
PCL_PUBLIC pcl_json_t * pcl_json_null (void)
‪Create a null value.
PCL_PUBLIC pcl_json_t * pcl_json_real (double real)
‪Create a json real (number) object.
PCL_PUBLIC pcl_json_t * pcl_json_int (long long integer)
‪Create a json integer (number) object.
PCL_INLINE pcl_json_t * pcl_json_ref (pcl_json_t *j, int amt)
‪Increase or decrease a json object's reference count.
Detailed Description
A JSON encoder and decoder.
Macro Definition Documentation
PCL_JSON_INVINT
#define PCL_JSON_INVINT LONG_LONG_MIN
#include <pcl/json.h>
‪Invalid JSON integer value used as return value.
See also
‪pcl_json_objgetint, pcl_json_arrgetint
Definition at line 99 of file json.h.
PCL_JSON_INVREAL
#define PCL_JSON_INVREAL DBL_MIN
#include <pcl/json.h>
‪Invalid JSON real value use as return value.
See also
‪pcl_json_objgetreal, pcl_json_arrgetreal
Definition at line 105 of file json.h.
pcl_json_isnull
#define pcl_json_isnull (_j) ((_j) ? (_j)->type == 0 : false)
#include <pcl/json.h>
‪Indicates if a json object is a null value.
Parameters
_j ‪pointer to a json object
Returns
‪boolean
Definition at line 111 of file json.h.
pcl_json_isbool
#define pcl_json_isbool (_j) ((_j) ? (_j)->type == 'b' : false)
#include <pcl/json.h>
‪Indicates if a json object is a boolean value.
Parameters
_j ‪pointer to a json object
Returns
‪boolean
Definition at line 117 of file json.h.
pcl_json_istrue
#define pcl_json_istrue (_j) ((_j) ? pcl_json_isbool(_j) && (_j)->boolean : false)
#include <pcl/json.h>
‪Indicates if a json object is a boolean true value.
Parameters
_j ‪pointer to a json object
Returns
‪boolean
Definition at line 123 of file json.h.
pcl_json_isfalse
#define pcl_json_isfalse (_j) ((_j) ? pcl_json_isbool(_j) && !(_j)->boolean : false)
#include <pcl/json.h>
‪Indicates if a json object is a boolean false value.
Parameters
_j ‪pointer to a json object
Returns
‪boolean
Definition at line 129 of file json.h.
pcl_json_isreal
#define pcl_json_isreal (_j) ((_j) ? (_j)->type == 'r' : false)
#include <pcl/json.h>
‪Indicates if a json object is a real value.
Parameters
_j ‪pointer to a json object
Returns
‪boolean
Definition at line 135 of file json.h.
pcl_json_isint
#define pcl_json_isint (_j) ((_j) ? (_j)->type == 'i' : false)
#include <pcl/json.h>
‪Indicates if a json object is an integer value.
Parameters
_j ‪pointer to a json object
Returns
‪boolean
Definition at line 141 of file json.h.
pcl_json_isnum
#define pcl_json_isnum (_j) (pcl_json_isreal(_j) || pcl_json_isint(_j))
#include <pcl/json.h>
‪Indicates if a json object is a number (integer or real) value.
Parameters
_j ‪pointer to a json object
Returns
‪boolean
Definition at line 147 of file json.h.
pcl_json_isstr
#define pcl_json_isstr (_j) ((_j) ? (_j)->type == 's' : false)
#include <pcl/json.h>
‪Indicates if a json object is a string value.
Parameters
_j ‪pointer to a json object
Returns
‪boolean
Definition at line 153 of file json.h.
pcl_json_isarr
#define pcl_json_isarr (_j) ((_j) ? (_j)->type == 'a' : false)
#include <pcl/json.h>
‪Indicates if a json object is an array value.
Parameters
_j ‪pointer to a json object
Returns
‪boolean
Definition at line 159 of file json.h.
pcl_json_isobj
#define pcl_json_isobj (_j) ((_j) ? (_j)->type == 'o' : false)
#include <pcl/json.h>
‪Indicates if a json object is an object value.
Parameters
_j ‪pointer to a json object
Returns
‪boolean
Definition at line 165 of file json.h.
Typedef Documentation
pcl_json_t
typedef struct tag_pcl_json pcl_json_t
#include <pcl/types.h>
‪A JSON value object.
This represents any valid JSON value: boolean, number (integer or real), string, null, array or object.
Definition at line 74 of file types.h.
Function Documentation
pcl_json_decode()
PCL_PUBLIC pcl_json_t* pcl_json_decode (const char * json, size_t len, const char ** end)
#include <pcl/json.h>
‪Decode a JSON string.
This parses a JSON string that represents a single JSON value. A JSON value can be an object {}, array [], string "", number -102.84, boolean true or false or a null null. Parsing stops when the parsing of the JSON value at json is complete, regardless of the len argument. However, if a complete JSON value is not found before reaching json + len, an error occurs. The json string can contain bogus data after the value being parsed, since the parser stops at the end of the value. For example:
{
  "name": "Henry Ford"
}#invalid json here
The above is completely valid, since a valid JSON object exists and ends before any invalid JSON text is encountered. When the end argument is supplied, it would be pointing at the '#' in the above example. This is very useful if a string contains multiple JSON values. pcl_json_decode can be called multiple times by passing the value of end as json, allowing one to iterate through a series of json values.
Parameters
json ‪pointer to a json string. This must be NUL terminated if len is 0.
len ‪number of bytes within json argument. If 0, json must be NUL terminated.
end ‪pointer to the first character not parsed. This can be NULL.
Returns
‪pointer to a json value or NULL on error
Definition at line 37 of file json_decode.c.
References ipcl_json_state_t::ctx, ipcl_json_state_t::end, ipcl_json_parse_value(), ipcl_json_state_t::line, min, ipcl_json_state_t::next, PCL_EINVAL, R_SETERR, R_SETERRMSG, and R_TRCMSG.
pcl_json_encode()
PCL_PUBLIC char* pcl_json_encode (pcl_json_t * value, bool format)
#include <pcl/json.h>
‪Encode a json object as a string.
Parameters
value ‪pointer to a json object
format ‪if true, spaces and tabs will be added to the output.
Returns
‪poin ter to an allocated json string
Definition at line 37 of file json_encode.c.
References ipcl_json_encode_t::b, tag_pcl_buf::data, ipcl_json_encode_t::format, ipcl_json_encode_value(), pcl_buf_clear(), pcl_buf_init(), PclBufText, and ipcl_json_encode_t::tabs.
pcl_json_compile()
PCL_PUBLIC pcl_json_path_t* pcl_json_compile (const char * path)
#include <pcl/json.h>
‪Compile a json path.
Parameters
path ‪A JSONPath string. This doesn't support filters.
Returns
‪pointer to a compiled json path object which must be freed with pcl_json_freepath.
Definition at line 39 of file json_compile.c.
References tag_pcl_json_path::idx_list, tag_pcl_json_path::idx_slice, tag_pcl_json_path::index, tag_pcl_json_path::member, tag_pcl_json_path::next, PCL_ESYNTAX, pcl_free(), pcl_json_freepath(), pcl_malloc(), pcl_strndup(), pcl_strskipws(), pcl_strtoi(), pcl_vector(), pcl_vector_append(), pcl_vector_free(), PclPathElement, PclPathElementList, PclPathElementSlice, PclPathMember, PclPathRecursiveDescent, PclPathRoot, PclPathWildcardElement, PclPathWildcardMember, R_SETERRMSG, R_TRCMSG, and tag_pcl_json_path::type.
Referenced by pcl_json_query().
pcl_json_freepath()
PCL_PUBLIC void pcl_json_freepath (pcl_json_path_t * path)
#include <pcl/json.h>
‪Release all resources used by a json path object.
Parameters
path ‪pointer to a path object.
Definition at line 37 of file json_freepath.c.
References tag_pcl_json_path::next, pcl_free(), pcl_free_safe(), pcl_vector_free(), PclPathElementList, and PclPathMember.
Referenced by pcl_json_compile(), and pcl_json_query().
pcl_json_match()
PCL_PUBLIC pcl_array_t* pcl_json_match (pcl_json_t * j, const pcl_json_path_t * path)
#include <pcl/json.h>
‪Match a JSON value against a compiled JSON Path.
Parameters
j ‪pointer to a json value
path ‪a compiled JSON Path
Returns
‪a pointer to an array of pcl_json_t values or NULL on error. Each json value's reference count has been increased by one. This array can be empty. Free with pcl_array_free.
Definition at line 228 of file json_match.c.
References tag_pcl_json::array, pcl_json_arr(), and pcl_json_free().
Referenced by pcl_json_query().
pcl_json_query()
PCL_PUBLIC pcl_array_t* pcl_json_query (pcl_json_t * j, const char * path)
#include <pcl/json.h>
‪Query a json object with a path.
Internally, this performs a pcl_json_compile followed by pcl_json_match. Although this is convenient, if a compiled path is to be used across many documents, it is better to compile and then use the match function.
Parameters
j ‪pointer to a json object
path ‪json path
Returns
‪a pointer to an array of pcl_json_t values or NULL on error. Each json value's reference count has been increased by one. This array can be empty. Free with pcl_array_free.
Definition at line 35 of file json_query.c.
References PCL_EINVAL, pcl_json_compile(), pcl_json_freepath(), pcl_json_match(), R_SETERR, and R_TRC.
pcl_json_free()
PCL_PUBLIC void pcl_json_free (pcl_json_t * j)
#include <pcl/json.h>
‪Release all resources used by a json value.
When the given json object's reference count is one, it will be freed. If greater than one, its reference count will be decremeted but it will not be freed.
Parameters
j ‪pointer to a json object
See also
‪pcl_json_ref
Definition at line 38 of file json_free.c.
References tag_pcl_json::array, tag_pcl_json::object, pcl_array_free(), pcl_free(), pcl_free_safe(), pcl_htable_free(), pcl_json_false(), pcl_json_null(), pcl_json_ref(), pcl_json_true(), tag_pcl_json::string, and tag_pcl_json::type.
Referenced by ipcl_json_parse_array(), ipcl_json_parse_object(), pcl_err_vjson(), pcl_json_arradd(), pcl_json_match(), and pcl_json_objput().
pcl_json_count()
PCL_PUBLIC int pcl_json_count (const pcl_json_t * j)
#include <pcl/json.h>
‪Get count of array elements or object keys.
Parameters
j ‪json value which must be an object ore array
Returns
‪number of items or -1 on error
Definition at line 37 of file json_count.c.
References tag_pcl_json::array, tag_pcl_array::count, tag_pcl_htable::count, tag_pcl_json::object, PCL_ETYPE, pcl_json_isarr, pcl_json_isobj, and SETERR.
Referenced by pcl_err_setjson().
pcl_json_str()
PCL_PUBLIC pcl_json_t* pcl_json_str (char * str, uint32_t flags)
#include <pcl/json.h>
‪Create a string object.
Parameters
str ‪pointer to a NUL-terminated string
flags ‪bitmask of Control Flags. PCL_JSON_FREEVALONERR is ignored.
Returns
‪pointer to a json object or NULL on error. Note that a NULL str is an error unless PCL_JSON_ALLOWNULL is set.
See also
‪pcl_json_strn
Definition at line 37 of file json_str.c.
References tag_pcl_json::nrefs, PCL_EINVAL, PCL_JSON_ALLOWNULL, PCL_JSON_EMPTYASNULL, pcl_json_null(), PCL_JSON_SHALLOW, PCL_JSON_SKIPUTF8CHK, pcl_malloc(), pcl_strndup(), pcl_utf8_check(), R_SETERR, R_TRC, tag_pcl_json::string, and tag_pcl_json::type.
Referenced by ipcl_json_parse_value(), pcl_err_vjson(), pcl_json_arraddstr(), and pcl_json_objputstr().
pcl_json_strn()
PCL_PUBLIC pcl_json_t* pcl_json_strn (const char * str, size_t len, uint32_t flags)
#include <pcl/json.h>
‪Create a string object.
Note
‪this function always copies len characters of the given str. Shallow copy is not supported.
Parameters
str ‪pointer to string, which does not need to be NUL-terminated
len ‪number of characters to copy from str
flags ‪bitmask of Control Flags. PCL_JSON_SHALLOW and PCL_JSON_FREEVALONERR are ignored.
Returns
‪pointer to a json object or NULL on error. Note that a NULL str is an error unless PCL_JSON_ALLOWNULL is set.
See also
‪pcl_json_str
Definition at line 37 of file json_strn.c.
References tag_pcl_json::nrefs, PCL_EINVAL, PCL_JSON_ALLOWNULL, PCL_JSON_EMPTYASNULL, pcl_json_null(), PCL_JSON_SKIPUTF8CHK, pcl_malloc(), pcl_strndup(), pcl_utf8_check(), R_SETERR, R_TRC, tag_pcl_json::string, and tag_pcl_json::type.
pcl_json_bool()
PCL_PUBLIC pcl_json_t* pcl_json_bool (bool value)
#include <pcl/json.h>
‪Create a boolean value.
Note
‪this function returns a singleton
Parameters
value ‪boolean value, true or false.
Returns
‪pointer to a json boolean object
Definition at line 36 of file json_bool.c.
References pcl_json_false(), and pcl_json_true().
Referenced by pcl_json_arraddbool(), and pcl_json_objputbool().
pcl_json_true()
PCL_PUBLIC pcl_json_t* pcl_json_true (void)
#include <pcl/json.h>
‪Create a boolean true value.
Note
‪this function returns a singleton
Returns
‪pointer to a json boolean object
Definition at line 35 of file json_true.c.
References tag_pcl_json::type.
Referenced by ipcl_json_parse_value(), pcl_json_bool(), pcl_json_free(), and pcl_json_ref().
pcl_json_false()
PCL_PUBLIC pcl_json_t* pcl_json_false (void)
#include <pcl/json.h>
‪Create a boolean false value.
Note
‪this function returns a singleton
Returns
‪pointer to a json boolean object
Definition at line 35 of file json_false.c.
References tag_pcl_json::type.
Referenced by ipcl_json_parse_value(), pcl_json_bool(), pcl_json_free(), and pcl_json_ref().
pcl_json_null()
PCL_PUBLIC pcl_json_t* pcl_json_null (void)
#include <pcl/json.h>
‪Create a null value.
Note
‪this function returns a singleton
Returns
‪pointer to a json null object
Definition at line 36 of file json_null.c.
References tag_pcl_json::type.
Referenced by ipcl_json_parse_value(), pcl_json_arraddnull(), pcl_json_free(), pcl_json_objputnull(), pcl_json_ref(), pcl_json_str(), and pcl_json_strn().
pcl_json_real()
PCL_PUBLIC pcl_json_t* pcl_json_real (double real)
#include <pcl/json.h>
‪Create a json real (number) object.
Parameters
real ‪value. This value cannot be NaN, Infinity or PCL_JSON_INVREAL
Returns
‪pointer to a json real object
Definition at line 37 of file json_real.c.
References tag_pcl_json::nrefs, PCL_EINVAL, PCL_JSON_INVREAL, pcl_malloc(), R_SETERR, R_SETERRMSG, tag_pcl_json::real, and tag_pcl_json::type.
Referenced by ipcl_json_parse_number(), pcl_json_arraddreal(), and pcl_json_objputreal().
pcl_json_int()
PCL_PUBLIC pcl_json_t* pcl_json_int (long long integer)
#include <pcl/json.h>
‪Create a json integer (number) object.
Parameters
integer ‪value. This value cannot be PCL_JSON_INVINT
Returns
‪pointer to a json integer object
Definition at line 36 of file json_int.c.
References tag_pcl_json::integer, tag_pcl_json::nrefs, PCL_EINVAL, PCL_JSON_INVINT, pcl_malloc(), R_SETERR, and tag_pcl_json::type.
Referenced by ipcl_json_parse_number(), pcl_json_arraddint(), and pcl_json_objputint().
pcl_json_ref()
PCL_INLINE pcl_json_t* pcl_json_ref (pcl_json_t * j, int amt)
#include <pcl/json.h>
‪Increase or decrease a json object's reference count.
A json object is not freed by pcl_json_free until its reference count is zero.
Parameters
j ‪pointer to a json object
amt ‪amount to increase or decrease (negative) the object's reference count.
Returns
‪pointer to j
See also
‪pcl_json_free
Definition at line 697 of file json.h.
References tag_pcl_json::nrefs, pcl_json_false(), pcl_json_null(), and pcl_json_true().
Referenced by pcl_json_free().