‪libpcl: ‪Vector
Vector
‪A PCL Vector is a dynamic and contiguous block of memory for an array of same-sized elements.
Data Structures
struct tag_pcl_vector
‪Vector object.
Macros
#define pcl_vector_get(v, pos) ((void *)(((pcl_vector_t *)(v))->elems + ((pos) * ((pcl_vector_t *)(v))->size)))
‪Get an element.
Typedefs
typedef struct tag_pcl_vector pcl_vector_t
‪Vector object.
Functions
PCL_PUBLIC pcl_vector_t * pcl_vector (int capacity, size_t elemsize, pcl_cleanup_t cleanup)
‪Creates a new vector object.
PCL_PUBLIC void * pcl_vector_insert (pcl_vector_t *v, const void *elem, int pos)
‪Insert an element.
PCL_PUBLIC int pcl_vector_remove (pcl_vector_t *v, int pos)
‪Remove an element.
PCL_PUBLIC void * pcl_vector_get_safe (pcl_vector_t *v, int pos)
‪Get an element with bounds checking (safe version of pcl_vector_get).
PCL_PUBLIC pcl_vector_t * pcl_vector_compact (pcl_vector_t *v)
‪Compact a vector such that its element capacity matches its element count.
PCL_PUBLIC pcl_vector_t * pcl_vector_clear (pcl_vector_t *v)
‪Clear/remove all elements from a vector.
PCL_PUBLIC void pcl_vector_free (pcl_vector_t *v)
‪Release all resources used by a vector as well as the vector itself.
PCL_PUBLIC pcl_vector_t * pcl_vector_sort (pcl_vector_t *v, pcl_compare_t compare)
‪Sort a vector using qsort.
PCL_INLINE void * pcl_vector_append (pcl_vector_t *v, void *elem)
‪Append an element.
Detailed Description
A PCL Vector is a dynamic and contiguous block of memory for an array of same-sized elements.
The vector automatically expands this block of memory if an insertion would exceed the vector's current capacity. The vector never automatically shrinks itself during an element removal, but a vector can be shrunk using pcl_vector_compact.
Although a vector can store strings, it is adviceable to use a pcl_array_t instead. When storing strings (or any pointer) as elements, a pointer to the element pointer must be stored within the vector, requiring a dereference when the element is retrieved: *(void **) pcl_vector_get(v, 0). This is not what the vector was designed for even though it will work.
Basic Usage
#include <pcl/init.h>
#include <pcl/vector.h>
#include <stdio.h>
int main(int argc, char **argv)
{
  // always first
  pcl_init();
  // cleanup handler can be NULL, integer doesn't need it
  pcl_vector_t *vec = pcl_vector(8, sizeof(int), NULL);
  for(int i=0; i < vec->capacity * 2; i++)
    pcl_vector_append(vec, &i); // vector will have to expand after 8 appends
  for(int i=0; i < vec->count; i++)
  {
    int *elem = pcl_vector_get(vec, i);
    printf("%d\n", *elem); // 0\n1\n...15\n
  }
  pcl_vector_free(vec);
}
Macro Definition Documentation
pcl_vector_get
#define pcl_vector_get (v, pos) ((void *)(((pcl_vector_t *)(v))->elems + ((pos) * ((pcl_vector_t *)(v))->size)))
#include <pcl/vector.h>
‪Get an element.
Warning
‪this provides no bounds checking on pos and is designed to be used in cases where pos is known to be valid: such as a loop constrained by the vector's count. This is an optimization for the most common usage pattern. Expect a core dump or undefined behavior if v or pos is invalid.
Parameters
v ‪pointer to a vector
pos ‪zero-based position of element to retreive
Returns
‪pointer to element at pos
See also
‪pcl_vector_get_safe
Definition at line 124 of file vector.h.
Typedef Documentation
pcl_vector_t
typedef struct tag_pcl_vector pcl_vector_t
#include <pcl/types.h>
‪Vector object.
Used to track elements and grow the internal elements array when required.
Definition at line 74 of file types.h.
Function Documentation
pcl_vector()
PCL_PUBLIC pcl_vector_t* pcl_vector (int capacity, size_t elemsize, pcl_cleanup_t cleanup)
#include <pcl/vector.h>
‪Creates a new vector object.
Parameters
capacity ‪initial capacity of the vector as number of elements
elemsize ‪byte size of each element
cleanup ‪element cleanup handler called whenever an element is removed from the vector.
Returns
‪an allocated vector object that must be freed by the application. It is an error to provide pcl_cleanup_ptr for cleanup.
See also
‪pcl_vector_free
Definition at line 37 of file vector.c.
References tag_pcl_vector::capacity, tag_pcl_vector::cleanup, tag_pcl_vector::count, tag_pcl_vector::elems, max, pcl_cleanup_ptr(), PCL_EINVAL, pcl_malloc(), R_SETERRMSG, and tag_pcl_vector::size.
Referenced by pcl_json_compile().
pcl_vector_insert()
PCL_PUBLIC void* pcl_vector_insert (pcl_vector_t * v, const void * elem, int pos)
#include <pcl/vector.h>
‪Insert an element.
To append an element, set pos to pcl_vector_t.count
Note
‪Starting at elem, pcl_vector_t.size bytes are copied into the vector's internal memory.
Parameters
v ‪pointer to a vector
elem ‪pointer to an element. If this is NULL, a zero'd element is inserted
pos ‪the 0-based position to insert the new element. If this is equal to the pcl_vector_t.count, the element will be appended.
Returns
‪pointer to the element inserted, which is not the same as elem. NULL is returned on error.
Definition at line 37 of file vector_insert.c.
References tag_pcl_vector::capacity, tag_pcl_vector::count, tag_pcl_vector::elems, pcl_realloc(), pcl_vector_get, and tag_pcl_vector::size.
Referenced by pcl_vector_append().
pcl_vector_remove()
PCL_PUBLIC int pcl_vector_remove (pcl_vector_t * v, int pos)
#include <pcl/vector.h>
‪Remove an element.
Parameters
v ‪pointer to a vector
pos ‪a zero-based position of the element to remove
Returns
‪0 for success and -1 on error.
Definition at line 36 of file vector_remove.c.
References tag_pcl_vector::cleanup, tag_pcl_vector::count, pcl_vector_get, and tag_pcl_vector::size.
pcl_vector_get_safe()
PCL_PUBLIC void* pcl_vector_get_safe (pcl_vector_t * v, int pos)
#include <pcl/vector.h>
‪Get an element with bounds checking (safe version of pcl_vector_get).
Parameters
v ‪pointer to a vector
pos ‪zero-based position of element to get
Returns
‪pointer to the element or NULL on error
See also
‪pcl_vector_get
Definition at line 36 of file vector_get_s.c.
References PCL_ENOTFOUND, pcl_vector_get, and R_SETERR.
pcl_vector_compact()
PCL_PUBLIC pcl_vector_t* pcl_vector_compact (pcl_vector_t * v)
#include <pcl/vector.h>
‪Compact a vector such that its element capacity matches its element count.
Parameters
v ‪pointer to a vector
Returns
‪pointer to v argument
Definition at line 36 of file vector_compact.c.
References tag_pcl_vector::capacity, tag_pcl_vector::count, tag_pcl_vector::elems, pcl_realloc(), and tag_pcl_vector::size.
pcl_vector_clear()
PCL_PUBLIC pcl_vector_t* pcl_vector_clear (pcl_vector_t * v)
#include <pcl/vector.h>
‪Clear/remove all elements from a vector.
This doesn't adjust the vector's capacity. To adjust its capacity, call pcl_vector_compact after this.
Parameters
v ‪pointer to a vector
Returns
‪pointer to the v argument
See also
‪pcl_vector_compact
Definition at line 35 of file vector_clear.c.
References tag_pcl_vector::cleanup, tag_pcl_vector::count, and pcl_vector_get.
Referenced by pcl_vector_free().
pcl_vector_free()
PCL_PUBLIC void pcl_vector_free (pcl_vector_t * v)
#include <pcl/vector.h>
‪Release all resources used by a vector as well as the vector itself.
Parameters
v ‪pointer to a vector that is unusable after this call. If this is NULL, the function silently ignores the request.
See also
‪pcl_vector
Definition at line 36 of file vector_free.c.
References tag_pcl_vector::elems, pcl_free_safe(), and pcl_vector_clear().
Referenced by pcl_json_compile(), and pcl_json_freepath().
pcl_vector_sort()
PCL_PUBLIC pcl_vector_t* pcl_vector_sort (pcl_vector_t * v, pcl_compare_t compare)
#include <pcl/vector.h>
‪Sort a vector using qsort.
Parameters
v ‪ppointer to a vector
compare ‪pointer to a function comparator whose behavior is identical to qsort
Returns
‪pointer to the v argument
Definition at line 42 of file vector_sort.c.
References tag_pcl_vector::count, tag_pcl_vector::elems, and tag_pcl_vector::size.
pcl_vector_append()
PCL_INLINE void* pcl_vector_append (pcl_vector_t * v, void * elem)
#include <pcl/vector.h>
‪Append an element.
Parameters
v ‪pointer to a vector
elem ‪pointer to an element
Returns
‪pointer to the vector element inserted or NULL on error
Definition at line 198 of file vector.h.
References tag_pcl_vector::count, and pcl_vector_insert().
Referenced by pcl_json_compile().