‪libpcl: ‪Hash Table
Hash Table
‪This defines a hash table object and associated management functions.
Data Structures
struct pcl_htable_entry_t
‪Hash table entry object.
struct tag_pcl_htable
Functions
PCL_PUBLIC pcl_htable_t * pcl_htable (int capacity)
‪Creates a new hash table object.
PCL_PUBLIC pcl_htable_entry_t * pcl_htable_lookup (const pcl_htable_t *ht, const void *key)
‪Lookup and return an entry.
PCL_PUBLIC void * pcl_htable_get (const pcl_htable_t *ht, const void *key)
‪Lookup an entry and return its value.
PCL_PUBLIC int pcl_htable_put (pcl_htable_t *ht, const void *key, void *value, bool unique)
‪Puts a key/value pair into the table.
PCL_PUBLIC int pcl_htable_remove (pcl_htable_t *ht, const void *key)
‪Remove an entry from the table.
PCL_PUBLIC pcl_array_t * pcl_htable_keys (const pcl_htable_t *ht)
‪Get hash table keys as an array.
PCL_PUBLIC pcl_htable_entry_t * pcl_htable_iter (pcl_htable_t *ht, int *index)
‪Iterate through a table's entries.
PCL_PUBLIC void pcl_htable_clear (pcl_htable_t *ht, bool shrink)
‪Clear all entries from the table.
PCL_PUBLIC void * pcl_htable_free (pcl_htable_t *ht)
‪Release all resources used by the given hash table.
Detailed Description
This defines a hash table object and associated management functions.
This implementation will preserve insertion order: like Java's LinkedHashMap but without the doubly-linked list.
Implementation
Whenever an entry is put, it is added sequentially to an array of entry objects. To handle collisions, the entry objects are a linked list using an integer value that represents the index of the next collision within the entry array. The key is hashed using Google's FarmHash and bitwise AND'd with the current table size minus 1 to get the hashed index value. The hashed index value is an index to a second array (entry_lookup) of entry array indexes. Thus, looking up a hashed index within the entry_lookup array, will give you the entry array index, which is the beginning of the entry collision list. This is how the PCL hash table can preserve insertion order: one array using hash index to find the index into the sequential array of entries.
Note
‪The entry_lookup and entry array idea came directly from PHP's new hash table implementation released in 7.0. Just like PHP, PCL allocates the entry and entry_lookup arrays as one allocation: both with capacity elements. When an entry is removed, the entry array marks it as deleted but does not adjust the array to close the gap. An entry is marked as deleted by setting its key to NULL, which PCL treats as an invalid key. On rehash, the entry array is defragmented.
Default Hash Function
Unlike PHP's implementation, PCL does not use the DJBX33A hash as its default, which stands for “Daniel J. Bernstein, Times 33 with Addition”. Google's farmhash proved to have far less collisions (on string data since DJBX33A is for string keys). In one test of 470,000 english words, Google's FarmHash had no collisions while DJBX33A had 320. Performance wise, they are about the same. Another benifit of Google's FarmHash is that it is not just designed for string keys, which PCL requires to allow binary and string keys. It is also prefered to provide a single generalized hash function for both binary and string keys out of the box.
Customizing
This implementation has the ability to set a minimum and maximum load factor. You can also set the key_len if not using string keys. If key_len is 0 (strings), then the default key_equals function uses strcmp. If key_len is not 0, memcmp is used. There are three callbacks to customize a hash table: pcl_htable_t.remove_entry, pcl_htable_t.hashcode and pcl_htable_t.key_equals. All of these customizations can be set after table creation.
Rehashing
Rehashing is implemented by allocating a new entry and entry_lookup array (single allocation) that is either double the current size or half the current size (uses powers of 2). When the copy is complete, the old entry and entry_lookup arrays are freed. No hash codes are recomputed, since each entry caches its own hash code. The entry array is defragmented, meaning all deleted entries are removed; count_used will always be the same as count.
Table Size Limitations
The table can grow to 33,554,432 on 32-bit machines and 1,073,741,824 on 64-bit machines. This table expands and contracts based on a max and min load factor – 0.75 and 0.20 respectively. Table capacity is always powers of two.
String and Binary Keys
The PCL hash table supports binary keys, which are fixed-length and normally do not change for the life of the hash table. After creating a hash table, one can specify the key length in bytes or provide zero (the default) for variable-length keys (strings). For example, when using a UUID string as a key, each key would require 36 bytes. However, only 16 bytes per key if binary. In this case, you would set the key_len to 16. The default key_equals will use memcmp when key_len is not zero and strcmp otherwise.
UUID Key Example
#include <pcl/htable.h>
#include <pcl/init.h>
#include <pcl/string.h>
#include "app/user.h"
static unsigned char *uuidtokey(unsigned char *out, const char *uuid)
{
  char *hex = pcl_strreplace(uuid, "-", "");
  pcl_hex_decode(out, 16, hex);
  pcl_free(hex);
  return out;
}
static void remove_entry(const void *key, void *value)
{
  pcl_free(key);
  app_user_free((app_user_t *) value);
}
int main(void)
{
  pcl_init();
  int num;
  app_user_t **users = app_user_fetchall(&num);
  pcl_htable_t *ht = pcl_htable(num);
  // let htable know key length, only used by default key_equals and hashcode callbacks
  ht->key_len = 16;
  ht->remove_entry = remove_entry;
  unsigned char uuid[16];
  for(int i = 0; i < num; i++)
  {
    void *key = pcl_malloc(16);
    memcpy(key, uuidtokey(uuid, users[i]->uuid), 16);
    pcl_htable_put(ht, key, users[i], true);
  }
  // elements will be freed by hash table's remove_entry
  pcl_free(users);
  const char *john = "37462d98-371b-11eb-adc1-0242ac120002";
  pcl_user_t *user = pcl_htable_get(ht, uuidtokey(uuid, john));
  printf("%s\n", user->surname);
  pcl_htable_free(ht);
  return 0;
}
One step further, is taking a 32 or 64-bit sequence value, like a user_id, and storing its value as the key pointer address: key = (const void *)(uintptr_t) user_id. This would require a custom key_equals (where key1 == key2 could be the implementation) and a custom hashcode callback (where return (uintptr_t) key; could be the implementation). This method is very efficient both in memory and performance, but only works if the numeric bit length is <= the number of bits used by pointers. Also, user_id of 0 is invalid, since keys cannot be NULL, but it is uncommon to start sequence values like user_ids with 0. An example of this is below.
UserId Key Example
#include <pcl/htable.h>
#include <pcl/init.h>
#include "app/user.h"
#define IDTOKEY(id) (const void *) ((uintptr_t) (id))
static bool key_equals(const void *a, const void *b, size_t key_len)
{
  UNUSED(key_len);
  return a == b; // key addresses are user_ids, compare them directly.
}
static uintptr_t hashcode(const void *key, size_t key_len)
{
  UNUSED(key_len);
  return (uintptr_t) key; // no need to hash keys, user_id is unique
}
static void remove_entry(const void *key, void *value)
{
  UNUSED(key);
  app_user_free((app_user_t *) value); // key doesn't need to be freed
}
int main(void)
{
  pcl_init();
  int num_users;
  app_user_t **users = app_user_fetchall(&num_users);
  // a table mapping a user_id => user.
  pcl_htable_t *ht = pcl_htable(num_users);
  // configuring a pcl_htable_t
  ht->remove_entry = remove_entry;
  ht->hashcode = hashcode;
  ht->key_equals = key_equals;
  // ignored since example sets hashcode and key_equals. Set if your callbacks need it.
  //ht->key_len = sizeof(int64_t);
  // set min and max load factor
  //ht->min_loadfac = 0.13f;
  //ht->max_loadfac = 0.85f;
  // set key address to user_id
  for(int i = 0; i < num_users; i++)
    pcl_htable_put(ht, IDTOKEY(users[i]->id), users[i], true);
  pcl_free(users); // elements freed by remove_entry
  app_user_t *user = pcl_htable_get(ht, IDTOKEY(1982734));
  printf("%s\n", user->name);
  pcl_htable_free(ht); // calls remove_entry foreach entry in table
  return 0;
}
Function Documentation
pcl_htable()
PCL_PUBLIC pcl_htable_t* pcl_htable (int capacity)
#include <pcl/htable.h>
‪Creates a new hash table object.
All hash table callbacks are set to the default implementations as documented. After creating a hash table, you can assign callbacks.
Parameters
capacity ‪initial capacity of hash table. If this is not a power of 2, it is rounded up to the next power of 2. A value less than 8, will set capacity to 8 (smallest table size).
Returns
‪hash table pointer or NULL on error.
Definition at line 59 of file htable.c.
References tag_pcl_htable::capacity, tag_pcl_htable::count, tag_pcl_htable::count_used, ipcl_htable_chkcapacity(), tag_pcl_htable::key_equals, tag_pcl_htable::key_len, tag_pcl_htable::max_loadfac, MAX_LOADFAC, tag_pcl_htable::min_loadfac, MIN_LOADFAC, pcl_malloc(), R_TRC, and tag_pcl_htable::table_mask.
Referenced by pcl_json_obj().
pcl_htable_lookup()
PCL_PUBLIC pcl_htable_entry_t* pcl_htable_lookup (const pcl_htable_t * ht, const void * key)
#include <pcl/htable.h>
‪Lookup and return an entry.
Parameters
ht ‪pointer to hash table object
key ‪pointer to the key to lookup
Returns
‪pointer to the key's entry or NULL if not found or an error occurs. If not found, the last PCL error (pcl_errno) is set to PCL_ENOTFOUND.
Definition at line 36 of file htable_lookup.c.
References ipcl_htable_lookup(), PCL_EINVAL, R_SETERR, and R_TRC.
Referenced by pcl_htable_get().
pcl_htable_get()
PCL_PUBLIC void* pcl_htable_get (const pcl_htable_t * ht, const void * key)
#include <pcl/htable.h>
‪Lookup an entry and return its value.
This is a convenience function that wraps pcl_htable_lookup.
Parameters
ht ‪pointer to hash table object
key ‪pointer to a key
Returns
‪value pointer or NULL if not found. values can be NULL. To detect an error verse a NULL value, check pcl_errno: if(value == NULL && pcl_errno == PCL_EOKAY) success; Or, use pcl_htable_lookup that never returns NULL on success.
Definition at line 36 of file htable_get.c.
References pcl_err_clear(), pcl_htable_lookup(), R_TRC, and pcl_htable_entry_t::value.
Referenced by pcl_json_objget().
pcl_htable_put()
PCL_PUBLIC int pcl_htable_put (pcl_htable_t * ht, const void * key, void * value, bool unique)
#include <pcl/htable.h>
‪Puts a key/value pair into the table.
Parameters
ht ‪pointer to hash table object
key ‪pointer to the key. This is shallow assignment.
value ‪pointer to the entry's value. This is shallow assignment.
unique ‪indicates if the put operation should enforce unique keys. When true, if a key exists the operation fails. When false, a matching entry's key and value are replaced with the given key and value; remove_entry called with old key and value.
Returns
‪0 on success and -1 on error. For unique puts, pcl_errno is set to PCL_EEXISTS.
Definition at line 37 of file htable_put.c.
References BADARG, tag_pcl_htable::capacity, pcl_htable_entry_t::code, tag_pcl_htable::count, tag_pcl_htable::count_used, tag_pcl_htable::entries, tag_pcl_htable::entry_lookup, ipcl_htable_lookup(), ipcl_htable_rehash(), pcl_htable_entry_t::key, tag_pcl_htable::max_loadfac, pcl_htable_entry_t::next, PCL_EEXIST, pcl_err_freeze(), tag_pcl_htable::remove_entry, SETERR, tag_pcl_htable::table_mask, TRC, and pcl_htable_entry_t::value.
Referenced by pcl_json_objput().
pcl_htable_remove()
PCL_PUBLIC int pcl_htable_remove (pcl_htable_t * ht, const void * key)
#include <pcl/htable.h>
‪Remove an entry from the table.
If the key does not exist, this call is silently ignored.
Parameters
ht ‪pointer to hash table object
key ‪pointer to the entry's key to remove
Returns
‪new count of entries or -1 on error
Definition at line 36 of file htable_remove.c.
References BADARG, tag_pcl_htable::capacity, pcl_htable_entry_t::code, tag_pcl_htable::count, tag_pcl_htable::entries, tag_pcl_htable::entry_lookup, tag_pcl_htable::hashcode, ipcl_htable_rehash(), pcl_htable_entry_t::key, tag_pcl_htable::key_equals, tag_pcl_htable::key_len, tag_pcl_htable::min_loadfac, MINTBLSIZE, pcl_htable_entry_t::next, tag_pcl_htable::remove_entry, tag_pcl_htable::table_mask, TRC, and pcl_htable_entry_t::value.
Referenced by pcl_json_objremove().
pcl_htable_keys()
PCL_PUBLIC pcl_array_t* pcl_htable_keys (const pcl_htable_t * ht)
#include <pcl/htable.h>
‪Get hash table keys as an array.
Parameters
ht ‪pointer to hash table object
Returns
‪array on success and NULL on error. An empty table produces an empty array. This array must be freed by caller.
Definition at line 36 of file htable_keys.c.
References tag_pcl_htable::count, tag_pcl_htable::count_used, tag_pcl_htable::entries, pcl_htable_entry_t::key, pcl_array(), and pcl_array_append().
pcl_htable_iter()
PCL_PUBLIC pcl_htable_entry_t* pcl_htable_iter (pcl_htable_t * ht, int * index)
#include <pcl/htable.h>
‪Iterate through a table's entries.
This automatically skips deleted entries, which means the given index pointer can skip indexes during the iteration: like given 1 on input could produce 5 on output.
// typical usage
int index = 0;
pcl_htable_entry_t *ent;
// the iteration is always insertion order. the index can skip index values,
// which means it skipped one or more deleted entries.
while((ent = pcl_htable_iter(ht, &index)))
  printf("entries[%d] %s\n", index - 1, ent->key);
// can also use this to retrieve the N-th entry
int index = 9; // logical 10-th entry inserted, physical depends on num deleted
pcl_htable_entry_t *ent = pcl_htable_iter(ht, &index);
Parameters
ht ‪pointer to a hash table
index ‪pointer to an integer that on input, represents the N-th entry to retrieve. On output, this represents the next index value. This cannot be less than zero or greater than count_used. This is typically set to zero to iterate through all entries.
Returns
‪pointer to the next entry or NULL when complete.
Definition at line 35 of file htable_iter.c.
References tag_pcl_htable::count_used, tag_pcl_htable::entries, and pcl_htable_entry_t::key.
Referenced by ipcl_json_encode_object().
pcl_htable_clear()
PCL_PUBLIC void pcl_htable_clear (pcl_htable_t * ht, bool shrink)
#include <pcl/htable.h>
‪Clear all entries from the table.
Parameters
ht ‪pointer to hash table object
shrink ‪when true, the table will be shrunk down to the smallest table size; 17.
Definition at line 37 of file htable_clear.c.
References tag_pcl_htable::capacity, tag_pcl_htable::count, tag_pcl_htable::count_used, tag_pcl_htable::entries, tag_pcl_htable::entry_lookup, ipcl_htable_init(), pcl_htable_entry_t::key, MINTBLSIZE, pcl_free(), tag_pcl_htable::remove_entry, tag_pcl_htable::table_mask, and pcl_htable_entry_t::value.
pcl_htable_free()
PCL_PUBLIC void* pcl_htable_free (pcl_htable_t * ht)
#include <pcl/htable.h>
‪Release all resources used by the given hash table.
If a remove_entry callback is set on the given hash table, it will be called for each entry.
Parameters
ht ‪pointer to hash table object
Returns
‪always returns NULL, which is useful as an assignment and free in a single line: my_obj->ht = pcl_htable_free(my_obj->ht)
Definition at line 36 of file htable_free.c.
References tag_pcl_htable::count_used, tag_pcl_htable::entries, pcl_htable_entry_t::key, pcl_free(), tag_pcl_htable::remove_entry, and pcl_htable_entry_t::value.
Referenced by pcl_json_free().