‪libpcl: ‪Allocation Functions
Allocation Functions
‪A set of function for managing memory.
Typedefs
typedef void(* pcl_memory_handler_t) (const char *type, void *ptr, size_t siz, PCL_LOCATION_PARAMS)
‪Prototype for a memory handler.
Functions
void * pcl_malloc (size_t n)
‪Allocate dynamic memory.
void * pcl_zalloc (size_t n)
‪Allocate and zero dynamic memory.
void * pcl_realloc (void *p, size_t n)
‪Re-allocate dynamic memory.
void * pcl_free (void *p)
‪Free memory space.
void * pcl_free_safe (void *p)
‪Safely free memory space.
PCL_PUBLIC void * pcl_malloc_trace (size_t n, PCL_LOCATION_PARAMS)
‪Allocate dynamic memory.
PCL_PUBLIC void * pcl_zalloc_trace (size_t n, PCL_LOCATION_PARAMS)
‪Allocate and zero dynamic memory.
PCL_PUBLIC void * pcl_realloc_trace (void *p, size_t n, PCL_LOCATION_PARAMS)
‪Re-allocate dynamic memory.
PCL_PUBLIC void * pcl_free_trace (void *p, PCL_LOCATION_PARAMS)
‪Free memory space.
PCL_PUBLIC void pcl_cleanup_ptr (void *item)
‪Implementation of a pcl_cleanup_t that passes item to free.
PCL_PUBLIC pcl_memory_handler_t pcl_set_memory_handler (pcl_memory_handler_t handler)
‪Set the process memory error handler.
PCL_PUBLIC void pcl_memory_error (const char *type, void *ptr, size_t siz, PCL_LOCATION_PARAMS)
‪Execute process memory error handler.
pchar_t * pcl_pmalloc (size_t n)
‪Allocate dynamic memory.
pchar_t * pcl_pzalloc (size_t n)
‪Allocate and zero dynamic memory.
pchar_t * pcl_prealloc (void *p, size_t n)
‪Re-allocate dynamic memory.
Detailed Description
A set of function for managing memory.
Typedef Documentation
pcl_memory_handler_t
typedef void(* pcl_memory_handler_t) (const char *type, void *ptr, size_t siz, PCL_LOCATION_PARAMS)
#include <pcl/alloc.h>
‪Prototype for a memory handler.
Parameters
type ‪the type of memory operation that encounted the error: pcl_malloc, strdup, etc.
ptr ‪memory address used during failed operation
siz ‪size in bytes of memory space used during failed operation
file ‪file name where the error took place
func ‪function name where the error took placce
line ‪line number within file where error took place
Definition at line 54 of file alloc.h.
Function Documentation
pcl_malloc()
void* pcl_malloc (size_t n)
#include <pcl/alloc.h>
‪Allocate dynamic memory.
Parameters
n ‪size in bytes
Returns
‪address of allocate memory
Note
‪implemented as a macro
Referenced by fmtconv(), ipcl_win32_name_to_sid(), ipcl_win32_sd_create(), ipcl_win32_sid_dup(), ipcl_win32_token_into(), ndup(), pcl_array(), pcl_buf_init(), pcl_cipher(), pcl_digest(), pcl_digest_final(), pcl_getenv(), pcl_htable(), pcl_initopt(), pcl_json_arr(), pcl_json_compile(), pcl_json_int(), pcl_json_obj(), pcl_json_real(), pcl_json_str(), pcl_json_strn(), pcl_opendir(), pcl_proc_exec(), pcl_queue(), pcl_queue_add(), pcl_realpath(), pcl_stack(), pcl_stack_push(), pcl_thread(), pcl_vector(), sd_get(), vaxprintf(), and vaxstrcatf().
pcl_zalloc()
void* pcl_zalloc (size_t n)
#include <pcl/alloc.h>
‪Allocate and zero dynamic memory.
Parameters
n ‪size in bytes
Returns
‪address of allocate memory
Note
‪implemented as a macro
Referenced by ipcl_file_alloc(), ipcl_htable_init(), ipcl_socket_alloc(), pcl_array(), pcl_err_vtrace(), pcl_ssl(), and pcl_ssl_accept().
pcl_realloc()
void* pcl_realloc (void * p, size_t n)
#include <pcl/alloc.h>
‪Re-allocate dynamic memory.
Parameters
p ‪address of allocated memory
n ‪new size in bytes
Returns
‪address of allocated memory
Note
‪implemented as a macro
Referenced by pcl_array_insert(), pcl_buf_copy(), pcl_buf_grow(), pcl_opendir(), pcl_vector_compact(), and pcl_vector_insert().
pcl_free()
void* pcl_free (void * p)
#include <pcl/alloc.h>
‪Free memory space.
Parameters
p ‪memory address
Returns
‪always returns NULL, which is useful for assignments
Note
‪implemented as a macro
Referenced by ipcl_err_trace_free(), ipcl_htable_rehash(), ipcl_json_parse_object(), ipcl_win32_file_security(), ipcl_win32_name_to_sid(), ipcl_win32_process_sid(), ipcl_win32_sd_clear(), ipcl_win32_sd_create(), ipcl_win32_sd_get(), ipcl_win32_token_into(), pcl_array_free(), pcl_bind(), pcl_buf_free(), pcl_cipher_free(), pcl_closedir(), pcl_digest_free(), pcl_fdpath(), pcl_file_close(), pcl_getenv(), pcl_htable_clear(), pcl_htable_free(), pcl_json_compile(), pcl_json_free(), pcl_json_freepath(), pcl_json_objput(), pcl_popen(), pcl_queue_clear(), pcl_queue_free(), pcl_queue_remove(), pcl_readdir(), pcl_socket_close(), pcl_ssl_free(), pcl_stack_clear(), pcl_stack_free(), pcl_stack_pop(), pcl_sysinfo(), pcl_tmpfile(), sd_get(), vaxprintf(), vaxstrcatf(), vfxprintf(), and vxprintf().
pcl_free_safe()
void* pcl_free_safe (void * p)
#include <pcl/alloc.h>
‪Safely free memory space.
Parameters
p ‪memory address, can be NULL in which case no operation is performed
Returns
‪always returns NULL, which is useful for assignments
Note
‪implemented as a macro
Referenced by pcl_array_free(), pcl_buf_clear(), pcl_cleanup_ptr(), pcl_closedir(), pcl_json_free(), pcl_json_freepath(), pcl_log_vevent(), pcl_socket_close(), pcl_ssl_free(), pcl_statent(), pcl_tmpfile(), and pcl_vector_free().
pcl_malloc_trace()
PCL_PUBLIC void* pcl_malloc_trace (size_t n, PCL_LOCATION_PARAMS)
#include <pcl/alloc.h>
‪Allocate dynamic memory.
Parameters
n ‪size in bytes
Returns
‪address of allocate memory
Definition at line 36 of file malloc_trace.c.
References PCL_LOCATION_VALS, and pcl_memory_error().
pcl_zalloc_trace()
PCL_PUBLIC void* pcl_zalloc_trace (size_t n, PCL_LOCATION_PARAMS)
#include <pcl/alloc.h>
‪Allocate and zero dynamic memory.
Parameters
n ‪size in bytes
Returns
‪address of allocate memory
Definition at line 36 of file zalloc_trace.c.
References PCL_LOCATION_VALS, and pcl_memory_error().
pcl_realloc_trace()
PCL_PUBLIC void* pcl_realloc_trace (void * p, size_t n, PCL_LOCATION_PARAMS)
#include <pcl/alloc.h>
‪Re-allocate dynamic memory.
Parameters
p ‪address of allocated memory
n ‪new size in bytes
Returns
‪address of allocated memory
Definition at line 36 of file realloc_trace.c.
References PCL_LOCATION_VALS, and pcl_memory_error().
pcl_free_trace()
PCL_PUBLIC void* pcl_free_trace (void * p, PCL_LOCATION_PARAMS)
#include <pcl/alloc.h>
‪Free memory space.
Parameters
p ‪memory address
Returns
‪always returns NULL, which is useful for assignments
Definition at line 36 of file free_trace.c.
References PCL_LOCATION_VALS, and pcl_memory_error().
pcl_cleanup_ptr()
PCL_PUBLIC void pcl_cleanup_ptr (void * item)
#include <pcl/alloc.h>
‪Implementation of a pcl_cleanup_t that passes item to free.
Parameters
item ‪pointer to a collection item
Definition at line 35 of file cleanup_ptr.c.
References pcl_free_safe().
Referenced by pcl_net_dnstxtrec(), pcl_net_resolve(), pcl_proc_parsecmd(), pcl_ssl_certentry(), and pcl_vector().
pcl_set_memory_handler()
PCL_PUBLIC pcl_memory_handler_t pcl_set_memory_handler (pcl_memory_handler_t handler)
#include <pcl/alloc.h>
‪Set the process memory error handler.
Parameters
handler ‪new memory error handler
Returns
‪previous memory error handler or NULL if it was unset
Definition at line 49 of file memory_handler.c.
References pcl_atomic_exchange().
pcl_memory_error()
PCL_PUBLIC void pcl_memory_error (const char * type, void * ptr, size_t siz, PCL_LOCATION_PARAMS)
#include <pcl/alloc.h>
‪Execute process memory error handler.
Definition at line 57 of file memory_handler.c.
References pcl_atomic_fetch().
Referenced by ndup(), pcl_free_trace(), pcl_malloc_trace(), pcl_realloc_trace(), and pcl_zalloc_trace().
pcl_pmalloc()
pchar_t* pcl_pmalloc (size_t n)
#include <pcl/alloc.h>
‪Allocate dynamic memory.
Parameters
n ‪size in pchar_t characters
Returns
‪address of allocate memory
Note
‪implemented as a macro
Referenced by pcl_fdpath(), pcl_proc_exec(), and pcl_tmpfile().
pcl_pzalloc()
pchar_t* pcl_pzalloc (size_t n)
#include <pcl/alloc.h>
‪Allocate and zero dynamic memory.
Parameters
n ‪size in pchar_t characters
Returns
‪address of allocate memory
Note
‪implemented as a macro
pcl_prealloc()
pchar_t* pcl_prealloc (void * p, size_t n)
#include <pcl/alloc.h>
‪Re-allocate dynamic memory.
Parameters
p ‪address of allocated memory
n ‪new size in pchar_t characters
Returns
‪address of allocated memory
Note
‪implemented as a macro