‪libpcl: ‪Atomic Operations
Atomic Operations
‪Perform atomic operations.
Functions
PCL_EXPORT pcl_atomic_t pcl_atomic_exchange (pcl_atomic_t *dest, pcl_atomic_t val)
‪Performs an atomic exchange operation.
PCL_EXPORT pcl_atomic_t pcl_atomic_add_fetch (pcl_atomic_t *dest, pcl_atomic_t add)
‪Performs an add and fetch operation.
PCL_EXPORT pcl_atomic_t pcl_atomic_fetch_add (pcl_atomic_t *dest, pcl_atomic_t add)
‪Performs a fetch and add.
PCL_EXPORT pcl_atomic_t pcl_atomic_compare_exchange (pcl_atomic_t *dest, pcl_atomic_t expected, pcl_atomic_t desired)
‪Performs a compare and exhange operation.
PCL_EXPORT pcl_atomic_t pcl_atomic_fetch (pcl_atomic_t *dest)
‪Performs an atomic fetch (load) operation.
Detailed Description
Perform atomic operations.
These functions are useful for updating or fetching a value in an atomic fashion: such as a global variable in a multi-threaded application. Atomic operations, where applicable, are a much faster synchronization technique than Mutexes.
Function Documentation
pcl_atomic_exchange()
PCL_EXPORT pcl_atomic_t pcl_atomic_exchange (pcl_atomic_t * dest, pcl_atomic_t val)
#include <pcl/atomic.h>
‪Performs an atomic exchange operation.
Parameters
dest ‪pointer to an atomic value that is set to val
val ‪new atomic value for dest
Returns
‪initial value of dest
Definition at line 39 of file atomic_exchange.c.
Referenced by pcl_set_memory_handler().
pcl_atomic_add_fetch()
PCL_EXPORT pcl_atomic_t pcl_atomic_add_fetch (pcl_atomic_t * dest, pcl_atomic_t add)
#include <pcl/atomic.h>
‪Performs an add and fetch operation.
Parameters
dest ‪pointer to an atomic value
add ‪value to add to dest, which can be negative to subtract
Returns
‪the result of the addition operation
Definition at line 39 of file atomic_add_fetch.c.
Referenced by pcl_rand().
pcl_atomic_fetch_add()
PCL_EXPORT pcl_atomic_t pcl_atomic_fetch_add (pcl_atomic_t * dest, pcl_atomic_t add)
#include <pcl/atomic.h>
‪Performs a fetch and add.
Parameters
dest ‪pointer to an atomic value
add ‪value to add to dest, which can be negative to subtract
Returns
‪initial value of dest
Definition at line 39 of file atomic_fetch_add.c.
pcl_atomic_compare_exchange()
PCL_EXPORT pcl_atomic_t pcl_atomic_compare_exchange (pcl_atomic_t * dest, pcl_atomic_t expected, pcl_atomic_t desired)
#include <pcl/atomic.h>
‪Performs a compare and exhange operation.
Parameters
dest ‪pointer to an atomic value
expected ‪a value to compare with dest
desired ‪value to be written to dest if dest and expected are equal
Returns
‪initial value of dest
Definition at line 39 of file atomic_compare_exchange.c.
Referenced by pcl_init().
pcl_atomic_fetch()
PCL_EXPORT pcl_atomic_t pcl_atomic_fetch (pcl_atomic_t * dest)
#include <pcl/atomic.h>
‪Performs an atomic fetch (load) operation.
Parameters
dest ‪pointer to an atomic
Returns
‪value of dest
Definition at line 39 of file atomic_fetch.c.
Referenced by pcl_memory_error().