‪libpcl: ‪Error Management
Error Management
‪Provides detailed error management functions.
Modules
Error Codes
‪A list of all PCL error codes.
Error Macros
‪Error macros allow for easily settting errors and adding traces to the per-thread stack trace.
Data Structures
struct tag_pcl_err_trace
‪Stack trace object implemented as a linked list.
struct tag_pcl_err
‪Represents a PCL error, with optional stack trace.
Macros
#define pcl_errno pcl_err_last()
‪Gets the last PCL error, mimics 'errno'.
#define pcl_oserrno errno
#define pcl_crterrno errno
#define pcl_sockerrno errno
#define pcl_setoserrno(e) errno = (int) (e)
#define pcl_setcrterrno(e) pcl_setoserrno(e)
#define pcl_err_osclear() (pcl_setoserrno(0), pcl_setcrterrno(0))
#define pcl_err_crt2pcl(_crt_errno) pcl_err_os2pcl(_crt_errno)
#define pcl_err_crt2os(_crt_errno) _crt_errno
Functions
PCL_PUBLIC pcl_err_t * pcl_err_get (void)
‪Gets the calling thread's error.
PCL_PUBLIC void pcl_err_freeze (bool freeze)
‪Freeze or thaw the current thread's error.
PCL_PUBLIC int pcl_err_last (void)
‪Gets the last PCL err code.
PCL_PUBLIC char * pcl_err_lastmsg (void)
‪Get the last error message, stack trace tail.
PCL_PUBLIC uint32_t pcl_err_lastos (void)
‪Get the last OS error code.
PCL_PUBLIC int pcl_err_fprintf (FILE *stream, int indent, const char *format,...)
PCL_PUBLIC int pcl_err_vfprintf (FILE *stream, int indent, const char *format, va_list args)
PCL_PUBLIC int pcl_err_sprintf (char *buf, size_t buf_size, int indent, const char *format,...)
PCL_PUBLIC int pcl_err_vsprintf (char *buf, size_t buf_size, int indent, const char *format, va_list args)
PCL_PUBLIC pcl_json_t * pcl_err_json (const char *message,...)
‪Format the current thread's error as a JSON string.
PCL_PUBLIC pcl_json_t * pcl_err_vjson (const char *message, va_list ap)
‪Format the current thread's error as a JSON string.
PCL_PUBLIC int pcl_err_setjson (pcl_json_t *error)
PCL_PUBLIC int pcl_err_clear (void)
PCL_PUBLIC int pcl_err_vset (PCL_LOCATION_PARAMS, int err, uint32_t oserr, const char *format, va_list ap)
PCL_PUBLIC int pcl_err_set (PCL_LOCATION_PARAMS, int err, uint32_t oserr, const char *format,...)
PCL_PUBLIC int pcl_err_trace (PCL_LOCATION_PARAMS, const char *format,...)
PCL_PUBLIC int pcl_err_vtrace (PCL_LOCATION_PARAMS, const char *format, va_list ap)
PCL_PUBLIC const char * pcl_err_msg (int err)
‪Get the default PCL error message given an PCL error code.
PCL_PUBLIC const char * pcl_err_name (int err)
PCL_PUBLIC int pcl_err_code (const char *pclname)
PCL_PUBLIC int pcl_err_os2pcl (uint32_t oserr)
PCL_PUBLIC const char * pcl_err_osname (uint32_t oserr)
PCL_PUBLIC int pcl_err_osmsg (uint32_t oserr, char *osmsg, size_t size)
Detailed Description
Provides detailed error management functions.
This includes a complete list of error mappings between PCL error codes and the host OS, full stack traces, per-thread error that can be switched in/out and frozen and large suite of error/trace set macros.
Macro Definition Documentation
pcl_errno
#define pcl_errno pcl_err_last()
#include <pcl/error.h>
‪Gets the last PCL error, mimics 'errno'.
Definition at line 177 of file error.h.
pcl_oserrno
#define pcl_oserrno errno
#include <pcl/error.h>
Definition at line 185 of file error.h.
pcl_crterrno
#define pcl_crterrno errno
#include <pcl/error.h>
Definition at line 186 of file error.h.
pcl_sockerrno
#define pcl_sockerrno errno
#include <pcl/error.h>
Definition at line 187 of file error.h.
pcl_setoserrno
#define pcl_setoserrno (e) errno = (int) (e)
#include <pcl/error.h>
Definition at line 292 of file error.h.
pcl_setcrterrno
#define pcl_setcrterrno (e) pcl_setoserrno(e)
#include <pcl/error.h>
Definition at line 293 of file error.h.
pcl_err_osclear
#define pcl_err_osclear () (pcl_setoserrno(0), pcl_setcrterrno(0))
#include <pcl/error.h>
Definition at line 298 of file error.h.
pcl_err_crt2pcl
#define pcl_err_crt2pcl (_crt_errno) pcl_err_os2pcl(_crt_errno)
#include <pcl/error.h>
Definition at line 352 of file error.h.
pcl_err_crt2os
#define pcl_err_crt2os (_crt_errno) _crt_errno
#include <pcl/error.h>
Definition at line 353 of file error.h.
Function Documentation
pcl_err_get()
PCL_PUBLIC pcl_err_t* pcl_err_get (void)
#include <pcl/error.h>
‪Gets the calling thread's error.
Warning
‪This is Thread Local Storage (TLS).
Returns
‪pointer to the thread error
See also
‪FREEZE_ERR
Definition at line 57 of file err_ctx.c.
References pcl_tls_get().
Referenced by ipcl_err_serialize(), pcl_err_clear(), pcl_err_freeze(), pcl_err_last(), pcl_err_lastmsg(), pcl_err_lastos(), pcl_err_setjson(), pcl_err_vfprintf(), pcl_err_vjson(), pcl_err_vset(), pcl_err_vsprintf(), and pcl_err_vtrace().
pcl_err_freeze()
PCL_PUBLIC void pcl_err_freeze (bool freeze)
#include <pcl/error.h>
‪Freeze or thaw the current thread's error.
Note
‪per-thread error cannot be cleared while frozen.
// pcl_err_freeze is shorthand for the below
pcl_err_t *err = pcl_err_get();
err->frozen = true; // or false
Parameters
freeze ‪if true, the error is frozen otherwise thawed.
See also
‪FREEZE_ERR
Definition at line 35 of file err_freeze.c.
References tag_pcl_err::frozen, and pcl_err_get().
Referenced by pcl_file_close(), pcl_htable_put(), and pcl_log_vevent().
pcl_err_last()
PCL_PUBLIC int pcl_err_last (void)
#include <pcl/error.h>
‪Gets the last PCL err code.
This is typically accessed through the pcl_errno macro.
Returns
‪last PCL error code
Definition at line 35 of file err_last.c.
References tag_pcl_err::err, and pcl_err_get().
pcl_err_lastmsg()
PCL_PUBLIC char* pcl_err_lastmsg (void)
#include <pcl/error.h>
‪Get the last error message, stack trace tail.
Returns
‪pointer to the last error message
Definition at line 35 of file err_lastmsg.c.
References tag_pcl_err_trace::msg, tag_pcl_err_trace::next, pcl_err_get(), and tag_pcl_err::strace.
pcl_err_lastos()
PCL_PUBLIC uint32_t pcl_err_lastos (void)
#include <pcl/error.h>
‪Get the last OS error code.
Note, this is only set if provided when setting the PCL error. In cases were a PCL error is set directly, w/o mapping OS error => PCL, this will be 0.
Returns
‪last OS error code
Definition at line 35 of file err_lastos.c.
References tag_pcl_err::oserr, and pcl_err_get().
pcl_err_fprintf()
PCL_PUBLIC int pcl_err_fprintf (FILE * stream, int indent, const char * format, ...)
#include <pcl/error.h>
Definition at line 35 of file err_fprintf.c.
References pcl_err_vfprintf().
Referenced by pcl_log_vevent(), and pcl_proc_exec().
pcl_err_vfprintf()
PCL_PUBLIC int pcl_err_vfprintf (FILE * stream, int indent, const char * format, va_list args)
#include <pcl/error.h>
Definition at line 36 of file err_vfprintf.c.
References tag_pcl_buf::data, tag_pcl_err::frozen, ipcl_err_serialize(), tag_pcl_buf::len, and pcl_err_get().
Referenced by pcl_err_fprintf().
pcl_err_sprintf()
PCL_PUBLIC int pcl_err_sprintf (char * buf, size_t buf_size, int indent, const char * format, ...)
#include <pcl/error.h>
Definition at line 35 of file err_sprintf.c.
References pcl_err_vsprintf().
pcl_err_vsprintf()
PCL_PUBLIC int pcl_err_vsprintf (char * buf, size_t buf_size, int indent, const char * format, va_list args)
#include <pcl/error.h>
Definition at line 37 of file err_vsprintf.c.
References tag_pcl_buf::data, tag_pcl_err::frozen, ipcl_err_serialize(), tag_pcl_buf::len, and pcl_err_get().
Referenced by pcl_err_sprintf().
pcl_err_json()
PCL_PUBLIC pcl_json_t* pcl_err_json (const char * message, ...)
#include <pcl/error.h>
‪Format the current thread's error as a JSON string.
The returned JSON string has no spaces or newlines when it comes to the JSON structure itself.
This function performs JSON string escaping on special characters: \ / " \b \t \n \f \r and any remaining control character (<0x20) as \u0000: eg. 0x1f as \u001f.
The below example includes spacing and newlines for demostration purposes:
{
  "err": <number>           // PCL error code
  "oserr": <number>         // OS error code
  "msg": <string|null>      // optional message provided to pcl_err_json
  "strace": [               // array of trace objects: in stack order
    {
      "file": <string|null> // file name
      "func": <string|null> // function name
      "line": <number>      // line number
      "msg": <string|null>  // optional context message
    },
    {
      etc...
    }
  ]
}
Parameters
message ‪additional message to include with the JSON. This can be NULL.
... ‪variable arguments
Returns
‪pointer to a JSON object
Definition at line 35 of file err_json.c.
References pcl_err_vjson().
pcl_err_vjson()
PCL_PUBLIC pcl_json_t* pcl_err_vjson (const char * message, va_list ap)
#include <pcl/error.h>
‪Format the current thread's error as a JSON string.
The returned JSON string has no spaces or newlines when it comes to the JSON structure itself.
This function performs JSON string escaping on special characters: \ / " \b \t \n \f \r and any remaining control character (<0x20) as \u0000: eg. 0x1f as \u001f.
Note
‪see pcl_err_json for an example
Parameters
message ‪additional message to include with the JSON. This can be NULL.
ap ‪variable argument list
Returns
‪pointer to a json object
See also
‪pcl_err_json
Definition at line 44 of file err_vjson.c.
References tag_pcl_err::err, FAILED, tag_pcl_err_trace::next, tag_pcl_err::oserr, pcl_err_get(), pcl_err_name(), pcl_err_osname(), PCL_JSON_ALLOWNULL, pcl_json_arr(), pcl_json_arradd(), PCL_JSON_EMPTYASNULL, pcl_json_free(), PCL_JSON_FREEVALONERR, pcl_json_obj(), pcl_json_objput(), pcl_json_objputint(), pcl_json_objputstr(), PCL_JSON_SHALLOW, PCL_JSON_SKIPUTF8CHK, pcl_json_str(), pcl_vasprintf(), tag_pcl_err::strace, and strempty.
Referenced by pcl_err_json().
pcl_err_setjson()
PCL_PUBLIC int pcl_err_setjson (pcl_json_t * error)
#include <pcl/error.h>
Definition at line 39 of file err_setjson.c.
References tag_pcl_err::err, tag_pcl_err::frozen, tag_pcl_err::oserr, PCL_EFORMAT, pcl_err_clear(), pcl_err_get(), pcl_err_trace(), PCL_ETYPE, pcl_json_arrget(), pcl_json_count(), PCL_JSON_INVINT, pcl_json_isarr, pcl_json_isobj, pcl_json_objget(), pcl_json_objgetint(), pcl_json_objgetstr(), and SETERR.
pcl_err_clear()
PCL_PUBLIC int pcl_err_clear (void)
#include <pcl/error.h>
Definition at line 35 of file err_clear.c.
References tag_pcl_err::err, tag_pcl_err::frozen, ipcl_err_trace_free(), tag_pcl_err::oserr, PCL_EOKAY, pcl_err_get(), pcl_err_osclear, and tag_pcl_err::strace.
Referenced by pcl_array_get(), pcl_err_setjson(), pcl_err_vset(), pcl_htable_get(), pcl_ssl_recv(), and pcl_ssl_send().
pcl_err_vset()
PCL_PUBLIC int pcl_err_vset (PCL_LOCATION_PARAMS , int err, uint32_t oserr, const char * format, va_list ap)
#include <pcl/error.h>
Definition at line 35 of file err_vset.c.
References tag_pcl_err::err, tag_pcl_err::frozen, tag_pcl_err::oserr, PCL_EOKAY, pcl_err_clear(), pcl_err_get(), pcl_err_vtrace(), and PCL_LOCATION_VALS.
Referenced by pcl_err_set().
pcl_err_set()
PCL_PUBLIC int pcl_err_set (PCL_LOCATION_PARAMS , int err, uint32_t oserr, const char * format, ...)
#include <pcl/error.h>
Definition at line 35 of file err_set.c.
References pcl_err_vset(), and PCL_LOCATION_VALS.
Referenced by ipcl_json_parse_number().
pcl_err_trace()
PCL_PUBLIC int pcl_err_trace (PCL_LOCATION_PARAMS , const char * format, ...)
#include <pcl/error.h>
Definition at line 35 of file err_trace.c.
References pcl_err_vtrace(), and PCL_LOCATION_VALS.
Referenced by pcl_err_setjson().
pcl_err_vtrace()
PCL_PUBLIC int pcl_err_vtrace (PCL_LOCATION_PARAMS , const char * format, va_list ap)
#include <pcl/error.h>
Definition at line 38 of file err_vtrace.c.
References tag_pcl_err::err, tag_pcl_err_trace::file, tag_pcl_err::frozen, tag_pcl_err_trace::func, tag_pcl_err_trace::line, tag_pcl_err_trace::msg, tag_pcl_err_trace::next, PCL_EOKAY, pcl_err_get(), pcl_strrepchr(), pcl_vsprintf(), pcl_zalloc(), tag_pcl_err_trace::size, tag_pcl_err::strace, and strempty.
Referenced by pcl_err_trace(), and pcl_err_vset().
pcl_err_msg()
PCL_PUBLIC const char* pcl_err_msg (int err)
#include <pcl/error.h>
‪Get the default PCL error message given an PCL error code.
Definition at line 35 of file err_msg.c.
References ipcl_err_msgmap(), and ipcl_err_msgmap_t::msg.
Referenced by ipcl_err_serialize().
pcl_err_name()
PCL_PUBLIC const char* pcl_err_name (int err)
#include <pcl/error.h>
Definition at line 35 of file err_name.c.
References ipcl_err_msgmap(), and ipcl_err_msgmap_t::name.
Referenced by ipcl_err_serialize(), and pcl_err_vjson().
pcl_err_code()
PCL_PUBLIC int pcl_err_code (const char * pclname)
#include <pcl/error.h>
Definition at line 36 of file err_code.c.
References ipcl_err_msgmap_t::err, ipcl_err_msgmap(), and PCL_EUNDEF.
pcl_err_os2pcl()
PCL_PUBLIC int pcl_err_os2pcl (uint32_t oserr)
#include <pcl/error.h>
Definition at line 35 of file err_os2pcl.c.
References ipcl_err_map_t::err, ipcl_err_map(), and PCL_EUNDEF.
Referenced by pcl_accept(), pcl_connect(), pcl_net_ai2pcl(), pcl_net_dns2pcl(), pcl_proc_exec(), pcl_recv(), pcl_send(), pcl_socket_error(), and pcl_ssl_recv().
pcl_err_osname()
PCL_PUBLIC const char* pcl_err_osname (uint32_t oserr)
#include <pcl/error.h>
Definition at line 35 of file err_osname.c.
References ipcl_err_map(), and ipcl_err_map_t::osname.
Referenced by ipcl_win32_socket_handler(), and pcl_err_vjson().
pcl_err_osmsg()
PCL_PUBLIC int pcl_err_osmsg (uint32_t oserr, char * osmsg, size_t size)
#include <pcl/error.h>
Definition at line 40 of file err_osmsg.c.
References min, and pcl_strcpy().
Referenced by ipcl_win32_socket_handler().