‪libpcl: ‪Queue
Queue
‪A FIFO data structure.
Functions
PCL_PUBLIC pcl_queue_t * pcl_queue (pcl_cleanup_t cleanup)
‪Create a queue object.
PCL_PUBLIC int pcl_queue_size (pcl_queue_t *q)
‪Get the size (number of items) of a queue.
PCL_PUBLIC bool pcl_queue_empty (pcl_queue_t *q)
‪Indicates if a queue is empty.
PCL_PUBLIC void pcl_queue_add (pcl_queue_t *q, void *item)
‪Enqueues an item.
PCL_PUBLIC void * pcl_queue_peek (pcl_queue_t *q)
‪Retrieve the item at the head of a queue without removing it.
PCL_PUBLIC void * pcl_queue_remove (pcl_queue_t *q)
‪Dequeue an item.
PCL_PUBLIC void pcl_queue_clear (pcl_queue_t *q)
‪Remove all items from a queue.
PCL_PUBLIC void pcl_queue_free (pcl_queue_t *q)
‪Release all resources used by a queue.
Detailed Description
A FIFO data structure.
Function Documentation
pcl_queue()
PCL_PUBLIC pcl_queue_t* pcl_queue (pcl_cleanup_t cleanup)
#include <pcl/queue.h>
‪Create a queue object.
Parameters
cleanup ‪optional cleanup handler for queue items
Returns
‪pointer to a new queue object that must be freed via pcl_queue_free
Definition at line 36 of file queue.c.
References tag_pcl_queue::cleanup, tag_pcl_queue::head, pcl_malloc(), tag_pcl_queue::size, and tag_pcl_queue::tail.
pcl_queue_size()
PCL_PUBLIC int pcl_queue_size (pcl_queue_t * q)
#include <pcl/queue.h>
‪Get the size (number of items) of a queue.
Parameters
q ‪pointer to a queue object
Returns
‪number of items in the queue
Definition at line 35 of file queue_size.c.
References tag_pcl_queue::size.
Referenced by pcl_queue_empty().
pcl_queue_empty()
PCL_PUBLIC bool pcl_queue_empty (pcl_queue_t * q)
#include <pcl/queue.h>
‪Indicates if a queue is empty.
Parameters
q ‪pointer to a queue object
Returns
‪true if empty and false otherwise
Definition at line 35 of file queue_empty.c.
References pcl_queue_size().
Referenced by pcl_queue_peek(), and pcl_queue_remove().
pcl_queue_add()
PCL_PUBLIC void pcl_queue_add (pcl_queue_t * q, void * item)
#include <pcl/queue.h>
‪Enqueues an item.
Parameters
q ‪pointer to a queue object
item ‪pointer to an item to enqueue
Definition at line 36 of file queue_add.c.
References tag_pcl_queue::head, queue_item::next, pcl_malloc(), tag_pcl_queue::size, tag_pcl_queue::tail, and queue_item::value.
pcl_queue_peek()
PCL_PUBLIC void* pcl_queue_peek (pcl_queue_t * q)
#include <pcl/queue.h>
‪Retrieve the item at the head of a queue without removing it.
Parameters
q ‪pointer to a queue object
Returns
‪pointer to an item or NULL if queue is empty. To avoid ambiguity, do not enqueue NULL items.
Definition at line 35 of file queue_peek.c.
References tag_pcl_queue::head, pcl_queue_empty(), and queue_item::value.
pcl_queue_remove()
PCL_PUBLIC void* pcl_queue_remove (pcl_queue_t * q)
#include <pcl/queue.h>
‪Dequeue an item.
Note
‪caller repsonsible for releasing any resources used by returned item
Parameters
q ‪pointer to a queue object
Returns
‪pointer to an item or NULL if queue is empty. To avoid ambiguity, do not enqueue NULL items.
Definition at line 36 of file queue_remove.c.
References tag_pcl_queue::head, queue_item::next, pcl_free(), pcl_queue_empty(), tag_pcl_queue::size, tag_pcl_queue::tail, and queue_item::value.
pcl_queue_clear()
PCL_PUBLIC void pcl_queue_clear (pcl_queue_t * q)
#include <pcl/queue.h>
‪Remove all items from a queue.
Note
‪if the queue is not empty, this will call the optional pcl_cleanup_t for each item.
Parameters
q ‪pointer to a queue object
Definition at line 36 of file queue_clear.c.
References tag_pcl_queue::cleanup, tag_pcl_queue::head, queue_item::next, pcl_free(), tag_pcl_queue::size, tag_pcl_queue::tail, and queue_item::value.
Referenced by pcl_queue_free().
pcl_queue_free()
PCL_PUBLIC void pcl_queue_free (pcl_queue_t * q)
#include <pcl/queue.h>
‪Release all resources used by a queue.
Note
‪if the queue is not empty, this will call the optional pcl_cleanup_t for each item.
Parameters
q ‪pointer to a queue object
Definition at line 36 of file queue_free.c.
References pcl_free(), and pcl_queue_clear().