‪libpcl: ‪Array Management
Array Management
JSON Decoder and Encoder
‪A set of functions for managing JSON objects of type array.
Macros
#define pcl_json_arrisnum(arr, idx) (pcl_json_arrisint(arr, idx) || pcl_json_arrisreal(arr, idx))
‪Indicates if an array element is a number.
Functions
PCL_PUBLIC pcl_json_t * pcl_json_arr (void)
‪Create an array object.
PCL_PUBLIC int pcl_json_arradd (pcl_json_t *arr, pcl_json_t *elem, uint32_t flags)
‪Add an element to an array.
PCL_PUBLIC int pcl_json_arraddstr (pcl_json_t *arr, char *value, uint32_t flags)
‪Add a string value to an array.
PCL_PUBLIC int pcl_json_arraddint (pcl_json_t *arr, long long value)
‪Add an integer value to an array.
PCL_PUBLIC int pcl_json_arraddreal (pcl_json_t *arr, double value)
‪Add a real value to an array.
PCL_PUBLIC int pcl_json_arraddbool (pcl_json_t *arr, bool value)
‪Add a boolean value to an array.
PCL_PUBLIC int pcl_json_arraddnull (pcl_json_t *arr)
‪Add a null value to an array.
PCL_PUBLIC pcl_json_t * pcl_json_arrget (const pcl_json_t *arr, int index)
‪Get a json object from an array.
PCL_PUBLIC const char * pcl_json_arrgetstr (const pcl_json_t *arr, int index)
‪Get a string from an array.
PCL_PUBLIC long long pcl_json_arrgetint (const pcl_json_t *arr, int index)
‪Get an integer (number) from an array.
PCL_PUBLIC double pcl_json_arrgetreal (const pcl_json_t *arr, int index)
‪Get a real (number) from an array.
PCL_PUBLIC bool pcl_json_arrisstr (const pcl_json_t *arr, int index)
‪Indicates if an array element is a string.
PCL_PUBLIC bool pcl_json_arrisint (const pcl_json_t *arr, int index)
‪Indicates if an array element is an integer.
PCL_PUBLIC bool pcl_json_arrisreal (const pcl_json_t *arr, int index)
‪Indicates if an array element is a real.
PCL_PUBLIC bool pcl_json_arrisobj (const pcl_json_t *arr, int index)
‪Indicates if an array element is an object.
PCL_PUBLIC bool pcl_json_arrisarr (const pcl_json_t *arr, int index)
‪Indicates if an array element is an array.
PCL_PUBLIC bool pcl_json_arrisnull (const pcl_json_t *arr, int index)
‪Indicates if an array element is a null.
PCL_PUBLIC bool pcl_json_arrisbool (const pcl_json_t *arr, int index)
‪Indicates if an array element is a boolean.
PCL_PUBLIC bool pcl_json_arristrue (const pcl_json_t *arr, int index)
‪Indicates if an array element is a boolean true.
PCL_PUBLIC bool pcl_json_arrisfalse (const pcl_json_t *arr, int index)
‪Indicates if an array element is a boolean false.
PCL_PUBLIC int pcl_json_arrremove (pcl_json_t *arr, int index)
‪Remove an element from an array.
Detailed Description
A set of functions for managing JSON objects of type array.
Macro Definition Documentation
pcl_json_arrisnum
#define pcl_json_arrisnum (arr, idx) (pcl_json_arrisint(arr, idx) || pcl_json_arrisreal(arr, idx))
#include <pcl/json.h>
‪Indicates if an array element is a number.
Parameters
arr ‪pointer to a json array object
idx ‪element index
Returns
‪true if element is an integer or real and false otherwise.
Definition at line 619 of file json.h.
Function Documentation
pcl_json_arr()
PCL_PUBLIC pcl_json_t* pcl_json_arr (void)
#include <pcl/json.h>
‪Create an array object.
It is safe to use the array module for managing a JSON array. Internally, a json array is backed by a pcl_array_t. For a given pcl_json_t, ensure the type member is 'a' and then use json->array with the array functions. However, do not use pcl_array_free.
Returns
‪pointer to a json object of type array
Definition at line 43 of file json_arr.c.
References tag_pcl_json::array, tag_pcl_json::nrefs, pcl_array(), pcl_malloc(), and tag_pcl_json::type.
Referenced by ipcl_json_parse_array(), pcl_err_vjson(), and pcl_json_match().
pcl_json_arradd()
PCL_PUBLIC int pcl_json_arradd (pcl_json_t * arr, pcl_json_t * elem, uint32_t flags)
#include <pcl/json.h>
‪Add an element to an array.
Parameters
arr ‪pointer to a json array object
elem ‪pointer to a json object of any type
flags ‪This only suports PCL_JSON_FREEVALONERR.
Returns
‪0 on success and -1 on error
Definition at line 36 of file json_arradd.c.
References tag_pcl_json::array, BADARG, pcl_array_append(), PCL_ETYPE, pcl_json_free(), PCL_JSON_FREEVALONERR, pcl_json_isarr, SETERRMSG, TRCMSG, and tag_pcl_json::type.
Referenced by ipcl_json_parse_array(), pcl_err_vjson(), pcl_json_arraddbool(), pcl_json_arraddint(), pcl_json_arraddnull(), pcl_json_arraddreal(), and pcl_json_arraddstr().
pcl_json_arraddstr()
PCL_PUBLIC int pcl_json_arraddstr (pcl_json_t * arr, char * value, uint32_t flags)
#include <pcl/json.h>
‪Add a string value to an array.
Parameters
arr ‪pointer to a json array object
value ‪pointer to a string.
flags ‪For value, all flags supported by pcl_json_str are supported here. This also supprts PCL_JSON_FREEVALONERR.
Returns
‪0 on success and -1 on error
Definition at line 35 of file json_arraddstr.c.
References pcl_json_arradd(), PCL_JSON_FREEVALONERR, pcl_json_str(), and TRC.
pcl_json_arraddint()
PCL_PUBLIC int pcl_json_arraddint (pcl_json_t * arr, long long value)
#include <pcl/json.h>
‪Add an integer value to an array.
Parameters
arr ‪pointer to a json array object
value ‪integer value. This cannot be PCL_JSON_INVINT.
Returns
‪0 on success and -1 on error
Definition at line 35 of file json_arraddint.c.
References pcl_json_arradd(), PCL_JSON_FREEVALONERR, pcl_json_int(), and TRC.
pcl_json_arraddreal()
PCL_PUBLIC int pcl_json_arraddreal (pcl_json_t * arr, double value)
#include <pcl/json.h>
‪Add a real value to an array.
Parameters
arr ‪pointer to a json array object
value ‪real value. This cannot be PCL_JSON_INVREAL, NaN or Infinity.
Returns
‪0 on success and -1 on error
Definition at line 35 of file json_arraddreal.c.
References pcl_json_arradd(), PCL_JSON_FREEVALONERR, pcl_json_real(), and TRC.
pcl_json_arraddbool()
PCL_PUBLIC int pcl_json_arraddbool (pcl_json_t * arr, bool value)
#include <pcl/json.h>
‪Add a boolean value to an array.
Parameters
arr ‪pointer to a json array object
value ‪boolean value
Returns
‪0 on success and -1 on error
Definition at line 35 of file json_arraddbool.c.
References pcl_json_arradd(), pcl_json_bool(), and TRC.
pcl_json_arraddnull()
PCL_PUBLIC int pcl_json_arraddnull (pcl_json_t * arr)
#include <pcl/json.h>
‪Add a null value to an array.
Parameters
arr ‪pointer to a json array object
Returns
‪0 on success and -1 on error
Definition at line 35 of file json_arraddnull.c.
References pcl_json_arradd(), pcl_json_null(), and TRC.
pcl_json_arrget()
PCL_PUBLIC pcl_json_t* pcl_json_arrget (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Get a json object from an array.
Parameters
arr ‪pointer to a json array object
index ‪element index
Returns
‪pointer to a json object that is only valid while arr is valid.
See also
‪pcl_json_ref
Definition at line 36 of file json_arrget.c.
References tag_pcl_json::array, pcl_array_get(), PCL_EINVAL, PCL_ETYPE, pcl_json_isarr, R_SETERR, R_SETERRMSG, R_TRC, and tag_pcl_json::type.
Referenced by pcl_err_setjson(), pcl_json_arrgetint(), pcl_json_arrgetreal(), pcl_json_arrgetstr(), pcl_json_arrisarr(), pcl_json_arrisbool(), pcl_json_arrisfalse(), pcl_json_arrisint(), pcl_json_arrisnull(), pcl_json_arrisobj(), pcl_json_arrisreal(), pcl_json_arrisstr(), and pcl_json_arristrue().
pcl_json_arrgetstr()
PCL_PUBLIC const char* pcl_json_arrgetstr (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Get a string from an array.
Parameters
arr ‪pointer to a json array object
index ‪element index
Returns
‪pointer to a string that is the value at index. The returned string is managed by arr and a copy is required if it is to persist past the life of arr. On error, NULL is returned.
Definition at line 35 of file json_arrgetstr.c.
References PCL_ETYPE, pcl_json_arrget(), pcl_json_isstr, R_SETERRMSG, R_TRC, tag_pcl_json::string, and tag_pcl_json::type.
pcl_json_arrgetint()
PCL_PUBLIC long long pcl_json_arrgetint (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Get an integer (number) from an array.
Parameters
arr ‪pointer to a json array object
index ‪element index
Returns
‪integer value found at index. If an error occurs, PCL_JSON_INVINT is returned.
Definition at line 35 of file json_arrgetint.c.
References tag_pcl_json::integer, PCL_ETYPE, pcl_json_arrget(), PCL_JSON_INVINT, pcl_json_isint, R_SETERRMSG, R_TRC, and tag_pcl_json::type.
pcl_json_arrgetreal()
PCL_PUBLIC double pcl_json_arrgetreal (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Get a real (number) from an array.
Parameters
arr ‪pointer to a json array object
index ‪element index
Returns
‪double value found at index. If an error occurs, PCL_JSON_INVREAL is returned.
Definition at line 35 of file json_arrgetreal.c.
References PCL_ETYPE, pcl_json_arrget(), PCL_JSON_INVREAL, pcl_json_isreal, R_SETERRMSG, R_TRC, tag_pcl_json::real, and tag_pcl_json::type.
pcl_json_arrisstr()
PCL_PUBLIC bool pcl_json_arrisstr (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Indicates if an array element is a string.
Parameters
arr ‪pointer to a json array object
index ‪element index
Returns
‪true if element is a string and false otherwise.
Definition at line 35 of file json_arrisstr.c.
References pcl_json_arrget(), and pcl_json_isstr.
pcl_json_arrisint()
PCL_PUBLIC bool pcl_json_arrisint (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Indicates if an array element is an integer.
Parameters
arr ‪pointer to a json array object
index ‪element index
Returns
‪true if element is an integer and false otherwise.
Definition at line 35 of file json_arrisint.c.
References pcl_json_arrget(), and pcl_json_isint.
pcl_json_arrisreal()
PCL_PUBLIC bool pcl_json_arrisreal (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Indicates if an array element is a real.
Parameters
arr ‪pointer to a json array object
index ‪element index
Returns
‪true if element is a real and false otherwise.
Definition at line 35 of file json_arrisreal.c.
References pcl_json_arrget(), and pcl_json_isreal.
pcl_json_arrisobj()
PCL_PUBLIC bool pcl_json_arrisobj (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Indicates if an array element is an object.
Parameters
arr ‪pointer to a json array object
index ‪element index
Returns
‪true if element is an object and false otherwise.
Definition at line 35 of file json_arrisobj.c.
References pcl_json_arrget(), and pcl_json_isobj.
pcl_json_arrisarr()
PCL_PUBLIC bool pcl_json_arrisarr (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Indicates if an array element is an array.
Parameters
arr ‪pointer to a json array object
index ‪element index
Returns
‪true if element is an array and false otherwise.
Definition at line 35 of file json_arrisarr.c.
References pcl_json_arrget(), and pcl_json_isarr.
pcl_json_arrisnull()
PCL_PUBLIC bool pcl_json_arrisnull (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Indicates if an array element is a null.
Parameters
arr ‪pointer to a json array object
index ‪element index
Returns
‪true if element is a null and false otherwise.
Definition at line 35 of file json_arrisnull.c.
References pcl_json_arrget(), and pcl_json_isnull.
pcl_json_arrisbool()
PCL_PUBLIC bool pcl_json_arrisbool (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Indicates if an array element is a boolean.
Parameters
arr ‪pointer to a json array object
index ‪element index
Returns
‪true if element is a boolean and false otherwise.
Definition at line 35 of file json_arrisbool.c.
References pcl_json_arrget(), and pcl_json_isbool.
pcl_json_arristrue()
PCL_PUBLIC bool pcl_json_arristrue (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Indicates if an array element is a boolean true.
Parameters
arr ‪pointer to a json array object
idx ‪element index
Returns
‪true if element is a boolean true and false otherwise.
Definition at line 35 of file json_arristrue.c.
References tag_pcl_json::boolean, pcl_json_arrget(), and pcl_json_isbool.
pcl_json_arrisfalse()
PCL_PUBLIC bool pcl_json_arrisfalse (const pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Indicates if an array element is a boolean false.
Parameters
arr ‪pointer to a json array object
idx ‪element index
Returns
‪true if element is a boolean false and false otherwise.
Definition at line 35 of file json_arrisfalse.c.
References tag_pcl_json::boolean, pcl_json_arrget(), and pcl_json_isbool.
pcl_json_arrremove()
PCL_PUBLIC int pcl_json_arrremove (pcl_json_t * arr, int index)
#include <pcl/json.h>
‪Remove an element from an array.
Parameters
arr ‪pointer to a json array object
index ‪element index
Returns
‪new count or -1 on error
Definition at line 36 of file json_arrremove.c.
References tag_pcl_json::array, BADARG, pcl_array_remove(), PCL_ETYPE, pcl_json_isarr, SETERRMSG, TRC, and tag_pcl_json::type.