‪libpcl: ‪Object Management
Object Management
JSON Decoder and Encoder
‪A set of functions for managing JSON objects of type object.
Macros
#define pcl_json_objisnum(obj, key) (pcl_json_objisint(obj, key) || pcl_json_objisreal(obj, key))
‪Indicates if an object key's value is a number (real or integer).
Functions
PCL_PUBLIC pcl_json_t * pcl_json_obj (void)
‪Create an object.
PCL_PUBLIC int pcl_json_objput (pcl_json_t *obj, char *key, pcl_json_t *value, uint32_t flags)
‪Put a json value into an object.
PCL_PUBLIC int pcl_json_objputstr (pcl_json_t *obj, char *key, char *value, uint32_t flags)
‪Put a string value into an object.
PCL_PUBLIC int pcl_json_objputint (pcl_json_t *obj, char *key, long long value, uint32_t flags)
‪Put an integer value into an object.
PCL_PUBLIC int pcl_json_objputreal (pcl_json_t *obj, char *key, double value, uint32_t flags)
‪Put a real value into an object.
PCL_PUBLIC int pcl_json_objputbool (pcl_json_t *obj, char *key, bool value, uint32_t flags)
‪Put a boolean value into an object.
PCL_PUBLIC int pcl_json_objputnull (pcl_json_t *obj, char *key, uint32_t flags)
‪Put a null value into an object.
PCL_PUBLIC pcl_json_t * pcl_json_objget (const pcl_json_t *obj, const char *key)
‪Get a json value from an object.
PCL_PUBLIC const char * pcl_json_objgetstr (const pcl_json_t *obj, const char *key)
‪Get a string value from an object.
PCL_PUBLIC long long pcl_json_objgetint (const pcl_json_t *obj, const char *key)
‪Get a integer value from an object.
PCL_PUBLIC double pcl_json_objgetreal (const pcl_json_t *obj, const char *key)
‪Get a real value from an object.
PCL_PUBLIC bool pcl_json_objisstr (const pcl_json_t *obj, const char *key)
‪Indicates if an object key's value is a string.
PCL_PUBLIC bool pcl_json_objisint (const pcl_json_t *obj, const char *key)
‪Indicates if an object key's value is an integer.
PCL_PUBLIC bool pcl_json_objisreal (const pcl_json_t *obj, const char *key)
‪Indicates if an object key's value is a real.
PCL_PUBLIC bool pcl_json_objisobj (const pcl_json_t *obj, const char *key)
‪Indicates if an object key's value is an object.
PCL_PUBLIC bool pcl_json_objisarr (const pcl_json_t *obj, const char *key)
‪Indicates if an object key's value is an array.
PCL_PUBLIC bool pcl_json_objisnull (const pcl_json_t *obj, const char *key)
‪Indicates if an object key's value is a null.
PCL_PUBLIC bool pcl_json_objisbool (const pcl_json_t *obj, const char *key)
‪Indicates if an object key's value is a boolean.
PCL_PUBLIC bool pcl_json_objistrue (const pcl_json_t *obj, const char *key)
‪Indicates if an object key's value is a boolean true.
PCL_PUBLIC bool pcl_json_objisfalse (const pcl_json_t *obj, const char *key)
‪Indicates if an object key's value is a boolean false.
PCL_PUBLIC int pcl_json_objremove (pcl_json_t *obj, const char *key)
‪Remove a value from a json object.
Detailed Description
A set of functions for managing JSON objects of type object.
Macro Definition Documentation
pcl_json_objisnum
#define pcl_json_objisnum (obj, key) (pcl_json_objisint(obj, key) || pcl_json_objisreal(obj, key))
#include <pcl/json.h>
‪Indicates if an object key's value is a number (real or integer).
Parameters
arr ‪pointer to a json object of type object
key ‪pointer to a string
Returns
‪true if key's value is a number and false otherwise.
Definition at line 452 of file json.h.
Function Documentation
pcl_json_obj()
PCL_PUBLIC pcl_json_t* pcl_json_obj (void)
#include <pcl/json.h>
‪Create an object.
It is safe to use the hash table module for managing a JSON object. Internally, a json object is backed by a pcl_htable_t. For a given pcl_json_t, ensure the type member is 'o' and then use json->object with the htable functions. However, do not use pcl_htable_free.
Returns
‪pointer to a json object of type object
Definition at line 44 of file json_obj.c.
References tag_pcl_json::nrefs, tag_pcl_json::object, pcl_htable(), pcl_malloc(), tag_pcl_htable::remove_entry, and tag_pcl_json::type.
Referenced by ipcl_json_parse_object(), and pcl_err_vjson().
pcl_json_objput()
PCL_PUBLIC int pcl_json_objput (pcl_json_t * obj, char * key, pcl_json_t * value, uint32_t flags)
#include <pcl/json.h>
‪Put a json value into an object.
Parameters
obj ‪pointer to a json object of type object
key ‪pointer to a string key
value ‪pointer to a json value
flags ‪a bitmask of Control Flags
Returns
‪0 for success or -1 on error
Definition at line 38 of file json_objput.c.
References BADARG, tag_pcl_json::object, PCL_ETYPE, pcl_free(), pcl_htable_put(), pcl_json_free(), PCL_JSON_FREEVALONERR, pcl_json_isobj, PCL_JSON_SHALLOW, PCL_JSON_SKIPUTF8CHK, pcl_strdup(), pcl_utf8_check(), SETERRMSG, TRC, TRCMSG, and tag_pcl_json::type.
Referenced by ipcl_json_parse_object(), pcl_err_vjson(), pcl_json_objputbool(), pcl_json_objputint(), pcl_json_objputnull(), pcl_json_objputreal(), and pcl_json_objputstr().
pcl_json_objputstr()
PCL_PUBLIC int pcl_json_objputstr (pcl_json_t * obj, char * key, char * value, uint32_t flags)
#include <pcl/json.h>
‪Put a string value into an object.
Parameters
obj ‪pointer to a json object of type object
key ‪pointer to a string key
value ‪pointer to a string value
flags ‪a bitmask of Control Flags. String control flags apply to both key and value
Returns
‪0 for success or -1 on error
Definition at line 35 of file json_objputstr.c.
References PCL_JSON_FREEVALONERR, pcl_json_objput(), pcl_json_str(), and TRC.
Referenced by pcl_err_vjson().
pcl_json_objputint()
PCL_PUBLIC int pcl_json_objputint (pcl_json_t * obj, char * key, long long value, uint32_t flags)
#include <pcl/json.h>
‪Put an integer value into an object.
Parameters
obj ‪pointer to a json object of type object
key ‪pointer to a string key
value ‪integer value
flags ‪a bitmask of Control Flags
Returns
‪0 for success or -1 on error
Definition at line 35 of file json_objputint.c.
References PCL_JSON_FREEVALONERR, pcl_json_int(), pcl_json_objput(), and TRC.
Referenced by pcl_err_vjson().
pcl_json_objputreal()
PCL_PUBLIC int pcl_json_objputreal (pcl_json_t * obj, char * key, double value, uint32_t flags)
#include <pcl/json.h>
‪Put a real value into an object.
Parameters
obj ‪pointer to a json object of type object
key ‪pointer to a string key
value ‪real value
flags ‪a bitmask of Control Flags
Returns
‪0 for success or -1 on error
Definition at line 35 of file json_objputreal.c.
References PCL_JSON_FREEVALONERR, pcl_json_objput(), pcl_json_real(), and TRC.
pcl_json_objputbool()
PCL_PUBLIC int pcl_json_objputbool (pcl_json_t * obj, char * key, bool value, uint32_t flags)
#include <pcl/json.h>
‪Put a boolean value into an object.
Parameters
obj ‪pointer to a json object of type object
key ‪pointer to a string key
value ‪boolean value
flags ‪a bitmask of Control Flags
Returns
‪0 for success or -1 on error
Definition at line 35 of file json_objputbool.c.
References pcl_json_bool(), PCL_JSON_FREEVALONERR, pcl_json_objput(), and TRC.
pcl_json_objputnull()
PCL_PUBLIC int pcl_json_objputnull (pcl_json_t * obj, char * key, uint32_t flags)
#include <pcl/json.h>
‪Put a null value into an object.
Parameters
obj ‪pointer to a json object of type object
key ‪pointer to a string key
flags ‪a bitmask of Control Flags
Returns
‪0 for success or -1 on error
Definition at line 35 of file json_objputnull.c.
References PCL_JSON_FREEVALONERR, pcl_json_null(), pcl_json_objput(), and TRC.
pcl_json_objget()
PCL_PUBLIC pcl_json_t* pcl_json_objget (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Get a json value from an object.
Parameters
obj ‪pointer to a json object of type object
key ‪pointer to a string key
Returns
‪pointer to a json object.
Definition at line 36 of file json_objget.c.
References tag_pcl_json::object, PCL_EINVAL, PCL_ENOTFOUND, pcl_errno, PCL_ETYPE, pcl_htable_get(), pcl_json_isobj, R_SETERR, R_SETERRMSG, R_TRC, and tag_pcl_json::type.
Referenced by pcl_err_setjson(), pcl_json_objgetint(), pcl_json_objgetreal(), pcl_json_objgetstr(), pcl_json_objisarr(), pcl_json_objisbool(), pcl_json_objisfalse(), pcl_json_objisint(), pcl_json_objisnull(), pcl_json_objisobj(), pcl_json_objisreal(), pcl_json_objisstr(), and pcl_json_objistrue().
pcl_json_objgetstr()
PCL_PUBLIC const char* pcl_json_objgetstr (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Get a string value from an object.
Parameters
obj ‪pointer to a json object of type object
key ‪pointer to a string key
Returns
‪pointer to a string that is the value for key. The returned string is managed by obj and a copy is required if it is to persist past the life of obj. On error, NULL is returned.
Definition at line 35 of file json_objgetstr.c.
References PCL_ETYPE, pcl_json_isstr, pcl_json_objget(), R_SETERRMSG, R_TRC, tag_pcl_json::string, and tag_pcl_json::type.
Referenced by pcl_err_setjson().
pcl_json_objgetint()
PCL_PUBLIC long long pcl_json_objgetint (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Get a integer value from an object.
Parameters
obj ‪pointer to a json object of type object
key ‪pointer to a string key
Returns
‪integer value found at key. If an error occurs, PCL_JSON_INVINT is returned.
Definition at line 35 of file json_objgetint.c.
References tag_pcl_json::integer, PCL_ETYPE, PCL_JSON_INVINT, pcl_json_isint, pcl_json_objget(), R_SETERRMSG, R_TRC, and tag_pcl_json::type.
Referenced by pcl_err_setjson().
pcl_json_objgetreal()
PCL_PUBLIC double pcl_json_objgetreal (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Get a real value from an object.
Parameters
obj ‪pointer to a json object of type object
key ‪pointer to a string key
Returns
‪double value found at key. If an error occurs, PCL_JSON_INVREAL is returned.
Definition at line 35 of file json_objgetreal.c.
References PCL_ETYPE, PCL_JSON_INVREAL, pcl_json_isreal, pcl_json_objget(), R_SETERRMSG, R_TRC, tag_pcl_json::real, and tag_pcl_json::type.
pcl_json_objisstr()
PCL_PUBLIC bool pcl_json_objisstr (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Indicates if an object key's value is a string.
Parameters
arr ‪pointer to a json object of type object
key ‪pointer to a string
Returns
‪true if key's value is a string and false otherwise.
Definition at line 35 of file json_objisstr.c.
References pcl_json_isstr, and pcl_json_objget().
pcl_json_objisint()
PCL_PUBLIC bool pcl_json_objisint (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Indicates if an object key's value is an integer.
Parameters
arr ‪pointer to a json object of type object
key ‪pointer to a string
Returns
‪true if key's value is an integer and false otherwise.
Definition at line 35 of file json_objisint.c.
References pcl_json_isint, and pcl_json_objget().
pcl_json_objisreal()
PCL_PUBLIC bool pcl_json_objisreal (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Indicates if an object key's value is a real.
Parameters
arr ‪pointer to a json object of type object
key ‪pointer to a string
Returns
‪true if key's value is a real and false otherwise.
Definition at line 35 of file json_objisreal.c.
References pcl_json_isreal, and pcl_json_objget().
pcl_json_objisobj()
PCL_PUBLIC bool pcl_json_objisobj (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Indicates if an object key's value is an object.
Parameters
arr ‪pointer to a json object of type object
key ‪pointer to a string
Returns
‪true if key's value is an object and false otherwise.
Definition at line 35 of file json_objisobj.c.
References pcl_json_isobj, and pcl_json_objget().
pcl_json_objisarr()
PCL_PUBLIC bool pcl_json_objisarr (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Indicates if an object key's value is an array.
Parameters
arr ‪pointer to a json object of type object
key ‪pointer to a string
Returns
‪true if key's value is an array and false otherwise.
Definition at line 35 of file json_objisarr.c.
References pcl_json_isarr, and pcl_json_objget().
pcl_json_objisnull()
PCL_PUBLIC bool pcl_json_objisnull (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Indicates if an object key's value is a null.
Parameters
arr ‪pointer to a json object of type object
key ‪pointer to a string
Returns
‪true if key's value is a null and false otherwise.
Definition at line 35 of file json_objisnull.c.
References pcl_json_isnull, and pcl_json_objget().
pcl_json_objisbool()
PCL_PUBLIC bool pcl_json_objisbool (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Indicates if an object key's value is a boolean.
Parameters
arr ‪pointer to a json object of type object
key ‪pointer to a string
Returns
‪true if key's value is a boolean and false otherwise.
Definition at line 35 of file json_objisbool.c.
References pcl_json_isbool, and pcl_json_objget().
pcl_json_objistrue()
PCL_PUBLIC bool pcl_json_objistrue (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Indicates if an object key's value is a boolean true.
Parameters
arr ‪pointer to a json object of type object
key ‪pointer to a string
Returns
‪true if key's value is a boolean true and false otherwise.
Definition at line 35 of file json_objistrue.c.
References tag_pcl_json::boolean, pcl_json_isbool, and pcl_json_objget().
pcl_json_objisfalse()
PCL_PUBLIC bool pcl_json_objisfalse (const pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Indicates if an object key's value is a boolean false.
Parameters
arr ‪pointer to a json object of type object
key ‪pointer to a string
Returns
‪true if key's value is a boolean false and false otherwise.
Definition at line 35 of file json_objisfalse.c.
References tag_pcl_json::boolean, pcl_json_isbool, and pcl_json_objget().
pcl_json_objremove()
PCL_PUBLIC int pcl_json_objremove (pcl_json_t * obj, const char * key)
#include <pcl/json.h>
‪Remove a value from a json object.
Parameters
obj ‪pointer to a json object of type object.
key ‪pointer to a string
Returns
‪0 on success and -1 on error
Definition at line 36 of file json_objremove.c.
References BADARG, tag_pcl_json::object, PCL_ETYPE, pcl_htable_remove(), pcl_json_isobj, SETERRMSG, TRC, and tag_pcl_json::type.